<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Mis ex&aacute;menes</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<!--<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>-->
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
<!-- 				<div class="btn-group btn-breadcrumb"> -->
<!-- 			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a> -->
<!-- 			        <a href="#" class="btn btn-default">Bachillerato</a> -->
<!-- 			        <a href="#" class="btn btn-default">Mis examenes</a> -->
<!-- 				</div> -->
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title amaranth text-size-20">Informaci&oacute;n de mis ex&aacute;menes</h3>
		</div>
		
		<?php 

		if ($this->flashMessenger()->hasMessages()) {
		
		    echo '<div class="alert alert-info messages">';
		
		    $messages = $this->flashMessenger()->getMessages();
		    foreach($messages as $message) {
		        echo $message;
		    }
		
		    echo '</div>';
		}
		
		?>
		<div class="panel-body">
			<?php if($this->exams){?>
				<?php if($this->role == 1){?>
					<a style="text-decoration:none;" href="<?php echo $this->basePath();?>/exams/exam/add">
        			<img src="<?php echo $this->basePath("/public/img/add.png")?>"/>
					</a>
					Crear examen
					<br><br>
					<div class="table-responsive">
						<table class="table table-striped table-bordered" id="table">     
						  <thead>
						    <tr>
				    		    <th>Nombre del Examen</th>
				        		<th>Descripci&oacute;n</th>
				        		<th>Duraci&oacute;n</th>
				        		<th>Desde</th>
				        		<th>Hasta</th>
				        		<th>Actualizar</th>
					        	<th>Eliminar</th>
						        <th>Responder</th>
				    		</tr>
			 			  </thead>
			 			  <tbody>
			       			<?php foreach ($this->exams as $exams): ?>
			        		<tr>
			        			<td><a title="Ver Preguntas" href="<?php echo $this->basePath("/exams/examquestions/".$exams['id_topic']);?>"><?php echo $exams['topic_name'];?></a></font></td>
			        			<td><?php echo $exams['description'];?></td>
		    					<td><?php echo $exams['time']." : 00";?></td>
		    					<td><?php echo $exams['startDate'];?></td>
		    					<td><?php echo $exams['endDate'];?></td>
		    					<td><center><a href="<?php echo $this->basePath("/exams/exam/edit/".$exams['id_topic'])?>"><img src=<?php echo $this->basePath("/public/img/update.png")?>></a></center></td>
		    					<td><center><a href="<?php echo $this->basePath("/exams/exam/delete/".$exams['id_topic'])?>"onclick="return confirm('¿Seguro que deseas eliminar este exámen?');" ><img src=<?php echo $this->basePath("/public/img/deleteBook.png")?>></a></center></td>
		    					<td></center><a href="<?php echo $this->basePath("/exams/exam/replyexam/".$exams['id_topic']);?>">Responder examen</a></center></td>
					        </tr>
			   				<?php endforeach;?>
					    </tbody>
					  </table>
					</div>
				<?php } ?>
				<?php if($this->role == 4){?>
						<?php if($this->time == 1){?>
							<p>La siguiente tabla contiene informaci&oacute;n relacionada a tus ex&aacute;menes</p>
							<div class="table-responsive">
								<table class="table table-striped table-bordered" id="table">
								<thead>
								    <tr>
						    		    <th style="width:250px;">Ex&aacute;menes</th>
						        		<th style="width:250px;">Descripci&oacute;n</th>
						        		<th style="width:100px;">Duraci&oacute;n</th>
<!-- 						        		<th>Desde</th> -->
<!-- 						        		<th>Hasta</th> -->
								        <th>Intentos Restantes</th>
								        <th></th>
						    		</tr>
					 			  </thead>
					    		<tbody>
					    		
					    		<?php foreach ($this->exams as $exams): ?>
			        			<tr>
					        		<td><?php echo $exams['topic_name'];?></td>
					        		<td><?php echo $exams['description'];?></td>
		    						<td><?php echo $exams['time']." : 00";?></td>
		    						<!-- <td><?php //echo $exams['startDate'];?></td>-->
		    						<!-- <td><?php //echo $exams['endDate'];?></td>-->
				    				<?php if($this->attemps>= 1 && $this->attemps <=3  && $this->scoreValidation < 6){?>
				    				<td align="center"><?php echo $this->attemps;?></td>
		    						<td><center><a data-toggle="modal" data-target="#myModal" href="#">Responder examen</a></center></td>
		    						<?php }elseif($this->attemps>= 1 && $this->attemps <=3 && $this->scoreValidation > 6){?>
		    						<td align="center"><?php echo $this->attemps;?></td>
			    					<td>Tu Calificaci&oacute;n fue: <?php echo $this->scoreValidation;?> has aprobado el Trimestre, contacta al equipo de Ctec en L&iacute;nea para m&aacute;s informaci&oacute;n </td>
		    						<?php }elseif($this->attemps == 0 && $this->scoreValidation < 6){ ?>
		    							<?php if($this->extraAttemps != null){?>
		    								<td>Oportunidad Extra</td>
		    								<td></center><a data-toggle="modal" data-target="#myModal" href="#">Responder examen</a></center></td>
		    							<?php }elseif($this->extraAttemps == null && $this->extraScoreValidation >= 6){?>
		    								<td align="center"> - </td>
				    						<td>Tu Calificaci&oacute;n fue: <?php echo $this->extraScoreValidation;?> Has aprobado el Trimestre en examen extraordinario, contacta al equipo de Ctec en L&iacute;nea para m&aacute;s informaci&oacute;n </td>
		    							<?php }elseif($this->extraAttemps == null && $this->extraScoreValidation < 6){?>
		    								<td align="center"><?php echo $this->attemps;?></td>
					    					<td></center>Haz repobado el trimestre, contacta al equipo de Ctec en L&iacute;nea para m&aacute;s informaci&oacute;n </td>
		    							<?php }?>
				    				<?php }elseif($this->scoreValidation >= 6){?>
				    					<td align="center"> - </td>
				    					<td>Tu Calificaci&oacute;n fue: <?php echo $this->scoreValidation;?> Has aprobado el Trimestre, contacta al equipo de Ctec en L&iacute;nea para m&aacute;s informaci&oacute;n </td>
				    				<?php }?>
						       </tr>
			   					<?php endforeach;?>
							    </tbody>     
							</table>
							</div>
						<?php }else{?>
							<span>Todavia no cumples las horas de estudio necesarias para realizar el examen.
							Cuando cumplas este requisito se te enviara un mail indicandote que ya tienes acceso.
							</span>
						<?php }?>
				<?php }?>
			<?php }else{ ?>
					<span>No hay examenes disponibles, contacta al Administrador para mas informaci&oacute;
					</span>
			<?php }?>
		</div>
	</div>
</div>

<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog modal-lg">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header bg-primary">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title"><h2>Instrucciones</h2></h4>
      </div>
      <div class="modal-body">
        <div id="instructions">
			<p>Has completado las 80 horas de estudio y tienes derecho a contestar el examen para pasar al siguiente trimestre</p>
			<ul style="text-align:justify">
			<li>Vas a contar con 20 minutos para contestar el examen el cual consta de 20 preguntas.</li>
			<li>Una vez que seleccionas una respuesta y das click en el bot&oacute;n de siguiente ya no podr&aacute;s corregir tu respuesta, as&iacute; que revisa bien tu respuesta
			antes de avanzar.</li>
			<li>En caso de que se te acabe el tiempo tu calificaci&oacute;n se calcula en base a las preguntas que alcanzaste a contestar.</li>
			<li>La calificaci&oacute;n minima para aprobar es 6.</li>
			<li>En caso de que no apruebes el examen, tienes 3 oportunidades para volverlo a hacer</li>
			<li>Si acabas el examen dentro del tiempo tu calificaci&oacute;n ser&aacute; enviada a tu correo.</li>
			</ul>
			
			<p>Una vez que est&eacute;s listo presiona el bot&oacute;n de iniciar para comenzar tu examen</p>
			<center><a href="<?php echo $this->basePath("/exams/exam/replyexam/".$exams['id_topic']);?>" class="btn btn-info">Iniciar Examen</a>			</center>
			</div>
      </div>
      <div class="modal-footer">
      </div>
    </div>

  </div>
</div>