<?php $this->headLink()->appendStylesheet($this->baseUrl('/public/css/paysPop.css')); ?>
<?php echo $this->headScript()
					   ->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/crmFunctions.js')) ;?>

<script>
	$(document).ready(function(){

		$("#name_company").change(function(){
			$(".nClie").html('"' + $(this).val() + '"');
		});
		if($("#name_company").val() != ""){
			$(".nClie").html('"' + $("#name_company").val() + '"');
		}
		$('#mail_contact').change(function(){
			var mail = $(this).val();
			validaEmail(mail, $(this));
		});
		
		$('#rfc').change(function(){
			var rfc = $(this).val();
			validaRfcSupplier(rfc, $(this));
		});	
	});

</script>

<div id="fieldsetForm" class="forms">
<legend id="legendhelp">* Datos requeridos</legend>
	<fieldset>
<?=$this->element->getElement('user_name');?>
<?=$this->element->getElement('password');?>
<?=$this->element->getElement('canlogin');?>
<?=$this->element->getElement('id_company'); ?>
<?=$this->element->getElement('id_address'); ?>
<?=$this->element->getElement('action'); ?>
<?=$this->element->getElement('id_contact'); ?>	
		<legend>Informaci&oacute;n comercial</legend>
	    <table> 
	        <tbody>
	            <tr class="center">
	                <td>* Nombre o Raz&oacute;n social:</td>
	                <td>Marca:</td>
	                <td>RFC:</td>	                
	                <td>Sitio web:</td>
	            </tr>
	            <tr class="center">
	                <td><?=$this->element->getElement('name_company'); ?></td>
	                <td><?=$this->element->getElement('brand'); ?></td>
	                <td><?=$this->element->getElement('rfc'); ?>
	                	<img id="loaderRfc" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
	                </td>	                
	                <td><?=$this->element->getElement('website'); ?></td>
	            </tr>	        
	            <tr class="center">
	                <td colspan="4"> * Interesado en:</td>
	            </tr>
	            <tr class="center">	                
	                <td colspan="4"><?=$this->element->getElement('interestingin'); ?></td>
	            </tr>	        
	        </tbody>
	    </table>
	</fieldset>
	<fieldset id="fieldset-address">
	<legend>Direcci&oacute;n</legend>
	    <table>
	        <tbody>
	          	<tr>
	             	<td colspan="2">Calle:</td>
	                <td>N&uacute;mero exterior:</td>
	                <td>N&uacute;mero interior:</td>
	            </tr>
	            <tr>
		            <td colspan="2"><?=$this->element->getElement('street'); ?></td>
	               	<td><?=$this->element->getElement('number'); ?></td>
	               	<td><?=$this->element->getElement('interior'); ?></td>
	            </tr>
	        	<tr>
	              	<td>Estado:</td>
	                <td>Delegaci&oacute;n o Municipio:</td>
	            	<td>Colonia:</td>
	            	<td>C&oacute;digo Postal:</td>
	            </tr>
	            <tr>
	            	<td><?=$this->element->getElement('state_id');?></td>
	               	<td><?=$this->element->getElement('district'); ?><img style="display:none" id="load" alt="" height="18" src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"></td>
	               	<td><?=$this->element->getElement('neighborhood'); ?><img style="display:none" id= "load_neighborhood" alt="" height="18" src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"></td>
	            	<td><?=$this->element->getElement('postalcode'); ?></td>
	            </tr>
	            <tr>
	            	<td>Tel&eacute;fono conmutador:</td>
	            	<td>URL Mapa:</td>
	            </tr>
	            <tr>
	               	<td><?=$this->element->getElement('phone'); ?></td>
	               	<td><?=$this->element->getElement('url_map'); ?></td>
	            </tr>
	        </tbody>
	    </table>
	</fieldset>
	
	<fieldset>
<legend>Informaci&oacute;n de contacto</legend>
    <table>
        <tbody>
            <tr>
    <div><h4>Este contacto será el favorito para el cliente <span class="nClie">?</span></h4></div>
            </tr>
             <tr>
             	<td>* Nombre:</hernandeztd>
                <td>* Ap. Paterno:</td>
                <td>Ap. Materno:</td>
            </tr>
            <tr>
            	<td><?=$this->element->getElement('name_contact'); ?></td>
               	<td><?=$this->element->getElement('surname_contact'); ?></td>
               	<td><?=$this->element->getElement('lastname_contact'); ?></td>
            </tr>
             <tr>
                <td>M&oacute;vil:</td>
            	<td>* E-Mail:</td>
                <td>Tel&eacute;fono local:</td>
            </tr>
            <tr>
                <td><?=$this->element->getElement('cellphone_contact'); ?></td>
               	<td><?=$this->element->getElement('mail_contact'); ?>
               		<img id="loaderEmail" style="display: none;" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
               	<br></td>
               	<td><?=$this->element->getElement('phone_contact'); ?></td>
            </tr> 
             <tr>
             	<td>Puesto:</td>
            </tr>
            <tr>
            	<td><?=$this->element->getElement('id_job');?></td>
            </tr>
        </tbody>
    </table>
	</fieldset>
	
	<div class="center">
	    <?=$this->element->getElement('Guardar');?>
	    <a href="javascript:location.href='<?=$this->baseUrl("/In/crm/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
	</div>
</div> 

<!-- 
    Inicia popup
-->
	<div id="paysPop" class="popHorus">
	<h2>Especique las fechas de cobro por favor.</h2>
		<div id="btnAccept">Aceptar</div>
		<ul id="paysArea"></ul>
	</div>
	<div id="paysBack"></div>
<!-- 
    termina popup
-->
