<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/checkbox/label-checkbox.css'; ?>" rel="stylesheet" />

<script type="text/javascript" src="<?php echo $this->basePath() . "/public/js/permissions.js" ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Agregar permisos</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Sistema</a>
			        <a href="#" class="btn btn-default">Permisos</a>
			        <a href="#" class="btn btn-default">Agregar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->


<div class="container">

	<p class="triangle-border text-size-20 amaranth">Ingresa los datos del rol y sus permisos.</p>

	<div class="content-forms">

		<div style="text-align:right;">
			<span style="text-align:right;" class="label label-info">* Datos requeridos</span>
		</div>

		<?php
		//Preparamos el formulario
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
		?>

			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-tag"></span> Datos del rol
				</legend>

				<div class="col-md-6">
					<div class="form-group">
						<label class="text-amaranth">Nombre del rol:</label>
						<?php
						echo $this->formElement($form->get('rol_name'));
						?>
					</div>
				</div>

				<div class="col-md-6">
					<div class="form-group">
						<label class="text-amaranth">Status:</label><br>
						<?php
						echo $this->formElement($form->get('status'));
						?>
					</div>
				</div>

			</fieldset>

			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-tag"></span> Permisos
				</legend>

				<div class="col-md-5">
					<div class="form-group">
						<label class="text-amaranth">Permisos Disponibles:</label>
						<?php
						echo $this->formElement($form->get('permissions'));
						?>
					</div>
				</div>

				<div class="col-md-2" style="text-align: center;">
					 <button type="button" class="btn btn-default" id="origin">
					 	<span class="glyphicon glyphicon-chevron-right"></span>
					 	<span class="glyphicon glyphicon-chevron-right"></span>
					 </button>
					 <br><br>
					 <button type="button" class="btn btn-default" id="destination">
					 	<span class="glyphicon glyphicon-chevron-left"></span>
					 	<span class="glyphicon glyphicon-chevron-left"></span>
					 </button>
				</div>

				<div class="col-md-5">
					<div class="form-group">
						<label class="text-amaranth">Permisos Asignados:</label>
						<?php
						echo $this->formElement($form->get('destinationPermissions'));
						?>
					</div>
				</div><!-- Fin div col-md-5 -->

				<div class="col-md-12" id="checkPermissions" style="display:none;">
				  	<div class="panel panel-primary">
				       	<div class="panel-heading">
				           	<h1 class="panel-title">Permisos disponibles</h1>
				      	</div>
				      	<div id="showPermissions"></div><!-- Find de div showPermissions -->
				    	<div class="panel-body">
							<a id="savePermissions" href="" class="btn btn-primary">Guardar</a>
							<a id="cancelPermissions" href="" class="btn btn-danger">Cancelar</a>
				    	</div>
				    </div>
				</div><!-- Fin del div de permisos -->

			</fieldset>

			<div class="clearfix padding-bottom-20">
				<div class="col-md-6">
					<label></label>
					<?php echo $this->formElement($form->get('saveRole')); ?>
				</div>
				<div class="col-md-6">
					<label></label>
					<a href="<?php echo $this->basePath()."/system/permissions/index";?>" class="btn btn-danger btn-lg btn-block">Cancelar</a>
				</div>
			</div>

		<?php
		//Cerramos el formulario
		echo $this->form()->closeTag();
		?>

	</div>

</div>

<script>
var $basePath = "<?php echo $this->basePath(); ?>";
var $id_role  = "<?php echo $this->role_id + 1; ?>";

</script>

<style>
input[type="checkbox"], li{
	cursor: pointer;
}

/*ul li:hover{
	background-color: #faebcc ;
}*/

/*fieldset { border: 1px solid #faebcc; border-radius: 10px; margin-bottom:10px;}*/
/*legend{
	width: auto;
	margin-left: 10px;
	background-color: #faebcc;
	opacity: 0.5;
	border-radius: 5px;
	padding:5px;
	margin-bottom: 10px;
}*/
</style>