<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/addresses.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/users.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Editar detalle alumno</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<!--<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>-->
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Cetec</a>
			        <a href="#" class="btn btn-default">Alumno</a>
			        <a href="#" class="btn btn-default">Editar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

	<p class="triangle-border text-size-20 font-open-sans">Modifica los datos del usuario o alumnos.</p>

	<div class="content-forms">

		<div style="text-align:right;">
			<span style="text-align:right;" class="label label-info">* Datos requeridos</span>
		</div>

		<?php
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
		?>
			<?php echo $this->formElement($form->get('user_id')); ?>

			<div class="row">

				<div class="col-md-6">
					<fieldset class="responsive-fieldset fieldset">

						<legend class="legend amaranth">
							<span class="glyphicon glyphicon-tag"></span> Datos Generales
						</legend>

						<!--<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="contract_type" class="font-raleway">Tipo de contrato:</label>
									<?php echo $this->formElement($form->get('contract_type')); ?>
								</div>
							</div>
						</div>-->

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="birthday" class="font-raleway"> Fecha de nacimiento</label>
									<?php echo $this->formElement($form->get('birthday')); ?>
								</div>
							</div>
						</div>

						<!--<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="number_ss" class="font-raleway"> N&uacute;mero de IMSS.</label>
									<?php echo $this->formElement($form->get('number_ss')); ?>
								</div>
							</div>
						</div>-->

					</fieldset>
				</div>

				<div class="col-md-6">
					<fieldset class="responsive-fieldset fieldset">
						<legend class="legend amaranth">
							<span class="glyphicon glyphicon-lock"></span> Informaci&oacute;n de contacto
						</legend>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="local_phone" class="font-raleway">Telefono local</label>
									<?php echo $this->formElement($form->get('local_phone')); ?>
								</div>
							</div>
						</div>

						<div class="row">
							<div class="col-md-6">
								<div class="form-group">
									<label for="local_phone" class="font-raleway">Telefono celular</label>
									<?php echo $this->formElement($form->get('cellphone')); ?>
								</div>
							</div>
						</div>

					</fieldset>
				</div>

			</div>

			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-lock"></span> Direcci&oacute;n
				</legend>

				<div class="row">

					<div class="col-md-12">

						<div class="col-md-6">
							<div class="form-group">
								<label class="font-raleway">* Calle:</label>
								<?php echo $this->formElement($form->get('street')); ?>
							</div>
						</div>

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">* Numero exterior:</label>
								<?php echo $this->formElement($form->get('number')); ?>
							</div>
						</div>

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">Numero interior:</label>
								<?php echo $this->formElement($form->get('interior')); ?>
							</div>
						</div>

					</div>

				</div>


				<div class="row">

					<div class="col-md-12">

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">* Estado:</label>
								<?php echo $this->formElement($form->get('state_id')); ?>
							</div>
						</div>

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">* Delegaci&oacute;n / Municipio:</label>
								<?php echo $this->formElement($form->get('district')); ?>
							</div>
						</div>

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">* Colonia:</label>
								<?php echo $this->formElement($form->get('neighborhood')); ?>
							</div>
						</div>

						<div class="col-md-3">
							<div class="form-group">
								<label class="font-raleway">* C&oacute;digo postal:</label>
								<?php echo $this->formElement($form->get('postalcode')); ?>
							</div>
						</div>

					</div>

				</div>

			</fieldset>

			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-lock"></span> Informaci&oacute;n bancaria
				</legend>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label class="font-raleway">Nombre del banco:</label>
							<?php echo $this->formElement($form->get('name_bank')); ?>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="font-raleway">N&#176; de Cuenta bancaria:</label>
							<?php echo $this->formElement($form->get('number_acount')); ?>
						</div>
					</div>
				</div>

				<div class="row">
					<div class="col-md-6">
						<div class="form-group">
							<label class="font-raleway">CLABE:</label>
							<?php echo $this->formElement($form->get('interbank_clabe')); ?>
						</div>
					</div>
					<div class="col-md-6">
						<div class="form-group">
							<label class="font-raleway">Sucursal:</label>
							<?php echo $this->formElement($form->get('sucursal_name')); ?>
						</div>
					</div>
				</div>

			</fieldset>

			<!--<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-picture"></span> Documentos
				</legend>

				<div class="row">
					<div class="col-md-12">

						<div class="col-md-4">
							<h3 class="text-uppercase text-center">Suba IFE</h3>
							
							<?php echo $this->formElement($form->get('photofile_ife')); ?>
							<input type="file" accept="image/*" class="input-file" />
							<div class="thumbnail thumbnail-image">
								<a href="#" class="btn btn-default file-select">Elegir archivo</a>
								<img src="<?php echo $this->basePath().'/public/img/send_file.png'; ?>" alt="licencia">
							</div>

						</div>

						<div class="col-md-4">
							<h3 class="text-uppercase text-center">Suba licencia</h3>
							
							<?php echo $this->formElement($form->get('photofile_license')); ?>
							<input type="file" accept="image/*" class="input-file" />
							<div class="thumbnail thumbnail-image">
								<a href="#" class="btn btn-default file-select">Elegir archivo</a>
								<img src="<?php echo $this->basePath().'/public/img/send_file.png'; ?>" alt="licencia">
							</div>

						</div>

						<div class="col-md-4">
							<h3 class="text-uppercase text-center">Suba certificaci&oacute;n</h3>
							
							<?php echo $this->formElement($form->get('photofile_certification')); ?>
							<input type="file" accept="image/*" class="input-file" />
							<div class="thumbnail thumbnail-image">
								<a href="#" class="btn btn-default file-select">Elegir archivo</a>
								<img src="<?php echo $this->basePath().'/public/img/send_file.png'; ?>" alt="certificaci&oacute;n">
							</div>

						</div>

					</div>
				</div>

			</fieldset>-->

			<div style="margin-top: 15px; margin-bottom:10px;" class="row">
				<div class="col-md-6">
					<?php echo $this->formElement($form->get('saveUser')); ?>
				</div>
				<div class="col-md-6">
					<a href="<?php echo $this->basePath()."/horus/employee/index";?>" class="btn btn-danger btn-lg btn-block">Cancelar</a>
				</div>
			</div>


		<?php
		echo $this->form()->closeTag();
		?>
	</div>

</div>

<script>
	var $basePath     = "<?php echo $this->basePath(); ?>";
	var $district     = "<?php echo $this->district; ?>";
	var $neighborhood = "<?php echo $this->neighborhood; ?>";
</script>