<?php 
	$this->headLink()->appendStylesheet($this->baseUrl('/public/css/popupArticle.css'));
	$this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/functions.js'));
	$helpUser = $this->helps->proposalsAddorder;
	$helpUser = $this->helps->proposalsIndex;	
?>

<INPUT type="hidden" value="<?php echo $this->idCli ?>" name="cli" id="client"> 
<INPUT type="hidden" value="<?php echo $this->cust_type ?>" name="cus" id="custype"> 

<script>

$(document).ready(function(){
	var idCli = "<?php echo ($this->idCli); ?>";
	var cust_type = "<?php echo ($this->cust_type); ?>";
	
	if(idCli){
		if (cust_type != null ) {
		$('input[name=mybrand][value='+ cust_type +']').attr('checked', true);
		if($("input[name='mybrand']:checked").val() == 1){
			$("#suppl").html("* Cliente: ");	
			$("#supplAdd").show();
			var check = $("input[name='mybrand']:checked").val();
			$("#mybrand option[value="+ check +"]").attr("selected",true);
			//chek = 1 - cliente check = 0 - prospecto	
			getClientOrProspect(check);
			$('#purchaseorderForm').removeAttr('onsubmit');
			$('#purchaseorderForm').attr("onsubmit", "return isEmptyForm('purchaseorderForm',5)");
		}else{
			var check = $("input[name='mybrand']:checked").val();
			$("#suppl").html("* Cliente prospecto: ");	
			$("#supplAdd").show();
			//chek = 1 - cliente check = 0 - prospecto	
			getClientOrProspect(check);
			$('#purchaseorderForm').removeAttr('onsubmit');
			$('#purchaseorderForm').attr("onsubmit", "return isEmptyForm('purchaseorderForm',5)");
		}
		setTimeout(function() {
			$('#id_company option[value='+idCli+']').attr('selected','selected')
			//$('#id_company').attr('disabled','disabled')
			//$("#company").val(idCli)
			$("#supplAdd").hide();
			$('input[name=mybrand]').attr("disabled",true);
		}, 4000);
/*if ($("#client") != 0) {
		setTimeout(function() {
			$("#id_company").val(idCli);
		}, 3000);		
}*/	
		}
	}



	var stock = 0;
	
	addPurchase();	

	$('#article').change(function(){
		var text = $('#article').val();
		var idProduct = $('#article option:selected').val();
		var amount = $('#amount');
		if(text != '0'){
			amount.attr("disabled",true);
			$.get(
				 BASE_URL + "/In/stock/reload", { product: true , id_product :idProduct , type: 1},
				  function(data){
				  	 $('.stoks').show();
					  var Json = $.parseJSON(data);
					  for(var i = 0; i < Json.length; i++){
						 var item = Json[i];
						 $('#amount').val(item.p_price).formatCurrency();
						 $('#quantity').val("");	
						 stock = item.stock;
						 $('#stock').val(item.stock);
						 $('#minstock').val(item.min_stock);
						 $('#maxstock').val(item.max_stock);
						 $('#toS').html(stock);
				      }			      
				  }  
			);
		}else{
			amount.attr("disabled",false);
			$('#amount').val("");	
			$('#quantity').val("");	
			$('.stoks').hide();	
		}			
	});

	
	//evento change en monto
	$("#amount").change(function(){
		//al ingresar el monto de lo que va a apgar 
		$(this).formatCurrency();
	});

	$('#Enviar').click(function(){
			$('#amount').toNumber();
			$('#subtotal').toNumber();
			$('#total').toNumber();
			
	});

	currencyField("price", "Agregar");

	$('#addPurchase').click(function(){	
		  $("#max").remove();
		  var alerta = "";
		  
	  	if($('#quantity').val() != "" && $('#amount').val() != "" && $('#article').val() != "0" ){
	  		
	  		if(parseInt($('#quantity').val()) > parseInt($('#stock').val())){
	  			horusAlert("No hay suficientes productos en el almacen, genera un pedido");
			}
			
	  		addPurchas();
	  					
		}else if($.trim($('#quantity').val()) == "" || $.trim($('#amount').val()) == ""){
			//$('#addPurchase').after("<label id='max' style='color:red;'><br/><-- tienes que llenar los 3 campos</label>"); 
			$('#maxErr').show();
		}else if($.trim($('#article').val()) == "0"){
			$('#article').val("");
			$('#amount').val("");
			$('#quantity').val("");
			//$('#addPurchase').after("<label id='max' style='color:red;'><br/><--- tienes que elegir un art&iacute;culo</label>");
			$('#maxErr').show();
		}
	});
	
	//cuando se aceptan las fechas se asignan a un campo oculto para esperar el submit
	$("#btnAccept").click(function() {
		var arrayDate = new Array();
		$('#total').formatCurrency();
		$("#dates").val(null);
		$("#paysArea input.inputDate").each(function(index) {
			arrayDate.push($(this).val());
		});
		$("#dates").val(arrayDate);
		disablePopup("paysBack","paysPop");
	});

	 $('#tableOrder').show();

	 oTablePurchase = jqueryTablePopup('#tableOrder');
	 oTablePurchase = $('#tableOrder').dataTable(
				 	{
				 		bFilter:false,
				 		bRetrieve:true
				 	});
		
});
</script>

<h3 class="centerIn">Agregar Cotizaci&oacute;n de productos</h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity">
			<a href="<?php echo $this->baseUrl('/In/proposals/index')?>">
				<img title="Cotizaciones de Producto" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconorder.png')?>"/>
			</a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','Actualizar los datos de un proyecto')">
			<a>
				<img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
			</a>
		</li>
		<div id="clock"></div>
	</div>	
</ul>

<?php if(isset($_GET['er']) == 'notProd') :?>
<h2>Tienes que agregar minimo 1 producto a tu compra</h2>
<?php endif; ?>

<div id="overflow">
	<p class="triangle-border">Ingresa los datos de la cotizaci&oacute;n.</p>
	<?php print $this->formulario; ?>
</div>
<!-- 
    Inicia popup
-->
<div id="popupArticle" class="popHorus">
	<div id="btnCloseArticle" title="Cerrar ventana">X</div>
	<div id="formArticle">
		<div class="center">
			<?=$this->articleForm;?>
		</div>
	</div>
</div>
<div id="backgroundArticle"></div>
