<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/payroll/checkbox-css.css'; ?>" rel="stylesheet" />
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/users.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Agregar usuario</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Sistema</a>
			        <a href="#" class="btn btn-default">Usuarios</a>
			        <a href="#" class="btn btn-default">Agregar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
<?php
$flash=$this->flashMessenger()
            ->setMessageOpenFormat('<div%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');
?>

	<?php echo $flash->render('duplicado',array('alert', 'alert-danger')); ?>
	
	<p class="triangle-border text-size-20 font-open-sans">Ingresa los datos del usuario o empleado.</p>
	
	<div class="content-forms">
	
		<div style="text-align:right;">
			<span style="text-align:right;" class="label label-info">* Datos requeridos</span>
		</div>
		
		<?php
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formElement($form->get('user_id'));
		?>
			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-tag"></span> Datos Personales
				</legend>
				
				<div style="padding:50px;" class="col-md-4">
					<?php echo $this->formElement($form->get('file')); ?>
					<?php echo $this->formElement($form->get('photofilename')); ?>
					<?php echo $this->formElement($form->get('photofile')); ?>
					
					<strong><p class="text-center font-raleway">Foto de perfil:</p></strong>
					
					<div id="preview" class="thumbnail">
    					<a href="#" id="file-select" class="btn btn-info">Elegir archivo</a>
    					<img style="width:200px; height:200px;" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100"/>
					</div>
				</div>
				
				<div class="col-md-8">
					
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label font-raleway">* Tipo de usuario:</label>
						<div class="col-sm-9">
							<?php $this->formRadio()->setSeparator('</div><div class="radio">'); ?>
							<div class="radio">
    							<?php echo $this->formRadio($form->get('user_type')->setValue(1)) ?>
							</div>
						</div>
					</div>
					
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label font-raleway">* RFC:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('rfc')); ?>
						</div>
					</div>
					
					<!-- div para mostrar campos si es usuario externo -->
					<div id="external_user_div">
					
						<div class="form-group">
							<label for="name" class="col-sm-3 control-label font-raleway">* Compa&ntilde;ia:</label>
							<div class="col-sm-9">
								<?php echo $this->formElement($form->get('id_company')); ?>
							</div>
						</div>
					
						<div class="form-group">
							<label for="name" class="col-sm-3 control-label font-raleway">Usuario favorito:</label>
							<div class="col-sm-9">
								<label for="user_principal" class="label-check lead">
			  						<?php echo $this->formElement($form->get('user_principal')); ?>
			  						<i></i> 
								</label>
								<?php //echo $this->formElement($form->get('user_principal')); ?>
							</div>
						</div>
						
					</div>
				
					<div class="form-group">
						<label for="name" class="col-sm-3 control-label font-raleway">* Nombre:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('name')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label for="" class="col-sm-3 control-label font-raleway">* Apellido paterno:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('surname')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label for="" class="col-sm-3 control-label font-raleway">Apellido materno:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('lastname')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label for="" class="col-sm-3 control-label font-raleway">* Correo:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('email')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label for="" class="col-sm-3 control-label font-raleway">* Departamento:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('id_department')); ?>
						</div>
					</div>
					
					<div class="form-group">
						<label for="" class="col-sm-3 control-label font-raleway">* Puesto:</label>
						<div class="col-sm-9">
							<?php echo $this->formElement($form->get('id_job')); ?>
						</div>
					</div>
					
				</div>	
			</fieldset>
			
			<fieldset class="responsive-fieldset fieldset">
			
				<legend class="legend amaranth">
					<span class="glyphicon glyphicon-lock"></span> Datos de acceso y seguridad
				</legend>
				
				<div class="row">
					<div class="col-md-12">
						<label style="margin: 20px 0;" for="canlogin" class="label-check lead">
							<span>&iquest;Puede entrar a OSIRIS ?</span>
			  				<?php echo $this->formElement($form->get('canlogin')); ?>
			  				<i></i> 
						</label>
					</div>
				</div>
				
				<div id="contenedor-datos-seguridad" style="display:none;margin-bottom:20px;">
						
					<div style="margin-left:0;margin-right:0;margin-bottom:20px;" class="row">
						<div class="col-xs-12 col-sm-6 col-md-6">
							<label for="role" class="font-raleway">Roles Disponibles</label>
							<?php echo $this->formElement($form->get('role')); ?>
						</div>
					</div>	
					
					<div style="margin-left:0;margin-right:0;margin-bottom:20px;" class="row">
						<div class="col-xs-12 col-sm-6 col-md-6">
							<label for="user_name" class="font-raleway">Clave de usuario:</label>
							<?php echo $this->formElement($form->get('user_name')); ?>
						</div>
					</div>
					
					<div style="margin-left:0;margin-right:0;margin-bottom:20px;" class="row">
                   		<div class="col-xs-12 col-sm-6 col-md-6">
                   			<label for="password" class="font-raleway">Contrase&ntilde;a:</label>
                        	<?php echo $this->formElement($form->get('password')); ?>                                    
                        </div>
                     	<div class="col-xs-12 col-sm-6 col-md-6">
                     		<label for="password2" class="font-raleway">Confirmar Contrase&ntilde;a:</label>
                        	<input type="password" name="password2" class="form-control input-lg" id="password2" placeholder="********"/>                                    
                        </div>
					</div>
						
				</div>
				
			</fieldset>
			
			<div style="margin-top: 15px; margin-bottom:10px;" class="row">
				<div class="col-md-6">
					<?php echo $this->formElement($form->get('saveUser')); ?>
				</div>
				<div class="col-md-6">
					<a href="<?php echo $this->basePath()."/system/users/index";?>" class="btn btn-danger btn-lg btn-block">Cancelar</a>
				</div>
			</div>
			
		<?php
		echo $this->form()->closeTag();
		?>
	</div>

</div>

<script>
	var $basePath = "<?php echo $this->basePath(); ?>";
	var $nameView  = "add_user";
	var $role_user = 0;
</script>