<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Usuarios</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<!--<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>-->
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Sistema</a>
			        <a href="#" class="btn btn-default">Usuarios</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

<?php
$flash = $this->flashMessenger()
            ->setMessageOpenFormat('<div id="userAdd"%s>')
            ->setMessageSeparatorString('')
            ->setMessageCloseString('</div>');
?>
<?php echo $flash->render('add_correcto',array('alert', 'alert-success'));?>
<?php echo $flash->render('eliminado',array('alert', 'alert-success'));?>

<div class="panel panel-default">
	<div class="panel-heading">
		<h3 class="panel-title font-raleway text-size-20">Informaci&oacute;n de usuarios</h3>
	</div>
	<div class="panel-body">
		<p>La siguiente tabla contiene informaci&oacute;n relacionada a los usuarios</p>
		<table id="usersTable" class="table table-striped table-hover table-condensed table-bordered">
			<thead>
				<th>Nombre</th>
				<th>A. paterno</th>
				<th>A. materno</th>
				<th>Correo</th>
				<th>Rol</th>
				<th>Departamento</th>
				<th></th>
				<th></th>
				<th>
					<a class="btn btn-success" href="<?php echo $this->basePath()."/system/users/add"?>" data-toggle="tooltip" data-placement="top" title="Agregar Usuario">
						<span class="glyphicon glyphicon-plus-sign"></span>
					</a>
				</th>
			</thead>
			<tbody>
		    	<?php foreach($users as $usuario) : ?>
				<tr>
			        <td>
			        	<a class="btn" href="<?php echo $this->basePath()."/system/users/seedetail/".$usuario["user_id"]; ?>" data-toggle="tooltip" data-placement="top" title="Detalle Usuario">
			        		<span class="glyphicon glyphicon-search"></span>
			        		<?php echo $usuario["name"]; ?>
			        	</a>
			        </td>
			        <td><?php echo $usuario["surname"]; ?></td>
			        <td><?php echo $usuario["lastname"]; ?></td>
					<td><?php echo $usuario["email"]; ?></td>
					<td><?php echo $usuario["role_name"]; ?></td>
					<td><?php echo $usuario["d_name"]; ?></td>
			        <td><a class="btn btn-warning" href="<?php echo $this->basePath()."/system/users/changepass/".$usuario["user_id"]; ?>" data-toggle="tooltip" data-placement="top" title="Cambiar Contrase&ntilde;a"><span class="glyphicon glyphicon-lock"></span></a></td>
			        <td><a class="btn btn-primary" href="<?php echo $this->basePath()."/system/users/edit/".$usuario["user_id"]; ?>" data-toggle="tooltip" data-placement="top" title="Editar Usuario"><span class="glyphicon glyphicon-pencil"></span></a></td>
			        <td><a class="btn btn-danger" href="<?php echo $this->basePath()?>/system/users/delete/<?php echo $usuario["user_id"]?>" data-toggle="tooltip" data-placement="top" title="Eliminar Usuario"><span class="glyphicon glyphicon-trash"></span></a></td>
		    	</tr>
		    	<?php endforeach; ?>
		    </tbody>
		</table>
	</div>
</div>

</div>

<style>
</style>

<script>
$(document).ready(function(){
	$("#usersTable").dataTable({
		"aoColumnDefs" : [ {
	    	'bSortable' : false,
	        'aTargets' : [ 6, 7, 8 ]
		} ]
	});	
});
</script>