<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Detalle usuario</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Sistema</a>
			        <a href="#" class="btn btn-default">Usuarios</a>
			        <a href="#" class="btn btn-default">Detalle</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title font-raleway text-size-20">
				<span class="glyphicon glyphicon-tag"></span>
				<?php echo $user[0]["name"]." ".$user[0]["surname"]." ".$user[0]["lastname"]; ?>
			</h3>
		</div>
		<div class="panel-body">
			<div class="col-md-3 col-lg-3">
				<center>
					<img height="200" width="200" alt="Foto usuario" src="https://lh5.googleusercontent.com/-b0-k99FZlyE/AAAAAAAAAAI/AAAAAAAAAAA/eu7opA4byxI/photo.jpg?sz=100" class="img-circle">
				</center>
			</div>
			<div class="col-md-9 col-lg-9">
				<div class="row">
					<div class="col-md-6 col-lg-6">
						<fieldset class="responsive-fieldset fieldset">
							<legend class="legend amaranth">Informaci&oacute;n general</legend>
							<div class="table-responsive">
								<table class="table font-raleway text-size-15">
									<tbody>
										<tr>
			                        		<td>N&uacute;mero de Empleado:</td>
			                       			<td><?php echo Util_Tools::format($user[0]["user_id"], 4); ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>Nombre:</td>
			                       			<td><?php echo $user[0]["name"]; ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>Apellido Paterno:</td>
			                       			<td><?php echo $user[0]["surname"]; ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>Apellido Materno:</td>
			                       			<td><?php echo $user[0]["lastname"]; ?></td>
			                      		</tr>
			                      		<tr>
					                    	<td>Correo:</td>
					                    	<td><?php echo $user[0]["email"]; ?></td>
					                    </tr>
									</tbody>
								</table>
							</div>
						</fieldset>
					</div>
					<div class="col-md-6 col-lg-6">
						<fieldset class="responsive-fieldset fieldset">
							<legend class="legend amaranth">Detalles</legend>
							<div class="table-responsive">
								<table class="table font-raleway text-size-15">
									<tbody>
										<tr>
			                        		<td>Usuario:</td>
			                       			<td><?php echo $user[0]["user_name"]; ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>Fecha de Ingreso:</td>
			                       			<td><?php echo Util_Tools::dateFormat("-", $user[0]["date_admission"]); ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>Tel&eacute;fono:</td>
			                       			<td><?php echo $user[0]["local_phone"]; ?></td>
			                      		</tr>
			                      		<tr>
			                        		<td>M&oacute;vil:</td>
			                       			<td><?php echo $user[0]["cellphone"]; ?></td>
			                      		</tr>
			                      		<tr>
					                    	<td>Cumplea&ntilde;os</td>
					                    	<td><?php echo Util_Tools::dateFormat("-", $user[0]["birthday"]); ?></td>
					                    </tr>
									</tbody>
								</table>
							</div>
						</fieldset>
					</div>
				</div>
				
				<fieldset class="responsive-fieldset fieldset">
					<legend class="legend amaranth">Direcci&oacute;n</legend>
					<div class="table-responsive">
						<table class="table font-raleway text-size-15">
							<tbody>
								<tr>
									<td>Calle:</td>
									<td><?php echo $user[0]["street"]; ?></td>
								</tr>
								<tr>
	                        		<td>N&uacute;mero Interio:</td>
	                       			<td><?php echo $user[0]["interior"]; ?></td>
	                      		</tr>
	                      		<tr>
	                        		<td>N&uacute;mero Exterior:</td>
	                       			<td><?php echo $user[0]["number"]; ?></td>
	                      		</tr>
								<tr>
	                        		<td>Estado:</td>
	                       			<td><?php echo $user[0]["name_state"]; ?></td>
	                      		</tr>
	                      		<tr>
	                        		<td>Delegaci&oacute;n o Municipio:</td>
	                       			<td><?php echo $user[0]["name_district"]; ?></td>
	                      		</tr>
	                      		<tr>
	                        		<td>Colonia:</td>
	                       			<td><?php echo $user[0]["name_neighborhood"]; ?></td>
	                      		</tr>
	                      		<tr>
	                        		<td>C&oacute;digo Postal:</td>
	                       			<td><?php echo $user[0]["postalcode"]; ?></td>
	                      		</tr>
							</tbody>
						</table>
					</div>
				</fieldset>
			</div>
		</div>
		<div class="panel-footer">
			<div class="clearfix">
			<span class="pull-right">
				<a href="<?php  echo $this->basePath()."/system/users/editdetail/".$user[0]["user_id"];?>"  class="btn btn-primary" data-toggle="tooltip" data-placement="top" title="Informaci&oacute;n Adicional"><span class="glyphicon glyphicon-edit"></span></a>
				<a class="btn btn-default" href="<?php echo $this->basePath("/system/users/index")?>" data-toggle="tooltip" data-placement="top" title="Regresar">
					<span class="glyphicon glyphicon-repeat"></span>
				</a>
			</span>
			</div>
		</div>
	</div>
</div>