<h3 class="centerIn">Agregar Datos Generales</h3>
<ul class="toolbar">
	<div id="icons">
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','En el formulario puede agregar los datos de la compa&ntilde;ia y del contacto de esta')" >
				<a><img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>	
</ul>
<p class="triangle-border" >Ingresa la experiencia en proyectos.</p>
<?php echo $this->form; ?>