<div id="fieldsetForm" class="forms">
<legend id="legendhelp">* Datos requeridos</legend>
<fieldset>
		<legend>Componente</legend>
    <table>
    		<tbody>
    		<tr>
    			<td><?=$this->element->getElement('componente_id'); ?></td>
    		</tr>
    		<tr align="center">
    			<td>*Nombre:</td>
                <td>*Tipo:</td>
            </tr>
    		<tr align="center">
    			<td><?=$this->element->getElement('name'); ?></td>
    			<td><?=$this->element->getElement('type_component'); ?></td>
            </tr>
            <tr style="text-align: center;">
               		<td colspan="5">Descripci&oacute;n:</td>
	            </tr>
	            <tr style="text-align: center;">
	               	<td colspan="5"><?=$this->element->getElement('description'); ?></td>
	            </tr>
            </tbody>		
    </table>
</fieldset>
<div class="center">
	<?=$this->element->getElement('Guardar'); ?>
	<!--  
    <a href="javascript:document.forms['components'].submit();" class="horusBtn big icon-iconsave">Guardar</a>
    -->
    <a href="javascript:location.href='<?=$this->baseUrl("/Ioteca/components/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
</div>
</div>