<?php 
	$this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/getContact.js')) 
	->appendFile($this->baseUrl('/public/js/jsFunctions/addDatesOfPayment.js'))
	->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/1000.js'))
	 ->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/prospectsprojectFunctions.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('/public/css/paysPop.css'));
	
	$layout = Zend_Layout::getMvcInstance();
 	$view = $layout->getView(); 
?>
<script>
	var iconsFile = "<?php echo $view->iconset; ?>";
	var IconSet = "<?php echo $this->iconset; ?>";
</script>
<div style="width:80%;margin-left:auto;margin-right:auto;">
<div id="fieldsetForm" class="forms" style="overflow-x:hidden;">
<legend id="legendhelp">* Datos requeridos</legend>
<div align="center">	

</div>
	<?=$this->element->getElement('purchaseItem');?>
	<?=$this->element->getElement('ID'); ?>
	<?=$this->element->getElement('developersIds'); ?>
	<?=$this->element->getElement('costtable'); ?>	
	<?=$this->element->getElement('idcustomerselect'); ?>	
	<?=$this->element->getElement('dates'); ?>
	<?=$this->element->getElement('id_datePayment'); ?>
	<?=$this->element->getElement('id_contact'); ?>
	<?=$this->element->getElement('profitpercent'); ?>
	<?=$this->element->getElement('discountpercent'); ?>	
	<?=$this->element->getElement('id_references'); ?>
	<?=$this->element->getElement('type'); ?>
	<fieldset>
	<?=$this->element->getElement('status'); ?>
		<legend>1) Ingresa los datos generales</legend>
		<table style="margin-left:15%; margin-right:15%;">
			<tbody>
						<tr>
							<td>
								<input type="radio" name="mybrand" checked="checked" value="1" style="height: 10px; width: 10px;">
								<span id="span" style="margin-left: 5px;">Cliente</span><br />
								<input type="radio" name="mybrand" value="0" style="height: 10px; width: 10px;">
								<span id="span" style="margin-left: 5px;">Prospecto</span>
							</td>
						</tr>
				<tr>
					<td><span id="suppl"> </span> </td>
					<td>Fecha:</td>
				</tr>
				<tr>
					<td>
						<span id="supplSelect">
							<?=$this->element->getElement('company_ID'); ?>
							<img id="loadCp" style="display:none;" src="<?php echo $this->baseUrl("/public/img/loader.gif");?>"/>
						</span> 
						<a id="supplAdd">
							<img src="<?php echo $this->baseUrl("/public/img/icons/".$view->iconset."/iconplus.png"); ?>"/>
						</a>
					</td>
					<td><?=$this->element->getElement('start_date'); ?></td>
				</tr>

				<tr>
					<td>*Servicio:</td>
					<td>*Fecha Entrega:</td>
				</tr>
				<tr>
					<td><?=$this->element->getElement('project_name'); ?></td>
					<td><?=$this->element->getElement('end_date'); ?></td>
				</tr>
				<table>
					<tbody>
				<tr>
					<td colspan="4" class="center">Descripci&oacute;n:</td>
				</tr>
				<tr>
					<td colspan="4" class="center"><?=$this->element->getElement('description'); ?>
					</td>
				</tr>	
					</tbody>	
				</table>		
			</tbody>
		</table>
	</fieldset>
	<fieldset id="fieldset-addteam">
		<legend>3) Asigna los recursos humanos</legend>
		<table>
			<tbody>
				<tr>
					<td>Personal disponible:</td>				
					<td></td>
					<td>Personal asignado:</td>
				</tr>
				<tr>
					<td><?=$this->element->getElement('availableTeam'); ?></td>				
					<td><?=$this->element->getElement('toTeam'); ?> <br /> <br /> <?=$this->element->getElement('toavailableTeam'); ?>
					</td>
					<td><?=$this->element->getElement('team'); ?></td>
				</tr>
			</tbody>
		</table>
		<table>
				<!--<tr>
					<td>
					 </td>
				 </tr>
				<tr>
					<td><?=$this->element->getElement('createProjectEmployee'); ?>Agregar nuevo empleado</td>
					<td>
						<img style="display: none;" id="load_contacts" alt="" height="18"
							src="<?php echo $this->baseUrl('/public/img/load.gif') ?>">
					</td>
					<td>
					</td>
				</tr>-->
			</table>
	</fieldset>	
	<fieldset id="projectEmployee" style="display: none;" >
		<legend>3)Agregar nuevo empleado</legend>
		<table>
				<tbody>
					<tr>
						<td>*Nombre:</td>
						<td>*Ap. Paterno:</td>
						<td>Ap. Materno:</td>
					</tr>
					<tr>
						<td><?=$this->element->getElement('name_contact2'); ?></td>
						<td><?=$this->element->getElement('surname_contact2'); ?></td>
						<td><?=$this->element->getElement('lastname_contact2'); ?></td>
					</tr>
					<tr>
						<td>*E-Mail:</td>
						<td>*Tel&eacute;fono local:</td>
						<td>Extensi&oacute;n:</td>
					</tr>
					<tr>
						<td><?=$this->element->getElement('mail_contact2'); ?><br><span style="display: true;" id="malMail"></span></td>
						<td><?=$this->element->getElement('phone_contact2'); ?></td>
						<td><?=$this->element->getElement('ext_phone2'); ?></td>
					</tr>
					<tr>
						<td>M&oacute;vil:</td>
						<td>* Cargo: </td>
					</tr>
					<tr>
						<td><?=$this->element->getElement('cellphone_contact2'); ?><br></td>
						<td><?=$this->element->getElement('id_job2'); ?><br></td>
					</tr>
				</tbody>
			</table>
			
			<fieldset>
			<legend>Datos de acceso y seguridad</legend>
		    <table>
		        <tbody>
		            <tr>
		          		<td><label>* Privilegio:</label></td>  
		            </tr>
		            <tr>
		            	<td><h2>Empleado</h2></td>
		            </tr>
		            <tr>
		            	<td><label>* Clave de usuario:</label></td>
		            	<td>&iquest;Puede entrar a horus?</td>
		            </tr>            
		            <tr>
		               	<td>
		               		<?=$this->element->getElement('user_name2'); ?>
		               		<img id="loaderUser" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
		               	</td>
		               	<td><?=$this->element->getElement('canlogin2'); ?></td>
		            </tr>
		            <tr>
		            	<td><label>* Contrase&ntilde;a:</label></td>
		                <td colspan="2"><label>* Confirmar contrase&ntilde;a:</label></td>
		            </tr>
		            <tr>
		                <td>
		                	<?=$this->element->getElement('password2'); ?>
		                	<div id="showErrPass2" style=" padding: 3px; font-size: 10px; width: auto; height: auto; position: absolute; background-color: #FFEE7C; z-index: 1; float: right; display: none;"></div>
		                	<img id="loaderPass2" style="display: none;" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
		                </td>
		               	<td><?=$this->element->getElement('confirm_password2'); ?><?=$this->element->getElement('subPay2');?></td>
		            </tr>
		        </tbody>
		    </table>
		    <table>
		    	<tbody>
		    		<tr>
		    			<td></td>
		    			<td class="center"><span id="labelkey" hidden="true"> Clave  Generada:</span></td>
		    			<td></td>
		    		</tr>
		    		<tr>
		    			<td></td>
		    			<td class="center"><?=$this->element->getElement('key2');?></td>
		    			<td><input type="button" id="subPay3" name="reset" value="Limpiar"/></td>
		    		</tr>
		    	</tbody>
		    </table>
		</fieldset>
    		<div class="center">	
				<?=$this->element->getElement('GuardarContact2'); ?>
				<?=$this->element->getElement('CancelarContact2'); ?>
			</div>
	</fieldset>
	<fieldset>
		<legend>4) Costos</legend>
		<div class="maininvoiceLow">
			<div>
				<table style="margin-left:15%; margin-right:15%;">
					<tr>
						<td><label for="quantity">* Cantidad:</label></td>
						<td><label for="concept">* Concepto:</label></td>
						<td><div class="center"><label for="unityPrice">* Precio:</label></div></td>
						<td><label for="unityPrice">Importe:</label></td>
						<td><a href="javascript:addit();"><img class="iconOpacity"
								src="<?php echo $this->baseUrl('/public/img/icons/'.$view->iconset.'/iconplus.png');?>"> </a>
							<p id="badTable"></p>
						</td>
					</tr>
					<tr>
						<td><?=$this->element->getElement('quantity'); ?></td>
						<td><?=$this->element->getElement('concept'); ?></td>
						<td><div class="center"><?=$this->element->getElement('unityPrice'); ?></div></td>
						<td><?=$this->element->getElement('price'); ?></td>
						<td></td>
					</tr>
				</table>
				<div style="margin-left:25%;">
					<img id="load" src="<?php echo $this->baseUrl('/public/img/loadtd.gif')?>">
					<table id="invoicedetail" class="display">
						<thead>
							<tr>
								<th>id</th>
								<th>Cantidad</th>
								<th>Concepto</th>
								<th>Importe Unit.</th>
								<th>Importe</th>
								<th></th>
							</tr>
						</thead>
						<tbody>
						</tbody>
					</table>
				</div>
			</div>
		</div>
	</fieldset>
	<fieldset>
		<legend>5) Ingresa las condiciones de Pago</legend>
		<table class="formsshorttable"  style="margin-left:15%;">
			<tbody>
				<tr>
					<td>*N&uacute;mero de pagos:</td>
					<td><?=$this->element->getElement('numberofpayments');?>
						<?=$this->element->getElement('value'); ?>
					</td>
					<td>&nbsp;</td>
				</tr>
				<tr>
				<td colspan="3">
				<fieldset>
				<legend>Detalle</legend>
				<table>
					<tbody>
					<tr>
						<td>COSTO:</td><td><?=$this->element->getElement('cost'); ?></td>
					</tr>
					<tr>
						<td>IMPORTE:<input type="hidden" id="amhid" value="0" name="amhid">
						</td><td><?=$this->element->getElement('amount'); ?></td>
						<th><label for="slideram">% de Utilidad:</label></th>
						<td>0%<br><img src="<?php echo $this->baseUrl('/public/img/trian.png') ?>"/><br>
							<div style="margin-left:5px; margin-bottom: 10px;">
							  <div id="slideram" style="width: 100%;"></div>
							</div>
						</td>
					</tr>
					<tr>
						<td>Anticipo:</td><td><?=$this->element->getElement('advance'); ?></td>
					</tr>
					<tr>
					<td>Descuento:</td><td><?=$this->element->getElement('descto'); ?></td>
					<th><label for="sliderper">% de Descto:</label></th>
					<td>0%<br><img src="<?php echo $this->baseUrl('/public/img/trian.png') ?>"/><br>
						<div style="margin-left:5px; margin-bottom: 10px;">
						      <div id="sliderper" style="width: 100%;"></div>
						</div>
					</td>
					</tr>
					<tr>
						<td>SUBTOTAL:</td><td><?=$this->element->getElement('subtotal'); ?></td>
					</tr>
					<tr>
						<td>I.V.A:</td><td><?=$this->element->getElement('tax'); ?></td>
					</tr>								
					<tr>
						<td>TOTAL:</td><td><?=$this->element->getElement('total'); ?></td>
					</tr>
					</tbody>
				</table>
				</fieldset>
				</td>
				</tr>
			</tbody>
		</table>
	</fieldset>					
	<div>

	</div>

	<div class="center">
		<?= $this->element->getElement('Guardar'); ?>
	    <a href="javascript:location.href='<?=$this->baseUrl("/In/prospectprojects/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
	</div>
</div>
</div>
<!-- 
    Inicia popup
-->
<div id="paysPop" class="popHorus">
	<h2>Especifique las fechas de cobro.</h2>
	<div id="btnAccept">Aceptar</div>
	<ul id="paysArea"></ul>
</div>
<div id="paysBack"></div>