<?php
	$this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/1000.js'));
	$this->headLink()->appendStylesheet($this->baseUrl('/public/css/paysPop.css'));
 ?>

<script>
	$(document).ready(function() {
		
		$("#name_company").change(function(){
			$(".nClie").html('"' + $(this).val() + '"');
		});

		if($("#name_company").val() != ""){
				$(".nClie").html('"' + $("#name_company").val() + '"');
		}
	
		$('#user_name').change(function(){
			var user_name = $(this).val();
			validaUser_Name(user_name, $(this));
		});
	
		$('#mail_contact').change(function(){
			var mail = $(this).val();
			validaEmail(mail, $(this));
		});
		
		$('#rfc').change(function(){
			var rfc = $(this).val();
			validaRfcSupplier(rfc, $(this));
		});
		
		if($('#canlogin').is(':checked')){
			
			$('.PrivilegSection').show("slow");
			
			$('#customerForm').removeAttr('onSubmit');
			$('#customerForm').attr("onSubmit", "return isEmptyForm('customerForm',14)");
			
			$('#password').attr("class", "Required::canBeNull");
			$('#passwordCon').attr("class", "Required::canBeNull");
			
			$('#user_name').removeAttr('class');
			
			$('#password').hide();
			$('#passwordCon').hide();
			
			$('.hide').hide();
			$('#subPay').hide();

		}else{
			
			$('.PrivilegSection').hide("slow");
			
			$('#customerForm').removeAttr('onSubmit');
			$('#customerForm').attr("onSubmit", "return isEmptyForm('customerForm',13)");
			
			$('#user_name').attr("class", "Required::canBeNull");
			$('#password').attr("class", "Required::canBeNull");
			$('#passwordCon').attr("class", "Required::canBeNull");
			
			$('#password').hide();
			$('#passwordCon').hide();
			
			$('.hide').hide();

		}
		
		$('#canlogin').change(function(){
			if($('#canlogin').is(':checked')){
				$('.PrivilegSection').show("slow");
				$('#customerForm').removeAttr('onSubmit');
				$('#customerForm').attr("onSubmit", "return isEmptyForm('customerForm',16)");
				
				$('#user_name').removeAttr('class');
				$('#password').removeAttr('class');
				$('#passwordCon').removeAttr('class');
				
				$('#password').show();
				$('#passwordCon').show();
				
				$('#user_name').val("");
				
				$('.hide').show();
				$('#subPay').show();
			}else{
				$('.PrivilegSection').hide("slow");
				$('#customerForm').removeAttr('onSubmit');
				$('#customerForm').attr("onSubmit", "return isEmptyForm('customerForm',13)");
				
				$('#user_name').attr("class", "Required::canBeNull");
				$('#password').attr("class", "Required::canBeNull");
				$('#passwordCon').attr("class", "Required::canBeNull");
			}
		});
		
		$(".nClie").html('"' + $("#name_company").val() + '"');
		
	$('#subPay1').click(function(){
		$('#password').val("");
		$('#passwordCon').val("");
		$('#key').val("");
		$('#key').hide();
		$('#labelkey').hide();
		$('#subPay1').hide();
	});

	$('#subPay').click(function(){
		var a = azar();
		$('#key').val(a);
		$('#password').val(a);
		$('#passwordCon').val(a);
		$('#key').show();
		$('#labelkey').show();
		$('#subPay1').show();
	});
	
		$('#password').change(function(){
			validpass($(this).val(), $('#submitbutton'));
		});
	});
</script>
<script>
    var caracter="1234567890";
    caracter+="ABCDEFGHIJKLMNOPQRSTUVWXYZ";
    caracter+="abcdefghijklmnopqrstuvwxyz";
    var numero_caracteres=8;
    var total=caracter.length;

    function azar(){
    	var clave="";
    	for(a=0;a<numero_caracteres;a++){
    		clave+=caracter.charAt(parseInt(total*Math.random(1)));
    	}
    	return clave;
    }
</script>

<div id="fieldsetForm" class="forms">
<?=$this->element->getElement('id_company'); ?>
<?=$this->element->getSubForm('base')->getElement('id_address'); ?>
<?=$this->element->getElement('action'); ?>
<?=$this->element->getElement('id_contact'); ?>
<?=$this->element->getElement('id_user'); ?>
<legend id="legendhelp">* Datos requeridos</legend>
<fieldset>
<legend>Informaci&oacute;n comercial</legend>
    <table  >
        <tbody>
         	<tr>
            
                <td>* Nombre o Raz&oacute;n social:</td>
                <td>* Marca:</td>
                <td>Interesado en: </td>
            </tr>
            <tr>
                <td>
                	<div class="form-group has-success has-feedback">
                	<?=$this->element->getElement('name_company'); ?>
                	</div>
                </td>
                <td><?=$this->element->getElement('brand'); ?></td>
                <td><?=$this->element->getElement('interestingin'); ?></td>
            </tr>
            <tr>
            	 <td>* RFC:</td>
                 <td>Sitio web:</td>
                 <td>* Giro de la empresa:</td>
            </tr> 
            <tr>
            	<td>
            		<?=$this->element->getElement('rfc'); ?>
            		<img id="loaderRfc" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
            	</td>
                <td><?=$this->element->getElement('website'); ?></td>
                <td><?=$this->element->getElement('business'); ?></td>
            </tr>
        </tbody>
    </table>
</fieldset>
<fieldset id="fieldset-address">
<legend>Direcci&oacute;n</legend>
    <table>
        <tbody>
         <tr>
             	<td colspan="2">Calle:</td>
                <td>*N&uacute;mero exterior:</td>
                <td>N&uacute;mero interior:</td>
            </tr>
            <tr>
	            <td colspan="2"><?=$this->element->getSubForm('base')->getElement('street'); ?></td>
               	<td><?=$this->element->getSubForm('base')->getElement('number'); ?></td>
               	<td><?=$this->element->getSubForm('base')->getElement('interior'); ?></td>
            </tr>
        	 <tr>
              	<td>*Estado:</td>
                <td>*Delegaci&oacute;n o Municipio:</td>
            	<td>*Colonia:</td>
            	<td>*C&oacute;digo Postal:</td>
            </tr>
            <tr>
            	<td><?=$this->element->getSubForm('base')->getElement('state_id');?></td>
               	<td ><?=$this->element->getSubForm('base')->getElement('district'); ?><img style="display:none" id="load" alt="" height="18" src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"></td>
               	<td><?=$this->element->getSubForm('base')->getElement('neighborhood'); ?><img style="display:none" id= "load_neighborhood" alt="" height="18" src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"></td>
				<td><?=$this->element->getSubForm('base')->getElement('postalcode'); ?></td>           
			</tr>
            <tr>
            	<td>Tel&eacute;fono conmutador:</td>
            	<td>Extensi&oacute;n:</td>
            	<td>URL Mapa:</td>
            </tr>
            <tr>
               	<td><?=$this->element->getSubForm('base')->getElement('phone'); ?></td>
               	<td><?=$this->element->getSubForm('base')->getElement('ext'); ?></td>
               	<td><?=$this->element->getSubForm('base')->getElement('url_map'); ?></td>
            </tr>
        </tbody>
    </table>
</fieldset>
<fieldset>
<legend>Informaci&oacute;n de contacto</legend>
    <div>Este contacto será el favorito para el cliente <span class="nClie">?</span></div>
    <table>
        <tbody>
             <tr>
             	<td>* Nombre:</td>
                <td>* Ap. Paterno:</td>
                <td>Ap. Materno:</td>
            </tr>
            <tr>
            	<td><?=$this->element->getElement('name_contact'); ?></td>
               	<td><?=$this->element->getElement('surname_contact'); ?></td>
               	<td><?=$this->element->getElement('lastname_contact'); ?></td>
            </tr>
             <tr>
                <td>* Puesto:</td>
                <td>Tel&eacute;fono local:</td>
            </tr>
            <tr>
               	<td><?=$this->element->getElement('id_job');?></td>
               	<td><?=$this->element->getElement('phone_contact'); ?></td>
            </tr> 
             <tr>
            	<td>M&oacute;vil:</td>
            	<td>* E-Mail:</td>
            </tr>
            <tr>
            	<td><?=$this->element->getElement('cellphone_contact'); ?><br></td>
               	<td><?=$this->element->getElement('mail_contact'); ?>
               		<p id="malMail"></p>
               		<img id="loaderEmail" style="display: none;" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
               	<br></td>
            </tr>
        </tbody>
    </table>
</fieldset>
<fieldset>
		<legend>Datos de acceso y seguridad</legend>
			<div id="canLog">
				<pan>¿Puede entrar a Horus?</span>
				<?=$this->element->getElement('canlogin'); ?>
			</div>
			<table class="PrivilegSection" style="display: none;">
				<tbody>
					
					<tr class="hide">
						<td>Privilegio:</td>
					</tr>
					<tr class="hide">
						<td><h2>Cliente</h2></td>
					</tr>
					<tr>
						<td>* Clave de usuario:</td>
					</tr>
					<tr>
						<td><?=$this->element->getElement('user_name'); ?>
							<img id="loaderUser" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
						</td>
					</tr>
					
					<tr>
						<td><label class="hide">* Contrase&ntilde;a:</label></td>
						<td><label class="hide">* Confirmar Contrase&ntilde;a:</label></td>
					</tr>
					<tr>
						<td>
							<?=$this->element->getElement('password'); ?> 
							<div id="showErrPass" style=" padding: 3px; font-size: 10px; width: auto; height: auto; position: absolute; background-color: #FFEE7C; z-index: 1; float: right; display: none;"></div>
	                		<img id="loaderPass" style="display: none;" src="<?php echo $this->baseUrl('/public/img/loader.gif'); ?>">
						</td>
						<td><?=$this->element->getElement('passwordCon'); ?> <?=$this->element->getElement('subPay');?></td>
					</tr>
				</tbody>
			</table>
			<table class="PrivilegSection" style="display: none;">
		    	<tbody>
		    		<tr class="hide">
		    			<td></td>
		    			<td class="center"><span id="labelkey" hidden="true"> Clave  Generada:</span></td>
		    			<td></td>
		    		</tr>
		    		<tr class="hide">
		    			<td></td>
		    			<td class="center"><?=$this->element->getElement('key');?></td>
		    			<td><input type="button" class="hide" id="subPay1" name="reset" value="Limpiar"/></td>
		    		</tr>
		    	</tbody>
	 		</table>
 </fieldset>
	<div class="center"> 
    <?=$this->element->getElement('Guardar');?>
    <a href="javascript:javascript:history.back();" class="horusCancelBtn big icon-cancel">Cancelar</a>
	</div>
</div>
