<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>GLÁNDULA</i></font></font><font color="#000066"><font size="5" style="font-size: 18pt"><i>
PITUITARIA</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
glándula pituitaria –</font></font><a href="http://eswikipediaorg/wiki/Pituitaria"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>pituitaria</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
se encuentra en la base del cerebro, que más adelante veremos, y
encima del paladar Entre las funciones que tiene esta glándula, se
encuentra generar y secretar la hormona del crecimiento, misma
que retiene </font></font><a href="http://eswikipediaorg/wiki/Aminoacidos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>aminoácidos</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
con los cuales se forma la </font></font><a href="http://eswikipediaorg/wiki/Proteina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>proteína</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
La escasez de esta </font></font><a href="http://eswikipediaorg/wiki/Hormona"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>hormona</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">hace
que la gente no crezca, de ahí que haya enanos o gente de baja
estatura Por el contrario, cuando es abundante, se produce el
gigantismo y la gente es muy alta, inclusive, puede crecerle de
manera anormal cualquier parte del cuerpo, como la nariz, las manos,
la mandíbula, los brazos, etc A la pituitaria también se le
llama </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>glándula
maestra</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Esto es debido a que genera </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>hormonas</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">para
que otras glándulas generen a su vez otras hormonas, como más
adelante lo veremos</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>pituitaria
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">produce
una hormona que envía a la </font></font><a href="http://eswikipediaorg/wiki/Gl%C3%A1ndula_tiroides"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>glándula
tiroides</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
través de la sangre</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="GLÁNDULATIROIDES"></a>
