<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 20pt"><i>GLÁNDULA
TIROIDES</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
glándula se encuentra delante del cuello y produce la hormona
llamada</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><a href="http://eswikipediaorg/wiki/Tiroxina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroxina</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
misma que tiene como función aumentar la respiración Además
la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroxina</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
en cantidades suficientes, hace que la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>pituitaria</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
no produzca la hormona que estimula a la tiroides para producir
la tiroxina Cuando la tiroxina baja, entonces la pituitaria
vuelve a producir su hormona para que la </font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroides</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><a href="http://wwwyoutubecom/watch?v=QjgZ8TqZWgE&amp;nofeather=True"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
<a href="http://wwwyoutubecom/watch?v=bpv0qrUmT5Q&amp;nofeather=True">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=jgzQwfK4Olo&amp;nofeather=True">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=Il_AgbXX0CQ&amp;nofeather=True">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?v=XKhwTeqda7A&amp;nofeather=True">VIDEO
5</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">produzca
más tiroxina Es decir, ellas mismas se regulan No pueden fallar,
porque entonces hay un desequilibrio y se presentan alteraciones en
el funcionamiento de otros órganos y causan enfermedad</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Recordemos
que la respiración es para obtener </font></font><a href="http://eswikipediaorg/wiki/Oxigeno"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>oxígeno</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
del medio ambiente, el cual es llevado a las células para que
se genere energía desbaratando a la glucosa Por supuesto se genera
en esta reacción química bióxido de carbono, que hay que
expulsarlo porque es venenoso Por lo tanto, si no hay
suficiente oxígeno, no se genera suficiente energía que
requieren las células, tejidos y órganos debido a la falta también
de la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroxina</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
producida por la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroides</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entonces
la gente se siente cansada, lógicamente siente frío, no tiene
ganas de hacer nada, baja la intensidad de los latidos del corazón y
como no hay oxidación de los alimentos, entonces la persona
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“engorda”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
La obesidad trae consecuencia mayores provocando un
desequilibrio que puede llevar a la muerte, pasando por la
enfermedad y situaciones psicológicas y fisiológicas desastrosas</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Uno
de los principales elementos químicos de la </font></font><a href="http://eswikipediaorg/wiki/Tiroxina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroxina</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
es el </font></font><a href="http://eswikipediaorg/wiki/Yodo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>yodo</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>I</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)</font></font><font size="3" style="font-size: 12pt">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=ZEeB5MECi3Y">VIDEO
1</a> –</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Cuando
el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>yodo</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>I</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
le falta a la tiroides, ésta no puede funcionar adecuadamente,
ya que se inflama de manera exagerada y generando lo que se
llama </font></font><a href="http://eswikipediaorg/wiki/Bocio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>bocio</b></i></font></font></a><font size="3" style="font-size: 12pt">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=iO7TzFi9OZs">VIDEO
1</a> –</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lógicamente
al estar en estas condiciones, la glándula </font></font><a href="http://eswikipediaorg/wiki/Tiroides"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroides</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
no produce la hormona tiroxina, y al no producirla hace que
la glán-dula </font></font><a href="http://eswikipediaorg/wiki/Pituitaria"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>pituitaria</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
genere su hormona, de manera permanente, porque al no haber tiroxina
está en permanente estimulación para estar obligando, a través de
su hormona, a la tiroides</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">a
que trabaje, formándose el bocio En estas condiciones, la
persona que padece bocio, si es menor de edad, no crece ni se
desarrolla bien, además de tener una inteligencia anormal Si la
persona es adulta, sufre de hinchazón en la cara y manos, se vuelve
torpe y habla lentamente Por el contrario, cuando la glándula
tiroides produce demasiada tiroxina, la persona se vuelve muy
nerviosa e inestable y tiene la necesidad de respirar muy
rápido, porque precisamente por lo inestable y nerviosa
requiere más oxígeno y produce más bióxido de carbono que
requiere expulsar</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
anterior nos explica, y debemos comprender, la dependencia entre
órganos, tejidos y células, que deben estar sanos para un
desarrollo armónico y sustentable Además, y muy importante, es que
debemos tener conciencia de la buena alimentación, que sea
suficiente y balanceada, que nos permita tener todos los elementos y
compuestos químicos que requiere el cuerpo humano para su buen
funcionamiento y conservar la salud</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pero
también es muy importante tener conciencia de que no basta comer lo
suficiente y balanceado, sino lo sano de los alimentos, sobre
todo el agua y el aire, lo cual se logra evitando la </font></font><a href="http://eswikipediaorg/wiki/Contaminaci%C3%B3n"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>contaminación</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
  </font></font>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ya
hemos visto lo que sucede si no hay </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>yodo</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>I</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
por eso, debemos comer rábanos, que contienen yodo; la sal (</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>NaCl</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
que es cloruro de sodio, debe llevar también yodo, por lo que
debemos consumir la sal yodatada</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="GLANDULAPARATIROIDES"></a>
