<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>GLÁNDULA
PARATIROIDES</i></font></font></b></font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Dentro
de las glándulas </font></font><a href="http://eswikipediaorg/wiki/Gl%C3%A1ndula_tiroides"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>tiroides</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
se encuentran las glándulas </font></font><a href="http://eswikipediaorg/wiki/Paratiroides"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>paratiroides</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que son cuatro La hormona que producen estas glándulas paratiroides
es de suma importancia, ya que regula el metabolismo del </font></font><a href="http://eswikipediaorg/wiki/Calcio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>calcio</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Ca</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
y del </font></font><a href="http://eswikipediaorg/wiki/Fosforo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>fósforo</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>P</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
El </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>calcio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Ca</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
tiene una gran importancia, ya que la falta de este elemento químico,
que además es un metal, nos produce trastornos, como que no nos
permite una buena coagulación cuando tenemos alguna herida en
algún tejido El calcio, por lo tanto, es base de las plaquetas El
calcio ayuda a los músculos a contraerse, es decir a tener
movimiento La falta de calcio produce espasmos en los músculos
También ayuda a regular el sistema nervioso que más adelante
veremos</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
calcio se encuentra también formando parte de los </font></font><a href="http://eswikipediaorg/wiki/Huesos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>huesos</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
 </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=L0Wie56plQ4">VIDEO
1</a>   – <a href="http://wwwyoutubecom/watch?v=ONCFwXy0JT0&amp;feature=related">VIDEO
3</a> – </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
de los </font></font><a href="http://eswikipediaorg/wiki/Dientes"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>dientes</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
La falta de calcio genera la osteoporosis –</font></font><a href="http://eswikipediaorg/wiki/Osteoporosis"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>osteoporosis</b></i></font></font></a><font size="3" style="font-size: 12pt">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
<a href="http://wwwyoutubecom/watch?v=tu-5LfSlXBk">VIDEO 3</a> –
<a href="http://wwwyoutubecom/watch?NR=1&amp;v=RUeb3iQlJY0">VIDEO 5</a>
–</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Esta es otra razón para comer alimentos suficientes y
balanceados que contengan calcio, como la leche, los huevos,
pescados, frijoles, espinacas, etc Por supuesto cocinadas con agua y
aire sanos</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
otro lado, la importancia del </font></font><a href="http://eswikipediaorg/wiki/Fosforo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>fósforo</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>P</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
se debe a que participa en la división de las células y, por
supuesto, en su crecimiento, de ahí su presencia fundamental
También participa en la formación de los </font></font><a href="http://eswikipediaorg/wiki/Huesos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>huesos</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que más adelante veremos, y de los dientes Interviene en la
formación de los músculos y de la formación de las células El
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>fósforo</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>P</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
se encuentra en las carnes, leche, frutas, granos, huevos y
legumbres; lo cual confirma la importancia de la alimentación
suficiente, balanceada y sana Al igual que con el </font></font><a href="http://eswikipediaorg/wiki/Calcio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>calcio</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
la falta de fósforo genera en la persona, debilidad, temblores,
anorexia, decaimiento y problemas de respiración Además,
en caso de faltar o que hubiera demasiado fósforo, afecta el
que se pueda absorber el calcio y viceversa, si no hay suficiente
calcio, no se puede absorber el fósforo Deben estar en equilibrio</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="GLÁNDULASUPRARRENALES"></a>
