<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>INSULINA</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
</font></font><a href="http://eswikipediaorg/wiki/Pancreas"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>páncreas</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
actúa como una glándula que produce varias hormonas que ya hemos
visto y que son los jugos pancreáticos que ayudan a la digestión
Pero también produce una importantísima hormona llamada </font></font><a href="http://eswikipediaorg/wiki/Insulina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>insulina</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
cuya principal función es controlar el aprovechamiento de la
glucosa, por parte de las células La insulina</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">hace
que las células absorban la glucosa necesaria para su desarrollo
normal Cuando la insulina</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">no
es producida por el páncreas, entonces las células no se
pueden alimentar con la glucosa y no realizan su trabajo, con los
trastornos graves que esto conlleva, ya que todas las células de
todos los tejidos y de todos los órganos no se alimentan, por lo que
irremediablemente nadie cumple con su función y sobreviene la
muerte</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
esta enfermedad de falta de</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><a href="http://eswikipediaorg/wiki/Insulina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>insulina</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
se le llama </font></font><a href="http://eswikipediaorg/wiki/Diabetes_mellitus_gestacional"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>diabetes
mellitus</b></i></font></font></a><font size="3" style="font-size: 12pt">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=QYyS_wtuYpA">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=qTJoQSzq0Zg&amp;feature=related">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=NwmOr8SaZII&amp;feature=related">VIDEO
3</a> –</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
glucosa se queda en el torrente sanguíneo y es cuando se dice
que la persona tiene altos los niveles de azúcar Se generan
trastornos de presión sanguínea, no se generan plaquetas y se
corre el riesgo de que cualquier herida no cicatrice y haya
desangrados, pero corre el riesgo de la gangrena, que lleva a mutilar
piernas, manos, etc En los ojos se produce el </font></font><a href="http://eswikipediaorg/wiki/Glaucoma"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>glaucoma</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Los riñones se afectan gravemente al igual que el hígado, por
exceso de trabajo y pocos nutrientes Esto nos debe hacer conciencia
de la necesidad de prevenir la salud con una buena alimentación y
evitar contaminaciones con alcohol, cigarros, y los que ya hemos
visto Es una manera de cuidar nuestro cuerpo y que pueda
desarrollarse armónicamente con su entorno</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="_GÓNADAS"></a><a name="GÓNADAS"></a>
