<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>VITAMINAS</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b><a href="http://eswikipediaorg/wiki/Vitaminas">vitaminas</a>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">son
unas </font></font><a href="http://eswikipediaorg/wiki/Coenzima"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>coenzimas</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
muy necesarias al cuerpo humano; ya que la función de estos
compuestos es hacer que se realicen funciones químicas que
permitan a las células cumplir con su trabajo Las vitaminas no
las produce el cuerpo humano, las producen las plantas y están
compuestas de glucosa y minerales El cuerpo humano no necesita
grandes cantidades de </font></font><a href="http://eswikipediaorg/wiki/Vitaminas"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>vitaminas</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
con las que obtienen a través de sus alimentos es suficiente  Sin
embargo, es necesario comer frutas, legumbres y vegetales
para obtener estas </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>vitaminas
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
</font></font><a href="http://eswikipediaorg/wiki/Minerales"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>minerales</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
que se requieren</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Cuando
el cuerpo humano no tiene esas vitaminas, porque no se le
proporcionan con los alimentos, entonces no se pueden hacer las
reacciones químicas en las células para generar sustancias que se
requieren, como ya lo hemos visto Por lo tanto, se generan
enfermedades y trastornos en el individuo</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_A"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
A</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,
RETINOL</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=RH-ND0XIYJ4">VIDEO
1</a> –</b></font></font><font face="Lucida Fax, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entre
sus funciones está la de tener una visión normal, piel
fresca y ayuda contra infecciones Cuando no se tiene esta </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>vitamina</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
provoca enfermedades de los ojos, piel seca, riesgos de infección
Por lo tanto, se debe comer: zanahorias, hígado, huevos,
mantequilla, espinacas, lechuga y frutas</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_B"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
B</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,
TIAMINA</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=S0_6pFm_Rs4">VIDEO
1</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ayuda
al buen funcionamiento del sistema nervioso y del corazón, así como
también del buen funcionamiento del sistema digestivo</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
falta de esta vitamina provoca insuficiencia cardiaca, nerviosismo,
trastornos digestivos, trastornos cerebrales y fatiga Por lo tanto,
se debe comer: cereales, hígado, carne de cerdo, huevos,
patatas, nueces, legumbres</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Riboflavina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
B2</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,
RIBOFLAVINA</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
Sus funciones principales son la transformación de los
hidratos de carbono y que funcionen bien las membranas mucosas
La falta de esta vitamina en los menores de edad hace que su
crecimiento sea retardado En los mayores, y de todas las
edades, se provocan enfermedades de los ojos, agrietamiento de
los labios y comisuras de la boca, problemas en la piel, pérdida
de pelo y afectación al sistema nervioso Por eso es necesario
comer: hígado, huevos, leche, zanahorias, cereales</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_B-6"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
B6</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,
PIRIDOXINA</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
–</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
<a href="http://wwwyoutubecom/watch?v=gSS4Q0nt1_Y">VIDEO 2</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Sus
principales funciones son Transformación de los aminoácidos y
los ácidos grasos, también hace que funcione bien el sistema
nervioso y mantiene la piel sana Cuando se carece de esta
vitamina, se produce anemia, trastornos nerviosos, pelagra,
diarrea y, en los niños, poco crecimiento y convulsiones Por
eso se debe comer: pescado, legumbres, hígado, leche, carne de
cerdo, nueces</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_B-12"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
B12</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,
COBALAMINA</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=FZ2QSSo2u3k">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=GcWWmCBWuoQ&amp;feature=related">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=c8aS42ZiDG4">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=FZ2QSSo2u3k">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=keMm-BcPrNQ">VIDEO
5</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entre
sus principales funciones está la de formar y madurar los glóbulos
rojos, que como ya vimos, son los que transportan el oxígeno a todas
las células y recogen el bióxido de carbono para ser expulsado
durante la respiración También, la vitamina participa para el buen
funcionamiento del sistema nervioso El carecer de ella provoca
una </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>anemia
perniciosa</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
ya que no se generan glóbulos rojos y por lo tanto hay escasez
de oxígeno en todas las células, principalmente en el cerebro,
por lo que se provocan lesiones nerviosas y cerebrales; hay
debilidad, palidez, se reduce la producción de jugos gástricos,
y falta de visión Por lo cual se debe comer: hígado, carnes de res
y cerdo, huevos y leche</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_C"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
C</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=x8CZysbYw70">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=3K9Y3eejSlw">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=z4XH8QYjJB0">VIDEO
3</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entre
las principales funciones de esta vitamina está la de formar y
hacer crecer los tejidos de los huesos y de los dientes, así como
también del tejido conjuntivo; ayuda al buen funcionamiento de
los vasos sanguíneos La carencia de esta vitamina provoca:
escorbuto, hemorragias en las encías, caída de los dientes, dolor
en las articulaciones e inflación de las encías Para obtener esta
vitamina se debe comer: naranjas, toronjas, limones, guayaba,
tomates, col, verduras, pimientos verdes y papas</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_D"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
D</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=YKTIKcXTGSk">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=qUa9QtvlRMU">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=7U1VA0G7AsM">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=4QOh56Iya-M">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?v=XGjLCNcpdUw">VIDEO
5</a> – <a href="http://wwwyoutubecom/watch?v=K_V5QOAur6Y&amp;feature=related">VIDEO
6</a> – <a href="http://wwwyoutubecom/watch?v=q_ZH7gAEDXo&amp;feature=related">VIDEO
7</a> –</b></font></font><font face="Lucida Fax, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
principal función de esta vitamina es la absorción de calcio y
fósforo, para el crecimiento y reparación de los huesos y dientes
La falta de esta vitamina produce raquitismo, así como el
crecimiento y mantenimiento de huesos en forma anormal Se
producen también temblores musculares Pueden torcerse las
piernas; sufrir caries dentales inflamación de las articulaciones
Esta vitamina se sintetiza en la piel mediante la luz solar Por eso
hay que asolearse alrededor de 15 minutos También se puede
obtener comiendo: pescado y huevos</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_E"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
E</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
La función de esta vitamina es ser antioxidante, lo cual significa
proteger a todas las células del cuerpo contra lesiones que
compuestos químicos pueden producir La falta de esta vitamina
produce rotura de los glóbulos rojos, cuya importancia ya
la hemos visto También provoca lesiones nerviosas, lo cual
redunda en reflejos disminuidos, dificultad para caminar, pérdida
de equilibrio y debilidad muscular Esta vitamina la obtenemos
si comemos: lechuga, germen de trigo, huevos, vegetales de
hojas verdes y legumbres</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Vitamina_K"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VITAMINA
K</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
Su principal función es ayudar en la coagulación de la sangre El
no contar con esta vitamina nos produce hemorragias de la piel, de la
nariz, del estómago o de una herida; se producen vómitos y se
pueden llegar a presentar hemorragias cerebrales Esta vitamina
la podremos obtener si comemos: hígado, col, espinacas y
tomates</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/%C3%81cido_f%C3%B3lico"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ÁCIDO
FÓLICO</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=LaL1k2ALGFk">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=gI710TFaUhw&amp;feature=related">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=S_urkKWf_oE">VIDEO
3</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Su
principal función es la maduración de los glóbulos rojos La falta
de este ácido puede producir anemia Debemos comer: hígado,
vegetales de hojas verdes y frutas</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Estas
son las principales vitaminas que requiere el cuerpo, aunque hay
otras más Además de vitaminas, el cuerpo requiere de algunos
minerales que le permitan reacciones químicas que formen compuestos
necesarios para las células, tejido y órganos, para un
desarrollo armónico de la persona</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="_MINERALES"></a><a name="MINERALES"></a>
