<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>MINERALES</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Potasio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>POTASIO</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>(K)</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>-</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Este mineral es del que más se encuentra en el cuerpo humano y sirve
para tener un buen funcionamiento de los músculos y del sistema
nervioso Además, regula el balance del agua en el organismo Ayuda
a eliminar los excesos del </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Sodio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Na</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
  </font></font>
</p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
falta de </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Potasio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
(K)</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
hace que la gente se sienta débil, tiene náuseas, se vuelve
irritable y puede tener alteraciones cardiacas El </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Potasio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>K</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
lo encontramos comiendo: plátano, leche, ciruelas, uvas, pasas
El consumo excesivo de café, té y alcohol, hace perder </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Potasio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>K</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
ya que estimula el orinar mucho y en la orina se va el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Potasio</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>K</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
ya que interviene en la formación de la he-moglobina</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Hierro"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>HIERRO</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>(Fe)</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Hierro</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Fe</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
es el principal componente de los glóbulos rojos y de las células
de los músculos La falta de </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Hierro</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Fe</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
nos produce anemia, ya que como hemos visto, es parte de los glóbulos
rojos y la disminución de éstos produce la anemia La falta
del hierro hace que las uñas de doblen; se tienen problemas en
el aprendizaje y además, no se tiene rendimiento en las actividades
de la persona; también se tienen alteraciones de la conducta
debido precisamente a la falta de oxígeno a las células del
cerebro, porque no hay suficientes glóbulos rojos, cuyo componente
principal es el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Hierro</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Fe</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
Este mineral se encuentra en nuestros alimentos como: frijoles,
carne, hígado, chícharos, almejas, frutas secas y huevo</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Zinc"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ZINC</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>(Zn)</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
El </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Zinc</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Zn</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
es el componente de la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>insulina</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b></b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Ya hemos visto la importancia de la insulina, ya que es la que actúa
para que todas las células del cuerpo se puedan alimentar La falta
de insulina produce la enfermedad </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>diabetes
mellitus</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Al ser también componente de otras enzimas, ayuda a aumentar la
inmunidad contra infecciones bacteriológicas y ayuda a evitar los
daños que causa el humo de cigarros Ayuda a la maduración sexual
Se le encuentra en las uñas y huesos La falta del </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Zinc</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Zn</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)
causa anemia, disminución del sentido del gusto, problemas de
la próstata y problemas menstruales, problemas de
cicatrización, pérdida de apetito, del olfato y problemas
sexuales Por eso es importante comer: mariscos, hígado, pescado,
huevo y leche El consumo de café, tabaco y alcohol en
exceso, baja los niveles del </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Zinc</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Zn</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">),
con las consecuencias que ya hemos visto</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Manganeso"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>MANGANESO</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Mn</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)-</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Este mineral es el componente de varias enzimas y es muy importante
para la estructura ósea y el desarrollo de los tejidos La falta de
este mineral provoca dolor de las articulaciones, fiebre,
malformación de huesos, lento crecimiento de uñas y pelo,
inflamación de los ganglios linfáticos y agrandamiento del hígado
Por eso debemos comer: cereales, frutas secas, vegetales de
hojas verdes, huevo y pan integral</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<a href="http://eswikipediaorg/wiki/Magnesio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>MAGNESIO</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Mg</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Este mineral también es componente de varias enzimas, mismas
que sirven para la formación de huesos y dientes También para el
buen funcionamiento de los músculos y los nervios, ya que
participa en la transmisión de impulsos nerviosos, así como la
contracción y relajación de los músculos, o sea, el movimiento
La falta de este mineral provoca nerviosismo anormal, calambres,
nauseas, problemas cardíacos, convulsiones, debilidad muscular De
ahí la necesidad de comer: mariscos, pescado, nueces, frutas secas,
chocolate, germen de trigo, verduras, lechuga, espinacas Pierden
mucho </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Magnesio
</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">(</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Mg</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
las personas que tienen vómitos, los alcohólicos crónicos,
los enfermos de cirrosis, y los que toman diuréticos</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos estado observando, todo es química y se utilizan los
elementos químicos que ya hemos visto para la realización
de reacciones químicas, que forman compuestos necesarios para
la vida celular, el mantenimiento de los tejidos y el buen
funcionamiento de los órganos, que en conjunto, permiten el
desarrollo armónico y sustentable del ser humano, al igual que
de las plantas y los animales</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Hemos
visto lo que es la ingestión de alimentos, su digestión, la
absorción de los nutrientes y el desecho de los restos de alimentos
que sobraron y que no son necesarios Pero también hemos estado
observando que, a través del trabajo de las células, las
cuales se alimentan de los nutrientes que fueron absorbidos por
el intestino delgado y que fueron enviados al hígado y a todas
las células por conducto del torrente sanguíneo, se generan
reacciones químicas que producen compuestos necesarios a la vida del
ser humano Al mismo tiempo, también se generan desechos de estas
reacciones químicas y que no son necesarios al cuerpo
humano y hay que expulsarlos del organismo Esto lo vamos a ver
ahora a través del aparato excretor</font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 049in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="SISTEMAEXCRETOR"></a>
