<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>SISTEMA
EXCRETOR</i></font></font></b></font></font></p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ya
hemos visto que en el torrente sanguíneo se encuentran los
nutrientes que cada célula escoge para su mantenimiento,
crecimiento, reproducción y, sobre todo, su función, entre la que
sobresalen las secreciones que hacen para que otras células las
utilicen y puedan realizar su función Pero, además, cada célula
desecha compuestos que ya no necesita pero que son resultado de las
reacciones químicas que realizó y que el cuerpo debe expulsar
Además en el torrente sanguíneo se encuentran también
excesos de nutrientes que hay que desechar como azúcar</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Precisamente
quien regula excesos y desecha compuestos no necesarios, e inclusive
dañinos al organismo, es el </font></font><a href="http://eswikipediaorg/wiki/Sistema_excretor"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>sistema
excretor</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=vP40wkFfVWE">VIDEO
1</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">que
está formado por los</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
riñones</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="RIÑONES"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>RIÑONES</b></i></font></font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
</font></font><a href="http://eswikipediaorg/wiki/Ri%C3%B1ones"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>riñones</b></i></font></font></a><font size="3" style="font-size: 12pt">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b><a href="http://wwwyoutubecom/watch?v=VEisWU-Mxq8">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=HT0WNqBCbvg">VIDEO
2</a> –</b></font></font><font face="Lucida Fax, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">son
dos órganos que tiene el cuerpo humano, uno de cada lado de la
columna vertebral y a la altura del dorso Cada </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>riñón</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
está compuesto por más de un millón de </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>nefrones</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Cada </font></font><a href="http://eswikipediaorg/wiki/Nefron"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>nefron</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">realiza
la función del riñón, y está constituido por </font></font><a href="http://eswikipediaorg/wiki/Glom%C3%A9rulo_renal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>glomérulos</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y éstos se encuentran en una cápsula llamada </font></font><a href="http://eswikipediaorg/wiki/C%C3%A1psula_de_Bowman"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>bowman</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
en túbulo y una serie de vasos capilares Dentro del nefron se hace
un filtrado de la sangre que llega a través de la vena cava inferior
y aorta dorsal, mismos que conectan al riñón a través de la
arteria renal y la vena renal</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
nefron filtra la sangre que trae productos de desecho, agua, glucosa
y sales Devuelve a la sangre los nutrientes útiles y los
desechos se convierten en </font></font><a href="http://eswikipediaorg/wiki/Orina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>orina</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
<a href="http://wwwyoutubecom/watch?v=PyZKpw8T_gU&amp;NR=1">VIDEO 2</a>
–</b></font></font><font face="Lucida Fax, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
compuestos de desecho normalmente son productos nitrogenados que se
formen al descomponer los aminoácidos que están compuestos por
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>aminos</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">formados
por </font></font><a href="http://eswikipediaorg/wiki/Nitr%C3%B3geno"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>nitrógeno</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
como ya hemos visto; for-mándose </font></font><a href="http://eswikipediaorg/wiki/Amoniaco"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>amoníaco</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
sustancia muy venenosa y su acumulación sería fatal; a estos
compuestos se les llama </font></font><a href="http://eswikipediaorg/wiki/Urea"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>urea</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y </font></font><a href="http://eswikipediaorg/wiki/%C3%81cido_%C3%BArico"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ácido
úrico</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
El ácido úrico se forma por la descomposición de ácidos
nucleicos El ácido úrico es insoluble en el agua, por lo que se
forman cristales que se acumulan en las articulaciones, provocando
fuertes dolores y se le conoce como </font></font><a href="http://eswikipediaorg/wiki/Gota_(enfermedad)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>gota</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
En bajas cantidades, el ácido úrico estimula la actividad mental
La urea</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">es
soluble en el agua y forma parte de la orina El </font></font><a href="http://eswikipediaorg/wiki/Ri%C3%B1on"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>riñón</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
también excreta azúcar, ácidos, y grasas, en exceso, ya que
una función del riñón es guardar el equilibrio</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h1 lang="es-MX" class="western"><a name="TEMAVIII"></a><font color="#000066"><font size="6" style="font-size: 22pt"><i>INDICE
- TEMA VIII</i></font></font></h1>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
