A PRIMER INDICE</span></b></span></font></font></a><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX"><b>
</b></span></font></font>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-inside: avoid; page-break-after: avoid"><a name="CEREBROYSISTNERVIOSO"></a>
<font color="#404040"><font face="Cambria, serif"><font size="2" style="font-size: 10pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>CEREBRO
Y SISTEMA NERVIOSO</b></i></font></font></font></font></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Después
de que hemos visto cómo se forma el </span></font></font><a href="http://eswikipediaorg/wiki/Cuerpo_humano"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cuerpo
humano</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y gran parte de la </span></font></font><a href="http://eswikipediaorg/wiki/Naturaleza"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>naturaleza</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
así como lo asombroso de la función de cada órgano, su
mantenimiento y su restauración, ahora veremos otras maravillas de
nuestro cuerpo, que nos hacen </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tener</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Todos
los seres humanos sentimos, reaccionamos, nos enojamos, estamos
alegres, tristes, sanos; olemos, vemos, saboreamos, nos movemos,
comemos, sentimos dolor, cosquillas; tenemos calor o frío;
dormimos y despertamos; tenemos recuerdos; sufrimos
depresiones, estrés; pensamos, lloramos, reímos, amamos,
deseamos, odiamos; tenemos rencores; nos enfermamos, tenemos mareos;
pintamos, cantamos, fumamos; gritamos y hablamos; escribimos;
manejamos y operamos computadoras; nadamos y jugamos; y tantas
y tantas cosas que el ser humano es capaz de hacer diariamente</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Al
mismo tiempo, podemos sentir comezón por la ropa que traemos puesta;
al mismo tiempo estamos escuchando música y platicando con alguien;
también estamos observando a la persona con la que platicamos y a
nuestro alrededor; también podemos estar saboreando un cigarro y
café; de la misma manera estamos oliendo el aroma del café, de la
loción de nuestro acompañante, el smog; todo al mismo tiempo
Pero somos capaces de discriminar Solo ponemos atención a lo que
nos interesa o nos produce algún sobresalto o gusto; como podría
ser un tronido grande que nos alarma y nos llama más la atención y
nos pone en alerta O puede ser la voz de alguien que nos llama y nos
produce una agradable sensación Una charla nos puede poner triste o
hacer llorar O contentos y hacer reír O la charla nos produce
coraje y agredimos a una persona, verbal o físicamente O
la charla nos produce un sentimiento de confianza y agradecimiento  </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Un
ruido puede hacer que corramos; si sentimos frío, nos cobijamos, nos
ponemos un saco o una cobija Si sentimos calor, nos quitamos parte
de la ropa Podemos sentir sed y buscamos un líquido para saciarla;
si tenemos hambre, buscamos algo para comer Cuando tenemos sueño
nos vamos a dormir Podemos sentir ganas de una necesidad
fisiológica, como orinar, y buscamos dónde hacerlo   </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Tomamos
decisiones y actuamos Estudiamos y trabajamos Lo anterior, solo son
algunas acciones y reacciones que realiza el ser humano Las
preguntas que nos hacemos: ¿por qué somos capaces de hacerlo?,
¿cómo lo hacemos?, ¿qué hace que nos pase todo eso?, y otras
preguntas, todo se lo debemos al cerebro – </span></font></font><a href="http://eswikipediaorg/wiki/Cerebro"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cerebro</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
al </span></font></font><a href="http://eswikipediaorg/wiki/Sistema_nervioso"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>sistema
nervioso</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–</b></font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Toda
acción del ser humano se debe a que recibe </span></font></font><a href="http://eswikipediaorg/wiki/Est%C3%ADmulo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>estímulos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=u_V1GNBTTTo">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">del
exterior o del interior del individuo; asimismo estímulos internos,
que se generan dentro del cuerpo humano Los </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>estímulos
externos</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
se reciben a través de los </span></font></font><a href="http://eswikipediaorg/wiki/Sentidos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>sentidos</i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
como son: oído – </span></font></font><a href="http://eswikipediaorg/wiki/Oido"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>oído</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=HKblTQfOJJ4">VIDEO 1</a>,   
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>el
tacto –</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><a href="http://eswikipediaorg/wiki/Tacto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tacto</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=vwrVgjE6g9o">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=yqfY-unzYLY">VIDEO 2</a>, </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>el
olfato –</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><a href="http://eswikipediaorg/wiki/Olfato"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><span lang="es-MX"><i><b>olfato</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=2jyXUrgkexo">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=XckpfULCmVE">VIDEO 2</a>,  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
vista, –</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
 </b></font></font><a href="http://eswikipediaorg/wiki/Vista"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>vista</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
 <a href="http://wwwyoutubecom/watch?v=2WGdqA0k-is">VIDEO 6</a></b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>y
el gusto – </b></span></font></font><a href="http://eswikipediaorg/wiki/Gusto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>gusto</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=cWQV82bpwbc">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b><a href="http://wwwyoutubecom/watch?v=qyF_lHSmvo4">VIDEO
2</a> – </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
ejemplo, cuando tocamos algo muy caliente y sentimos que nos
quemamos, inmediatamente retiramos la mano Al sentir algo que quema,
a través del </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tacto</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">se
envía una señal por medio de una </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>red</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>de
nervios</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que son parte del </span></font></font><a href="http://eswikipediaorg/wiki/Sistema_nervioso"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>sistema
nervioso periférico</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=6oDmSbfwUFE">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=0-7y4KJEZng&amp;feature=related">VIDEO
2</a> –</b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="SISTNERVIOSOPERIFÉRICO"></a>
