<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>SISTEMA
NERVIOSO AUTÓNOMO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Como
ya hemos visto, el sistema nervioso del cuerpo humano está dividido
en el </span></font></font><a href="http://eswikipediaorg/wiki/Acto_reflejo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>sistema
somático-sensorial</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que es el que se encuentra en todo el cuerpo y recibe todos los
estímulos internos y externos y los envía al sistema nervioso
autónomo, el que emite las ordenes de acción y las envía, a través
del mismo sistema nervioso somático-sensorial, para que se
cumplan</span></font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
sistema nervioso autónomo está conectado con los órganos internos
como, el </span></font></font><a href="http://eswikipediaorg/wiki/P%C3%A1ncreas"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>páncreas</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Coraz%C3%B3n"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>corazón</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Higado">hígado</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><a href="http://eswikipediaorg/wiki/Pulmones"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>pulmones</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Est%C3%B3mago"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>estómago</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Intestinos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>intestinos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
etc, además, con una serie de glándulas, con el objeto de
que, en forma autónoma, controlar y ordenar su funcionamiento
en cualquier momento y circunstancia Este sistema autónomo está
conectado directamente de la </span></font></font><a href="http://eswikipediaorg/wiki/Medula_espinal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>médula
espinal</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Este
sistema nervioso autónomo es de una vital importancia, y sobre todo,
de un gran interés por parte de la gente que desea conocerse y
comprender, el por qué reacciona de diferentes maneras El por
qué su estado de ánimo, e inclusive, algunas enfermedades
Veamos el por qué:</span></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
