<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>TÁLAMO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
</span></font></font><a href="http://eswikipediaorg/wiki/T%C3%A1lamo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tálamo</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=vyEIdF9YTM0">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=rJUakT3wWgE">VIDEO 2</a> –
<a href="http://wwwyoutubecom/watch?v=LLIxP_R9IfQ&amp;NR=1">VIDEO 3</a>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">es
una estructura que se encuentra abajo del cerebro y encima del bulbo
raquídeo Su función es recibir todos los estímulos y conectarlos
con el cerebro Asimismo, recibe las órdenes del cerebro y las envía
al sistema nervioso del bulbo raquídeo y la médula espinal,
con el objeto de hacer reaccionar a la parte conveniente del cuerpo
Por ejemplo, si una persona sintió un golpe, la señal pasa por el
tálamo y éste envía la señal al cerebro De igual manera la orden
del cerebro, que envía a través del tálamo, llega al hipotálamo,
el cual cumplirá con su función de ordenar la emisión de enzimas
que ayuden a soportar el dolor</span></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="HIPOTÁLAMO"></a>
