<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>CEREBRO
</i></font></font></b></font></font>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Como
ya lo hemos mencionado, el </span></font></font><a href="http://eswikipediaorg/wiki/Cerebro"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cerebro</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">se
encuentra dividido en dos hemisferios, el izquierdo y el derecho
Cada hemisferio está dividido en cuatro lóbulos: </span></font></font><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_frontal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lóbulo
frontal</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=oiK9fOjKAx8">VIDEO 1</a>  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">es
el que está al frente del cráneo El </span></font></font><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_parietal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lóbulo
parietal</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=jYvProEHPpI">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">se
encuentra en la parte media del cráneo El </span></font></font><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_temporal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lóbulo
temporal</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=2OcpH_3nNGI">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">es
el que se encuentra abajo del parietal y el </span></font></font><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_occipital"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lóbulo
occipital</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que se encuentra atrás del cráneo</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">En
el </span></font></font><a href="http://eswikipediaorg/wiki/Cerebro"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cerebro</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">se
encuentran las maravillas de la </span></font></font><a href="http://eswikipediaorg/wiki/Memoria"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>memoria</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=BbVsh3ooFCw">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?NR=1&amp;v=PxQB3yP4QY8">VIDEO 2</a>
– <a href="http://wwwyoutubecom/watch?v=a2cdjASosH4">VIDEO 3</a>
– <a href="http://wwwyoutubecom/watch?NR=1&amp;v=3XTug46extA">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?feature=fvwp&amp;NR=1&amp;v=0boHDct-kpU">VIDEO
5</a> – </b></font></font><a href="http://eswikipediaorg/wiki/Inteligencia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>inteligencia</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Entendimiento"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>entendimiento</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Conciencia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>conciencia</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Sentimiento"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>sentimientos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Deseo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>deseos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Emociones"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>emociones</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Crisis"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>crisis</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Recuerdos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>recuerdos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Visi%C3%B3n"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>visión</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Olfato"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>olfato</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Gusto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>gusto</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><a href="http://eswikipediaorg/wiki/Tacto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tacto</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/O%C3%ADdo">oído</a>,
<a href="http://eswikipediaorg/wiki/Conducta">conducta</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que le per-mitan a la persona desarrollarse como persona y
como integrante de la sociedad También su relación
familiar, con la naturaleza, le permite defenderse y defender
su entorno Ser feliz y dar felicidad Realizarse y ayudar
a los demás a realizarse Estar en permanente bús-queda
de la verdad Aprender nuevas habilidades para enfrentar
los nuevos retos</span></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Diariamente,
el ser humano vive nuevas realidades, nuevos hechos y nuevas
experiencias, que le proporcionan satisfacciones o frustraciones;
alegría o tristeza; emoción y pasión, estrés o relajamiento, etc
Todo lo que vivimos lo guardamos, lo almacenamos en el cerebro y le
llamamos </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Memoria">memoria</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
La memoria se almacena en el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_frontal">lóbulo
frontal</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Aquí se nos presenta una maravilla Cuando vivimos una experiencia,
tenemos la gran oportunidad de compararla con una experiencia
parecida que traemos de la memoria, lo que nos permite tener una
mejor reacción Por ejemplo: nos presentan a una persona y la
conocemos por primera vez Registramos y almacenamos todo lo que
percibimos de ella, como su imagen, voz, olor, y todo lo que nos
agradó Cuando la volvemos a ver, comparamos la imagen de ese
momento con lo que tenemos almacenada en la memoria, entonces podemos
reaccionar saludando a esa persona de una manera más afectuosa,
porque nos causa alegría Pero, también es cierto, que si la
comparación es diferente, porque ahora nos causa una imagen
desagradable, podemos reaccionar no tan agradablemente, porque nos
causa un desengaño Esta es una de las grandes maravillas del
cerebro del ser humano Por eso, debemos aprovechar y disfrutar
de este gran </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Don_(tratamiento)">don</a></b></i></span></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="EMOCIONES"></a>
