<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>CONOCIMIENTO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Es
muy cierto que, a pesar de que nos guste o no una realidad que
vivimos, vamos buscando un método, una estrategia para
enfrentar todos los retos que vivimos en todo momento La verdad de
los casos que nos suceden, y la forma óptima de enfrentarlos, nos
van dando un conocimiento que nos hará tener un equilibrio
emocional y por tanto, que nos de </span></font></font><a href="http://eswikipediaorg/wiki/Salud"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>salud</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
mental y física</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="SENTIDOS"></a>
