<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>SENTIDOS</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Todas
las experiencias y vivencias que tenemos en todo momento durante
nuestra vida, es a través de los cinco</span></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
</span></font></font></font><a href="http://eswikipediaorg/wiki/Sentidos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>sentidos</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="LAVISTA"></a>
