<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>PUPILA</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
orificio en medio del iris se llama </span></font></font><a href="http://eswikipediaorg/wiki/Pupila"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>pupila</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
La función de la pupila es abrirse o cerrarse, dependiendo la
cantidad de luz que recibe el ojo El cerrarse o abrirse la pupila es
de manera automática, dependiente de la intensidad de la luz Si la
luz es muy tenue, la pupila se dilata, se abre más, para dejar pasar
más luz Si la luz es muy intensa, la pupila se contrae evitando un
deslumbramiento Esto también es con el objeto de proteger al
ojo y tener una mejor visión</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Recordemos
que cuando tenemos algún imprevisto, como una agresión que nos pone
en alerta, se pone en funcionamiento la glándula que secreta la
</span></font></font><a href="http://eswikipediaorg/wiki/Adrenalina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>adrenalina</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y ésta estimula, entre otros órganos, al ojo, dilatando la pupila
para que la persona pueda ver mejor y poder tomar una acción Esto
nos da idea de que cada célula, órgano o sistema, es un todo y todo
está integrado, no puede fallar nada</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="RETINA"></a>
