<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>RETINA</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
tercera membrana dentro del ojo se llama </span></font></font><a href="http://eswikipediaorg/wiki/Retina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>retina</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
La función de esta retina es la de recibir las imágenes de luz que
le llegan del exterior, grabarlos y retenerlos, como lo hace la
película de una cámara fotográfica</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="CRISTALINO"></a>
