<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>CRISTALINO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Detrás
del </span></font></font><a href="http://eswikipediaorg/wiki/Iris"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>iris</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">se
encuentra el </span></font></font><a href="http://eswikipediaorg/wiki/Cristalino"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cristalino</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Es la parte del ojo que es una lente, el cual se contrae o se dilata,
haciéndose delgado o grueso, dependiendo la distancia de la imagen
que se está viendo, para hacerla más nítida Es lo mismo que hace
un fotógrafo con su cámara, para “enfocar” la imagen y hacerla
nítida, dependiendo la distancia Esto se hace de manera automática
Por eso podemos ver de lejos y de cerca con mucha nitidez Cuando la
persona no puede enfocar bien los objetos y los ve borrosos, tanto de
lejos y/o de cerca, es que el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cristalino</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
no está funcionando bien y es necesario usar lentes para corregir
esa  anomalía,  que  puede  ser   </span></font></font><a href="http://eswikipediaorg/wiki/Astigmatismo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>astigmatismo</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,
 </b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
 <a href="http://wwwyoutubecom/watch?v=H5DlINcNjqk">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?NR=1&amp;v=Q7LPergg00U">VIDEO 2</a>
– <a href="http://wwwyoutubecom/watch?v=SBNElFZGbVY&amp;feature=related">VIDEO
3</a> –  </b></font></font><a href="http://eswikipediaorg/wiki/Miopia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>miopía</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">o
</span></font></font><a href="http://eswikipediaorg/wiki/Presbicia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>presbicia</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
aunque puede haber otras anomalías como </span></font></font><a href="http://eswikipediaorg/wiki/Catarata"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>cataratas</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">o
</span></font></font><a href="http://eswikipediaorg/wiki/Glaucoma"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>glaucoma</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
cristalino está sostenido y controlado por los </span></font></font><a href="http://eswikipediaorg/wiki/Ligamento_suspensorio_del_cristalino"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ligamentos
suspensorios</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que se encuentran en cada extremo</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="HUMORACUOSO"></a>
