<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>OLFATO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
</span></font></font><a href="http://eswikipediaorg/wiki/Olfato"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>olfato</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
es la percepción de olores cuando, de manera natural, respiramos
Este fenómeno se realiza cuando al respirar, pasa el aire por la
nariz, donde están localizados los </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>epitelios
olfatorios</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i></i></span></font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Estos
epitelios constan de células receptoras de moléculas que producen
las personas, animales, flores, frutas; compuestos químicos como
gasolinas, ácidos, comidas, etc Estas moléculas, al pasar por la
nariz cuando respiramos, son atrapadas por el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Moco">mocus</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que cubre los epitelios y producen la sensación de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Olor">olor</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Esta sensación de olor genera impulsos nerviosos que van al </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Nervio_olfativo">nervio
olfatorio</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que conecta con el cerebro y, en específico, con el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_frontal">lóbulo
frontal</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Cada vez la maravilla de los sentidos se va haciendo más grande
Ahora, nos damos cuenta que podemos vivir las escenas en tercera
dimensión, a todo color, con sonido y con olor Podemos disfrutar de
un jardín, observando plantas, pájaros, flores, a diversas
distancias, haciendo un bonito paisaje Además, podemos disfrutar
la variedad de colores que nos presenta ese jardín</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
si fuera poco, disfrutamos los sonidos, como el canto de los pájaros,
el aire Además, el perfume de las flores, del paso y nuestro propio
olor Esta maravilla debemos disfrutarla y aprovecharla para
crear un ambiente de tranquilidad, de reflexión, de equilibrio
emocional Algunas veces tenemos problemas con el olfato, y éste
disminuye o se pierde totalmente cuando tenemos alguna infección en
las vías respiratorias Sin embargo, la naturaleza tiene más para
nosotros Este algo más es el sentido del gusto</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="GUSTO"></a>
