<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt">GUSTO</font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Cuando
comemos o bebemos algo, y con la ayuda de la saliva, estimulamos las
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Papilas_gustativas">papilas
gustativas</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que se encuentran en la </span></font></font><a href="http://eswikipediaorg/wiki/Lengua"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lengua</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
en el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Paladar">paladar</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
</span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Las
sensaciones primarias del gusto y que experimentamos cuando comemos
o bebemos son: lo dulce, lo amargo, lo salado y lo ácido En la
parte de arriba y al frente de la lengua se tiene la sensación de lo
salado A los lados de la lengua se tienen las sensaciones de lo
dulce En la parte de atrás y arriba de la lengua es la sensación
de lo amargo Y en la parte de la orilla y arriba de la lengua se
tiene la sensación de lo ácido Todo es debido a que en esas partes
de la lengua están las </span></font></font><a href="http://eswikipediaorg/wiki/Papilas_gustativas"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>papilas
gustativas</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que conectan con las neuronas y éstas con el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Nervio_facial">nervio
facial</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que a su vez conecta con el cerebro en el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_frontal">lóbulo
frontal</a></b></i></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Es
importante saber que el gusto también tiene una muy estrecha
relación con la temperatura, de ahí los alimentos calientes o
fríos A su vez, tiene que ser el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Tacto">tacto</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
ya que en el gusto influye la dureza o blandura de los alimentos
Pero también el olor de los alimentos, que al ser masticados se
escapan vapores que van a la cavidad nasal, estimulando el nervio
olfativo, lo que hace que los alimentos los podamos disfrutar desde
varios sentidos, causando un extraordinario placer De ahí, la
importancia del buen comer o la cultura de la alimentación</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Algunas
veces notamos que no tenemos sabor y tampoco gusto por la comida,
esto se da cuando tenemos gripe o malestares de infección, ya que
normalmente se congestionan los epitelios olfatorios Ahora
veremos otro importantísimo sentido</font></font></p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="TACTO"></a>
