<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>TACTO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Los
seres humanos tenemos la capacidad de sentir estímulos en todo el
cuerpo, ya que la piel que nos cubre tiene una serie de receptores
táctiles que nos permiten sentir frío, calor, presión Cuando
tocamos algo sentimos si es duro, blando, áspero, liso, sólido o
líquido Esto es el tacto Algunas partes de nuestro cuerpo son más
sensibles que otras Por ejemplo, las manos y la lengua son más
sensibles que la piel de los brazos o las piernas   </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Uno
de los principales receptores táctiles es el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Corp%C3%BAsculos_de_Pacini">corpúsculo
de pacini</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Este receptor llamado corpúsculo de pacini es un receptor de
presión, el cual nos hace sentir cuando algo nos toca o lo tocamos,
ya que al presionar con el toque, este receptor se deforma Al
deformarse genera una corriente eléctrica, que es enviada a la
médula espinal y de ahí al cerebro, en especial, en el </span></font></font><a href="http://eswikipediaorg/wiki/L%C3%B3bulo_parietal"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>lóbulo
parietal</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
quedan grabados estos estímulos, independientemente de las órdenes
de acción, de acuerdo al tipo de estímulo</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="margin-bottom: 0in; line-height: 100%">
<font face="Tahoma, serif"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Como
hemos podido observar, los cinco sentidos que alimentan con
estímulos al cerebro son una maravilla, ya que nos hacen
experimentar, pensar y desarrollar la inteligencia, la cual nos va
creando hábitos y habilidades, que son parte de nuestra conducta,
carácter y personalidad Estimula nuestros sentimientos,
emociones y pasiones Veamos un ejemplo muy positivo:</font></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Estamos
en un jardín lleno de flores, árboles, pájaros, mariposas; nos
encontramos en un lugar muy propicio para comer unos suculentos
platillos Tenemos la oportunidad de ver esa escena en tercera
dimensión, a todo color, con el sonido de los pájaros y el viento;
el olor de las flores y de los aromas de la comida, la cual tiene una
presentación sugestiva; comemos con el gusto de saborear esos
platillos y bebidas, sintiendo el crujir del pan y la suavidad de la
carne bañada con una rica salsa, sintiendo la temperatura de la
comida en la boca Además, sentimos en la piel el roce del aire y la
temperatura del medio ambiente, sin frío ni calor</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Todos
los sentidos, al mismo tiempo, nos hicieron disfrutar del día y de
la escena Todo lo almacenamos en la memoria, por lo que siempre lo
recordaremos, ya que también la compañía que tuvimos fue
extraordinaria Esto nos hace ser felices, estar tranquilos y
relajados; nos hace pensar en lo bonito de la vida y que es la
compensación al esfuerzo que hemos realizado para tener esos
momentos Nuestro carácter se vuelve amable Renace el amor Nos
olvidamos de las tristezas Nos estimula para continuar con más fe y
ganas, luchando por la vida, realizándonos Nos hace tener </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>salud</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
mental y física   </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Pero
también es cierto que podemos tener experiencias nada agradables,
vemos cosas desagradables en ese mismo lugar, como un perro muerto en
estado de descomposición, con olor desagradable; escuchamos
voces de asco; nos espinamos; comemos algo muy duro; se rompió un
diente Es verdad, pero todo fue en tercera dimensión, a todo color
Escuchamos, sentimos, olemos y tenemos sabor Todo también
quedó grabado en la memoria Esto podría hacernos sentir mal,
vomitar, sentir asco, etc, lo cual cambiaría nuestro buen humor,
habrá frustración, enojo, y tantas cosas que nos harían reaccionar
mal, con coraje, lo que nos lleva a estados anímicos que con el
tiempo llegan a deteriorar nuestra salud física y mental Depende de
nosotros el valor que le demos a los acontecimientos Está en
nosotros superar todo lo que nos afecta de manera negativa Está en
nosotros la decisión de sentirnos bien o mal Todo de acuerdo a
nuestra cultura, comportamiento, conducta y personalidad</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Pero
aun así, lo que experimentamos, bien o mal, lo llevamos y
almacenamos en el cerebro Tenemos la gran oportunidad y la
maravilla de poderlo expresar con palabras, a través de la voz, y
comunicarlo a otras personas</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="VOZ"></a>
