<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>VOZ</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
</span></font></font><a href="http://eswikipediaorg/wiki/Voz_(fonolog%C3%ADa)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>voz</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">es
un sonido que emitimos a través del aire, el cual pasa por la
</span></font></font><a href="http://eswikipediaorg/wiki/Laringe"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>laringe</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
atraviesa por unas membranas llamadas </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Cuerdas_vocales">cuerdas
vocales</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Estas cuerdas vocales se abren al paso del aire cuando respiramos de
manera normal Si jalamos más aire del normal, estas membranas se
abren más, de manera automática Pero cuando deseamos hablar,
emitir nuestra voz, entones el cerebro manda la orden de
cerrarse, y al pasar el aire de los pulmones y del estómago, a
través de la laringe, hacen vibrar estas membranas y se produce el
sonido llamado voz La lengua y los labios realizan una gran
función, son ordenadas por el cerebro para dar los sonidos que
forman las palabras Al estar hablando estamos narrando las vivencias
que tuvimos, las cuales estamos recordando y las estamos
transmitiendo Lo mismo, podemos hacer especulaciones de qué
pudo haber pasado y qué no debió haber pasado, así como qué
conclusión hacer Estas son las grandes maravillas del cuerpo
humano, y sobre todo del cerebro</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Algunas
veces no podemos hablar o hablamos ronco, esto es debido a la
inflamación que puede haber en la laringe y las membranas que
son las cuerdas vocales, debido a la gripe o a alguna infección en
las vías respiratorias que nos pueden causar también garraspera,
tos o sonidos involuntarios</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Dependiendo
del tamaño y dureza de las cuerdas vocales, es el timbre de la voz
Las mujeres tienen esas membranas más delgadas y menos duras, por
eso su voz es más débil Los hombres, por lo general, son todo lo
contrario y su voz es más fuerte y más grave</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="FUNCIONESCEREBRALES"></a>
