<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>FUNCIONES
CEREBRALES</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Ya
hemos dicho que el cerebro está dividido en dos hemisferios Las
funciones del hemisferio izquierdo son controlar la mitad del
cuerpo, el lado derecho Las funciones del cuerpo del lado
izquierdo las controla el hemisferio derecho Pero también
tienen otras funciones los hemisferios</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="HEMISFERIOIZQUIERDO"></a>
