<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>HEMISFERIO
IZQUIERDO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
hemisferio izquierdo tiene el control de la habilidad numérica, de
ahí que se puedan hacer operaciones matemáticas: sumar, restar,
dividir, multiplicar, desarrollar operaciones más complejas,
como el álgebra, trigonometría, etc También tiene el control del
lenguaje hablado; podemos hablar y entender lo que nos dicen;
aprender idiomas Otra función es la de escribir y leer lo escrito
Así también desarrollar habilidades científicas, descubrir el
perfil de las cosas y, por supuesto, el control de los miembros del
lado derecho Pero lo más importante, la función del
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Razonamiento">razonamiento</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Esta cualidad de razonamiento la debemos aprovechar para
analizar, pensar, sacar conclusiones y actuar de la mejor manera,
para tener resultados que nos realicen como seres humanos; así como
tener las mejores relaciones con los demás y con nuestro entorno Si
no aprovechamos esta cualidad, entonces nos dejaremos llevar por
los instintos, el coraje, el resentimiento, y actuaremos mal, lo que
nos ocasionará una cultura que nos lleve a la enfermedad, a la
destrucción, a la infelicidad y a la muerte Está en nosotros
decidir nuestra vida, porque tenemos esa capacidad</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="HEMISFERIODERECHO"></a>
