<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>HEMISFERIO
DERECHO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Las
funciones del </span></font></font><a href="http://eswikipediaorg/wiki/Hemisferio_cerebral"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hemisferio
derecho</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
</span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=lZKDP_Tm9zo&amp;feature=results_video&amp;playnext=1&amp;list=PL62162758DED5685F">VIDEO
1</a> – <a href="http://wwwyoutubecom/watch?v=OKLPL0s6M2Q&amp;feature=autoplay&amp;list=PL62162758DED5685F&amp;lf=results_video&amp;playnext=2">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=fDr0tj3zT9M&amp;feature=autoplay&amp;list=PL62162758DED5685F&amp;lf=results_video&amp;playnext=3">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=QTXT7pxDDC4&amp;feature=related">VIDEO
4</a> –</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">controlan
los miembros del lado izquierdo Además, podemos percibir lo
tridimensional Ahí se encuentra el sentido artístico, por eso
nos gusta pintar y observar las grandes pinturas, o la música, que
nos motiva, el baile que disfrutamos, el teatro, el cine, etc
También se encuentra la </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Imaginativo">perspicacia</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que nos hace prevenir tratar de adivinar el por qué de las cosas y
qué hacer Otra función importante es la de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Imaginacion">imaginar</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Crear escenas, situaciones, obras, y tantas cosas Con todo lo
anterior podemos </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Ser">ser</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
</i></span></font></font><a href="http://eswikipediaorg/wiki/Hacer"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><a href="http://eswikipediaorg/wiki/Propiedad_(derecho)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tener</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
todo lo que nos hace felices y nuestra participación con
nuestros semejantes y con la naturaleza Todo lo podemos hacer de
igual manera, negativamente, destruyéndonos y destruyendo
nuestro entorno Depende de la persona todo, ser feliz o infeliz
Construirse o destruirse    </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Sin
embargo, existe gente que toda la capacidad mental la utiliza de
manera destructiva Eso quiere decir que tiene alguna
</span></font></font><a href="http://eswikipediaorg/w/indexphp?search=Enfermedad+mental&amp;title=Especial%3ABuscar"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>enfermedad
mental</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
<a href="http://wwwyoutubecom/watch?v=QOMT61f_Rfs">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?NR=1&amp;v=xjUQky-Wmzc">VIDEO 2</a>
– <a href="http://wwwyoutubecom/watch?v=Ygvk1xwsvAk">VIDEO 3</a>
– <a href="http://wwwyoutubecom/watch?NR=1&amp;v=uZcAYPwrQCk">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=z0r2gLiTYho">VIDEO
5</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=ie0Q14S3sYk">VIDEO
6</a> – </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">por
accidente generalmente, por mala nutrición, genéticamente o
por adicciones</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-inside: avoid; page-break-after: avoid"><a name="ENFERMEDADESMENTALES"></a>
<font color="#404040"><font face="Cambria, serif"><font size="2" style="font-size: 10pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>ENFERMEDADES
MENTALES</b></i></font></font></font></font></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Todas
las neuronas que componen el cerebro, en condiciones normales
requieren de glucosa, que es la energía que en todo momento
requiere el cerebro, así como también necesita del oxígeno Esto
no puede faltar en ningún momento y en ninguna circunstancia,
ya que no habría la energía y la oxigenación necesarias y, por
lógica, morirían, causando muchos trastornos e inclusive la muerte
Esto se logra con una buena alimentación, la que lleva también al
buen funcionamiento de todas las células, órganos y glándulas, que
mantienen la salud física y mental Cuando no se toman los
nutrientes necesarios, las glándulas no producen sustancias
indispensables para órganos y células, trastornando el
funcionamiento de las neuronas que requieren esas sustancias, como la
</span></font></font><a href="http://eswikipediaorg/wiki/Serotonina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>serotonina</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
y </i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Dopamina">dopamina</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que son </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Neurotransmisores">neurotransmisoras</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
De ahí que mucha gente tenga </span></font></font><a href="http://eswikipediaorg/wiki/Depresi%C3%B3n"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>depresiones</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=miVLOSZiSGo">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">por
falta de suficiente concentración de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>serotonina</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>dopamina</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
así como también no poder enfrentar causas externas, como el
</span></font></font><a href="http://eswikipediaorg/wiki/Estr%C3%A9s"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>estrés</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=ZOry9zwSWLY">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=qXLkeE_cWQk&amp;feature=related">VIDEO
2</a>  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">problemas
y falta de recursos</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Vemos
el caso de los niños y gente desnutrida, que no piensa, no tiene
ganas de nada, que no es capaz siquiera de quitarse las moscas,
que no entiende, con muchas enfermedades Todo por falta de una
adecuada alimentación Por lo tanto, el cerebro no puede trabajar
bien y al no hacerlo, no puede controlar ni ordenar al resto del
cuerpo, provocándose todo tipo de enfermedades</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Cuando
no hay los neurotransmisores necesarios, no debe extrañar el mal
carácter, acciones ilógicas que hacen ser </span></font></font><a href="http://eswikipediaorg/wiki/Hiperactivo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hiperactivas</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">a
las personas, sufrir de </span></font></font><a href="http://eswikipediaorg/wiki/Paranoia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>paranoia</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=JwpJrq7iJsc&amp;feature=youtube">VIDEO
1</a> – </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Esquizofrenia">esquizofrenia</a>
</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=4VGP6PkknVs&amp;feature=fvwrel">VIDEO
1</a> – </b></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">También
afectan al cerebro algunos golpes que lo lesionan y destruyen
algunas neuronas, por lo que la persona ya no puede actuar con
normalidad Cuando llegamos a tener algún golpe en la cabeza, aparte
del mismo golpe, podemos sentir dolor de cabeza, debido a alguna
inflamación en el cerebro Muchas veces hay derrames
cerebrales, con consecuencias graves Sentimos también
parálisis, ceguera temporal, mareos, etc Puede ser también causa
de la </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Anorexia">anorexia</a>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
por la falta de apetito, o lo contrario, exceso de apetito, con la
consecuencia de la </span></font></font><a href="http://eswikipediaorg/wiki/Obesidad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>obesidad</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Baja o alta temperatura Reacciones inesperadas y disparatadas</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="_GoBack"></a>
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
supuesto, lo que más daña al cerebro son las adicciones a las
drogas –</span></font></font><a href="http://eswikipediaorg/wiki/Drogadicto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>drogas</b></i></span></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
 </b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=v4xuKp1cSLQ">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=30zhsYsr9Fk">VIDEO 2</a> –
<a href="http://wwwyoutubecom/watch?feature=fvwp&amp;v=9H9Y9Ou4Dqc&amp;NR=1">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=dG3tRP8bAgk">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=-08J6Iadsdc&amp;NR=1">VIDEO
5</a> – <a href="http://wwwyoutubecom/watch?v=MuJLmbv88K8">VIDEO
6</a> – <a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=LVD-sWb2tR8&amp;NR=1">VIDEO
7</a> – <a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=GS41zgpeNfg">VIDEO
8</a> – <a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=z0YYXBcPOD8">VIDEO
9</a>  </b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><span lang="es-MX"><b>y
al, el alcohol, – </b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><span lang="es-MX"><i><b><a href="http://eswikipediaorg/wiki/Alcoholismo">alcohol</a></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– <a href="http://wwwyoutubecom/watch?v=PpCijQOnhkU&amp;feature=related">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=BAOQ2Qzz-Cc&amp;feature=endscreen">VIDEO
3</a> – <a href="http://wwwyoutubecom/watch?v=IScmupcdYNA&amp;feature=related">VIDEO
4</a> – <a href="http://wwwyoutubecom/watch?NR=1&amp;v=NN7qJjgVja8&amp;feature=endscreen">VIDEO
5</a> </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
dependencia de estos compuestos alteran el funcionamiento cerebral
y convierten a las personas en adictas No pudiendo funcionar si no
tienen las drogas, pero al mismo tiempo, las neuronas se van
destruyendo, con las consecuencias graves que esto ocasiona Está en
cada persona cuidar su salud física y mental, que lo llevará a su
realización como ser humano, o a destruirse y llegar hasta la
muerte</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
todo lo anterior, el ser humano ha tenido la capacidad de crear sus
propias normas de conducta para vivir en armonía y de manera
integral, con su sociedad y con la naturaleza</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h1 lang="es-MX" class="western"><a name="TEMAIX"></a><font color="#000066"><font size="6" style="font-size: 22pt"><i>INDICE
– TEMA IX</i></font></font></h1>
<p lang="es-MX" align="center" style="margin-bottom: 0in; line-height: 100%">
<br>
</p>
