<font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>DERECHO</i></font></font></b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Como
ya nos hemos podido dar cuenta del enorme potencial que tiene el ser
humano a través de su cerebro y, sobre todo, que cada persona piensa
y actúa de diferente manera, de acuerdo a su cultura,
educación, capacitación, alimentación, salud mental y física,
su entorno y muchas características más, es que se puede caer en el
caos, en el desorden, porque cada quien quiere poner sus condiciones
de vida, sus ambiciones, sus intereses, inclusive, su propia
justicia; lo cual desencadena una lucha fratricida, una guerra
social que llevaría a la destrucción personal, de la sociedad y de
la naturaleza misma</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
lo anterior, el ser humano, después de muchas luchas históricas, ha
creado una serie de normas que le permitan un desarrollo integral,
congruente, sólido, razonado y armónico, tanto en lo personal como
en su relación con la sociedad, a las cuales les llama: </span></font></font><a href="http://eswikipediaorg/wiki/Derecho_a_decidir"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>derecho</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=uCdB3JLKO4s">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?v=tsyrhFieUQY&amp;feature=related">VIDEO
2</a> – <a href="http://wwwyoutubecom/watch?v=mvsKggBrXp8&amp;feature=related">VIDEO
3</a> –</b></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
primer derecho y más importante del individuo es, </span></font></font><a href="http://eswikipediaorg/wiki/La_vida"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>la
vida</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=mZ7JuIyreAQ">VIDEO 1</a> –
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Sin
la vida no existe nada y, por lo tanto, no existe la razón del
derecho El primer principio universal es el respeto Por ende,
el respeto a la vida es la razón del derecho El primer valor
moral de la persona es el amor El amor a la vida nos da la razón de
existir</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Sin
este primer derecho (la vida), sin este primer principio (respeto) y,
sin este primer valor moral (amor), no hay la razón de existir</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Pero
es importantísimo ver el segundo derecho del individuo, que es </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">la</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=DdMyLxpxPiI">VIDEO 1</a> –
<a href="http://wwwyoutubecom/watch?NR=1&amp;v=dEaeVy7o618&amp;feature=endscreen">VIDEO
2</a> – </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
libertad del trabajo, de la educación, de la formación de la
familia; libertad de tránsito, de realización, de religión, de
preferencias, de todo, pero en especial, de pensamiento Podemos
estar privados de todo por la fuerza, pero siempre </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">el</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><a href="http://eswikipediaorg/wiki/Pensamiento"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>pensamiento</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
estará libre, aún en la peor de las prisiones El pensamiento
viaja a todas partes sin más límite que las capacidades de cada
persona Por lo tanto, si una persona tiene vida y libertad, y
además, el principio universal del respeto y el valor moral del
amor, la persona tiene todo asegurado para conseguir otros dos
derechos de vital importancia, como son, </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">la</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><a href="http://eswikipediaorg/wiki/Propiedad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>propiedad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
 </b></span></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
<a href="http://wwwyoutubecom/watch?v=BqiCFcoL7Po">VIDEO 1</a> </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>–
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">la</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><a href="http://eswikipediaorg/wiki/Felicidad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>felicidad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b></b></i></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
propiedad del patrimonio que con esfuerzo la persona ha conseguido,
tiene el derecho de la posesión y de que todo mundo la respete y la
reconozca La propiedad de una cosa, muebles, vehículos, equipo y
utensilios, obras artísticas, propiedad de un título, que
ampara el esfuerzo realizado para obtener los conocimientos y
experiencias que le permitan desarrollar habilidades a la persona,
para su realización como ser humano</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">En
resumidas cuentas, el ser humano primero tiene que </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>existir</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tener</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
vida</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">,
la cual debe ser respetada por sobre todas las cosas y por todos los
</span></font></font><a href="http://eswikipediaorg/wiki/Seres_humanos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>seres
humanos</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>
</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">vivos</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
 Este es el máximo derecho que todo ser humano tiene Si no hay
vida, si no se existe, no hay nada Inclusive la vida, la existencia
animal y vegetal debe ser respetada, en base a un equilibrio
ecológico De no respetar el ser humano el equilibrio ecológico,
pone en riesgo su propia vida y estará violando el derecho a la </span></font></font><a href="http://eswikipediaorg/wiki/Vida"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>vida</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
propia y a la de los demás seres humanos</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Después
del </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
viene el siguiente derecho que sería el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
El </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
el poder hacer, requiere de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>libertad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
</i></span></font></font><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Libertad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
de acción, pero antes, </span></font></font><a href="http://eswikipediaorg/wiki/Libre_pensamiento"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad
de pensar</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
de </span></font></font><a href="http://eswikipediaorg/wiki/Razonar"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>razonar</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
lo que se va a hacer Así también par hacer bien las cosas se
requiere la </span></font></font><a href="http://eswikipediaorg/wiki/Racionalista"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad
de aprender</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
es decir la educación, la capacitación, la cultura</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b></b></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">significa
también </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>trabajo</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Tener la </span></font></font><a href="http://eswikipediaorg/wiki/Derecho_laboral"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad
de trabajar</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>;</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
trabajar en lo que se desea y puede, de acuerdo a sus
limitaciones y capacidades, libertad de adquirir las </span></font></font><a href="http://eswikipediaorg/wiki/Habilidad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>habilidades</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que se deseen para tener una realización personal, para encontrar
soluciones personales para su familia y sociedad Soluciones
como la alimentación Por lo que se debe tener el derecho a comer lo
que la gente desea, necesita y puede adquirir para su desarrollo
psicológico, físico y fisiológico</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">De
la misma manera, tener la libertad de adquirir la vestimenta que
requiere, de acuerdo a sus necesidades, gustos y posibilidades,
así también su tipo de vivienda que le proteja de las agresiones de
la naturaleza y el entorno que lo rodea Se requiere la </span></font></font><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">para
vivir en donde se desea y se pueda, de acuerdo a sus capacidades</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Las
libertades anteriores redundan en la </span></font></font><a href="http://eswikipediaorg/wiki/Salud"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>salud</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
física y mental del ser humano, a la cual tiene derecho Se requiere
también la </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>libertad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
de trascender, a través de formar su propia familia, en las
condiciones que se desea, sin más límite que el respeto a los
derechos de la familia, que no pueden ser diferentes a las del
</span></font></font><a href="http://eswikipediaorg/wiki/Ser_humano"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ser
humano</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b></b></i></span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Todo
lo anterior, </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">nos
da el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tener</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
tener, es el derecho a la propiedad El hacer es generar riqueza
</span></font></font><a href="http://eswikipediaorg/wiki/Espiritual"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>espiritual</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">y
</span></font></font><a href="http://eswikipediaorg/wiki/Material"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>material</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
por parte del </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser
humano</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
</i></span></font></font><a href="http://eswikipediaorg/wiki/Riqueza"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Riqueza</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que tiene derecho a </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>poseer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>,</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
ya que la generó a través de su hacer</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
riqueza puede ser generada en lo personal o en grupo, pero al fin es
riqueza Si es generada en lo personal, todo es de la persona
que lo generó</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Si
la riqueza fue generada en grupo, se repartirá en forma equitativa y
proporcional, de acuerdo a la inversión que cada persona haya
realizado en tiempo, trabajo y talento</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Cuando
existen los derechos básicos de, </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>vida</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>libertad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>propiedad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
o lo que es lo mismo, </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>vida-ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>;
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>libertad-hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>propiedad-tener</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
como ya lo hemos visto, entonces se consigue el mayor anhelo del </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
humano, la </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>felicidad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que es otro derecho</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">La
</span></font></font><a href="http://eswikipediaorg/wiki/Felicidad_Interna_Bruta"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>felicidad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">consiste
en la </span></font></font><a href="http://eswikipediaorg/wiki/Paz_interior"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>paz
interna</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>
</i></span></font></font><a href="http://eswikipediaorg/wiki/Espiritualidad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>espiritual</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>,</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que siente el </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
humano debido a la satisfacción de obtener todos los satisfactores
(bienes y servicios) que sus necesidades le exigen, para </span></font></font><a href="http://eswikipediaorg/wiki/Vivir"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>vivir</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
de una manera </span></font></font><a href="http://eswikipediaorg/wiki/Dignidad_Humana"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>digna</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
y </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>humana</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b><span style="background: #ffff00">,</span></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
así como en forma integral y armónica en lo personal, en sociedad y
con su entorno</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Asimismo,
la felicidad le da la alegría y la motivación de vivir, para estar
en continua búsqueda de la verdad, que le permita un desarrollo
permanente, sólido y comprometido para lograr condiciones superiores
de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>vida
digna</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>humana</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>;</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
así como el mejor uso de la </span></font></font><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>libertad</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y tener cada vez mejores satisfactores de </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>propiedad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que le incentiven y motiven a </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>ser</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i>,
</i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>hacer</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
y </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>tener</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
para su </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b>felicidad</b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
en un círculo </span></font></font><a href="http://eswikipediaorg/wiki/Virtuoso"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>virtuoso</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><i><b></b></i></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
Esto se llama amor</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Como
hemos observado, el ser humano nace con derechos que Dios le dio El</span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>
</b></span></font></font><a href="http://eswikipediaorg/wiki/Dios"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Dios</b></i></font></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
en el que cada quien crea, o la naturaleza o creación, de acuerdo a
las creencias de cada quien Pero lo importante es que ya se nace con
esos derechos, nadie terrenal se los dio</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Tahoma, serif"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Desafortunadamente,
de acuerdo a los vicios y virtudes de cada ser humano, se llegan a
conculcar esos derechos ¿Conculcar? ¿Y esa palabra qué quiere
decir? Es violar, no respetar o disimular, o alterar esos derechos</font></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Esos
derechos no respetados por algunos seres humanos, nos inducen a
enfrentamientos, pleitos, peleas, enojos, resentimiento, rencores y
odios, que nos llevan a cobrar esos agravios, esas violaciones a los
derechos propios, a la venganza Todos estos ingredientes nos
ocasionan la enfermedad física y mental, que redunda en la
destrucción, en la muerte</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Los
derechos son espontáneos y naturales, es decir, no son creados por
el hombre a su conveniencia ni impuestos por la fuerza Sin embargo,
como se ha podido observar desde tiempos remotos, desde que existe el
hombre, ha habido personas que se sienten superiores, semidioses, que
tienen otros derechos que algún dios les dio y se convierten en
emperadores, reyes, gobernantes, autoridades, etc, de lo que se
valen, para imponerse a las mayorías Gobernadores, administradores,
dirigentes, etc, con el pretexto de que es por el bien del pueblo,
se dicen que son los nuevos Mesías y que lo son por mandato de dios
Y cuando la gente no lo acepta o se revela, entones vienen los
problemas, se usa la fuerza física, la imposición, a través de la
privación de la libertad y, por supuesto, la pérdida de la
vida Se utilizan el miedo, el terror, para someter a la gente Y son
estas personas las que deciden quién tiene derecho a la vida, a la
libertad, propiedad y felicidad Todo se convierte en un poder
perverso, cruel e irracional de unos cuantos, para someter a los
pueblos De ahí la esclavitud, la división de clases sociales, de
ricos y pobres; cultos e ignorantes, etc Estos </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>“iluminados”</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
dicen quién tiene derechos, cuándo y cómo, y cómo se les otorgan</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Pero
también existen </span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX"><b>“personas
enfermas”</b></span></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">
que matan, violan, secuestran, torturan, etc </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Ese
gran sueño, ese paraíso que son los derechos espontáneos y
naturales que tiene el ser humano desde que nace, y que le fueron
entregados por dios o la naturaleza, de acuerdo a las creencias de
cada quien, se desvanece, se obscurece, se convierte para la
mayoría en una amarga verdad, una realidad trágica</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Por
supuesto que también se han aparecido los enviados de dios, que han
formado las religiones, que según ellos tienen como base el amor
Sin embargo, actúan como dictadores, con castigos a los que se
considera que han ofendido a Dios, y esas ofensas las llaman pecados;
por supuesto los castigos son suplicios, torturas, quemados en la
hoguera, etc Caso concreto, la santa inquisición
Independientemente que también tenían sus propios ejércitos
Les gustaban y gusta la guerra La muerte entre seres humanos por
seres humanos ¿Y el amor?     </span></font></font>
</p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Lógicamente,
y en todos los tiempos, autoridades y religiones van a la conquista
de otros pueblos para someterlos y obtener riquezas, así como más
poder Solo basta leer un poco de la historia universal de todos los
tiempos para conocer a los conquistadores y a los pueblos sumisos</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">¿La
maldad solo es exclusiva del hombre? Los animales atacan en defensa
propia y matan para comer Pero, ¿el hombre? no mata para comer,
ataca no solo en defensa propia Los animales no buscan venganza Los
hombres sí la buscan, y lo que es más, la disfrutan ¿Entonces, la
maldad es solo del ser humano? Cada quien tiene el derecho a
contestar esta interrogante y, por supuesto, es válida</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Cada
quien tiene su verdad, y debe ser respetada, aunque no estemos de
acuerdo con ella y aunque nadie esté de acuerdo con nosotros Es la
libertad de pensamiento</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Es
claro que el hombre se convierte en una bestia y si la bestia
prevalece, el hombre cae por debajo de las bestias, porque pone su
entendimiento al servicio de la bestialidad</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">El
problema está en que el mal es contagioso, es una epidemia, y la
mayoría de los seres humanos hemos sido contagiados Hacer el
mal no solo es hacer daño a los demás, sino hacernos daño a
nosotros mismos y, lo más grave, permitir que se lo hagan a los
demás Y lo peor es que no nos damos cuenta que tenemos el mal y lo
estamos contagiando Lo vemos como algo natural, algo normal</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-MX">Tanta
maldad, falta de respeto, abuso, arbitrariedad, rompe con los
límites de la tolerancia y provoca conflictos graves que llaman
a la destrucción y muerte Es cuando surgen seres humanos que
intentan, y muchas veces logran algunos objetivos que detengan en
algo ese desequilibrio que no permite una vida digna y humana</span></font></font></p>
<p lang="es-MX" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="margin-bottom: 0in; line-height: 100%"><br>
</p>
</body>
</html>