<?php 
    $this->headLink()->appendStylesheet($this->baseUrl('/public/css/proposalsStyle.css'));
	$this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/documentsFunctions.js'));
	
	$show = (isset($_GET['edit'])=="true")? $_GET['edit'] : "false";
	$idDoc = (isset($_GET['idDoc']))?$_GET['idDoc'] : "false";
	$idVersion = (isset($_GET['idVer']))?$_GET['idVer'] : "false";
?>
<script>
var show = "<?php echo $show; ?>";
var idDoc = "<?php echo $idDoc; ?>";
var idVersion = "<?php echo $idVersion; ?>";
var separator = "<?php echo SeparatorString::SEPARATOR; ?>";
var separator2 = "<?php echo SeparatorString::SEPARATOR2; ?>";
$(document).ready(function(){
	jqueryTable('#docVersion', 3);
	
	if(show == "true"){
		geContentFields(idDoc, idVersion);
	}
	
	$('.enviarDoc').click(function(){
		editFormDoc();
	});
});	
</script>
<h3 class="centerIn">Versiones del Documento</h3>
<ul class="toolbar">
	<div id="icons">
			<li class="iconOpacity ">
				<a href="<?php echo $this->baseUrl('/Horus/documents/index') ?>"><img title="Documentos" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/icondocgear.png');?>" /></a>
			</li>
			<li class="iconOpacity ">
				<a href="<?php echo $this->baseUrl('/Horus/documents/index?CreAnExp=true') ?>"><img title="Crear una nueva version" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" /></a>
			</li>
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','ayuda')">
				<a><img title="Ayuda"  src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>	
</ul>

<?php if($show == "true"):?>

<div id="fieldsetForm" class="forms">
	<div id="title" style="margin-bottom: 10px;" class="center">
		<h2 style="font-size: 34px;position:relative;color: #000;font-weight: 400;text-shadow: 0px 0px 1px rgba(0,0,0,0.3);padding: 20px;text-transform: uppercase;text-align: center;">Editar Versi&oacuten de documento</h2>
		<br />
	</div>
	
	<div style="margin-left: 20px;">
		<div id="descDoc" style="font-size: 15px; font-weight: bold;"> Descripci&oacute;n Documento: <span id="contDesc" style=" font-size: 15px; font-weight: normal;"><?php echo $this->document['description']; ?></span></div>
	</div>
	<br/>
	<br/>
	<div id="contentDoc" style="padding:10px; border: graytext dashed;">
		<div id="nameDoc" style=" width:60%; font-size: 30px; text-align: center; margin-top: 20px; margin-bottom: 40px; margin-left: 15%;">
			<span id="nameDocText"><?php echo $this->document['name']; ?></span>
			<input id="id_version" type="hidden">
			<input id="date_version" type="hidden">
		</div>
			<?php 
				$pos = "";
				$maxWith = "";
				$minWith = "";
				$cont = 0;
				foreach ($this->field as $field): ?>
				<?php if($field['type'] == 1){ ?>
				   <?php if($field['position'] == 1):?>
						<?php $pos = "35%"; ?>
				   <?php elseif ($field['position'] == 3):?>
						<?php $pos = "65%"; ?>
				   <?php else : ?>
						<?php $pos = "3%"; ?>
			       <?php endif; ?>
					<div <?php echo 'style="width: 200px; margin-left:'.$pos.';"'; ?>>
						<input id="<?php echo $field['id_field']; ?>" style="width: 200px;" type="text" class="element" placeholder="<?php echo $field['label']; ?>"/>
						<input type="hidden" class="position" value="<?php echo $field['position'] . "-*-" . $field['id_field']; ?>">
						<input id="<?php echo "cont-".$cont++; ?>" type="hidden" class="contentField">
					</div>
					<br />
			   <?php }elseif ($field['type'] == 2){ ?>
			  	   <?php if($field['position'] == 2):?>
						<?php 
							$pos = "3%;";
							$maxWith = "30%";
							$minWith = "30%"; 
						?>
				   <?php elseif ($field['position'] == 3):?>
						<?php 
							$pos = "60%";
							$maxWith = "30%";
							$minWith = "30%";  
						?>
				   <?php else : ?>
						<?php 
							$pos = "3%";
							$maxWith = "90%";
							$minWith = "90%"; 
						?>
			       <?php endif; ?>
			        <div>
						<textarea id="<?php echo $field['id_field']; ?>" class="element" style="<?php echo "margin-top:20px; margin-left:$pos; max-width:$maxWith; min-width:$minWith;"?>" placeholder="<?php echo $field['label']; ?>"></textarea>
						<input type="hidden" class="position" value="<?php echo $field['position'] . "-*-" . $field['id_field']; ?>">
						<input id="<?php echo "cont-".$cont++; ?>" type="hidden" class="contentField">
					</div>
					<br />
				<?php } ?>
			<?php endforeach; ?>
	</div>
	<input type="hidden" id="contentReal">
	<div class="center" style="margin-top: 40px;">
		<button class="enviarDoc" id="subPay" >Guardar</button>
		<script>
			var idDoc = "<?php echo $_GET['idDoc']; ?>";
			var v = "<?php echo (isset($_GET['edit']))? $_GET['edit'] : ""; ?>";

			function backList(){
				if(v == "true"){
					location.href = BASE_URL + '/Horus/documents/versions?idDoc=' + idDoc ;
				}else{
					location.href = BASE_URL + '/Horus/documents/index?CreAnExp=true';
				}
			}
		</script>
		<button id="subPay" onclick="javascript:backList();">Regresar</button>
	</div>
 <?php else :?>
	 <div id="overflow">
	 <table id="docVersion" class="display">
		<thead>
			<tr>
				<th>N&uacute;mero</th>
				<th>Nombre</th>
				<th>Fecha</th>
				<th >
					<a href="<?php echo $this->baseUrl("/Horus/documents/creaexpor?idDoc=").$_GET['idDoc']."&v=show"; ?>">
						<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" title="Crear Nueva Version">
					</a>
				</th>
			</tr>
		</thead>
		<tbody>
			<?php foreach($this->version as $docVersion):?>
				<tr>
					<td><?php echo $docVersion['id_content_field'];?></td>
					<td><?php echo $docVersion['name'];?></td>
					<td><?php echo $docVersion['date'];?></td>
					<td>
						<a href="<?php echo $this->baseUrl("/Horus/documents/versions?idDoc=").$docVersion['id_document']."&edit=true&idVer=".$docVersion['id_content_field']; ?>">
							<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconedit.png')?>" title="Actualizar" alt="Actualizar">
						</a>
					
						<a onclick="javascript:deleteRecord('docVersion',this,'<?php echo $docVersion['id_content_field'];?>','<?php echo "/Horus/documents/deleteversion?d=".$docVersion['id_content_field'];?>')"> 
							<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconminus.png')?>" title="Eliminar"	alt="Eliminar">
						</a>
					
						<a href="<?php echo $this->baseUrl("/Horus/documents/export?idDoc=".$docVersion['id_document']."&idVer=".$docVersion['id_content_field']);?>">
							<img class="iconOpacity" src="<?php echo $this->baseUrl("/public/img/icons/".$this->iconset."/iconexport.png")?>">
						</a>
					</td>
				</tr>
			<?php endforeach;?>
		</tbody>
	</table>
	</div>
 <?php endif;?>
 