<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Gutenberg\Module'                        => __DIR__ . '/Module.php',
    'Gutenberg\Controller\CustomersController' => __DIR__ . '/src/Gutenberg/Controller/CustomersController.php',
    'GutenbergTest\Framework\TestCase'        => __DIR__ . '/tests/Gutenberg/Framework/TestCase.php',
    'GutenbergTest\SampleTest'                => __DIR__ . '/tests/Gutenberg/SampleTest.php',
);
