<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/payroll/checkbox-css.css'; ?>" rel="stylesheet" />
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/addresses.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/companies.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Editar patrocinadore</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Patrocinadores</a>
			        <a href="#" class="btn btn-default">Empresas</a>
			        <a href="#" class="btn btn-default">Editar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

	<p class="triangle-border text-size-20 font-open-sans">Modifica los datos del patrocinadore.</p>
	
	<div class="content-forms">
	
		<?php 
		$form = $this->form;
		$form->prepare();
		echo $this->form()->openTag($form);
		echo $this->formElement($form->get('type_company')->setValue(1));
		echo $this->formElement($form->get('id_company'));
		?>
	
		<div style="text-align:right;">
			<span style="text-align:right;" class="label label-info">* Datos requeridos</span>
		</div>
		
		<fieldset class="responsive-fieldset fieldset">
		
			<legend class="legend amaranth">
				<span class="glyphicon glyphicon-tag"></span> Informaci&oacute;n comercial
			</legend>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Nombre o Raz&oacute;n social:</label>
							<?php echo $this->formElement($form->get('name_company')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* RFC:</label>
							<?php echo $this->formElement($form->get('rfc')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Marca:</label>
							<?php echo $this->formElement($form->get('brand')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Giro de la empresa:</label>
							<?php echo $this->formElement($form->get('business')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Sitio web:</label>
							<?php echo $this->formElement($form->get('website')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Interesado en:</label>
							<?php echo $this->formElement($form->get('interestingin')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-4">
						<div class="form-group">
								<label class="font-raleway">Tipo de patrocinadore:</label>
								<?php echo $this->formElement($form->get('type_client')); ?>
						</div>
					</div>
				</div>
			</div>
			
		</fieldset>
		
		<fieldset class="responsive-fieldset fieldset">
		
			<legend class="legend amaranth">
				<span class="glyphicon glyphicon-tag"></span> Direccio&oacute;n
			</legend>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-6">
						<div class="form-group">
							<label class="font-raleway">* Calle:</label>
							<?php echo $this->formElement($form->get('street')); ?>
						</div>
					</div>
					
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">* Numero exterior:</label>
							<?php echo $this->formElement($form->get('number')); ?>
						</div>
					</div>
					
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">Numero interior:</label>
							<?php echo $this->formElement($form->get('interior')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">* Estado:</label>
							<?php echo $this->formElement($form->get('state_id')); ?>
						</div>
					</div>
					
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">* Delegaci&oacute;n / Municipio:</label>
							<?php echo $this->formElement($form->get('district')); ?>
						</div>
					</div>
					
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">* Colonia:</label>
							<?php echo $this->formElement($form->get('neighborhood')); ?>
						</div>
					</div>
					
					<div class="col-md-3">
						<div class="form-group">
							<label class="font-raleway">* C&oacute;digo postal:</label>
							<?php echo $this->formElement($form->get('postalcode')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Tel&eacute;fono conmutador:</label>
							<?php echo $this->formElement($form->get('phone')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Extensi&oacute;n:</label>
							<?php echo $this->formElement($form->get('ext')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">URL Mapa:</label>
							<?php echo $this->formElement($form->get('url_map')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
		</fieldset>
		
		<fieldset class="responsive-fieldset fieldset">
		
			<legend class="legend amaranth">
				<span class="glyphicon glyphicon-tag"></span> Informaci&oacute;n de contacto
			</legend>
			
			<div class="row">
				<div class="col-md-12">
				
					<p class="text-primary nova-flat text-size-15 font-bold" style="margin-top: 10px; margin-left: 15px;">Este contacto sera el favorito para el patrocinadore <span class="name_client">""</span></p>
				
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Nombre:</label>
							<?php echo $this->formElement($form->get('name_contact')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Apellido Paterno:</label>
							<?php echo $this->formElement($form->get('surname_contact')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Apellido Materno:</label>
							<?php echo $this->formElement($form->get('lastname_contact')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
				
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">Tel&eacute;fono local:</label>
							<?php echo $this->formElement($form->get('phone_contact')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">M&oacute;vil:</label>
							<?php echo $this->formElement($form->get('cellphone_contact')); ?>
						</div>
					</div>
					
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* E-Mail:</label>
							<?php echo $this->formElement($form->get('mail_contact')); ?>
						</div>
					</div>
					
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-12">
					<div class="col-md-4">
						<div class="form-group">
							<label class="font-raleway">* Puesto:</label>
							<?php echo $this->formElement($form->get('id_job')); ?>
						</div>
					</div>
				</div>
			</div>
			
		</fieldset>
		
		<fieldset class="responsive-fieldset fieldset">
		
			<legend class="legend amaranth">
				<span class="glyphicon glyphicon-tag"></span> Datos de acceso y seguridad
			</legend>

			<div class="row">
				<div class="col-md-12">
					<label class="label-check lead" for="canlogin" style="margin: 20px 0;">
						<span>¿Puede entrar a OSIRIS ?</span>
						<?php echo $this->formElement($form->get('canlogin')); ?>		
						<i></i> 
					</label>
				</div>
			</div>

			
			<div style="margin-bottom: 20px; display: none;" id="contenedor-datos-seguridad">
				
				<input type="hidden" name="role" value="5" />		
				<div class="row" style="margin-left:0;margin-right:0;margin-bottom:20px;">
					<div class="col-xs-12 col-sm-6 col-md-6">
						<label class="font-raleway" for="role">Privilegio</label>
						<?php echo $this->formElement($form->get('select-role')->setValue(5)); ?>
					</div>
				</div>	
				
				<?php echo $this->formElement($form->get('user_id')); ?>
				<div class="row" style="margin-left:0;margin-right:0;margin-bottom:20px;">
					<div class="col-xs-12 col-sm-6 col-md-6">
						<label class="font-raleway" for="user_name">Clave de usuario:</label>
						<?php echo $this->formElement($form->get('user_name')); ?>
					</div>
				</div>
					
				<!--<div class="row" style="margin-left:0;margin-right:0;margin-bottom:20px;">
                	<div class="col-xs-12 col-sm-6 col-md-6">
                		<label class="font-raleway" for="password">Contraseña:</label>
                    	<?php //echo $this->formElement($form->get('password')); ?>
                    </div>
                   	<div class="col-xs-12 col-sm-6 col-md-6">
                   		<label class="font-raleway" for="password2">Confirmar Contraseña:</label>
                   		<input type="password" name="password2" class="form-control input-lg" id="password2" placeholder="********"/>                         
                	</div>
				</div>-->
						
			</div>
			
		</fieldset>
		
		<div style="margin-top: 15px; margin-bottom:10px;" class="row">
			<div class="col-md-6">
				<?php echo $this->formElement($form->get('submitbutton')); ?>
			</div>
			<div class="col-md-6">
				<a href="<?php echo $this->basePath()."/in/customers/index";?>" class="btn btn-danger btn-lg btn-block">Cancelar</a>
			</div>
		</div>
		
		
		<?php
		echo $this->form()->closeTag();
		?>
		
	</div>

</div>

<script>
	var $basePath     = "<?php echo $this->basePath(); ?>";
	var $district     = "<?php echo $this->district; ?>";
	var $neighborhood = "<?php echo $this->neighborhood; ?>";
</script>