<script src="<?php echo $this->basePath().'/public/bootstrap-3.3.1/dist/js/companies.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Patrocinadores</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<!--<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>-->
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Patrocinadores</a>
			        <a href="#" class="btn btn-default">Empresas</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title font-raleway text-size-20">Informaci&oacute;n de patrocinadores</h3>
		</div>
		<div class="panel-body">
			<p>La siguiente tabla contiene informaci&oacute;n relacionada a los patrocinadores</p>
			<table id="companies" class="table table-striped table-hover table-condensed table-bordered">
				<thead>
					<th>Patrocinador</th>
					<th>Contacto</th>
					<th>Tel&eacute;fono</th>
					<th>Correo</th>
					<th>Registro</th>
					<!-- <th>Proyectos</th>  -->
					<th></th>
					<th></th>
					<th>
						<a class="btn btn-success" href="<?php echo $this->basePath()."/in/customers/add"?>" data-toggle="tooltip" data-placement="top" title="Agregar patrocinador">
							<span class="glyphicon glyphicon-plus-sign"></span>
						</a>
					</th>
				</thead>
				<tbody>
			    	<?php foreach($this->companies as $comp) : ?>
					<tr data-id="<?php echo $comp["id_company"]; ?>">
				        <td>
					        <a class="btn" href="<?php echo $this->basePath()."/in/customers/detail/".$comp["id_company"]; ?>" data-toggle="tooltip" data-placement="top" title="Detalle patrocinador">
				        		<span class="glyphicon glyphicon-search"></span>
				        		<?php echo $comp["name_company"]; ?>
				        	</a>
				        </td>
				        <td><?php echo $comp["name"]." ".$comp["surname"]; ?></td>
						<td><?php echo $comp["phone"]; ?></td>
						<td><?php echo $comp["email"]; ?></td>
						<td><?php echo $comp["record_date"]; ?></td>
						<!--<td>
							<center>
								<button type="button" class="btn btn-warning" data-company="<?php echo $comp["name_company"]; ?>" data-toggle="modal" data-target="#modalCompanyProjects" data-backdrop="static" data-keyboard="false">
									<span class="glyphicon glyphicon-folder-open"></span>
								</button>
							</center>
						</td>-->
						<td>
			    			<button type="button" class="btn btn-info btn-modal-cont" data-toggle="tooltip" data-placement="top" title="Contactos patrocinador">
  								<span class="glyphicon glyphicon-user"></span>
							</button>
			    		</td>
				        <td><a class="btn btn-primary" href="<?php echo $this->basePath().'/in/customers/edit/'.$comp["id_company"]; ?>" data-toggle="tooltip" data-placement="top" title="Editar patrocinador"><span class="glyphicon glyphicon-pencil"></span></a></td>
				        <td><a class="btn btn-danger" href="<?php echo $this->basePath().'/in/customers/delete/'.$comp["id_company"];?>" data-toggle="tooltip" data-placement="top" title="Eliminar patrocinador"><span class="glyphicon glyphicon-trash"></span></a></td>
			    	</tr>
			    	<?php endforeach; ?>
			    </tbody>
			</table>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="modalContacts" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title text-info" id="myModalLabel">Contactos</h4>
      		</div>
		    <div class="modal-body" id="modal-body-contacts">
		    </div>
		    <div class="modal-footer">
		    	<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		    </div>
		</div>
	</div>
</div>

<!-- mod -->
<div class="modal fade" id="modalCompanyProjects" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title text-info" id="myModalLabel"></h4>
      		</div>
		    <div class="modal-body" id="modal-body-company-projects">
		    </div>
		    <div class="modal-footer">
		    	<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		    </div>
		</div>
	</div>
</div>

<script>
var $basePath = "<?php echo $this->basepath(); ?>";

$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();

	$(".tool-top").tooltip({placement : 'top'});

    /*$('.tool-top').on('hidden.bs.tooltip', function(){

        alert("Tooltip has been completely closed.");

    });*/

	$("#companies").dataTable({
		"aoColumnDefs" : [ {
	    	'bSortable' : false,
	        'aTargets' : [ 5, 6, 7 ]
		} ]
	});
});
</script>