<h3 class="centerHor"> Agregar Minutas</h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity">
			<a class="tooltipcenter" title="Minutas" href="<?php echo $this->baseUrl('/Gutenberg/minute/index')?>">
				<img title="Minuta" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconminute.png')?>" /></a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser; ?>')">
			<a class="tooltipcenter" title="Ayuda">
				<img title="Ayuda" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
			</a>
		</li>
		<div id="clock"></div>
	</div>	
</ul>	

<div class="overflow">
	<p class="triangle-border" >Ingresa los datos de la minuta.</p>
	<?php echo $this->form; ?>	
</div>    