<div style="text-align: center;">
	<p><h4 style="color: red;">Borrar la Minuta de: 
		<?php echo $this->escape($this->minutes['objective']); ?>? 
	</h4></p> 
<form action="<?php echo $this->url(array('action'=>'delete')); ?>" method="post"> 
	<div> 
  		<input type="hidden" name="idminutes" value="<?php echo $this->minutes['idminutes']; ?>" /> 
  		<input type="submit" name="del" value="Si" /> 
  		<input type="submit" name="del" value="No" /> 
	</div> 
</div>