<!-- 
   archivo: sendMail
   autores: jesus y nadia
 -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />
<h1></h1>
     <a href="<?php echo $this->baseUrl('/minute/ver') ?>"><img style="opacity:0.4;filter:alpha(opacity=40)" onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100" onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40" alt="regresar" src="<?php echo $this->baseUrl('/public/img/returnIOF.png') ?>" ><strong>Regresar</strong></a>
     
<h1 align="center"><?php echo $this->mensaje;?></h1>
