<!-- 
   archivo: sendMail
   autores: jesus y nadia
 -->
<meta http-equiv="Content-Type" content="text/html; charset=utf-8" />

<h1></h1>
     <a href="<?php echo $this->baseUrl('/minute/ver') ?>"><img style="opacity:0.4;filter:alpha(opacity=40)" onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100" onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40" alt="regresar" src="<?php echo $this->baseUrl('/public/img/returnIOF.png') ?>" ><strong>Regresar</strong></a>
     
     <h1 align="center"><?php echo $this->mensaje ;?></h1>
     <html>
     <head></head>
     <body>
 <fieldset>
<legend><h1>Minuta del proyecto <?php echo $this->proy ;?></h1></legend>

<?php echo $this->form ;?>
</fieldset>

<fieldset>
<legend><h1>Temas acordados en la junta anterior</h1></legend>
<textarea rows="20" cols="80"><?php echo $this->form2 ;?></textarea>
</fieldset>
</body>
</html>