<div class="container">
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<div class="panel panel-info data-panel">
				<div class="panel-heading">
					<h3 style="font-weight:bold;" class="panel-title text-uppercase">
						<span class="glyphicon glyphicon-trash"></span> 
						<?php echo $this->escapeHtml("Eliminar Viaje"); ?>
					</h3>
			  	</div>
			  	<div class="panel-body text-center">
			    	<strong><p class="text-info">&#191;Seguro que quieres eliminar "<?php echo $this->escapeHtml($data['project_name']); ?>"&#63;</p></strong>
			  		
			  		<form action="" method="post">
						<input type="hidden" name="id" value="<?php echo (int) $data['ID']; ?>" />
						<input type="submit" name="del" value="Si" class="btn btn-primary" />
						<input type="submit" name="del" value="No" class="btn btn-danger" />
					</form>
			
			  	</div>
			</div>
		</div>
	</div>
</div>