<div style="width:660px; height:450px; overflow:scroll;">
	<p>.</p><p></p><p></p><p></p><p></p>
<div style="text-align: right">
<span><a href="<?php echo $this->baseUrl('/projects/index') ?>"><img style="opacity:0.4;filter:alpha(opacity=40)" onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100" onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40" src="<?php echo $this->baseUrl('/public/img/returnIOF.png') ?>" title="Regresar al menú anterior" style="width: 50px; height: 50px; text-align: right;"></a></span></button>
</div>
<div style="text-align: center"><h2>Proyectos</h2></div> 

<table> 
<tr> 
<th>Cliente</th> 
<th>RFC</th> 
<th>Proyecto</th> 
<th>Inicio</th> 
<th>Termino</th> 
<th>Estatus</th> 
<th>Descuento%</th> 
<th>Duraci&oacute;n (días)</th> 
<th>N&uacute;m.pagos</th> 
<th>Total</th> 
</tr> 
<?php foreach($this->projects as $inventories) : ?> 

<tr> 
	<td>
<?php             echo "{$inventories['name_company']}<br>\n"; ?>
  </td>
 <td>
<?php             echo "{$inventories['rfc']}<br>\n"; ?>
  </td>
<td>
<?php             echo "{$inventories['name_project']}<br>\n"; ?>
  </td>
  <td>
<?php             echo "{$inventories['start_date']}<br>\n"; ?>
  </td>
  <td>
<?php             echo "{$inventories['end_date']}<br>\n"; ?>
  </td>
  <td>
<?php             echo "{$inventories['status']}<br>\n"; ?>
  </td>
   <td>
<?php             echo "{$inventories['descto']}<br>\n"; ?>
  </td>
     <td>
<?php             echo "{$inventories['percentage_duration']}<br>\n"; ?>
  </td>
       <td>
<?php             echo "{$inventories['numberofpayments']}<br>\n"; ?>
  </td>
      <td>
      <?php echo"$";?>
<?php             echo "{$inventories['total']}<br>\n"; ?>
  </td>

</tr> 
<?php endforeach; ?> 
</table>

</div>

