<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Viajes</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Ingresos</a>
			        <a href="#" class="btn btn-default">Viajes</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title amaranth text-size-20">Informaci&oacute;n de los viajes</h3>
		</div>
		<div class="panel-body">
			<p>La siguiente tabla contiene informaci&oacute;n relacionada a los viajes</p>
			<table id="projects" class="table table-striped table-hover table-condensed">
				<thead>
					<th>Cliente</th>
					<th>Viaje</th>
					<th>Fecha inicio</th>
					<th>Fecha termino</th>
					<th>Estatus</th>
					<!-- <th>Avance</th>  -->
					<th></th>
					<th></th>
					<th>
						<a class="btn btn-success" href="<?php echo $this->basePath()."/in/projects/add"?>" data-toggle="tooltip" data-placement="top" title="Agregar viaje">
							<span class="glyphicon glyphicon-plus-sign"></span>
						</a>
					</th>
				</thead>
				<tbody>
			    	<?php foreach($this->projects as $obj) : ?>
					<tr>
				        <td>
					        <a class="btn" href="<?php echo $this->basePath()."/in/customers/detail/".$obj["company_ID"]; ?>" data-toggle="tooltip" data-placement="top" title="Detalle cliente">
				        		<span class="glyphicon glyphicon-search"></span>
				        		<?php echo $obj["name_company"]; ?>
				        	</a>
				        </td>
				        <td>
				        	<a class="btn" href="<?php echo $this->basePath()."/in/projects/detail/".$obj["ID"]; ?>" data-toggle="tooltip" data-placement="top" title="Detalle viaje">
				        		<span class="glyphicon glyphicon-paperclip"></span>
				        		<?php echo $obj["project_name"]; ?>
				        	</a>
				        </td>
						<td><?php echo $obj["start_date"]; ?></td>
						<td><?php echo $obj["end_date"]; ?></td>
						<td>
							<?php 
								if($obj["status"] == 1){
									echo "<span class='label label-success'>Activo</span>";
								}else{
									echo "<span class='label label-warning'>Inactivo</span>";
								}
							?>
						</td>
						<!-- <td>Avance</td> -->
						<td>
			    			<button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalContacts" data-backdrop="static" data-keyboard="false">
  								<span class="glyphicon glyphicon-user"></span>
							</button>
			    		</td>
				        <td><a class="btn btn-primary" href="<?php echo $this->basePath().'/in/projects/edit/'.$obj["ID"]; ?>" data-toggle="tooltip" data-placement="top" title="Editar viaje"><span class="glyphicon glyphicon-pencil"></span></a></td>
				        <td><a class="btn btn-danger" href="<?php echo $this->basePath().'/in/projects/delete/'.$obj["ID"];?>" data-toggle="tooltip" data-placement="top" title="Eliminar viaje"><span class="glyphicon glyphicon-trash"></span></a></td>
			    	</tr>
			    	<?php endforeach; ?>
			    </tbody>
			</table>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalContacts" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title" id="myModalLabel">Equipo de desarrollo</h4>
      		</div>
		    <div class="modal-body" id="modal-body-contacts">
		    </div>
		    <div class="modal-footer">
		    	<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
		    </div>
		</div>
	</div>
</div>

<script>
var $basePath = "<?php echo $this->basepath(); ?>";
$(document).ready(function(){
	$('[data-toggle="tooltip"]').tooltip();
	$("#projects").dataTable();
});
</script>