<h3 class="centerIn">Modificar proyecto</h3>
<ul class="toolbar">
	<div id="icons">
			<li class="iconOpacity"><a href="<?php echo $this->baseUrl('/In/projects/index')?>">
				<img title="Proyectos" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/icongear.png')?>"/></a>
			</li>
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','Actualizar los datos de un proyecto')">
					<a><img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>	
</ul>

<div class="center">
	<?php echo $this->form ;?>
