<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 40 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>BACHILLERATO  3er Trimestre</title>
	<meta name="generator" content="LibreOffice 4272 (Linux)">
	<meta name="author" content="Educación con Vida, para la Vida">
	<meta name="created" content="20141013;190900000000000">
	<meta name="changedby" content="Claudia Villar Cortés">
	<meta name="changed" content="20141014;165100000000000">
	<style type="text/css">
	<!--
		@page { size: 827in 1169in; margin-left: 118in; margin-right: 098in; margin-top: 049in; margin-bottom: 049in }
		@page:first { margin-top: 158in; margin-bottom: 049in }
		p { margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 150%; text-align: justify; widows: 2; orphans: 2 }
		pwestern { font-family: "Century Schoolbook", serif; font-size: 12pt; so-language: es-MX }
		pcjk { font-family: "Times New Roman"; font-size: 12pt; so-language: es-ES }
		pctl { font-family: "Tahoma"; font-size: 11pt; so-language: ar-SA }
		h1 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h1western { font-family: "Century Schoolbook", serif; font-size: 16pt; so-language: es-MX }
		h1cjk { font-family: "Times New Roman"; font-size: 16pt; so-language: es-ES }
		h1ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		a:link { color: #0000ff; so-language: zxx }
	-->
	</style>
</head>
<body lang="es-MX" text="#00000a" link="#0000ff" dir="ltr">
<h1 class="western"><a name="INDICETEMAX"></a><font color="#000066"><font size="6" style="font-size: 22pt"><i>INDICE
– TEMA X</i></font></font></h1>
<p class="western" align="justify" style="line-height: 115%"><br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">CONSTITUCIÓN
POLÍTICA DE LOS </font></font></u></span></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ESTADOS
UNIDOS MEXICANOS</font></font></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART1"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
1</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART2"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
2</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART3"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
3</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART4"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
4</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART5"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
5</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART6"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
6</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART7"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
7</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART8"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
8</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART9"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
9</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART10"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
10</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART11"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
11</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART12"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
12</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART13"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
13</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART14"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
14</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART15"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
15</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART16"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
16</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART17"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
17</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART18"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
18</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART19"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
19</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART20"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
20</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART21"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
21</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART22"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
22</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART23"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
23</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
       </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART24"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
24</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
        </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART25"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
25</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
        </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART26"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
26</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
        </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART27"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
27</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#FRONTERAS"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">FRONTERAS</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
        </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#POBLACIÓN"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">POBLACIÓN</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
       </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#AGRICULTURA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">AGRICULTURA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
      </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#GANADERÍA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">GANADERÍA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
    </font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#SILVICULTURA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">SILVICULTURA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART28"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
28</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="#ART29"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ARTÍCULO
29</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
         </font></font></font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 150%">
<br><br>
</p>
<p align="center" style="line-height: 100%"><a name="CONSTPOLÍTDLESTUNIDOSMEX"></a>
<font size="4" style="font-size: 15pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>CONSTITUCIÓN
POLÍTICA DE LOS </i></font></font></b></font>
</p>
<p align="center" style="line-height: 100%"><font size="4" style="font-size: 15pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ESTADOS
UNIDOS MEXICANOS</i></font></font></b></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	El
pueblo mexicano, a través de diferentes movimientos armados que la
historia nos muestra, entre los que destacan la Independencia de
México en 1810, el movimiento de reforma encabezada por Benito
Juárez y la Revolución Mexicana de 1910, crearon La Constitución
de los Estados Unidos Mexicanos Entre las Constituciones
destacan la de 1840, la de 1857 y la de 1917, en donde queda plasmada
la voluntad del Pueblo Mexicano a través de sus Constituyentes,
para establecer las Garantías Constitucionales de los Mexicanos, su
forma de Gobierno y las facultades de las Autoridades</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	La
Constitución del 5 de febrero de 1917 es la que actualmente nos
rige, y que en los primeros 29 artículos se encuentran las </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Garantías
Individuales</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=qv8JtvUWQU8&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=UOyLm6OXjD0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=XgT76FqlcqA"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">de
todos los habitantes de </font></font><font color="#17365d"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>La
</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>República
Mexicana</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Es el inicio del </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Estado
de Derecho</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
en que vive la sociedad mexicana y que debemos conocer para exigir su
estricto cumplimiento a las Autoridades del Gobierno</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Debemos
saber que La Constitución Política de los Estados Unidos Mexicanos
es La Ley Suprema de México También que ninguna Ley, Constitución
Estatal, Reglamentos, Decretos, Acuerdos o Circulares, pueden ir
más allá de lo que establece La Carta Magna, como lo estamos
viendo</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Después
de </font></font><font color="#17365d"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>La
</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Carta
Magna</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
en orden de superioridad, están las leyes que de ella emanen, que
regulan y aclaran los artículos establecidos en la ley suprema En
ese mismo nivel de las leyes se encuentran los tratados
internacionales, firmados por el Presidente de La República y
Autorizados por el Senado</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	En
el siguiente nivel se encuentran Las Constituciones Políticas de
cada Estado y después las leyes que de ella emanen De manera
reiterativa debemos dejar claro que, ninguna ley, constitución
estatal, leyes secundarias, reglamentos, acuerdos, decretos o
circulares, pueden ir más allá de lo que establece la </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Constitución
Política de los Estados Unidos Mexicanos</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Cuando
conozcamos nuestros derechos Constitucionales podremos tener La
Seguridad Jurídica de lo que podemos hacer y cómo exigirlos,
para poder desarrollar toda nuestra capacidad intelectual,
de trabajo, de estudio, de salud y todas nuestras habilidades, sin
más restricción que nuestros defectos y virtudes, así como
los deberes que debemos cumplir con nosotros mismos y con nuestra
sociedad</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%; page-break-before: always">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART1"></a>
