<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
1 </i></font></font></b></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%"><a name="_GoBack"></a>
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
este artículo 1º </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">se
nos garantiza que todo individuo gozará de las garantías que
otorga nuestra </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Constitución</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Es decir, mexicanos y no mexicanos que estemos en México gozaremos
de las garantías individuales Además, este artículo advierte
que ninguna garantía podrá restringirse ni suspenderse, sino en los
casos y con las condiciones que ella misma establece Es decir,
nadie por muy autoridad que sea, llámese Presidente de La República,
Juez, Gobernador, Diputado o cualquier funcionario de cualquier
dependencia, tanto del Gobierno Federal como de cada Estado, puede
restringir o suspender alguna garantía Por ejemplo, no puede nadie
decir qué podemos y qué no podemos estudiar o trabajar Lo
podemos hacer, siempre y cuando sea lícito No podemos trabajar
con drogas porque es ilícito</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ul>
	<li><p style="line-height: 100%"><font face="Tahoma, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Además
	este artículo nos menciona que está prohibida la esclavitud, a
	grado tal que si una persona que es esclava en otro país, por el
	sólo hecho de pisar suelo mexicano deja de ser esclavo, será
	garantizada su libertad y estará protegida por esta Constitución
	Entonces, mucho menos se puede esclavizar a un mexicano</font></font></font></font></p>
</ul>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">También nos
menciona este artículo que está prohibida la discriminación, por
ser indígena, o por ser hombre o mujer, joven o anciano, o por tener
capacidades diferentes, como andar en silla de ruedas o ser
ciego o sordo; tampoco por ser rico o pobre, estar enfermo de
cualquier enfermedad, como el sida Ni por profesar alguna religión
o tener opiniones diferentes al gobierno, partido político,
religión, etc O por preferencias como la homosexualidad y
lesbianismo Ni tampoco por ser casado, soltero, divorciado o viudo
Ante la ley todos somos iguales Tenemos los mismos derechos y los
mismos deberes Nadie es diferente Esto lo debemos tener muy
presente y exigir su estricto cumplimiento</p>
<p class="western" align="justify" style="margin-left: 047in; margin-right: 047in; text-indent: 039in; line-height: 100%">
<br>
</p>
<p align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Courier New, serif"><font size="2" style="font-size: 10pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CONSTITUCION
POLITICA DE LOS ESTADOS UNIDOS MEXICANOS</b></font></font></font></font></font></p>
<p align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Courier New, serif"><font size="2" style="font-size: 10pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>QUE
REFORMA LA DE 5 DE FEBRERO DE 1857</b></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Título
Primero</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Capítulo
I</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>De
las Garantías Individuales</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
1o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
En los Estados Unidos Mexicanos todo individuo gozará de las
garantías que otorga esta Constitución, las cuales no podrán
restringirse ni suspenderse, sino en los casos y con las
condiciones que ella misma establece</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Está
prohibida la esclavitud en los Estados Unidos Mexicanos Los esclavos
del extranjero que entren al territorio nacional alcanzarán, por
este solo hecho, su libertad y la protección de las leyes</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Queda
prohibida toda discriminación motivada por origen étnico o
nacional, el género, la edad, las discapacidades, la condición
social, las condiciones de salud, la religión, las opiniones, las
preferencias, el estado civil o cualquier otra que atente contra la
dignidad humana y tenga por objeto anular o menoscabar los derechos y
libertades de las personas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 047in; margin-right: 047in; text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART2"></a>
