<font size="4" style="font-size: 16pt"><b><font color="#0000ff"><font size="5" style="font-size: 18pt">ARTÍCULO
2</font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo nos habla de los derechos de los pueblos y comunidades
indígenas, para su propio desarrollo y respeto a sus usos y
costumbres</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 047in; margin-right: 047in; text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 047in; margin-right: 047in; text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
2o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La Nación Mexicana es única e indivisible</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Nación tiene una composición pluricultural sustentada originalmente
en sus pueblos indígenas que son aquellos que descienden de
poblaciones que habitaban en el territorio actual del país al
iniciarse la colonización y que conservan sus propias
instituciones sociales, económicas, culturales y políticas, o parte
de ellas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
conciencia de su identidad indígena deberá ser criterio fundamental
para determinar a quiénes se aplican las disposiciones sobre pueblos
indígenas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Son
comunidades integrantes de un pueblo indígena, aquellas que formen
una unidad social, económica y cultural, asentadas en un territorio
y que reconocen autoridades propias de acuerdo con sus usos y
costumbres</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
derecho de los pueblos indígenas a la libre determinación se
ejercerá en un marco constitucional de autonomía que asegure la
unidad nacional El reconocimiento de los pueblos y comunidades
indígenas se hará en las constituciones y leyes de las
entidades federativas, las que deberán tomar en cuenta, además de
los principios generales establecidos en los párrafos anteriores de
este artículo, criterios etnolingüísticos y de asentamiento
físico</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>A
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Esta
Constitución reconoce y garantiza el derecho de los pueblos y las
comunidades indígenas a la libre determinación y, en
consecuencia, a la autonomía para:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Decidir
sus formas internas de convivencia y organización social, económica,
política y cultural</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Aplicar
sus propios sistemas normativos en la regulación y solución de sus
conflictos internos, sujetándose a los principios generales de esta
Constitución, respetando las garantías individuales, los derechos
humanos y, de manera relevante, la dignidad e integridad de las
mujeres La ley establecerá los casos y procedimientos de
validación por los jueces o tribunales correspondientes</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i><b>III </b></i></font><font color="#0000ff"><i>Elegir
de acuerdo con sus normas, procedimientos y prácticas
tradicionales, a las autoridades o representantes para el
ejercicio de sus formas propias de gobierno interno, garantizando la
participación de las mujeres en condiciones de equidad frente a los
varones, en un marco que respete el pacto federal y la soberanía
de los estados</i></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Preservar
y enriquecer sus lenguas, conocimientos y todos los elementos que
constituyan su cultura e identidad</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Conservar
y mejorar el hábitat y preservar la integridad de sus tierras en los
términos establecidos en esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Acceder,
con respeto a las formas y modalidades de propiedad y tenencia de la
tierra establecidas en esta Constitución y a las leyes de la
materia, así como a los derechos adquiridos por terceros o por
integrantes de la comunidad, al uso y disfrute preferente de los
recursos naturales de los lugares que habitan y ocupan las
comunidades, salvo aquellos que corresponden a las áreas
estratégicas, en términos de esta Constitución Para estos efectos
las comunidades podrán asociarse en términos de ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i><b>VII </b></i></font><font color="#0000ff"><i>Elegir,
en los municipios con población indígena, representantes ante los
ayuntamientos</i></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
constituciones y leyes de las entidades federativas reconocerán y
regularán estos derechos en los municipios, con el propósito de
fortalecer la participación y representación política de
conformidad con sus tradiciones y normas internas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Acceder
plenamente a la jurisdicción del Estado Para garantizar ese
derecho, en todos los juicios y procedimientos en que sean
parte, individual o colectivamente, se deberán tomar en cuenta
sus costumbres y especificidades culturales respetando los preceptos
de esta Constitución Los indígenas tienen en todo tiempo el
derecho a ser asistidos por intérpretes y defensores que tengan
conocimiento de su lengua y cultura</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
constituciones y leyes de las entidades federativas establecerán las
características de libre determinación y autonomía que mejor
expresen las situaciones y aspiraciones de los pueblos indígenas en
cada entidad, así como las normas para el reconocimiento de las
comunidades indígenas como entidades de interés público</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>B
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Federación, los Estados y los Municipios, para promover la igualdad
de oportunidades de los indígenas y eliminar cualquier práctica
discriminatoria, establecerán las instituciones y determinarán
las políticas necesarias para garantizar la vigencia de los
derechos de los indígenas y el desarrollo integral de sus pueblos
y comunidades, las cuales deberán ser diseñadas y operadas
conjuntamente con ellos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Para
abatir las carencias y rezagos que afectan a los pueblos y
comunidades indígenas, dichas autoridades, tienen la obligación de:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Impulsar el desarrollo regional de las zonas indígenas con el
propósito de fortalecer las economías locales y mejorar las
condiciones de vida de sus pueblos, mediante acciones
coordinadas entre los tres órdenes de gobierno, con la participación
de las comunidades Las autoridades municipales determinarán
equitativamente las asignaciones presupuestales que las comunidades
administrarán directamente para fines específicos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Garantizar
e incrementar los niveles de escolaridad, favoreciendo la educación
bilingüe e intercultural, la alfabetización, la conclusión de la
educación básica, la capacitación productiva y la educación media
superior y superior Establecer un sistema de becas para los
estudiantes indígenas en todos los niveles Definir y
desarrollar programas educativos de contenido regional que reconozcan
la herencia cultural de sus pueblos, de acuerdo con las leyes de la
materia y en consulta con las comunidades indígenas Impulsar
el respeto y conocimiento de las diversas culturas existentes en
la nación</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Asegurar
el acceso efectivo a los servicios de salud mediante la ampliación
de la cobertura del sistema nacional, aprovechando debidamente la
medicina tradicional, así como apoyar la nutrición de los
indígenas mediante programas de alimentación, en especial para la
población infantil</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Mejorar
las condiciones de las comunidades indígenas y de sus espacios para
la convivencia y recreación, mediante acciones que faciliten el
acceso al financiamiento público y privado para la construcción
y mejoramiento de vivienda, así como ampliar la cobertura de los
servicios sociales básicos</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i><b>V </b></i></font><font color="#0000ff"><i>Propiciar
la incorporación de las mujeres indígenas al desarrollo, mediante
el apoyo a los proyectos productivos, la protección de su salud, el
otorgamiento de estímulos para favorecer su educación y su
participación en la toma de decisiones relacionadas con la vida
comunitaria</i></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Extender
la red de comunicaciones que permita la integración de las
comunidades, mediante la construcción y ampliación de vías de
comunicación y telecomunicación Establecer condiciones para
que los pueblos y las comunidades indígenas puedan adquirir,
operar y administrar medios de comunicación, en los términos que
las leyes de la materia determinen</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Apoyar
las actividades productivas y el desarrollo sustentable de las
comunidades indígenas mediante acciones que permitan alcanzar
la suficiencia de sus ingresos económicos, la aplicación de
estímulos para las inversiones públicas y privadas que propicien la
creación de empleos, la incorporación de tecnologías para
incrementar su propia capacidad productiva, así como para asegurar
el acceso equitativo a los sistemas de abasto y comercialización</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Establecer
políticas sociales para proteger a los migrantes de los pueblos
indígenas, tanto en el territorio nacional como en el extranjero,
mediante acciones para garantizar los derechos laborales de los
jornaleros agrícolas; mejorar las condiciones de salud de las
mujeres; apoyar con programas especiales de educación y nutrición a
niños y jóvenes de familias migrantes; velar por el respeto de sus
derechos humanos y promover la difusión de sus culturas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IX
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Consultar
a los pueblos indígenas en la elaboración del Plan Nacional de
Desarrollo y de los estatales y municipales y, en su caso, incorporar
las recomendaciones y propuestas que realicen</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Para
garantizar el cumplimiento de las obligaciones señaladas en este
apartado, la Cámara de Diputados del Congreso de la Unión, las
legislaturas de las entidades federativas y los ayuntamientos,
en el ámbito de sus respectivas competencias, establecerán las
partidas específicas destinadas al cumplimiento de estas
obligaciones en los presupuestos de egresos que aprueben, así como
las formas y procedimientos para que las comunidades participen en el
ejercicio y vigilancia de las mismas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Sin
perjuicio de los derechos aquí establecidos a favor de los
indígenas, sus comunidades y pueblos, toda comunidad
equiparable a aquéllos tendrá en lo conducente los mismos
derechos tal y como lo establezca la ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART3"></a>
