<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
3</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo 3º </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=Pw_pXwLCGBI"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=NYtBzvgADFo&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=7dCgDmBxjvA&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">les
garantiza a todos los individuos, es decir, mexicanos y no mexicanos
que se encuentren en territorio nacional, el derecho a que se le
proporcione educación El estado tiene la obligación de darles
a todos los habitantes de México la educación de preescolar,
primaria y secundaria, que es la educación básica Y no se
puede educar por educar, sino que la constitución garantiza que la
educación tenderá a desarrollar armónicamente todas las facultades
del ser humano, tanto físicas como mentales; para que se desarrolle
y aprenda nuevas habilidades que le permitan al individuo integrarse
a su sociedad, en el trabajo y con conocimientos sólidos; que su
cuerpo se desarrolle armónicamente para ser una persona sana
Además, la educación debe fomentar el amor a la patria, a México
El amor a la patria debe entenderse no solo amar a México de
palabra, sino también por los hechos Amar a México en los hechos
es estudiar permanentemente, actualizarse siempre, para trabajar con
los avances científicos y tecnológicos que den respuestas a
las nuevas necesidades de la sociedad mexicana El amor a la patria
es realizarse en lo personal, de manera integral, siendo sanos de
mente y cuerpo, para aportar a nuestra familia lo mejor de nosotros
mismos y ayudar a los demás, de manera solidaria, para que se
realicen El amor a la patria es cuidar y utilizar más recursos
naturales de una manera razonable, cuidando el equilibrio ecológico,
que tanto necesita de nuestra participación También tener
conciencia del daño trágico que nos causa el consumo de drogas,
lícitas e ilícitas, y de las consecuencias que sufre la sociedad
mexicana Amar a México es respetarnos a nosotros mismos y
guardar el respeto por la familia y la sociedad en general; cumplir y
hacer cumplir el estado de derecho que estamos viviendo en estos
momentos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
amor a México es ser parte de la solución y nunca ser parte del
problema Amar a México son sus aportaciones, ideas,
pensamientos y acciones, que permitan la convivencia digna y humana
entre todos los habitantes del mundo Es practicar todos los valores
morales y principios universales de manera comprometida, sólida,
permanente y positiva</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
crear conciencia de la solidaridad que debemos tener con nosotros
mismos y con otros pueblos Que tengamos conciencia de nuestra
independencia y sobre todo de lo que es la justicia Y esta es
la idea de conocer nuestras leyes, para que haya justicia y se cumpla
con este artículo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Asimismo,
en este artículo se reitera el derecho a tener la religión que cada
persona quiera adoptar</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el segundo inciso de este artículo se une, de manera lógica, el
criterio que debe asistir a la educación, mismo que nos indica en
que estará basado en los resultados del progreso científico, lo que
quiere decir que debe la educación contar con todos los avances
científicos y este es un derecho de todos los mexicanos, estar
actualizados para poder competir en un mundo globalizado</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Además
luchará contra la ignorancia y sus efectos, esto es muy importante,
ya que no podemos estar ignorando todos los acontecimientos y avances
científicos y tecnológicos, porque entonces no podremos aprender y
desarrollar nuevas habilidades Seríamos esclavos de la ignorancia;
y sus efectos son la pobreza mental, espiritual y material, que
nos llevaría a una vida indigna y deshumanizada Estaríamos
desintegrados de la realidad y de nuestra sociedad; seríamos parte
de los problemas y no de las soluciones Caeríamos en lo que el
inciso de este artículo quiere atacar y que es precisamente el
fanatismo, las servidumbres y los prejuicios Por eso, debemos
cumplir y hacer cumplir este derecho que tenemos todos los mexicanos
a través de la educación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Además,
este mismo artículo nos dice que la educación debe tener un
criterio democrático, entendiendo que la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Democracia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>democracia</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
no se agota en un régimen político, sino debe ser un sistema de
vida, fundado en el constante mejora-miento económico, social y
cultural del pueblo Lo que quiere decir que la educación debe
fomentar en todos los mexicanos la democracia, la cual se debe
construir diariamente con la participación de todos y cada uno de
los mexicanos, al tomar decisiones, hacer propuestas y, sobre
todo, acciones que permitan a la sociedad mexicana encontrar y
superar condiciones de vida humana y su relación con el entorno La
democracia evita los fanatismos, las servidumbres, y nos va mejorando
en lo político, económico y social; con libertad y en la búsqueda
permanente de la justicia social</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pero
este artículo va más allá todavía, al mencionar que el criterio
educativo será nacional, sin que haya hostigamientos ni
exclusivismos, nada por la fuerza o chantaje y menos, que sea para
unos cuantos Debe ser para todos este derecho, para que podamos
comprender y atender nuestros problemas, como son la pobreza interna
del ser humano, así como la pobreza material, que no permite
satisfacer las necesidades primarias También el problema de las
adicciones y narcotráfico, que nos envilecen y esclavizan; el
problema del rompimiento del equilibrio ecológico, al
contaminar las aguas de los mares, ríos, lagunas y mantos
freáticos, que causan cambios climáticos y enfermedades graves
Asimismo la contaminación de la atmósfera, que ha causado
enfermedades, cambios climáticos y desaparición de especies
animales y vegetales Otro grave problema es la tala inmoderada e
irracional de nuestros árboles lo cual redunda en perjuicio del
reino vegetal y animal, sobre todo del hombre No menos grave es
la producción de basura, que no se puede controlar y que provoca con
su descomposición una fuerte contaminación de la atmósfera y
mantos freáticos; así como la lenta degradación de alguna
basura, como los plásticos, vidrio y otros   </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
esto, debemos participar en forma democrática todos los días sin
excepción La democracia no solo se ejerce en tiempos de
elección, cuando vamos a votar La democracia es la participación
de todos los mexicanos en el desarrollo armónico e integral de la
sociedad, para que tenga mejores ingresos a través de su trabajo,
mejore su economía y al mismo tiempo tenga un lugar digno dentro de
la sociedad y no ser un número más en la misma Se debe crear una
gran cultura para el pueblo mexicano, sobre todo ahora que es el
tiempo de la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Economía"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>economía</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
del conocimiento</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nos
menciona también este artículo que debemos aprovechar todos
nuestros recursos y, por lo tanto, conocerlos México es rico
en recursos de todo tipo, los cuales debemos aprovechar, como son,
más de 10,000 kilómetros de litorales, con extraordinarias
playas; riqueza marina, como es la enorme variedad de peces y
mariscos, así como algas y corales Debemos tener conciencia y
estudiar esta gran oportunidad, para explotar y sembrar los mares,
para crear fuentes de trabajo, aportar alimentación rica en
nutrimentos; industrializar estos productos marinos para la
industria alimentaría; de fertilizantes y médica También
crear empresas de turismo en sus diferentes aspectos, aprovechando
las ventajas de cultura, playas, clima, cocina mexicana, productos
del campo, como frutos, verduras, legumbres, cereales, carne de
diferentes especies, bovino, caprino, porcino, avícola, etc, y
la riqueza alimentaría del mar El campo es otro gran recurso de
México, porque tenemos tierras cultivables, clima y agua, que bien
trabajadas crean industrias productoras agropecuarias, para la
alimentación del pueblo mexicano y nuestra aportación al
mundo Se crean fuentes de trabajo al producir materia prima y
además, otras fuentes de trabajo al industrializar estos
productos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
eso, el derecho a la educación y al aprovechamiento de ésta nos
hace desarrollar nuevas habilidades para emplear nuestros recursos y
además crear la inteligencia del turismo, del campo, del mar, de la
industria, del comercio, de la banca, de la política, en una
palabra, la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Inteligencia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>inteligencia</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
del pueblo mexicano</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ul>
	<li><p style="line-height: 100%"><font face="Tahoma, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
	anterior hace que defendamos nuestra independencia política y
	nuestra independencia económica, ya que no dependemos de otros
	países para comer, para financiarnos, para que nos den
	trabajo, evitando el maltrato de nuestra gente en los campos
	extranjeros Los mexicanos de todas las edades tienen en nuestro
	país las mayores oportunidades de desarrollo y realización</font></font></font></font></p>
</ul>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">La educación es la
esperanza, la oportunidad y el derecho más importante que nos da
nuestra constitución con otro de sus criterios, que está en el
artículo 3º y que consiste en que contribuirá a la mejor
convivencia humana, no solo sobrevivir, sino vivir en armonía
con nuestra sociedad, nos menciona que debemos ser humanos y no
máquinas Así también promover y fomentar el aprecio por la
dignidad de la persona y no practicar la crueldad y el desprecio,
darle a cada quien su lugar como persona, pero sobre todo, y esto es
muy importante, guardar y acrecentar la integridad de la familia, que
es la célula más importante de la sociedad No podemos
permitir la desintegración familiar, porque se perderían los
valores morales y los principios universales Cuando a la familia no
se le da la importancia que merece, no hay nada que hacer por la
sociedad Por lógica, si se le da importancia a la familia, se tiene
entonces la convicción del interés general de nuestra sociedad,
para desarrollar y sustentar los ideales de fraternidad que tanto
necesita la sociedad, así como la igualdad de derechos, lo que nos
hace respetar a los demás, y nos invita y enseña a evitar los
privilegios de razas, religión, grupos, sexos y de individuos
Todos somos seres humanos con nuestras propias potencialidades y
características personales, que permiten el intercambio de
ideas; pero nadie tiene el derecho a imponer a los demás sus
criterios, porque se sientan diferentes y superiores a los demás</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todos
los mexicanos debemos aprovechar en toda su magnitud este derecho
a la educación, ya que también nos dice que la educación que
imparta el estado será gratuita   </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
lo tanto, todos los mexicanos sin excepción, tenemos el derecho a la
educación básica -preescolar, primaria y secundaria, de manera
gratuita, ya que es pagada con los impuestos de todos los habitantes
de México</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
este artículo 3º nos da el derecho, a todos los habitantes de
México, a impartir educación en todos sus tipos y modalidades, como
lo establezca la ley Esto es, que todos podemos instalar
escuelas particulares de preescolar, primaria, secundaria,
bachilleratos, licenciaturas, capacitación para el trabajo,
computación, inglés, etc, en las modalidades de educación
escolarizada, que es a donde todos los alumnos tienen que ir a
la escuela; o la modalidad de educación abierta, que es aquella
en la que los alumnos estudian por su cuenta, sólo reciben asesorías
y presentan sus exámenes, obteniendo certificado de estudios
oficiales y, por último, la modalidad de sistema mixto, que consiste
en que el alumno está cierta parte del tiempo en la escuela y otra
parte el estudiante está en su casa Por lo tanto, es un
derecho más que otorga este artículo 3º, para que la gente tenga
su escuela particular, participando en la solución del problema
educativo y creando fuentes de trabajo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
3o </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Todo
individuo tiene derecho a recibir educación El Estado -federación,
estados, Distrito Federal y municipios-, impartirá educación
preescolar, primaria y secundaria La educación preescolar, primaria
y la secundaria conforman la educación básica obligatoria</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
educación que imparta el Estado tenderá a desarrollar armónicamente
todas las facultades del ser humano y fomentará en él, a la
vez, el amor a la Patria y la conciencia de la solidaridad
internacional, en la independencia y en la justicia</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Garantizada
por el artículo 24 la libertad de creencias, dicha educación será
laica y, por tanto, se mantendrá por completo ajena a cualquier
doctrina religiosa;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
criterio que orientará a esa educación se basará en los resultados
del progreso científico, luchará contra la ignorancia y sus
efectos, las servidumbres, los fanatismos y los prejuicios</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Además:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>a)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Será
democrático, considerando a la democracia no solamente como una
estructura jurídica y un régimen político, sino como un
sistema de vida fundado en el constante mejoramiento económico,
social y cultural del pueblo;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>b)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Será
nacional, en cuanto -sin hostilidades ni exclusivismos- atenderá a
la comprensión de nuestros problemas, al aprovechamiento de nuestros
recursos, a la defensa de nuestra independencia política, al
aseguramiento de nuestra independencia económica y a la
continuidad y acrecentamiento de nuestra cultura, y</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>c)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Contribuirá
a la mejor convivencia humana, tanto por los elementos que aporte a
fin de robustecer en el educando, junto con el aprecio para la
dignidad de la persona y la integridad de la familia, la convicción
del interés general de la sociedad, cuanto por el cuidado que
ponga en sustentar los ideales de fraternidad e igualdad de derechos
de todos los hombres, evitando los privilegios de razas, de religión,
de grupos, de sexos o de individuos;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Para
dar pleno cumplimiento a lo dispuesto en el segundo párrafo y en la
fracción II, el Ejecutivo Federal determinará los planes y
programas de estudio de la educación preescolar, primaria,
secundaria y normal para toda la República Para tales efectos, el
Ejecutivo Federal considerará la opinión de los gobiernos de las
entidades federativas y del Distrito Federal, así como de los
diversos sectores sociales involucrados en la educación, en los
términos que la ley señale</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
la educación que el Estado imparta será gratuita;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Además
de impartir la educación preescolar, primaria y secundaria
señaladas en el primer párrafo, el Estado promoverá y
atenderá todos los tipos y modalidades educativos -incluyendo
la educación inicial y a la educación superior- necesarios
para el desarrollo de la nación, apoyará la investigación
científica y tecnológica, y alentará el fortalecimiento y
difusión de nuestra cultura</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
particulares podrán impartir educación en todos sus tipos y
modalidades En los términos que establezca la ley, el Estado
otorgará y retirará el reconocimiento de validez oficial a los
estudios que se realicen en planteles particulares En el caso de la
educación preescolar, primaria, secundaria y normal, los
particulares deberán:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>a)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Impartir
la educación con apego a los mismos fines y criterios que establecen
el segundo párrafo y la fracción II, así como cumplir los planes y
programas a que se refiere la fracción III, y</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>b)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Obtener
previamente, en cada caso, la autorización expresa del poder
público, en los términos que establezca la ley;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
universidades y las demás instituciones de educación superior a las
que la ley otorgue autonomía, tendrán la facultad y la
responsabilidad de gobernarse a sí mismas; realizarán sus
fines de educar, investigar y difundir la cultura de acuerdo con los
principios de este artículo, respetando la libertad de cátedra e
investigación y de libre examen y discusión de las ideas;
determinarán sus planes y programas; fijarán los términos de
ingreso, promoción y permanencia de su personal académico; y
administrarán su patrimonio Las relaciones laborales, tanto del
personal académico como del administrativo, se normarán por el
apartado A del artículo 123 de esta Constitución, en los términos
y con las modalidades que establezca la Ley Federal del Trabajo
conforme a las características propias de un trabajo especial, de
manera que concuerden con la autonomía, la libertad de cátedra
e investigación y los fines de las instituciones a que esta fracción
se refiere, y</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Congreso de la Unión, con el fin de unificar y coordinar la
educación en toda la República, expedirá las leyes necesarias,
destinadas a distribuir la función social educativa entre la
Federación, los Estados y los Municipios, a fijar las aportaciones
económicas correspondientes a ese servicio público y a señalar las
sanciones aplicables a los funcionarios que no cumplan o no
hagan cumplir las disposiciones relativas, lo mismo que a todos
aquellos que las infrinjan</i></font></font></font></font></font></p>
<p class="western" align="left" style="margin-bottom: 014in; line-height: 100%"><a name="ART4"></a>
<br><br>
</p>
<p class="western" align="left" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
