<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
4</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo 4º </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=4KBAv50Vrek"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">es
de suma importancia, ya que ratifica lo mencionado en el artículo
1º, cuando nos garantiza que el hombre y la mujer son iguales ante
la ley, tienen las mismas oportunidades de estudiar y trabajar en lo
que quieran y en las mismas condiciones Igualdad en la política y
en lo social No hay ninguna diferencia en derechos y
obligaciones También este artículo reitera lo que está en el
artículo 3º que ya hemos visto y que se refiere a la protección y
el desarrollo de la familia Se le da a la familia el derecho de
que todos sus miembros, padres e hijos, velen por la integridad
de la misma, la defiendan y que juntos se desarrollen en armonía e
integridad, ya que es la célula principal de la sociedad Cuando una
familia se desintegra, viene la inseguridad de sus miembros, el
desamor, el resentimiento, que puede llevar a consecuencias, entre
otras, de drogadicción y destrucción Lógicamente, afectan a la
sociedad en general, siendo un posible problema que afecte a otras
familias y a la sociedad en general Entre otros derechos protegidos
de la familia por este artículo, está el derecho a que toda persona
decida, de manera libre y responsable e informada, sobre el
número de hijos que desea tener, así como cada cuando    </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
que quiere decir que nadie puede impedir a ninguna persona que tenga
hijos y los que desee tener, tanto biológicos como adoptados Por
supuesto que debe ser de manera responsable, que les de educación,
alimentación, vestido y vivienda; para lo cual debe estar informada
de los de derechos de los hijos, cómo educarlos, alimentarlos,
cuidarlos, darles asistencia médica, todo aquello que les permita un
desarrollo armónico, en lo físico y mental, como también lo
establece el artículo 3º Este mismo artículo nos menciona el
derecho que toda persona tiene a la protección de la salud De ahí
la importancia de los ciudadanos y autoridades para prevenir y
curar cualquier enfermedad Sobre todo la prevención, con medidas de
vacunación, nutrición y medidas razonables como evitar la
contaminación del medio ambiente, atmósfera y agua Pero también
en materia de medicina, para los que ya están enfermos Este derecho
nos dice que la ley definirá las bases y modalidades para tener
acceso a los servicios de salud Lo que quiere decir que deberá
haber una ley que fije el cómo y dónde se pueden tener los
servicios médicos; como son: el seguro social, ISSSTE, los
hospitales del gobierno y la participación de la sociedad con
hospitales particulares y el medio de financiamiento, que puede ser
por recursos propios, impuestos, o seguros médicos y otros que
puedan crearse, dependiendo de la capacidad e inteligencia de la
sociedad Pero queda claro que es un derecho a la salud</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
ya lo hemos visto, este artículo da el derecho a tener un medio
ambiente adecuado para el desarrollo y bienestar Este medio
ambiente es importante, ya que es parte del desarrollo físico y
mental, y si nos afecta mentalmente, actuaremos inadecuadamente,
afectando a nuestro cuerpo y familia por un comportamiento
destructivo o por no hacer nada, dejar de ser responsables Afectando
también a la sociedad </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
medio ambiente no solo es la atmósfera y el agua, sino también un
buen trabajo, en las mejores condiciones, que nos permita desarrollar
nuestras habilidades También es la seguridad jurídica y física
No estar con el miedo a los robos, secuestros, así como también
tener la seguridad de la aplicación de la ley para hacer uso de
nuestra libertad y se sancione a los infractores de nuestros
derechos Esto nos dará bienestar, derecho que nos garantiza este
artículo Es por esto que todos debemos conocer y ejercer nuestros
derechos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Veamos
otros derechos que nos garantiza este mismo artículo y consiste en
que toda familia debe tener y disfrutar de una vivienda digna y
decorosa Por lo tanto, tenemos derecho a una casa, no cualquier
casa, sino que sea digna y decorosa Lo que quiere decir que sea la
vivienda lo suficientemente amplia para dar cabida al número de
miembros de la familia y que no estén hacinados provocando la
promiscuidad Una vivienda que le de dignidad a la persona y a la
familia, que les de protección y descanso, lo cual le permita una
salud mental y física a todos sus miembros, se desarrollen sanamente
y aporten lo mejor a la sociedad La ley, nos dice este artículo,
establecerá los instrumentos y apoyos necesarios a fin de alcanzar
tal objetivo Cuando desconocemos nuestros derechos no exigimos
el cumplimiento de este precepto y sobre todo no aportamos tiempo,
trabajo y talento, para lograr estos objetivos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">Así como este
artículo nos dice que tenemos el derecho a tener el número de hijos
que deseemos, pero de manera responsable, así también este artículo
establece la garantía de los derechos de los niños y niñas, como
son la satisfacción de sus necesidades de alimentación, salud,
educación y sano esparcimiento, para su desarrollo integral De
ahí la necesidad de toda persona de pensar de manera responsable las
obligaciones a que se hacen acreedores al tener hijos Es una
grave responsabilidad ser padres de familia Los niños y niñas
tienen derechos que deben cumplirse Tan es así, que este mismo
artículo nos dice que los ascendientes, que son los padres o tutores
si no tienen padres o custodios, tienen la obligación de preservar
estos derechos de los niños y niñas, es decir, que se cumplan Por
eso también este artículo nos dice que el estado proveerá lo
necesario para propiciar el respeto a la dignidad de la niñez y el
ejercicio pleno de sus derechos Es decir, el estado hará las normas
o leyes para hacer cumplir con estos derechos de la niñez y las
sanciones a quien no cumpla Sobre todo el castigo severo a los que
abusen de la dignidad de los niños y niñas, como es la
pederastia, o hagan trabajar a los menores de edad y los exploten
Independientemente de la obligación del estado de impartir educación
básica gratuita a todos los menores de edad, como también lo
establece el artículo 3º y que ya hemos estudiado También el
estado está obligado a prevenir enfermedades de los menores a
través de los sistemas de vacunación y atención médica</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todos
los habitantes de la República Mexicana tenemos el deber de
participar, de manera responsable, comprometida, sólida,
permanente y patriótica, en la formación integral y armónica de
las nuevas generaciones, que son nuestros hijos y los hijos de
los demás, con valores morales y principios universales, que son la
base de toda familia y sociedad   </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
eso también el estado está obligado a otorgar todas las facilidades
a las personas, para que coadyuven y participen en el cumplimiento de
los derechos de la niñez Esto está en la garantía que nos da
este mismo artículo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
4o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
</i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(Se
deroga el párrafo primero)</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
varón y la mujer son iguales ante la ley Esta protegerá la
organización y el desarrollo de la familia</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho a decidir de manera libre, responsable e
informada sobre el número y el espaciamiento de sus hijos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho a la protección de la salud La Ley definirá
las bases y modalidades para el acceso a los servicios de salud
y establecerá la concurrencia de la Federación y las entidades
federativas en materia de salubridad general, conforme a lo que
dispone la fracción XVI del artículo 73 de esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho a un medio ambiente adecuado para su desarrollo
y bienestar</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
familia tiene derecho a disfrutar de vivienda digna y decorosa La
Ley establecerá los instrumentos y apoyos necesarios a fin de
alcanzar tal objetivo</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
niños y las niñas tienen derecho a la satisfacción de sus
necesidades de alimentación, salud, educación y sano esparcimiento
para su desarrollo integral</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
ascendientes, tutores y custodios tienen el deber de preservar estos
derechos El Estado proveerá lo necesario para propiciar el
respeto a la dignidad de la niñez y el ejercicio pleno de sus
derechos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado otorgará facilidades a los particulares para que coadyuven al
cumplimiento de los derechos de la niñez</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho al acceso a la cultura y al disfrute de los
bienes y servicios que presta el Estado en la materia, así como el
ejercicio de sus derechos culturales El Estado promoverá los medios
para la difusión y desarrollo de la cultura, atendiendo a la
diversidad cultural en todas sus manifestaciones y expresiones
con pleno respeto a la libertad creativa La ley establecerá los
mecanismos para el acceso y participación a cualquier manifestación
cultural</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART5"></a>
