<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
5 </i></font></font></b></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
lo estamos viendo, es muy importante conocer La Constitución de
nuestro país, para saber y comprender nuestros derechos y ponerlos
en práctica para el propio desarrollo, de la familia y la sociedad
Por eso es importante conocer este 5º artículo, que nos
garantiza que a ninguna persona se le podrá impedir que se
dedique a la profesión, industria, comercio o trabajo alguno que le
acomode, siendo lícito Es decir, todos podemos trabajar
ejerciendo nuestra libertad en lo que creamos más conveniente,
nos guste y deseemos Y nadie, incluyendo autoridad, podrá
impedirlo Podemos poner una tienda de abarrotes, ropa, artesanías,
etc, o un taller de hojalatería, pintura, mecánica, etc; o
podemos ser artistas, músicos, empleados, carpinteros,
taxistas, vendedores, abogados, maestros, médicos o cualquier
profesión u oficio que sean lícitos Nadie nos lo puede impedir
o prohibir con ningún argumento, acuerdo, ley, reglamento o
circular Esta es una libertad que solo podría vedarse por
determinación judicial, lo que quiere decir que sería mediante
un juicio llevado ante los tribunales competentes y de acuerdo a la
ley y procedimiento establecido, para que podamos defendernos,
siempre y cuando se ataquen por nuestra parte los derechos de otras
personas; o bien, por una resolución gubernativa, de acuerdo a la
ley, cuando se ofendan los derechos de la sociedad Pero si no
ofendemos los derechos de la sociedad, ni ofendemos los derechos de
alguna persona, no podrá impedírsenos dedicarnos al trabajo o
actividad que deseemos Ofender a la sociedad es por ejemplo,
dedicarnos al comercio de drogas o de la prostitución Estas
actividades no son lícitas</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Además,
se nos garantiza que nadie puede ser privado del producto de su
trabajo, o lo que es lo mismo, lo que ganó una persona por su
trabajo no se le puede quitar, o no pagárselo Al que realiza un
trabajo se le debe pagar y ese pago no se le puede quitar de ninguna
manera o circunstancia Solo se podrá hacer por resolución
judicial; por ejemplo, cuando un juez fija una pensión alimenticia
para los hijos y/o esposa En este caso, a la persona se le descuenta
de su sueldo la pensión fijada por el juez y se le entrega a quien
haya designado dicha autoridad</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Hay
profesiones que sólo las deben desarrollar las personas que hayan
estudiado y obtenido título y cédula profesional, debido a la
grave responsabilidad que tienen los que las ejercen, por las
consecuencias que pueden tener con la sociedad y que pueden ser de
difícil reparación como son, las del médico, que tiene en sus
manos la salud y la vida del paciente; y no cualquiera puede ejercer
esta profesión sin tener los conocimientos necesarios y
certificados por la Secretaría de Educación Pública Sin embargo,
cualquier persona tiene el derecho de estudiar y dedicarse a
esta profesión, sin que por ninguna circunstancia se le impida
Lo mismo sucede con los abogados, que tienen en sus manos la defensa
de los derechos de la gente, inclusive su libertad El contador
público, que es responsable y debe tener los conocimientos
necesarios para llevar a cabo la contabilidad de las personas o
empresas, con el objeto de saber las utilidades y el pago respectivo
de los impuestos, ya que no pagar impuestos lastima la economía
de la sociedad, y es delito que se puede castigar con cárcel
También están los ingenieros civiles, que tienen en sus manos las
construcciones de casas, puentes, presas, etc, que de no
tenerse los conocimientos y certificados necesarios, pueden
poner en peligro la salud y la vida de la gente ante cualquier
derrumbe, inundación, etc Muy importante, por supuesto, es el caso
de los maestros, quienes tienen en sus manos la formación y
educación de las nuevas generaciones de mexicanos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
está la carrera de enfermería, la que no es posible poner en manos
de gente inexperta, ya que son una extensión de los médicos, los
tratamientos y cuidados que requieren los enfermos Todos estos
profesionistas están sujetos a la obligación de tener un
titulo para poder ejercer, a las condiciones para obtenerlo y qué
autoridades lo expidan</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
estamos estudiando, este artículo garantiza que nadie, ninguna
persona puede ser obligada a trabajar sin que se le otorgue un
pago justo, nada gratis Además, debe haber el consentimiento de la
persona para trabajar A nadie se le puede obligar Salvo el trabajo
que debe realizar, de acuerdo a la ley y por decisión de un juez
después del juicio, como una pena que tiene que pagar por algún
delito Es verdad que hay servicios que no se pagan, como el
servicio militar, o la gente que está en las casillas cuando hay
elecciones Este es un servicio social, así como las personas que
trabajan en los censos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">Además, el Estado
está obligado a no permitir que alguna persona firme o se
comprometa a un contrato, pacto o convenio que tenga por objeto
perder o comprometer su libertad por cualquier causa Nadie puede ser
obligado, por ejemplo, a trabajar como esclavo, sin descansos o
sin ver a su familia, porque esto va contra la libertad de la
persona, y el estado está obligado a defender ese derecho y a
perseguir a quien lo haga Así como tampoco nadie puede admitir ni
aceptar un convenio o trato por medio del cual la persona se vea
obligada al destierro y, mucho menos, a que se le obligue a firmar un
convenio mediante el cual renuncie a ejercer algún trabajo,
profesión, industria o comercio Ni siquiera se puede hacer
temporalmente Esto quiere decir que estos derechos y garantías
son irrenunciables, y no tienen validez aunque se hayan firmado</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
otra parte, este mismo artículo nos garantiza que un contrato de
trabajo que firmamos, solo nos obliga a trabajar por el tiempo
que se convino y de acuerdo a la ley Es decir, no se puede trabajar
más de 8 horas al día; además se debe disfrutar de un día de
descanso cada semana Ese contrato no es obligatorio para el
trabajador por más de un año si va en su perjuicio No debemos
perder de vista estos derechos y las garantías que tenemos, por eso
es necesario conocerlos y estudiarlos para desarrollarnos con
armonía jurídica Ya también sabemos nuestras obligaciones</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
5o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
A ninguna persona podrá impedirse que se dedique a la profesión,
industria, comercio o trabajo que le acomode, siendo lícitos El
ejercicio de esta libertad sólo podrá vedarse por
determinación judicial, cuando se ataquen los derechos de
tercero, o por resolución gubernativa, dictada en los términos que
marque la ley, cuando se ofendan los derechos de la sociedad Nadie
puede ser privado del producto de su trabajo, sino por resolución
judicial</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Ley determinará en cada Estado, cuáles son las profesiones que
necesitan título para su ejercicio, las condiciones que deban
llenarse para obtenerlo y las autoridades que han de expedirlo</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Nadie
podrá ser obligado a prestar trabajos personales sin la justa
retribución y sin su pleno consentimiento, salvo el trabajo impuesto
como pena por la autoridad judicial, el cual se ajustará a lo
dispuesto en las fracciones I y II del artículo 123</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
cuanto a los servicios públicos, sólo podrán ser obligatorios, en
los términos que establezcan las leyes respectivas, el de las armas
y los jurados, así como el desempeño de los cargos concejiles y los
de elección popular, directa o indirecta Las funciones electorales
y censales tendrán carácter obligatorio y gratuito, pero serán
retribuidas aquéllas que se realicen profesionalmente en los
términos de esta Constitución y las leyes correspondientes Los
servicios profesionales de índole social serán obligatorios y
retribuidos en los términos de la ley y con las excepciones que
ésta señale</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado no puede permitir que se lleve a efecto ningún contrato,
pacto o convenio que tenga por objeto el menoscabo, la pérdida
o el irrevocable sacrificio de la libertad de la persona por
cualquier causa</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Tampoco
puede admitirse convenio en que la persona pacte su proscripción o
destierro, o en que renuncie temporal o permanentemente a ejercer
determinada profesión, industria o comercio</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
contrato de trabajo sólo obligará a prestar el servicio convenido
por el tiempo que fije la ley, sin poder exceder de un año en
perjuicio del trabajador, y no podrá extenderse, en ningún caso, a
la renuncia, pérdida o menoscabo de cualquiera de los derechos
políticos o civiles</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
falta de cumplimiento de dicho contrato, por lo que respecta al
trabajador, sólo obligará a éste a la correspondiente
responsabilidad civil, sin que en ningún caso pueda hacerse coacción
sobre su persona</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART6"></a>
