<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
7</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%"><font face="Tahoma, serif"><font face="Century Schoolbook, serif">Aunado
al artículo 6º tenemos que este artículo 7º nos garantiza otra
maravilla de nuestro cerebro que es la de escribir y dar a
conocer nuestros escritos sobre cualquier materia política,
económica, social, científica, tecnológica, sobre el gobierno,
partidos políticos, arte, espectáculos, deportes y todas las
cosas; ya que este derecho es irrenunciable Es más, nos
garantiza que nadie, ni siquiera una ley, ni autoridad, pueden
censurar nuestras ideas escritas Nuestras expresiones escritas
no tienen más límites que el respeto a la vida privada de las
personas, a la moral y a la paz pública</font></font></p>
<p style="text-indent: 039in; line-height: 100%"><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
7o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Es inviolable la libertad de escribir y publicar escritos sobre
cualquiera materia Ninguna ley ni autoridad puede establecer la
previa censura, ni exigir fianza a los autores o impresores, ni
coartar la libertad de imprenta, que no tiene más límites que el
respeto a la vida privada, a la moral y a la paz pública En ningún
caso podrá secuestrarse la imprenta como instrumento del delito</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes orgánicas dictarán cuantas disposiciones sean necesarias para
evitar que so pretexto de las denuncias por delito de prensa, sean
encarcelados los expendedores, &quot;papeleros&quot;, operarios
y demás empleados del establecimiento donde haya salido el escrito
denunciado, a menos que se demuestre previamente la responsabilidad
de aquéllos</i></font></font></font></font></font></p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART8"></a>
<br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
