<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
8 </i></font></font></b></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%"><font face="Tahoma, serif"><font face="Century Schoolbook, serif">Todos
los mexicanos tenemos necesidad de hacer alguna consulta o
solicitar: una licencia para abrir un negocio, una licencia de
manejo, realizar alguna queja; un juicio laboral o de divorcio, o
para que nos paguen; solicitar se arreglen baches en la calle
donde vivimos, una fuga de agua; cualquier cosa que solicitemos a
cualquier funcionario o empleado público es un derecho de petición
y todos tienen la obligación de respetarlo, siempre que sea por
escrito, de manera pacífica y respetuosa Este artículo garantiza
ese derecho de petición, pero también los funcionarios o empleados
públicos a los que se les hizo esa petición, tienen la
obligación de contestar en breve tiempo, mediante un acuerdo por
escrito, al peticionario que les haya dirigido la misma Si no se
hace la contestación, de acuerdo a esta garantía, se puede
aplicar la sanción respectiva al empleado o funcionario públicos
que no lo hicieron, de acuerdo a ley de responsabilidades de los
servidores públicos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
8o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Los funcionarios y empleados públicos respetarán el ejercicio del
derecho de petición, siempre que ésta se formule por escrito, de
manera pacífica y respetuosa; pero en materia política sólo podrán
hacer uso de ese derecho los ciudadanos de la República</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>A
toda petición deberá recaer un acuerdo escrito de la autoridad a
quien se haya dirigido, la cual tiene obligación de hacerlo conocer
en breve término al peticionario</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART9"></a>
<b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
9 </i></font></font></b>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%"><font face="Tahoma, serif"><font face="Century Schoolbook, serif">Todos
los mexicanos tenemos el derecho a reunirnos o asociarnos en un club,
una asociación, partido político, cámara, sindicato o, simplemente
tener una reunión de amigos o empleados para tratar asuntos
personales o de grupo, o bien en una fiesta Por supuesto, que
sea de manera pacífica Nadie puede tener una reunión armada En
reuniones o asociaciones de tipo político, sólo los mexicanos
podrán hacerlo, ya que ningún extranjero tiene derecho a venir
a nuestro país a hacer cosas de tipo político a su antojo Solo los
mexicanos tenemos derecho a decidir sobre cualquier cosa
política que afecta nuestro país</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo nos dice que es lícito que hagamos una reunión,
manifestación o asamblea, que tenga por objeto hacer una
petición o presentar una propuesta a una autoridad, y no
podrá ser disuelta, siempre y cuando no haya violencia o amenazas
para obligar a que se resuelva, por la fuerza, lo que se pide, porque
puede ser ilegal Si es legal la petición, no es necesaria la
violencia o amenaza, ya que la ley lo permite y debe cumplirse</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
9o</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
No se podrá coartar el derecho de asociarse o reunirse pacíficamente
con cualquier objeto lícito; pero solamente los ciudadanos de la
República podrán hacerlo para tomar parte en los asuntos políticos
del país Ninguna reunión armada, tiene derecho de deliberar</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
se considerará ilegal, y no podrá ser disuelta una asamblea o
reunión que tenga por objeto hacer una petición o presentar una
protesta por algún acto, a una autoridad, si no se profieren
injurias contra ésta, ni se hiciere uso de violencias o amenazas
para intimidarla u obligarla a resolver en el sentido que se
desee</i></font></font></font></font></font></p>
<p class="western" align="left" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="left" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="left" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p align="left" style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART10"></a>
