<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
10</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">Este artículo nos
permite tener dentro de nuestra casa un arma para nuestra defensa
Pero de ninguna manera portarla Además debe ser un arma que no sea
de las reservadas para uso exclusivo del Ejército, Armada o Fuerza
Aérea, como metralletas, ametralladoras, nueve milímetros, o un
calibre 45, tampoco granadas La ley puede autorizar a portar alguna
arma en caso de ir de cacería o tiro al blanco</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
10</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Los habitantes de los Estados Unidos Mexicanos tienen derecho a
poseer armas en su domicilio, para su seguridad y legítima defensa,
con excepción de las prohibidas por la Ley Federal y de las
reservadas para el uso exclusivo del Ejército, Armada, Fuerza
Aérea y Guardia Nacional La ley federal determinará los
casos, condiciones, requisitos y lugares en que se podrá autorizar a
los habitantes la portación de armas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART11"></a>
