<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
11</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo es muy importante porque nos garantiza la libertad de
entrar y salir del país, ir a cualquier parte de la república
así como establecer nuestra casa donde mejor nos convenga, y
mudarnos en cualquier momento y a dónde sea nuestro deseo, sin
necesitar pasaporte, carta de seguridad, salvoconducto o
cualquier requisito Nada ni nadie lo puede impedir, salvo que alguna
autoridad judicial lo decida, debido a algún acto criminal o civil;
o con extranjeros perniciosos y de acuerdo a las limitaciones
que impongan las leyes respecto a inmigración y emigración Por lo
tanto, podemos ir y venir por toda la república y vivir donde
sea nuestro deseo Es un derecho garantizado por este artículo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
11</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Todo hombre tiene derecho para entrar en la República, salir de
ella, viajar por su territorio y mudar de residencia, sin necesidad
de carta de seguridad, pasaporte, salvo-conducto u otros
requisitos semejantes El ejercicio de este derecho estará
subordinado a las facultades de la autoridad judicial, en los casos
de responsabilidad criminal o civil, y a las de la autoridad
adminis-trdativa, </i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(administrativa,
sic DOF 05-02-1917)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
por lo que toca a las limitaciones que impongan las leyes sobre
emigración, inmigración y salubridad general de la República,
o sobre extranjeros perniciosos residentes en el país</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART12"></a>
