<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
13</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Cada
vez estos artículos nos dan mayores garantías a nuestros derechos,
los que debemos ejercer para nuestro desarrollo personal y de la
sociedad En este artículo, se nos garantiza que nadie puede ser
juzgado por leyes privativas, es decir, no se pueden hacer leyes solo
para perseguir y castigar supuestos delitos sólo para una
persona  </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
leyes son para todos y no solo de manera privativa para una persona
Así como tampoco se permite que haya tribunales especiales para
alguna persona Los tribunales competentes para cada materia,
son para todos por igual Además, ninguna persona o corporación
tiene fuero, es decir, nadie tiene el derecho de ser impune ante
delitos que cometa Todo aquel que cometa algún delito será
sancionado, igual que a todos los que lo cometan y ante los
tribunales competentes Es el principio de igualdad, ya lo vimos en
el artículo 12, que nadie puede tener prerrogativas especiales,
ni títulos de nobleza que los hagan impunes</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
13</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Nadie puede ser juzgado por leyes privativas ni por tribunales
especiales Ninguna persona o corporación puede tener fuero, ni
gozar más emolumentos que los que sean compensación de servicios
públicos y estén fijados por la ley Subsiste el fuero de guerra
para los delitos y faltas contra la disciplina militar; pero los
tribunales militares en ningún caso y por ningún motivo podrán
extender su jurisdicción sobre personas que no pertenezcan al
Ejército Cuando en un delito o falta del orden militar estuviese
complicado un paisano, conocerá del caso la autoridad civil que
corresponda</i></font></font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
