<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
14</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todos
los artículos de garantías constitucionales son muy importantes,
pero este 14 tiene una importancia muy especial Veamos por qué</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nos
dice que a ninguna ley se le dará efecto retroactivo en perjuicio de
persona alguna Esto quiere decir que si a una persona que
cometió algún delito y, de acuerdo a la ley vigente se le
condena a 5 años de cárcel, deberá cumplirlos Pero cuando ya
está cumpliendo esa sentencia y la ley se cambiara, y ahora ese
delito se castigara con 10 años de cárcel, no se le puede hacer
retroactiva la nueva ley y condenarlo a 10 años en lugar de a
5, tal como lo establecía la ley anterior, porque va en
perjuicio de la persona Y ninguna ley es retroactiva en perjuicio de
alguna persona Tendría que pagar su pena de cinco años Por lo
que, si la nueva ley contiene ese mismo delito ahora a 10 años, esta
pena sólo será para los que cometan ese mismo delito, a partir de
la misma</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pero
si es al contrario, que la nueva ley, en lugar de 5 años ahora es de
2 años, si se puede hacer retroactiva la misma, porque no va en
perjuicio de la persona sino en su beneficio y entonces la pena
se le debe rebajar a 2 años, en lugar de 5 años, y a los nuevos
infractores se les castigará con 2 años tal y como lo establece la
nueva ley y no como lo establecía la anterior</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Otro
ejemplo sería que, de acuerdo a una ley o reglamento de tránsito se
otorgaran licencias de manejo por tiempo indefinido; pero un nuevo
gobierno emite una nueva ley o un nuevo reglamento en el cual se
menciona que las licencias de manejo solo tienen vigencia
por 10 años, esta ley no puede ser retroactiva a los que tienen
licencia por tiempo indefinido porque sería en perjuicio de las
personas que ya tienen esta licencia Solo será aplicable la nueva
ley o reglamento a los que obtengan por primera vez su licencia Este
mismo artículo nos da otra garantía importantísima, que
consiste en que nadie podrá ser privado de la libertad o de sus
propiedades, posesiones o derechos Es decir, nadie puede ser
encarcelado o secuestrado; así como tampoco a nadie se le pueden
quitar sus propiedades, como su casa, coche, joyas, dinero, muebles,
etc, o sus posesiones, como la casa que renta; es decir, no se le
puede lanzar de esa casa, aunque no sea suya, porque tiene la
posesión; tampoco se le pueden quitar sus derechos, como el
estudiar donde quiera, u obtener una licencia para una tienda de
abarrotes, o un reconocimiento de validez oficial de estudios;
nadie lo puede hacer</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Para
poder hacerlo, es decir, privar de sus derechos, posesiones,
propiedades o la libertad a alguien, tendrá que ser mediante
juicio seguido ante los tribunales previamente
establecidos, en el cual se cumplan las formalidades esenciales
del procedimiento y conforme a las leyes expedidas con anterioridad
al hecho Esto es, que primero haya una queja o denuncia en nuestra
contra ante las autoridades judiciales Estos tribunales ya deben
existir, no se pueden crear en el momento para ventilar el caso
Además, ya deben existir también las leyes que fueron
violadas, de otra manera no existiría el delito También debe
seguirse el procedimiento correspondiente, mediante el cual se le
permita al acusado defenderse y aportar las pruebas que a su derecho
convenga; después de ser vencido en juicio, entonces a esa persona
se le puede privar de la libertad, si el delito así lo amerita
y de acuerdo a la ley O se le puede despojar de su casa, si la
persona es embargada por alguna deuda y rematada, pero después
de haberle dado la oportunidad de defenderse También puede ser
desalojado de la casa que tenía en posesión porque la rentaba y no
pagaba la renta; después de un juicio en que tuvo la
oportunidad de demostrar si pago o no pago y comprobarlo Si no
demuestra el pago de las rentas, el juez resuelve el
lanzamiento, y posiblemente el embargo de sus bienes como la
televisión, refrigerador u otros Por lo anterior es de
vital importancia este artículo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
14 </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>A
ninguna ley se dará efecto retroactivo en perjuicio de persona
alguna</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Nadie
podrá ser privado de la libertad o de sus propiedades, posesiones o
derechos, sino mediante juicio seguido ante los tribunales
previamente establecidos, en el que se cumplan las formalidades
esenciales del procedimiento y conforme a las Leyes expedidas con
anterioridad al hecho</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
los juicios del orden criminal queda prohibido imponer, por simple
analogía, y aún por mayoría de razón, pena alguna que no esté
decretada por una ley exactamente aplicable al delito de que se
trata</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
los juicios del orden civil, la sentencia definitiva deberá ser
conforme a la letra o a la interpretación jurídica de la ley,
y a falta de ésta se fundará en los principios generales del
derecho</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%"><a name="ART15"></a>
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>ARTÍCULO
15</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">México puede
celebrar tratados Internacionales, que firma el Presidente de la
República y ratifica el Senado, pero nuestra Constitución no
permite celebrar tratados para extraditar a reos Políticos Si
es por motivos de tipo Político, y es buscada una persona extranjera
y ésta se encuentra en México, no se puede enviar de regreso a su
país Así como tampoco se puede tener un tratado para enviar a una
persona que cometió un delito de robo, asesinato, etc, si esa
persona era esclava en el país en que cometió dicho delito Mucho
menos, se pueden hacer tratados en los que se alteren las garantías
constitucionales de los habitantes de la república Por ejemplo, no
se puede hacer un tratado internacional que diga que los
mexicanos no pueden ejercer en México la profesión de médico,
porque sólo podrán hacerlo los médicos del otro país con el cual
se firmó el tratado Esto viola los derechos de los mexicanos,
consagrados en el artículo 5 de la constitución, que nos menciona
que todos los mexicanos se pueden dedicar a la profesión que
deseen; o un tratado en el que se mencione que los extranjeros tienen
fuero contra cualquier infracción que comentan en México Aquí se
viola el principio de igualdad establecido en el artículo 1º
constitucional que ya vimos</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
15</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
No se autoriza la celebración de tratados para la extradición de
reos políticos, ni para la de aquellos delincuentes del orden común
que hayan tenido en el país donde cometieron el delito, la
condición de esclavos; ni de convenios o tratados en virtud de
los que se alteren las garantías y derechos establecidos por
esta Constitución para el hombre y el ciudadano</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART16"></a>
