<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
16 </i></font></font></b></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo es importantísimo y se complementa con el 14, como ya lo
veremos Debemos ponerle muchísima atención Nos dice: nadie puede
ser molestado en su persona, familia, domicilio, papeles o
posesiones, sino en virtud de mandamiento escrito de la autoridad
competente que funde y motive la causa legal del procedimiento Esto
es muy importante, porque se garantiza que nadie puede ser molestado
en su persona, nadie le puede decir a alguien qué puede o qué
no puede hacer Nadie la puede detener, o esculcar, o
discriminar por capacidad diferente o por enfermedad Tampoco se
le puede prohibir caminar por la calle si no lleva identificación
Nadie puede molestar a alguna persona, ni siquiera por sospechosa, ni
se le puede preguntar en qué trabaja o estudia, dónde vive y qué
hace en determinado lugar Tampoco se puede meter nadie a su
domicilio y molestar a la familia Nadie puede decir cuántos
miembros deben ser en su familia, dónde y cómo deben
vivir, ni cobrarle a la familia deudas de alguno de sus miembros Ni
detener a algún miembro para obligar a otro se presente a responder
por algo Ni indicarle a la familia qué religión debe
profesar; ni afectar a la familia en represalia a algún
hecho cometido por alguno de sus miembros Tampoco se puede, y
nadie lo debe hacer, de revisar o catear el domicilio privado o de
oficinas de alguien Tampoco se le puede decir a alguna persona qué
puede o qué no puede tener en ese domicilio Mucho menos, se puede
penetrar al domicilio de alguien sin el permiso correspondiente
Ni obligar a nadie a que acepte vivir en el domicilio a una
persona ajena De la misma manera, nadie tiene derecho a revisar y
solicitar papeles de alguna persona, tales como escrituras de la
casa o contrato de trabajo, recibos de pago de luz o teléfono; ni
actas de nacimiento o matrimonio, ningún papel procede ser
solicitado o revisado porque es un acto de molestia para la
persona Asimismo, nadie puede ser molestado en sus posesiones, como
mercancía, automóviles, ropa, muebles, equipos, licencias,
permisos, concesiones, etc   </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos, visto nadie puede ser molestado en su persona, familia,
papeles, domicilio o posesiones Si por alguna
circunstancia alguna persona tiene que ser molestada, solo lo
podrá hacer una autoridad que tenga competencia Por ejemplo: si el
acto de molestia consiste en que nos van a revisar nuestros
papeles fiscales para ver si ya pagamos nuestros impuestos, en primer
lugar, debe ser por escrito y nunca de palabra En ese escrito
debe estar la firma y el puesto, así como la fundamentación de la
persona que lo ordena La fundamentación consiste en que se nos
diga claramente en el escrito, qué ley y qué artículo y
fracción le da esa facultad a la persona para emitir el acto de
molestia Así como decirnos qué dicen esos artículos y no
simplemente ponerlos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">No
cualquier autoridad puede emitir ese acto Así lo ordena este
artículo 16 Debe ser autoridad competente Además, debe
fundamentar y motivar el acto de molestia Esto consiste en que
nos especifiquen claramente las fracciones, artículos y leyes
que permitan realizar ese acto de molestia; no basta que lo emita una
autoridad competente, sino que además, nos debe especificar por qué
puede hacer ese acto y en qué ley lo menciona; aparte, nos debe
decir cuál es el motivo para hacernos ese acto de molestia Lo mismo
sería para una aprehensión, porque es un acto de molestia en
contra de la libertad Como también un embargo, un cateo
en el domicilio, una cancelación de una licencia o permiso,
etc Así lo establece esta garantía a un derecho constitucional
De la misma manera, cuando solicitamos una licencia de construcción;
de manejo o, para vender vinos y licores; abrir una oficina o
comercio; un pasaporte y se nos niega Lo debe hacer una autoridad
competente, por escrito, no de palabra y motivando y
fundamentando en qué ley se basa para negar lo solicitado y cuál es
el motivo, para que la persona afectada se pueda defender de acuerdo
a derecho No hacerlo, cumpliendo con el artículo 16
constitucional, es dejar a la persona en estado de indefensión,
lo que de ninguna manera se puede hacer porque se violan sus
garantías constitucionales</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el caso de una orden de aprehensión, tendrá que ser una autoridad
competente judicial quien emita ese acto de molestia y, al
ejecutar la orden, debe ponerse inmediatamente a disposición de
un juez No hacerlo es una responsabilidad de tipo penal para la
autoridad Lo mismo sería para cualquier autoridad que ejecute
cualquier acto de molestia sin tener facultades para ello y
no haberlo hecho por escrito</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ningún
detenido puede estar más de 48 horas ante el ministerio público Al
término de las 48 horas deberá ser consignado ante un juez o
puesto en libertad</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ninguna
autoridad, salvo autoridad judicial (juez), puede ordenar un cateo
a un domicilio u oficina; además debe ser por escrito esa orden
especificando con claridad el lugar que se va a inspeccionar y
la persona o personas que se vayan a aprehender, o los objetos que se
buscan, como puede ser algo robado (televisión, joyas, etc), drogas
o artículos piratas No se puede buscar nada más de lo que
está en la orden de cateo (acto de molestia) Al final del cateo
se debe levantar un acta, en donde se asiente lo que aconteció
durante el acto y deberá ser firmada por la autoridad, la persona
molestada y dos testigos que señale el afectado El afectado
tiene derecho a que se ponga en esa acta lo que a su derecho
convenga, como pudieran ser posibles arbitrariedades</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
otro lado, es un derecho, y este artículo lo garantiza, de que las
comunicaciones privadas no pueden ser violadas, como son
las cartas o llamadas telefónicas No pueden ser secuestradas o
abiertas las cartas que son de alguna persona; así como tampoco se
pueden intervenir las llamadas telefónicas o grabarlas Hacerlo
es un delito penal, porque es atentar contra la privación
y la libertad de la persona</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Solamente
cuando se persiga algún delito, una autoridad competente judicial
podrá ordenar la intervención telefónica o decomiso de
correspondencia Por supuesto, de acuerdo a lo que ya hemos visto:
por escrito, hecho por autoridad competente y diga qué ley
permite hacerlo y por qué se hace Esto es sólo en casos de delitos
penales Pero de ninguna manera se podrá hacer si se trata de
asuntos fiscales, como es el pago de impuestos; de tipo
electoral, para saber por quién van a votar o a quien, cómo apoyan
a algún candidato Tampoco en materia mercantil para saber qué
compra y en dónde y cuánto debe Ni en materia laboral, para
saber dónde trabaja una persona, cuánto gana y qué puesto tiene
Ni en materia administrativa, para conocer qué trámites hace
para conseguir un permiso o qué está haciendo para hacer un
negocio Tampoco en materia civil para saber si es casado o
divorciado, o con quién anda Son sólo algunos ejemplos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ul>
	<li><p style="line-height: 100%"><font face="Tahoma, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
	autoridades fiscales, como la secretaría de hacienda y el seguro
	social, podrán ordenar y hacer visitas domiciliaras para
	comprobar que se cumple con los reglamentos de policía y
	sanitarios Además, y es lo más común, podrán visitar el
	domicilio u oficina de alguna persona o empresa para comprobar
	que se han pagado los impuestos y, por lo tanto, solicitar se
	muestren libros y papeles contables para hacer dicha
	comprobación Pero, recordemos que debe ser ordenado el acto
	de molestia, o sea la visita domiciliaria, por autoridad competente,
	por escrito y diga el por qué de esa visita y en qué ley se
	basan Además, debe quedar muy claro el nombre de la persona o
	empresa que se va a visitar; de no ser así, se tiene el
	derecho a rechazarla, porque es nula Estas autoridades no tienen
	ninguna facultad para hacer cateos Los artículos 16 y el 14 son de
	los más importantes y debemos tenerlos muy presentes para
	evitar abusos y actuar en nuestras vidas con toda
	seguridad jurídica</font></font></font></font></p>
</ul>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
16</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Nadie puede ser molestado en su persona, familia, domicilio, papeles
o posesiones, sino en virtud de mandamiento escrito de la autoridad
competente, que funde y motive la causa legal del procedimiento</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho a la protección de sus datos personales, al
acceso, rectificación y cancelación de los mismos, así como a
manifestar su oposición, en los términos que fije la ley, la cual
establecerá los supuestos de excepción a los principios que rijan
el tratamiento de datos, por razones de seguridad nacional,
disposiciones de orden público, seguridad y salud públicas o para
proteger los derechos de terceros</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
podrá librarse orden de aprehensión sino por la autoridad judicial
y sin que preceda denuncia o querella de un hecho que la ley señale
como delito, sancionado con pena privativa de libertad y obren datos
que establezcan que se ha cometido ese hecho y que exista la
probabilidad de que el indiciado lo cometió o participó en su
comisión</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
autoridad que ejecute una orden judicial de aprehensión, deberá
poner al inculpado a disposición del juez, sin dilación alguna y
bajo su más estricta responsabilidad La contravención a lo
anterior será sancionada por la ley penal</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Cualquier
persona puede detener al indiciado en el momento en que esté
cometiendo un delito o inmediatamente después de haberlo
cometido, poniéndolo sin demora a disposición de la autoridad más
cercana y ésta con la misma prontitud, a la del Ministerio Público
Existirá un registro inmediato de la detención</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Sólo
en casos urgentes, cuando se trate de delito grave así calificado
por la ley y ante el riesgo fundado de que el indiciado pueda
sustraerse a la acción de la justicia, siempre y cuando no se
pueda ocurrir ante la autoridad judicial por razón de la hora, lugar
o circunstancia, el Ministerio Público podrá, bajo su
responsabilidad, ordenar su detención, fundando y expresando
los indicios que motiven su proceder</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
casos de urgencia o flagrancia, el juez que reciba la consignación
del detenido deberá inmediatamente ratificar la detención o
decretar la libertad con las reservas de ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
autoridad judicial, a petición del Ministerio Público y tratándose
de delitos de delincuencia organizada, podrá decretar el arraigo de
una persona, con las modalidades de lugar y tiempo que la ley
señale, sin que pueda exceder de cuarenta días, siempre que sea
necesario para el éxito de la investigación, la protección de
personas o bienes jurídicos, o cuando exista riesgo fundado de que
el inculpado se sustraiga a la acción de la justicia Este plazo
podrá prorrogarse, siempre y cuando el Ministerio Público acredite
que subsisten las causas que le dieron origen En todo caso, la
duración total del arraigo no podrá exceder los ochenta días</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Por
delincuencia organizada se entiende una organización de hecho de
tres o más personas, para cometer delitos en forma permanente o
reiterada, en los términos de la ley de la materia</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Ningún
indiciado podrá ser retenido por el Ministerio Público por más de
cuarenta y ocho horas, plazo en que deberá ordenarse su
libertad o ponérsele a disposición de la autoridad judicial;
este plazo podrá duplicarse en aquellos casos que la ley prevea como
delincuencia organizada Todo abuso a lo anteriormente dispuesto será
sancionado por la ley penal</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
toda orden de cateo, que sólo la autoridad judicial podrá expedir,
a solicitud del Ministerio Público, se expresará el lugar que ha de
inspeccionarse, la persona o personas que hayan de aprehenderse y los
objetos que se buscan, a lo que únicamente debe limitarse la
diligencia, levantándose al concluirla, un acta circunstanciada,
en presencia de dos testigos propuestos por el ocupante del lugar
cateado o en su ausencia o negativa, por la autoridad que practique
la diligencia</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
comunicaciones privadas son inviolables La ley sancionará
penalmente cualquier acto que atente contra la libertad y privacía
de las mismas, excepto cuando sean aportadas de forma voluntaria por
alguno de los particulares que participen en ellas El juez
valorará el alcance de éstas, siempre y cuando contengan
información relacionada con la comisión de un delito En ningún
caso se admitirán comunicaciones que violen el deber de
confidencialidad que establezca la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Exclusivamente
la autoridad judicial federal, a petición de la autoridad federal
que faculte la ley o del titular del Ministerio Público de la
entidad federativa correspondiente, podrá autorizar la
intervención de cualquier comunicación privada Para ello, la
autoridad competente deberá fundar y motivar las causas legales de
la solicitud, expresando además, el tipo de intervención, los
sujetos de la misma y su duración La autoridad judicial federal no
podrá otorgar estas autorizaciones cuando se trate de materias de
carácter electoral, fiscal, mercantil, civil, laboral o
administrativo, ni en el caso de las comunicaciones del detenido con
su defensor</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
Poderes Judiciales contarán con jueces de control que resolverán,
en forma inmediata, y por cualquier medio, las solicitudes de medidas
cautelares, providencias precautorias y técnicas de
investigación de la autoridad, que requieran control judicial,
garantizando los derechos de los indiciados y de las víctimas u
ofendidos Deberá existir un registro fehaciente de todas las
comunicaciones entre jueces y Ministerio Público y demás
autoridades competentes</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
intervenciones autorizadas se ajustarán a los requisitos y límites
previstos en las leyes Los resultados de las intervenciones que no
cumplan con éstos, carecerán de todo valor probatorio</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
autoridad administrativa podrá practicar visitas domiciliarias
únicamente para cerciorarse de que se han cumplido los reglamentos
sanitarios y de policía; y exigir la exhibición de los libros y
papeles indispensables para comprobar que se han acatado las
disposiciones fiscales, sujetándose en estos casos, a las leyes
respectivas y a las formalidades prescritas para los cateos</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
correspondencia que bajo cubierta circule por las estafetas estará
libre de todo registro, y su violación será penada por la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
tiempo de paz ningún miembro del Ejército podrá alojarse en casa
particular contra la voluntad del dueño, ni imponer prestación
alguna En tiempo de guerra los militares podrán exigir
alojamiento, bagajes, alimentos y otras prestaciones, en los
términos que establezca la ley marcial correspondiente</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART17"></a>
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
