<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
17</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo debemos tomarlo muy en cuenta porque nos garantiza un
derecho, pero además nos impone una obligación de respeto y
justicia Nos dice que nadie podrá hacerse justicia por sí mismo y,
mucho menos, ejercer violencia para reclamar su derecho Lo que
quiere decir, por ejemplo, que si alguien no pagó algo que le
vendimos, lo golpeemos y le quitemos su reloj para cobrarnos O
que si alguien golpeó nuestro coche, que dejamos estacionado,
vayamos a golpear y romper los vidrios de la casa del que golpeó
nuestro coche Y, lo más grave, si alguien mató a una persona, de
ninguna manera el familiar afectado puede hacerse justicia, matando
al agresor Son sólo algunos ejemplos Nadie puede hacerse justicia
por sí mismo, ni ejercer violencia para reclamar su derecho
Por el contrario, este artículo nos garantiza el derecho que tenemos
de que se nos administre justicia, y para eso están los
tribunales Estos tribunales tienen la obligación de impartir
justicia, en los plazos y de acuerdo estricto a las leyes, emitiendo
las sentencias o resoluciones de manera pronta y completa sin dejar
nada pendiente, porque entonces no es justicia y, sobre todo,
imparcial, no se puede tomar partido por nadie, no se pueden tener
preferencias, solo aplicar la Ley Además, la impartición de
Justicia debe ser gratuita, no se puede cobrar por impartir
Justicia; es más, está prohibido hacerlo Además se tiene la
garantía de que se cumpla la sentencia que emitan los jueces No
puede haber una sentencia y que no se cumpla Este artículo nos
menciona algo muy importante, como lo es el que nadie puede ser
aprisionado porque debe dinero, o sea por una deuda civil, aunque
haya firmado una letra o pagaré Es muy diferente firmar un cheque
sin fondos, porque esto sí es delito de fraude; ya que se supone
que quien firmó el cheque sabía que no tenía fondos y con mala fe
lo hizo Un cheque solo debe ser firmado si se tienen los fondos
suficientes</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
17</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Ninguna persona podrá hacerse justicia por sí misma, ni ejercer
violencia para reclamar su derecho</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Toda
persona tiene derecho a que se le administre justicia por tribunales
que estarán expeditos para impartirla en los plazos y términos que
fijen las leyes, emitiendo sus resoluciones de manera pronta,
completa e imparcial Su servicio será gratuito, quedando, en
consecuencia, prohibidas las costas judiciales</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Congreso de la Unión expedirá las leyes que regulen las acciones
colectivas Tales leyes determinarán las materias de aplicación,
los procedimientos judiciales y los mecanismos de reparación del
daño Los jueces federales conocerán de forma exclusiva sobre estos
procedimientos y mecanismos</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes preverán mecanismos alternativos de solución de
controversias En la materia penal regularán su aplicación,
asegurarán la reparación del daño y establecerán los casos
en los que se requerirá supervisión judicial</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
sentencias que pongan fin a los procedimientos orales deberán ser
explicadas en audiencia pública previa citación de las partes</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes federales y locales establecerán los medios necesarios para
que se garantice la independencia de los tribunales y la plena
ejecución de sus resoluciones</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Federación, los Estados y el Distrito Federal garantizarán la
existencia de un servicio de defensoría pública de calidad para la
población y asegurarán las condiciones para un servicio profesional
de carrera para los defensores Las percepciones de los
defensores no podrán ser inferiores a las que correspondan a los
agentes del Ministerio Público</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Nadie
puede ser aprisionado por deudas de carácter puramente civil</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART18"></a>
