<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
18</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entre
otras cosas que se garantizan en este artículo 18, se encuentra una
muy importante, porque se relaciona con los adolescentes menores
de 18 años y mayores de 12 que cometan alguna conducta tipificada
por las Leyes como delito penal; las Autoridades Federales,
Estatales y del Distrito Federal, establecerán un sistema
integral de justicia, ya que no se les puede tratar igual que los
adultos que cometan delitos Inclusive, deben ser tribunales
especiales dedicados a ventilar estas conductas de menores de
edad nada más De manera especial se deben aplicar a estos
menores, medidas de protección integral como son, una adecuada
orientación, protección y tratamiento que se seguirá para la
recuperación, desarrollo e integración del menor a la
sociedad, en las mejores condiciones físicas, mentales y educativas,
así como con su familia y pueda tener un pleno desarrollo como
persona, con todas sus capacidades Solo a los mayores de 14 años y
menores de 18 se les podrá aplicar un internamiento como medida
extrema, dependiendo la gravedad de su conducta pero, por el menor
tiempo posible Debe preocuparnos mucho la conducta de los menores,
ya que es el reflejo de la calidad de educación en la escuela y en
la familia; así como las condiciones internas de convivencia
familiar, sin descuidar el entorno de los menores como es, la
televisión, revistas, amigos y los peligros del crimen organizado, y
la alimentación Se debe poner mucha atención en los valores
morales y principios universales que se deben inculcar a los
menores de edad, y que son la base de cada individuo, de la familia y
la sociedad De ahí también la importancia de conocer y poner en
práctica los derechos que nos da esta constitución, como lo
hemos estado estudiando</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
18</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Sólo por delito que merezca pena privativa de libertad habrá lugar
a prisión preventiva El sitio de ésta será distinto del que se
destinare para la extinción de las penas y estarán completamente
separados</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
sistema penitenciario se organizará sobre la base del trabajo, la
capacitación para el mismo, la educación, la salud y el deporte
como medios para lograr la reinserción del sentenciado a la
sociedad y procurar que no vuelva a delinquir, observando los
beneficios que para él prevé la ley Las mujeres compurgarán sus
penas en lugares separados de los destinados a los hombres para tal
efecto</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Federación, los Estados y el Distrito Federal podrán celebrar
convenios para que los sentenciados por delitos del ámbito de su
competencia extingan las penas en establecimientos penitenciarios
dependientes de una jurisdicción diversa</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Federación, los Estados y el Distrito Federal establecerán, en el
ámbito de sus respectivas competencias, un sistema integral de
justicia que será aplicable a quienes se atribuya la realización de
una conducta tipificada como delito por las leyes penales y tengan
entre doce años cumplidos y menos de dieciocho años de edad, en el
que se garanticen los derechos fundamentales que reconoce esta
Constitución para todo individuo, así como aquellos derechos
específicos que por su condición de personas en desarrollo les han
sido reconocidos Las personas menores de doce años que hayan
realizado una conducta prevista como delito en la ley, solo serán
sujetos a rehabilitación y asistencia social</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
operación del sistema en cada orden de gobierno estará a cargo de
instituciones, tribunales y autoridades especializados en la
procuración e impartición de justicia para adolescentes Se podrán
aplicar las medidas de orientación, protección y tratamiento
que amerite cada caso, atendiendo a la protección integral y el
interés superior del adolescente</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
formas alternativas de justicia deberán observarse en la aplicación
de este sistema, siempre que resulte procedente En todos los
procedimientos seguidos a los adolescentes se observará la garantía
del debido proceso legal, así como la independencia entre las
autoridades que efectúen la remisión y las que impongan las
medidas Éstas deberán ser proporcionales a la conducta realizada y
tendrán como fin la reintegración social y familiar del
adolescente, así como el pleno desarrollo de su persona y
capacidades El internamiento se utilizará solo como medida extrema
y por el tiempo más breve que proceda, y podrá aplicarse únicamente
a los adolescentes mayores de catorce años de edad, por la comisión
de conductas antisociales calificadas como graves</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
sentenciados de nacionalidad mexicana que se encuentren compurgando
penas en países extranjeros, podrán ser trasladados a la República
para que cumplan sus condenas con base en los sistemas de
reinserción social previstos en este artículo, y los sentenciados
de nacionalidad extranjera por delitos del orden federal o del
fuero común, podrán ser trasladados al país de su origen o
residencia, sujetándose a los Tratados Internacionales que se hayan
celebrado para ese efecto El traslado de los reclusos sólo podrá
efectuarse con su consentimiento expreso</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
sentenciados, en los casos y condiciones que establezca la ley,
podrán compurgar sus penas en los centros penitenciarios más
cercanos a su domicilio, a fin de propiciar su reintegración a la
comunidad como forma de reinserción social Esta disposición no
aplicará en caso de delincuencia organizada y respecto de otros
internos que requieran medidas especiales de seguridad</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Para
la reclusión preventiva y la ejecución de sentencias en materia de
delincuencia organizada se destinarán centros especiales Las
autoridades competentes podrán restringir las comunicaciones de los
inculpados y sentenciados por delincuencia organizada con
terceros, salvo el acceso a su defensor, e imponer medidas de
vigilancia especial a quienes se encuentren internos en estos
establecimientos Lo anterior podrá aplicarse a otros internos que
requieran medidas especiales de seguridad, en términos de la ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART19"></a>
