<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
19</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
19</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Ninguna detención ante autoridad judicial podrá exceder del plazo
de setenta y dos horas, a partir de que el indiciado sea puesto a su
disposición, sin que se justifique con un auto de vinculación
a proceso en el que se expresará: el delito que se impute al
acusado; el lugar, tiempo y circunstancias de ejecución, así
como los datos que establezcan que se ha cometido un hecho que la ley
señale como delito y que exista la probabilidad de que el indiciado
lo cometió o participó en su comisión</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Ministerio Público sólo podrá solicitar al juez la prisión
preventiva cuando otras medidas cautelares no sean suficientes para
garantizar la comparecencia del imputado en el juicio, el desarrollo
de la investigación, la protección de la víctima, de los testigos
o de la comunidad, así como cuando el imputado esté siendo
procesado o haya sido sentenciado previamente por la comisión
de un delito doloso El juez ordenará la prisión preventiva,
oficiosamente, en los casos de delincuencia organizada,
homicidio doloso, violación, secuestro, delitos cometidos con medios
violentos como armas y explosivos, así como delitos graves que
determine la ley en contra de la seguridad de la nación, el libre
desarrollo de la personalidad y de la salud</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley determinará los casos en los cuales el juez podrá revocar la
libertad de los individuos vinculados a proceso</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
plazo para dictar el auto de vinculación a proceso podrá
prorrogarse únicamente a petición del indiciado, en la forma
que señale la ley La prolongación de la detención en su perjuicio
será sancionada por la ley penal La autoridad responsable del
establecimiento en el que se encuentre internado el indiciado, que
dentro del plazo antes señalado no reciba copia autorizada del auto
de vinculación a proceso y del que decrete la prisión
preventiva, o de la solicitud de prórroga del plazo constitucional,
deberá llamar la atención del juez sobre dicho particular en el
acto mismo de concluir el plazo y, si no recibe la constancia
mencionada dentro de las tres horas siguientes, pondrá al indiciado
en libertad</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Todo
proceso se seguirá forzosamente por el hecho o hechos delictivos
señalados en el auto de vinculación a proceso Si en la secuela de
un proceso apareciere que se ha cometido un delito distinto del que
se persigue, deberá ser objeto de investigación separada, sin
perjuicio de que después pueda decretarse la acumulación, si fuere
conducente</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Si
con posterioridad a la emisión del auto de vinculación a proceso
por delincuencia organizada el inculpado evade la acción de la
justicia o es puesto a disposición de otro juez que lo reclame
en el extranjero, se suspenderá el proceso junto con los plazos para
la prescripción de la acción penal</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Todo
mal tratamiento en la aprehensión o en las prisiones, toda molestia
que se infiera sin motivo legal, toda gabela o contribución, en las
cárceles, son abusos que serán corregidos por las leyes y
reprimidos por las autoridades</i></font></font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
