<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
20</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
20 </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
proceso penal será acusatorio y oral Se regirá por los principios
de publicidad, contradicción, concentración, continuidad e
inmediación</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>A</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
De los principios generales:</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
El proceso penal tendrá por objeto el esclarecimiento de los hechos,
proteger al inocente, procurar que el culpable no quede impune y que
los daños causados por el delito se reparen;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Toda audiencia se desarrollará en presencia del juez, sin que pueda
delegar en ninguna persona el desahogo y la valoración de las
pruebas, la cual deberá realizarse de manera libre y lógica;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Para los efectos de la sentencia sólo se considerarán como prueba
aquellas que hayan sido desahogadas en la audiencia de juicio La ley
establecerá las excepciones y los requisitos para admitir en
juicio la prueba anticipada, que por su naturaleza requiera desahogo
previo;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
El juicio se celebrará ante un juez que no haya conocido del caso
previamente La presentación de los argumentos y los elementos
probatorios se desarrollará de manera pública, contradictoria
y oral;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La carga de la prueba para demostrar la culpabilidad corresponde a la
parte acusadora, conforme lo establezca el tipo penal Las partes
tendrán igualdad procesal para sostener la acusación o la
defensa, respectivamente;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Ningún juzgador podrá tratar asuntos que estén sujetos a proceso
con cualquiera de las partes sin que esté presente la otra,
respetando en todo momento el principio de contradicción, salvo las
excepciones que establece esta Constitución;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Una vez iniciado el proceso penal, siempre y cuando no exista
oposición del inculpado, se podrá decretar su terminación
anticipada en los supuestos y bajo las modalidades que determine la
ley Si el imputado reconoce ante la autoridad judicial,
voluntariamente y con conocimiento de las consecuencias, su
participación en el delito y existen medios de convicción
suficientes para corroborar la imputación, el juez citará a
audiencia de sentencia La ley establecerá los beneficios que se
podrán otorgar al inculpado cuando acepte su responsabilidad;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
El juez sólo condenará cuando exista convicción de la culpabilidad
del procesado;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IX</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Cualquier prueba obtenida con violación de derechos fundamentales
será nula, y</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>X</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Los principios previstos en este artículo, se observarán también
en las audiencias preliminares al juicio</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>B</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
De los derechos de toda persona imputada:</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
A que se presuma su inocencia mientras no se declare su
responsabilidad mediante sentencia emitida por el juez de la causa;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
A declarar o a guardar silencio Desde el momento de su detención se
le harán saber los motivos de la misma y su derecho a guardar
silencio, el cual no podrá ser utilizado en su perjuicio Queda
prohibida y será sancionada por la ley penal, toda incomunicación,
intimidación o tortura La confesión rendida sin la asistencia del
defensor carecerá de todo valor probatorio;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
A que se le informe, tanto en el momento de su detención como en su
comparecencia ante el Ministerio Público o el juez, los hechos
que se le imputan y los derechos que le asisten Tratándose de
delincuencia organizada, la autoridad judicial podrá autorizar
que se mantenga en reserva el nombre y datos del acusador</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley establecerá beneficios a favor del inculpado, procesado o
sentenciado que preste ayuda eficaz para la investigación y
persecución de delitos en materia de delincuencia organizada;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Se le recibirán los testigos y demás pruebas pertinentes que
ofrezca, concediéndosele el tiempo que la ley estime necesario
al efecto y auxiliándosele para obtener la comparecencia de las
personas cuyo testimonio solicite, en los términos que señale la
ley;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Será juzgado en audiencia pública por un juez o tribunal La
publicidad sólo podrá restringirse en los casos de excepción que
determine la ley, por razones de seguridad nacional, seguridad
pública, protección de las víctimas, testigos y menores,
cuando se ponga en riesgo la revelación de datos legalmente
protegidos, o cuando el tribunal estime que existen razones fundadas
para justificarlo</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
delincuencia organizada, las actuaciones realizadas en la fase de
investigación podrán tener valor probatorio, cuando no puedan
ser reproducidas en juicio o exista riesgo para testigos o víctimas
Lo anterior sin perjuicio del derecho del inculpado de
objetarlas o impugnarlas y aportar pruebas en contra;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Le serán facilitados todos los datos que solicite para su defensa y
que consten en el proceso</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
imputado y su defensor tendrán acceso a los registros de la
investigación cuando el primero se encuentre detenido y cuando
pretenda recibírsele declaración o entrevistarlo Asimismo, antes
de su primera comparecencia ante juez podrán consultar dichos
registros, con la oportunidad debida para preparar la defensa A
partir de este momento no podrán mantenerse en reserva las
actuaciones de la investigación, salvo los casos excepcionales
expresamente señalados en la ley cuando ello sea imprescindible para
salvaguardar el éxito de la investigación y siempre que sean
oportunamente revelados para no afectar el derecho de defensa;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Será juzgado antes de cuatro meses si se tratare de delitos cuya
pena máxima no exceda de dos años de prisión, y antes de un año
si la pena excediere de ese tiempo, salvo que solicite mayor plazo
para su defensa;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Tendrá derecho a una defensa adecuada por abogado, al cual elegirá
libremente incluso desde el momento de su detención Si no
quiere o no puede nombrar un abogado, después de haber sido
requerido para hacerlo, el juez le designará un defensor
público También tendrá derecho a que su defensor comparezca en
todos los actos del proceso y éste tendrá obligación de hacerlo
cuantas veces se le requiera, y</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IX</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
En ningún caso podrá prolongarse la prisión o detención, por
falta de pago de honorarios de defensores o por cualquiera otra
prestación de dinero, por causa de responsabilidad civil o algún
otro motivo análogo</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
prisión preventiva no podrá exceder del tiempo que como máximo de
pena fije la ley al delito que motivare el proceso y en ningún caso
será superior a dos años, salvo que su prolongación se deba al
ejercicio del derecho de defensa del imputado Si cumplido este
término no se ha pronunciado sentencia, el imputado será puesto en
libertad de inmediato mientras se sigue el proceso, sin que ello
obste para imponer otras medidas cautelares</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
toda pena de prisión que imponga una sentencia, se computará el
tiempo de la detención</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>C</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
De los derechos de la víctima o del ofendido:</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Recibir asesoría jurídica; ser informado de los derechos que en su
favor establece la Constitución y, cuando lo solicite, ser
informado del desarrollo del procedimiento penal;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Coadyuvar con el Ministerio Público; a que se le reciban todos los
datos o elementos de prueba con los que cuente, tanto en la
investigación como en el proceso, a que se desahoguen las
diligencias correspondientes, y a intervenir en el juicio e
interponer los recursos en los términos que prevea la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Cuando
el Ministerio Público considere que no es necesario el desahogo de
la diligencia, deberá fundar y motivar su negativa;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Recibir, desde la comisión del delito, atención médica y
psicológica de urgencia;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Que se le repare el daño En los casos en que sea procedente, el
Ministerio Público estará obligado a solicitar la reparación del
daño, sin menoscabo de que la víctima u ofendido lo pueda solicitar
directamente, y el juzgador no podrá absolver al sentenciado de
dicha reparación si ha emitido una sentencia condenatoria</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley fijará procedimientos ágiles para ejecutar las sentencias en
materia de reparación del daño;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Al resguardo de su identidad y otros datos personales en los
siguientes casos: cuando sean menores de edad; cuando se trate
de delitos de violación, secuestro o delincuencia organizada; y
cuando a juicio del juzgador sea necesario para su protección,
salvaguardando en todo caso los derechos de la defensa</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Ministerio Público deberá garantizar la protección de víctimas,
ofendidos, testigos y en general todas los sujetos que intervengan en
el proceso Los jueces deberán vigilar el buen cumplimiento de esta
obligación;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Solicitar las medidas cautelares y providencias necesarias para la
protección y restitución de sus derechos, y</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Impugnar ante autoridad judicial las omisiones del Ministerio Público
en la investigación de los delitos, así como las resoluciones de
reserva, no ejercicio, desistimiento de la acción penal o
suspensión del procedimiento cuando no esté satisfecha la
reparación del daño</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART21"></a>
