<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
21</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Tenemos
también como garantía que nos da este artículo 21, el que nadie
nos puede condenar, en caso de haber cometido algún delito, más que
una Autoridad Judicial (Juez) que es el que tiene esta facultad
Ningún funcionario público lo puede hacer Además, la
investigación y persecución de algún delito que alguien haya
cometido, sólo la puede realizar el ministerio público, el cual
tiene bajo su autoridad a la policía judicial y que lo auxilia La
autoridad administrativa puede tener facultades para imponer
multas, como las de tránsito, o por faltas a algún reglamento y en
ocasiones decretar un arresto, que nunca puede pasar de 36 horas,
como el alcoholímetro A la persona que se tuviera que multar y sólo
ganara el salario mínimo, lo máximo que se le puede aplicar de
multa es un día de salario mínimo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Cuando
cualquier persona pone una denuncia o querella ante el ministerio
público y éste resuelve que no procede, se podrá impugnar dicha
resolución por la vía jurisdiccional, de acuerdo a la ley</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
autoridades federales, estatales, el distrito federal y los
municipios, tienen como función y obligación guardar y restablecer
la seguridad pública, para lo cual tendrá a su disposición a la
policía Todas las autoridades, de acuerdo a la ley, tienen la
obligación de coordinarse para establecer un sistema de seguridad
nacional</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 02in; line-height: 100%"><br>
</p>
<p class="western" align="justify" style="text-indent: 02in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
21</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La investigación de los delitos corresponde al Ministerio Público y
a las policías, las cuales actuarán bajo la conducción y mando de
aquél en el ejercicio de esta función</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
ejercicio de la acción penal ante los tribunales corresponde al
Ministerio Público La ley determinará los casos en que los
particulares podrán ejercer la acción penal ante la autoridad
judicial</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
imposición de las penas, su modificación y duración son propias y
exclusivas de la autoridad judicial</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Compete
a la autoridad administrativa la aplicación de sanciones por las
infracciones de los reglamentos gubernativos y de policía, las
que únicamente consistirán en multa, arresto hasta por treinta
y seis horas o en trabajo a favor de la comunidad; pero si el
infractor no pagare la multa que se le hubiese impuesto, se permutará
esta por el arresto correspondiente, que no excederá en ningún caso
de treinta y seis horas</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Si
el infractor de los reglamentos gubernativos y de policía fuese
jornalero, obrero o trabajador, no podrá ser sancionado con multa
mayor del importe de su jornal o salario de un día</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Tratándose
de trabajadores no asalariados, la multa que se imponga por
infracción de los reglamentos gubernativos y de policía, no
excederá del equivalente a un día de su ingreso</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Ministerio Público podrá considerar criterios de oportunidad para
el ejercicio de la acción penal, en los supuestos y condiciones que
fije la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Ejecutivo Federal podrá, con la aprobación del Senado en cada caso,
reconocer la jurisdicción de la Corte Penal Internacional</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
seguridad pública es una función a cargo de la Federación, el
Distrito Federal, los Estados y los Municipios, que comprende la
prevención de los delitos; la investigación y persecución
para hacerla efectiva, así como la sanción de las infracciones
administrativas, en los términos de la ley, en las respectivas
competencias que esta Constitución señala La actuación de las
instituciones de seguridad pública se regirá por los principios de
legalidad, objetividad, eficiencia, profesionalismo, honradez y
respeto a los derechos humanos reconocidos en esta Constitución</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
instituciones de seguridad pública serán de carácter civil,
disciplinado y profesional El Ministerio Público y las
instituciones policiales de los tres órdenes de gobierno deberán
coordinarse entre sí para cumplir los objetivos de la seguridad
pública y conformarán el Sistema Nacional de Seguridad Pública,
que estará sujeto a las siguientes bases mínimas:</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>a)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La regulación de la selección, ingreso, formación, permanencia,
evaluación, reconocimiento y certificación de los integrantes de
las instituciones de seguridad pública La operación y desarrollo
de estas acciones será competencia de la Federación, el
Distrito Federal, los Estados y los municipios en el ámbito de sus
respectivas atribuciones</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>b)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
El establecimiento de las bases de datos criminalísticos y de
personal para las instituciones de seguridad pública Ninguna
persona podrá ingresar a las instituciones de seguridad pública
si no ha sido debidamente certificado y registrado en el sistema</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>c)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La formulación de políticas públicas tendientes a prevenir la
comisión de delitos</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>d)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Se determinará la participación de la comunidad que coadyuvará,
entre otros, en los procesos de evaluación de las políticas de
prevención del delito así como de las instituciones de seguridad
pública</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>e)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Los fondos de ayuda federal para la seguridad pública, a nivel
nacional serán aportados a las entidades federativas y municipios
para ser destinados exclusivamente a estos fines</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART22"></a>
