<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>ARTÍCULO
22</i></span></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
México, y esto es muy importante saberlo, está prohibida la pena de
muerte para cualquier persona, por grave que sea su delito Además,
a nadie, porque está también prohibido, se le puede mutilar,
cortar un dedo, una mano, etc, ni tampoco injuriársele, es
decir, hablar mal de la persona, aunque sea culpable Mucho menos,
marcarlo con tatuajes, cicatrices o lo que se llama </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“ficharlo”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Tampoco se le puede golpear, no puede haber un castigo a base de
golpes, ni con ello hacerlo confesar algo Otra cosa que no se
puede hacer, por estar prohibido, es el tormento de cualquier
especie, ni física ni psicológica, diciendo, por ejemplo, que
tienen a su familia y la van a golpear o violar No puede haber
multas excesivas, ni confiscación de bienes a alguien; ni tampoco
penas que no están contempladas por la Ley La Autoridad que haga lo
que ya vimos que está prohibido, comete un delito que se encuentra
en el código penal, hay que denunciar estos hechos y exigir el
castigo severo a quien lo haga</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ul>
	<li><p style="line-height: 100%"><font face="Tahoma, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES">	Después
	de habérsele dado la oportunidad a cualquier persona de defenderse
	y habiéndose comprobado que no pagó impuestos, o una multa, o
	bienes ilícitos, enriquecimiento inexplicable, bienes
	obtenidos por secuestros, serán embargados o decomisados sin que se
	considere confiscación</span></font></font></font></font></p>
</ul>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
22</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Quedan prohibidas las penas de muerte, de mutilación, de infamia,
la marca, los azotes, los palos, el tormento de cualquier especie, la
multa excesiva, la confiscación de bienes y cualesquiera otras
penas inusitadas y trascendentales Toda pena deberá ser
proporcional al delito que sancione y al bien jurídico
afectado</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
se considerará confiscación la aplicación de bienes de una persona
cuando sea decretada para el pago de multas o impuestos, ni cuando la
decrete una autoridad judicial para el pago de responsabilidad
civil derivada de la comisión de un delito Tampoco se considerará
confiscación el decomiso que ordene la autoridad judicial de los
bienes en caso de enriquecimiento ilícito en los términos del
artículo 109, la aplicación a favor del Estado de bienes asegurados
que causen abandono en los términos de las disposiciones aplicables,
ni la de aquellos bienes cuyo dominio se declare extinto en
sentencia En el caso de extinción de dominio se establecerá un
procedimiento que se regirá por las siguientes reglas:</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Será jurisdiccional y autónomo del de materia penal;</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Procederá en los casos de delincuencia organizada, delitos contra la
salud, secuestro, robo de vehículos y trata de personas, respecto de
los bienes siguientes:</i></font></font></font></font></font></p>
<p lang="es-ES" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i><b>a)</b></i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i>
</i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Aquellos
que sean instrumento, objeto o producto del delito, aún cuando no se
haya dictado la sentencia que determine la responsabilidad penal,
pero existan elementos suficientes para determinar que el hecho
ilícito sucedió</i></font></font></font></font></font></p>
<p lang="es-ES" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i><b>b)</b></i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i>
</i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Aquellos
que no sean instrumento, objeto o producto del delito, pero que hayan
sido utilizados o destinados a ocultar o mezclar bienes producto del
delito, siempre y cuando se reúnan los extremos del inciso anterior</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i><b>c)</b></i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i>
</i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Aquellos
que estén siendo utilizados para la comisión de delitos por un
tercero, si su dueño tuvo conocimiento de ello y no lo notificó
a la autoridad o hizo algo para impedirlo</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i><b>d)</b></i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><span lang="es-ES"><i>
</i></span></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Aquellos
que estén intitulados a nombre de terceros, pero existan suficientes
elementos para determinar que son producto de delitos patrimoniales o
de delincuencia organizada, y el acusado por estos delitos se
comporte como dueño</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Toda persona que se considere afectada podrá interponer los recursos
respectivos para demostrar la procedencia lícita de los bienes
y su actuación de buena fe, así como que estaba impedida para
conocer la utilización ilícita de sus bienes</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART23"></a>
