<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
23</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
nuestro país, la constitución nos da la garantía de que todo
juicio de cualquier tipo, civil, laboral, penal, familiar,
administrativo, sólo tendrá tres instancias: la sentencia que dicte
el juez al término del juicio, en el que se permitieron, de
acuerdo a la ley y garantías constitucionales, las defensas de las
partes, que alegaron todo lo que a su derecho convino La segunda
instancia es la apelación que puede solicitar cualquiera de las
partes que se vieron involucradas en el juicio y no están de
acuerdo a la sentencia; esta instancia se lleva a cabo ante los
tribunales de alzada La tercera instancia es a nivel federal, que
consiste en el amparo; si alguna o todas las partes no están de
acuerdo con la resolución de segunda instancia</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
garantía, que es el artículo 23, nos da la seguridad a todos los
habitantes de México de que nadie puede ser juzgado dos veces
por el mismo delito Si una persona fue juzgada por algún delito y
salió sentenciado o absuelto, ya no se le puede volver a juzgar por
ningún motivo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
23</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Ningún juicio criminal deberá tener más de tres instancias Nadie
puede ser juzgado dos veces por el mismo delito, ya sea que en el
juicio se le absuelva o se le condene Queda prohibida la práctica
de absolver de la instancia</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART24"></a>
