<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
24</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo nos garantiza el derecho de y la libertad de profesar la
religión que más nos agrade No se nos puede imponer alguna
religión en especial, ni hay religión oficial Tampoco se puede
discriminar a nadie por profesar alguna determinada religión;
así lo establece y ratifica el artículo 1º de la constitución,
el derecho de igualdad y no discriminación También se garantiza
que puede practicar las ceremonias y devociones que su religión
disponga, siempre y cuando no se cometan delitos; como pueden ser:
sacrificios humanos, incitación a las drogas o prácticas de
tortura; hacerlo es delito sin importar la religión Ninguna
religión puede estar prohibida por alguna autoridad o alguna ley
Todo acto religioso debe llevarse a cabo dentro de sus respectivos
templos En caso de celebrar algún acto religioso fuera de sus
templos, deberá sujetarse a la ley reglamentaria para poderse
realizar</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
24</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Todo hombre es libre para profesar la creencia religiosa que más le
agrade y para practicar las ceremonias, devociones o actos del culto
respectivo, siempre que no constituyan un delito o falta penados por
la ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Congreso no puede dictar leyes que establezcan o prohiban religión
alguna</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
actos religiosos de culto público se celebrarán ordinariamente en
los templos Los que extraordinariamente se celebren fuera de
éstos se sujetarán a la ley reglamentaria</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; background: #ffffff; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART25"></a>
