<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
25</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Hasta
ahora hemos visto los primeros 24 artículos de la constitución,
mediante los cuales se nos garantizan los derechos individuales,
los que cada persona tiene y que el estado está obligado a
hacer cumplir frente a violaciones, interferencias o intromisiones de
los poderes públicos Es decir, ante las autoridades que
arbitrariamente y sin ninguna facultad quieren que la gente haga lo
que ellos quieren, porque creen que la autoridad puede hacerlo todo
Pero, también la autoridad está obligada a cumplir lo que la
ley le ordena Esto ya lo vimos en el artículo 16
constitucional También estas garantías protegen los derechos
de las personas en lo individual, contra grupos sociales como los
sindicatos, partidos políticos, religiosos, etc, que quieran
imponer sus políticas de acuerdo a sus intereses de grupo, violando
los derechos de cada persona Así también, contra las violaciones
de otros individuos, como serían los robos, el secuestro,
agresiones, amenazas y otros Esto es precisamente lo que garantiza y
defiende la constitución y la autoridad está obligada a hacerla
cumplir, para que cada persona disfrute de su libertad de ser, hacer
y tener</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ahora
bien, ya hemos visto y estudiado que cada persona tiene el derecho y
está garantizado por la constitución de que se le brinde educación,
salud, vivienda, justicia, servicios como agua, drenaje,
transporte, electricidad, comunicaciones, trabajo, y todo lo que
se requiere para el desarrollo armónico de cada individuo y de la
sociedad</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Es
verdad que cada persona tiene la libertad garantizada de trabajar en
lo que más le guste y le acomode, pero también es verdad que no lo
puede hacer todo Puede ser por decisión y gusto propio ser
carpintero y a eso dedicarse; pero requiere de alimentos que esta
persona no produce; además, vivienda, que tampoco construye; un auto
transporte que no fabrica y necesita para trasladarse a su
trabajo y, muchas cosas más Por lo tanto, requiere del trabajo de
otras personas que realizan funciones que esta persona necesita; y
asimismo todos necesitan de todos Pero puede suceder que muy poca
gente trabaje en la producción de alimentos, y no sean suficientes
para dar de comer a todos los miembros de la sociedad Esto
provocaría graves problemas de alimentación y especulación; ya que
el que tenga más recursos es el que come y los demás no Se
provocarían a su vez otros problemas como la desnutrición y
enfermedad por falta de alimentos; así también, luchas fratricidas
por obtener los pocos alimentos, cometiéndose delitos y
violaciones a los derechos individuales Este es solo un ejemplo,
pero lo mismo sucedería con la salud, vivienda, servicios y todo lo
que nos podamos imaginar De nada servirían las garantías
individuales si no son encauzadas por un orden, que garantice a todos
los miembros de la sociedad la satisfacción de sus necesidades
y se evite el caos</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
lo anterior, es de vital importancia la creación de una estructura
social, política y económica de nuestro país De ahí, que
nuestra constitución, en sus artículos 25, 26, 27 y 28 define
claramente el orden jurídico de los bienes, finanzas y procesos
económicos, que permitan que el estado tenga como función las
relaciones entre la economía de la sociedad y los derechos
individuales, para lograr, de manera armónica e integral, la
convivencia de la sociedad y el logro justo de la satisfacción
de sus necesidades, sin menoscabo de los derechos individuales
Por lo tanto, no sólo existen los derechos individuales garantizados
en nuestra constitución, sino también los derechos sociales, que
tienen como característica ser democráticos, igualitarios y
sociales El objetivo es que nadie se aproveche de las necesidades de
nadie, ni las mismas autoridades Esto pretende los siguientes
artículos que iremos analizando, para proteger estos derechos
sociales y que se cumplan</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">De
ahí, que el artículo 25 constitucional mencione que el estado debe
ser el rector y quien dirija el desarrollo nacional y garantizar que
sea integral y sustentable, es decir, que no sólo vea por separado
la producción de alimentos, descuidando la educación y
capacitación; ya que sin educación y capacitación no se
pueden producir alimentos Como tampoco se puede descuidar la
construcción de carreteras por donde se puedan transportar
los productos alimentarios a todos los lugares donde haya población
De la misma manera, nada serviría si se descuida la industria
eléctrica y de combustibles, necesarias para el trabajo de máquinas
y transportes Esto es un ejemplo del concepto integral Además,
debe ser sustentable que no tenga interrupción o que solo sea
esporádico Por lo tanto, el estado está obligado a que toda la
población tenga acceso a los alimentos, fomentando,
promoviendo, estimulando y garantizando la producción de todo tipo
de alimentos; y en caso de que hubiera algún déficit, deberá
ver la posibilidad de importar alimentos para cubrir la demanda
En la misma forma, de manera integral, deberá generar la
electricidad suficiente, así como los combustibles, para no
detener la producción de alimentos y todo lo necesario Lo mismo
sucede con todas las actividades requeridas para la satisfacción de
las necesidades de la sociedad, en lo individual y en lo general De
esta manera, se fortalece la soberanía nacional y su régimen
democrático; no dependiendo de otros países y de acuerdo a la
voluntad del pueblo mexicano</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entendiendo
régimen democrático, como lo establece el artículo 3º
constitucional, un sistema de vida a través del cual está la
participación de la sociedad y de cada uno de sus miembros en
la toma de decisiones, propuestas y acciones, que le permitan
una vida digna, para encontrar la solución y satisfactores que
una sociedad moderna requiere debido a su evolución Así el
estado, con la participación y por la sociedad, debe fomentar el
crecimiento económico y el empleo del pueblo Si no hay empleo y
alguien que lo dirija, la sociedad no puede tener un desarrollo
económico, cayendo en la pobreza mental, material y social Pero es
obligación del estado, junto con la sociedad, encontrar fórmulas
para una justa distribución de la riqueza creada por todos Esto,
nos menciona este artículo 25, y el estado debe garantizarlo en los
hechos Solo así habrá un pleno ejercicio de la libertad y la
dignidad de los mexicanos, organizaciones y clases sociales que
protege nuestra constitución</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
eso, el estado está obligado a planear, conducir, coordinar y
orientar la actividad económica nacional, así como regular y
fomentar, promover, incentivar y garantizar todas las
actividades, profesionales, comerciales, productivas, financieras e
industriales, que se requieran por la sociedad, en un marco de
libertad y derecho, que consagra nuestra constitución</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Así
lo establece la carta magna al garantizar, en este artículo 25, la
participación del sector público, que son las empresas y
organismos descentralizados del estado; el sector social, dónde
participan gobierno y sociedad; y el sector particular, consistente
en la participación de empresas particulares y todos y cada uno de
los mexicanos, con su trabajo, recursos e ideas y otras formas
de actividad económica, como la inversión extranjera, que
contribuye al desarrollo de la nación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
estado, a través del sector público, tendrá a su cargo, y de
manera exclusiva, las áreas estratégicas que están señaladas
en el artículo 28 que ya veremos cuando lleguemos a ese
artículo, así como el por qué de ello</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
el estado podrá participar, de acuerdo con la ley, en el sector
social y privado, para organizar e impulsar áreas
prioritarias y que no hayan sido debidamente atendidas por la
sociedad en general e individual, para el desarrollo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">El estado, de
acuerdo a este artículo, está obligado a ayudar e impulsar a las
empresas del sector social y particulares, para hacerlas más
productivas y cumplan con su función de generar empleos y bienes y
servicios que requiere la sociedad Sobre todo debe, el estado, poner
especial atención para la organización y crecimiento de la
actividad social, como son los ejidos, organizaciones de
trabajadores, cooperativas, comunidades y empresas de los
trabajadores, para que consoliden y aumenten su producción,
distribución y consumo de bienes y servicios que requiere el pueblo
mexicano</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
supuesto, que este artículo garantiza que el estado, de acuerdo a la
ley, alentará y protegerá la actividad económica que realicen
todos y cada uno de los mexicanos, y dará todas las facilidades y
condiciones para que el pueblo mexicano se desarrolle fuertemente en
sus actividades económicas del tipo que sean: artesanales,
industriales, comerciales, financieras, artísticas, deportivas,
talleres, campesinos, y toda actividad que contribuya al desarrollo
económico y social del pueblo mexicano Todo esto debemos conocerlo,
entenderlo, comprenderlo y, sobre todo, aprovecharlo, porque
tenemos derecho y está garantizado por la constitución Está en
nuestras manos el ser, el hacer y el tener</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
25</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Corresponde al Estado la rectoría del desarrollo nacional para
garantizar que éste sea integral y sustentable, que fortalezca
la Soberanía de la Nación y su régimen democrático y que,
mediante el fomento del crecimiento económico y el empleo y una
más justa distribución del ingreso y la riqueza, permita el pleno
ejercicio de la libertad y la dignidad de los individuos, grupos y
clases sociales, cuya seguridad protege esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado planeará, conducirá, coordinará y orientará la actividad
económica nacional, y llevará al cabo la regulación y fomento de
las actividades que demande el interés general en el marco de
libertades que otorga esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Al
desarrollo económico nacional concurrirán, con responsabilidad
social, el sector público, el sector social y el sector
privado, sin menoscabo de otras formas de actividad económica que
contribuyan al desarrollo de la Nación</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
sector público tendrá a su cargo, de manera exclusiva, las áreas
estratégicas que se señalan en el Artículo 28, párrafo cuarto de
la Constitución, manteniendo siempre el Gobierno Federal la
propiedad y el control sobre los organismos que en su caso se
establezcan</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Asimismo
podrá participar por sí o con los sectores social y privado, de
acuerdo con la ley, para impulsar y organizar las áreas prioritarias
del desarrollo</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Bajo
criterios de equidad social y productividad se apoyará e impulsará
a las empresas de los sectores social y privado de la economía,
sujetándolos a las modalidades que dicte el interés público y
al uso, en beneficio general, de los recursos productivos, cuidando
su conservación y el medio ambiente</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley establecerá los mecanismos que faciliten la organización y la
expansión de la actividad económica del sector social: de los
ejidos, organizaciones de trabajadores, cooperativas,
comunidades, empresas que pertenezcan mayoritaria o exclusivamente
a los trabajadores y, en general, de todas las formas de organización
social para la producción, distribución y consumo de bienes y
servicios socialmente necesarios</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley alentará y protegerá la actividad económica que realicen los
particulares y proveerá las condiciones para que el desenvolvimiento
del sector privado contribuya al desarrollo económico nacional,
en los términos que establece esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART26"></a>
