<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>ARTÍCULO
26 </i></span></font></font></b></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo obliga al estado a organizar un sistema de planeación
democrática, es decir, con la participación de la sociedad
mexicana a través de sus organismos y en lo particular, para el
desarrollo nacional y que se tengan bases sólidas, firmes y con
dinamismo, que no se detenga por ninguna causa, y de haber algún
problema, solucionarlo para no detener su marcha, que además sea
permanente y no se esté cambiando por improvisaciones; tener como
base la igualdad para todos, para que haya un constante y seguro
crecimiento de las actividades de la sociedad, cuidando la
independencia y la democracia política, social y cultural de la
nación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
sociedad tiene el derecho de participar indicando cuáles son sus
propuestas, necesidades y actividades, para que sean tomadas en
cuenta y se integren al plan y programa de desarrollo, que tiene
obligación todo gobierno de presentar al iniciar su ejercicio Esto
se le conoce como </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>P</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>lan
Nacional de Desarrollo</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">El estado
determinará los órganos responsables para que el ejecutivo federal
coordine, mediante convenios con los gobiernos de cada estado, así
como promueva y concerte con los mexicanos, a través de sus
organismos, empresas y en lo particular, las acciones que se deben
realizar para la elaboración y ejecución del plan nacional de
desarrollo Aprovechemos esta garantía que nos da nuestra carta
magna, para crear empleos, generar bienes y servicios que
necesitamos; crear riqueza y distribuirla de manera justa; hacer
una gran cultura del pueblo mexicano, que permita estar en constante
superación, con dignidad y humanismo</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
26 A </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado organizará un sistema de planeación democrática del
desarrollo nacional que imprima solidez, dinamismo, permanencia y
equidad al crecimiento de la economía para la independencia y la
democratización política, social y cultural de la Nación</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
fines del proyecto nacional contenidos en esta Constitución
determinarán los objetivos de la planeación La planeación será
democrática Mediante la participación de los diversos
sectores sociales recogerá las aspiraciones y demandas de la
sociedad para incorporarlas al plan y los programas de desarrollo
Habrá un plan nacional de desarrollo al que se sujetarán
obligatoriamente los programas de la Administración Pública
Federal</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley facultará al Ejecutivo para que establezca los procedimientos de
participación y consulta popular en el sistema nacional de
planeación democrática, y los criterios para la formulación,
instrumentación, control y evaluación del plan y los programas de
desarrollo Asimismo, determinará los órganos responsables del
proceso de planeación y las bases para que el Ejecutivo Federal
coordine mediante convenios con los gobiernos de las entidades
federativas e induzca y concierte con los particulares las acciones a
realizar para su elaboración y ejecución</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
el sistema de planeación democrática, el Congreso de la Unión
tendrá la intervención que señale la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>B
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado contará con un Sistema Nacional de Información Estadística
y Geográfica cuyos datos serán considerados oficiales Para la
Federación, estados, Distrito Federal y municipios, los datos
contenidos en el Sistema serán de uso obligatorio en los términos
que establezca la ley</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
responsabilidad de normar y coordinar dicho Sistema estará a cargo
de un organismo con autonomía técnica y de gestión, personalidad
jurídica y patrimonio propios, con las facultades necesarias para
regular la captación, procesamiento y publicación de la información
que se genere y proveer a su observancia</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
organismo tendrá una Junta de Gobierno integrada por cinco miembros,
uno de los cuales fungirá como Presidente de ésta y del propio
organismo; serán designados por el Presidente de la República
con la aprobación de la Cámara de Senadores o en sus recesos
por la Comisión Permanente del Congreso de la Unión</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley establecerá las bases de organización y funcionamiento del
Sistema Nacional de Información Estadística y Geográfica, de
acuerdo con los principios de accesibilidad a la información,
transparencia, objetividad e independencia; los requisitos que
deberán cumplir los miembros de la Junta de Gobierno, la duración y
escalonamiento de su encargo</i></font></font></font></font></font></p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 049in; margin-right: 043in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Arial, serif"><font size="2" style="font-size: 9pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
miembros de la Junta de Gobierno sólo podrán ser removidos por
causa grave y no podrán tener ningún otro empleo, cargo o comisión,
con excepción de los no remunerados en instituciones docentes,
científicas, culturales o de beneficencia; y estarán sujetos a lo
dispuesto por el Título Cuarto de esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
