<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>ARTÍCULO
27</i></span></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Recordemos
que estamos estudiando y tratando de comprender estos artículos
25, 26, 27 y 28, que son las garantías de los derechos sociales
Ahora veremos este artículo 27, en donde se nos garantiza a
todos y cada uno de los ciudadanos, que </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>México</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
es nuestro por igual y además, lo que compone a nuestro país
es la riqueza de todos los mexicanos; la forma en que nos
pertenece y cómo la podemos aprovechar</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo nos menciona que la propiedad de las tierras y aguas
comprendidas dentro de los límites del territorio nacional
corresponde originariamente a la nación Para empezar debemos
saber que el nombre oficial de </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>México</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
es: </i></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Estados
Unidos Mexicanos</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Tiene una extensión territorial de 1’964,375 kilómetros
cuadrados, que es la superficie continental y se encuentra en el
continente americano Además tiene 5,127 km</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">²</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
de superficie insular, es decir, de Islas Tiene también, y le
pertenecen, 3’149,920 kilómetros cuadrados de territorio marino
Es decir, 200 millas mar adentro de todos los litorales de la
</font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>República
Mexicana</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Por lo que la superficie total es de, 5’114,295 kilómetros
cuadrados</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
coordenadas extremas que enmarcan el territorio mexicano, son:</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>norte</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>:</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
32º 43’ 06” latitud norte, en el monumento 2006, en la frontera
con </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Estados
Unidos de América</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y que tiene una extensión de 3,15290 kilómetros</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al
</font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>sur</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>:</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
14º 32’ 27” latitud norte, en la desembocadura del </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Río
Suchiate</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
frontera con Guatemala, con extensión de 1,1498 km</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al
</font></font><font color="#000080"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>este</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>:</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
86º 42’ 36” longitud oeste, en el extremo suroeste de la </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Isla
Mujeres</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 038in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al
</font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>oeste</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>:</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
118º 27’ 24” longitud oeste, en la punta roca elefante de la
</font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Isla
de Guadalupe</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
en el </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Océano
Pacífico</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%"><a name="FRONTERAS"></a>
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>FRONTERAS:</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
república mexicana tiene fronteras con los </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Estados
Unidos de América</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Guatemala</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y </font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Belice</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
a lo largo de un total de 4,301 kilómetros, distribuidos de la
siguiente forma:</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 025in; line-height: 100%">
<br>
</p>
<ul>
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Con
	los Estados Unidos de América, se extiende una línea fronteriza
	a lo largo de 3,152 kilómetros, desde el movimiento 258 al noroeste
	de Tijuana, hasta la desembocadura del </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>río
	Bravo</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	en el </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Golfo
	de México</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	son estados limítrofes al norte del país: </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Baja
	California</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Sonora</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Chihuahua</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Coahuila</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Nuevo
	León</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	y </font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Tamaulipas</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b></b></i></font></font></font></font></p>
</ul>
<p class="western" align="justify" style="margin-left: 059in; text-indent: 025in; line-height: 100%">
<br>
</p>
<ul>
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
	línea fronteriza con </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Guatemala</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	tiene una extensión de 956 kilómetros; con </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Belice</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
	de 193 kilómetros  los estados fronterizos del sur y sureste del
	país son: </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Chiapas</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Tabasco</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
	</i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Campeche</b></i></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	y </font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Quintana
	Roo</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
</ul>
<p align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="center" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><b>LA
REPUBLICA MEXICANA</b></font></font></font></font></font></p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<span dir="ltr" style="float: left; width: 469in; height: 381in; border: 1px solid #000000; padding: 005in 01in; background: #ffffff">
	<p align="center" style="background: #e6e6e6; line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><b>LA
	DIVISIÓN POLÍTICA DE MÉXICO SE COMPONE DE</b></font></font></font></p>
	<p align="center" style="background: #e6e6e6; line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><b>32
	ENTIDADES FEDERATIVAS</b></font></font></font></p>
	<p align="center" style="background: #e6e6e6; line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><b>QUE
	SON:</b></font></font></font></p>
	<p align="center" style="margin-bottom: 014in; background: #e6e6e6; line-height: 115%">
	<br><br>
	</p>
	<p align="center" style="background: #e6e6e6; line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000080"><b>ESTADOS
	DE LA REPUBLICA</b></font></font></font></p>
</span><br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="line-height: 100%"><br>
</p>
<p class="western" align="center" style="line-height: 100%"><br>
</p>
<p class="western" align="center" style="line-height: 100%"><br>
</p>
<p class="western" align="center" style="line-height: 100%"><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p align="center" style="line-height: 100%"><br>
</p>
<p align="center" style="line-height: 100%"><br>
</p>
<p align="center" style="line-height: 100%"><br>
</p>
<p align="center" style="line-height: 100%"><font color="#000080"><b><font color="#0000ff"><font size="4" style="font-size: 14pt">LA
CAPITAL DE LA REPÚBLICA MEXICANA ES</font></font></b></font></p>
<p class="western" align="center" style="margin-bottom: 014in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><b>EL
DISTRITO FEDERAL</b></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<span dir="ltr" style="float: left; width: 417in; height: 337in; border: 1px solid #000000; padding: 005in 01in; background: #ffffff">
	<p align="left" style="margin-bottom: 014in; background: #e6e6e6; line-height: 115%">
	      
	</p>
	<p align="center" style="margin-bottom: 014in; background: #e6e6e6; line-height: 115%">
	<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000080"><font size="4" style="font-size: 14pt"><b>DISTRITO
	FEDERAL</b></font></font></font></font></p>
</span><br><br>
</p>
<p class="western" align="center" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%"><a name="POBLACIÓN"></a>
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>POBLACIÓN:</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">México
cuenta con una población de 112’203,388 habitantes, de acuerdo con
el más reciente censo del instituto nacional de estadística,
geografía e informática (2010), que representan el 16% por
ciento de la población mundial (6,500 millones de habitantes) De
ellos, 57 millones son mujeres y 55 millones son hombres En México,
por su origen histórico, las lenguas indígenas y el español
son lenguas nacionales y tienen la misma validez en todo el
territorio La unidad monetaria es el peso</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todo
lo anterior ya sabemos ahora que es de todos los mexicanos De ahí,
que la nación tiene el derecho de transmitir el dominio de tierras y
aguas a los particulares, a nosotros, lo que constituye la “propiedad
privada” Entendamos que la nación nos da el “dominio”
solamente; porque las tierras y aguas siguen siendo de su propiedad
Esto es así, porque de otra manera, cualquier país podría
comprar tierras y aguas de la nación y pasarían a ser propiedad de
esos países, desapareciendo la nación mexicana Nosotros sólo
tenemos el dominio, pero la propiedad es de la nación y de esa
manera, siempre estará integrada la misma El dominio consiste en
tener el título de usufructo de nuestra casa, oficina, rancho,
parcela, etc, mismo que podamos transmitir a otra persona,
cualquiera que sea Aun los mismos extranjeros pueden adquirir
el dominio de alguna cosa y venderla después, pero la propiedad
es de la nación mexicana y no del país al que se le otorgue el
dominio El título de dominio es lo que llamamos </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Propiedad_privada"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>propiedad
privada</b></i></font></font></a></u></span></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Sin
embargo, el estado tiene la facultad que le da este artículo para
hacer expropiaciones Estas expropiaciones sólo se harán cuando
sean de utilidad pública Esto lo entendemos cuando se
expropian casas y terrenos, por ejemplo, para dar paso a una calle o
construir alguna carretera, las cuales estarán al servicio de
cualquier persona que necesite transitar por ahí No se puede
expropiar para dárselos a un grupo de personas o a alguna
persona en particular, porque entonces sólo beneficiaría a ellos
esa expropiación y no a todos los mexicanos Además de hacerse
la expropiación, se debe indemnizar a la persona que tiene el
dominio o propiedad privada de esos terrenos Aunque sea de utilidad
pública se debe hacer el pago de esas propiedades por parte del
estado Independientemente de llevar el procedimiento
correspondiente, como lo establece el artículo 16 constitucional y
la ley respectiva</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
nos dice este artículo que la nación tiene el derecho a imponer a
la propiedad privada las modalidades que dicte el interés público
Esto quiere decir que el estado está facultado para decidir qué
tipo de dominio o modalidad es de interés público, que pueden ser
ejidos, en los que sólo un campesino tiene la posesión de su
parcela, pero no la puede vender sólo la puede transmitir, de
acuerdo a la ley, a su esposa y/o hijos De no existir éstos,
entonces se dará posesión a los campesinos que hayan
solicitado tierras y estén en lista de espera Lo mismo sucede con
la modalidad de tierras comunales, o la que ya hemos visto, la
propiedad privada con título y que sí se puede vender a cualquier
persona</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
otra parte, el estado tiene el derecho de regular, en beneficio de la
sociedad, el aprovechamiento de los elementos naturales que se
pueden apropiar, con el objeto de hacer una distribución equitativa
de esos elementos que son una riqueza pública, como árboles,
animales, agua, etc Así como también el estado está obligado a
cuidarlos y conservarlos para lograr el desarrollo equilibrado
del país y el mejoramiento de las condiciones de vida de la
población rural y urbana Muy importante es que, el estado
deberá tomar y dictar las medidas necesarias para ordenar los
asentamientos humanos Lo que quiere decir, que la gente no puede
arbitrariamente crear asentamientos donde vivir si no tienen las
seguridades necesarias de que no corren ningún riesgo, como ya lo
hemos visto No se pueden hacer fraccionamientos en zonas de reserva
ecológica Tampoco en zonas arqueológicas, ni donde se
requieran hacer obras públicas, como presas o carreteras
Menos, destruir y acabar con bosques para hacer asentamientos
poblacionales El estado está obligado a planear y regular la
fundación, conservación, mejoramiento y crecimiento de los centros
de población Es decir, se deben planear todos los servicios
como agua, drenaje, comunicaciones, electricidad, abasto de
alimentos, zonas comerciales, industriales y de todo tipo de trabajo,
previendo el crecimiento de esa población y con todas las
seguridades que se requieran Sobre todo, cuidando y restaurando el
equilibrio ecológico, que con ciertas causas, como la basura y el
desagüe de aguas negras, se pueden causar problemas ecológicos que
repercutan en la vida humana y en su entorno Ahora, también tiene
la facultad el estado de fraccionar los latifundios, ya que no
está permitido que una persona posea grandes extensiones de tierras,
como sucedía en tiempos pasados Además, de acuerdo a la ley
reglamentaria, el estado puede disponer la organización y
explotación con todos los ejidatarios de sus tierras y comunidades
para el desarrollo de la pequeña propiedad rural Los
campesinos que son ejidatarios ya pueden, de acuerdo a la ley
reglamentaria, convertir su parcela en propiedad privada y venderla a
quien deseen Pero, si la parcela sigue estando bajo el régimen
ejidal, no la pueden vender, como ya lo vimos antes</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todo
lo anterior, es con el objeto de que no se vuelvan a repetir las
injusticias del pasado, cuando muy pocas personas tenían
grandes extensiones de tierras, creando latifundios, dejando a
los campesinos en condiciones de esclavos y sin alguna esperanza de
vida digna, para ellos y sus familias Se tenían que someter a los
caprichos y abusos de los latifundistas, o no tenían trabajo ni
vivienda Sobre todo, eran controlados en las tiendas de raya,
que los tenían siempre endrogados y comprometidos a trabajar por una
miseria, para pagar sus deudas Y tenían deudas para medio comer y
mal vestir Independientemente de que los latifundistas,
aplicaban su propia ley para castigar a los campesinos que,
según ellos, alteraban el orden No había derechos humanos y, mucho
menos, garantías de esos derechos Por eso, este artículo garantiza
el desarrollo armónico del campo y su gente, garantizando
primeramente los derechos que la constitución y además, el
derecho social de apoyar, promover, fomentar y garantizar el
desarrollo del medio rural, base de la alimentación de todo el
pueblo mexicano, así como su tenencia y explotación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ol>
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
	eso, este artículo garantiza el derecho social de que el estado
	fomente, promueva, estimule y garantice el desarrollo armónico e
	integral de la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Agricultura"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>agricultura</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	para que todos los habitantes de la república mexicana tengan a su
	alcance los alimentos que requieren con una dieta balanceada,
	para el mejor desarrollo físico y mental, a precios
	accesibles Al mismo tiempo, creando fuentes de trabajo,
	aprovechando todos los recursos naturales que tiene México, como
	son, tierras cultivables, agua, clima y la gran variedad de especies
	vegetales, que son propias de nuestro país y, por supuesto,
	defendiendo la soberanía nacional, al no depender en esta
	materia alimentaría de otros países, con la consiguiente
	salida de divisas, al pagar la importación de alimentos, poniendo
	en riesgo la economía financiera del país La agricultura va muy
	de la mano, y es complementaria, de la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Ganadería"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ganadería</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	y la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Silvicultura"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>silvicultura</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Sobre todo, que estas actividades rurales, incentivan y
	promueven otras que se complementan, como ya lo veremos</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="AGRICULTURA"></a>
