<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>AGRICULTURA</i></span></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Agricultura"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>agricultura</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
son todas aquellas actividades relacionadas con el aprovechamiento
de los suelos y el cultivo de vegetales, que sirven de alimentos para
la gente y para los animales domésticos Así como el
aprovechamiento de bosques, cuidado y siembra de árboles y
diferentes plantas, que nos permitan guardar el equilibrio ecológico</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
es una actividad de vital importancia, en la que deben participar
todos los sectores y toda persona con iniciativa y creatividad
que quiera dedicarse a la agricultura; no sólo es una actividad de
campesinos Es una de las vocaciones de nuestro país, que
requiere de manera integral la participación de todos los sectores y
personas, armonizando con todos los derechos que nos garantiza la
constitución Sin esta actividad agrícola, México sería
dependiente de otros países y tendría que aceptar sus condiciones</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todos
los mexicanos debemos pensar y tener la creatividad para participar
en este sector, que tiene el mayor número de oportunidades para
realizarnos, participando en el desarrollo de la sociedad, y
creando una gran cantidad de fuentes de trabajo, para satisfacer la
mayor necesidad del pueblo mexicano, que es la alimentación Por
supuesto en un mundo moderno, deben adoptarse y adaptarse todos los
adelantos científicos y tecnológicos, para un mayor desarrollo
agropecuario, para lo cual se debe tener en cuenta la iniciativa de
la gente para prepararse en las diferentes actividades que se
requieren en este sector Además, aprovechar y hacer realidad las
garantías constitucionales que ya hemos visto hasta ahora</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lamentablemente
en México, no se está aprovechando, en toda su extensión y
potencialidades, esta actividad agrícola Por el contrario, se tiene
muy descuidada, con los resultados negativos que se crean, como
compra de alimentos a otros países, ignorancia educativa y
capacitación de la gente del campo Déficit de la balanza
comercial Creación de pobreza extrema, mental y material
Abandono de parcelas y emigración, con todos los riesgos e
indignidades que viven los que buscan en otros países, condiciones
mejores de vida, porque en su propio país no se las dan Sin
embargo, ofrece muchísimas oportunidades, como:</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ol>
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Habilitación
	de tierras</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	ya que muchas están agotadas por el monocultivo, que
	normalmente es de puro maíz Se requiere tener rotación de
	cultivos, ya que los nutrientes que absorben algunas plantas; en el
	cultivo siguiente, de plantas diferentes, se reponen esos
	nutrientes Se requieren ecólogos, agrónomos, técnicos en
	mecánica de maquinaria agrícola y auto transportes, técnicos en
	herramientas agropecuarias, biólogos, operadores de máquinas
	agropecuarias</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<ol start="2">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Captación
	de aguas y sistemas de riego</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Se debe aprovechar todo tipo de aguas (lluvias, ríos, lagunas,
	lagos, presas, etc), para tener agua disponible todo el año y no
	sólo en tiempos de lluvia Mantener esas aguas en las mejores
	condiciones para riego, bebida de animales y de la gente,
	evitando la contaminación de las mismas Para lo cual, se requieren
	técnicos en aguas, ingenieros constructores de presas, biólogos,
	técnicos en albañilería, agrónomos, operadores de maquinaria de
	construcción</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<ol start="3">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Sistema_de_riego"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Sistemas
	de riego</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Actualmente, en la mayoría de los campos agropecuarios,
	los sistemas de riego son arcaicos e irresponsables, ya que se
	desperdicia mucho agua, se contamina con fertilizantes,
	insecticidas, herbicidas; además, se erosionan las tierras
	cuando el agua corre por las siembras y se lleva los nutrientes Por
	lo tanto, se requieren verdaderos sistemas de riego que permitan
	aprovechar al máximo el agua, que no se contamine y no erosione las
	tierras Además, que durante el año se tenga el agua
	suficiente para otras siembras Se requieren técnicos en riego,
	técnicos en sistemas mecánicos de riego técnicos en
	mecánica de maquinaria agrícola y de transporte</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<ol start="4">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Administradores</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Se requiere gente especializada en administración de
	almacenes de productos agropecuarios, administradores de ventas
	de productos administradores de compras de insumos, maquinaria,
	equipo y herramientas, administradores financieros</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<ol start="5">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Administradores
	de distribución y ventas</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Se requieren para la planeación de la distribución de
	productos agropecuarios y con planeación a los lugares
	que se requieran; evitando, al máximo, la descomposición de
	estos productos, ya que son productos perecederos Créditos y
	pagos, sistemas de transporte y operación de ellos
	Mecánica de mantenimiento</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<ol start="6">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Industrialización
	de productos agropecuarios</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
	</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">con
	el objeto de darles valor agregado y evitar pérdidas por los
	excedentes, se requieren técnicos en maquinaria industrial,
	técnicos de mantenimiento, nutriólogos, biólogos, cocineras,
	transportes y mecánicos de mantenimiento para los transportes,
	electricistas, vendedores</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
anterior es lo que llamamos </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Cadena_productiva"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>cadena
productiva</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Lo que quiere decir que se debe tener planeada y comprometida la
producción agropecuaria, con sistemas de distribución seguros,
modernos, suficientes y eficientes, para satisfacer las demandas
de las necesidades de las diferentes poblaciones en la república
mexicana, y aportar al mundo nuestra cuota de alimentos El campo es
la gran oportunidad, ya que profesiones diferentes también tienen
cabida en el campo, como son los médicos, que tanta falta hacen en
el medio rural, con toda su infraestructura, como son hospitales,
consultorios, farmacias, enfermeras, ambulancias Los abogados, para
planear, de acuerdo a derecho, los contratos de compra-venta,
convenios de colaboración, convenios y contratos con finan-cieras y
bancos; controversias con autoridades y particulares, etc De la
misma manera, contadores públicos, arquitectos, pero, sobre
todo, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Maestro"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>maestros</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Se re-quiere una verdadera educación a nivel primaria, secundaria y
técnica; media superior y licenciaturas, especialmente en
materia agropecuaria Observemos que todo está contemplado en las
garantías que nos brindan los artículos 1, 2, 3, 4, 5, 8, 9, 11,
14, 15, 17, 18, 25, 26, 27 y 28 Un pueblo ignorante siempre será
esclavo de la pobreza mental y de gente sin escrúpulos, que se
aprovecha de la situación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">De
ahí, que el campos se encuentra en virtual quiebra y abandono,
generando hambre y desnutrición, pobreza mental, física y
material; indignidad y sin garantía de sus derechos No es posible
que por falta de creatividad y, sobre todo amor a México, se
explote a los campesinos comprándoles, a precio de risa, sus
productos, con la amenaza de que si no venden se les echa a perder su
producción Por eso vemos gran variedad de frutas, legumbres y
verduras pudriéndose en los campos; de la misma manera granos
como el fríjol, maíz, trigo, arroz y otros Esto no solo perjudica
a los campesinos, sino a toda la población, porque se les venden los
productos a precios muy elevados, lo que hace que la gente no tenga
acceso a productos vitales por lo caro, y se tenga que conformar sólo
con tortillas y frijoles como dieta principal, lo que no le permite
un desarrollo integral</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="GANADERÍA"></a>
<b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>GANADERÍA</i></span></font></font></b></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
actividad de la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Ganadería"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ganadería</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
es de suma importancia también, no sólo para el desarrollo del
campo y su gente, sino de toda la población de México, ya que es
una gran parte de la alimentación que contiene las proteínas más
importantes que requiere el cuerpo humano para su desarrollo
integral, de mente y cuerpo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">México
es un país con todas las ventajas para la explotación de la
actividad ganadera, ya que cuenta con campos, agua y clima para
su desarrollo Además de ser una actividad prioritaria para la
alimentación de la población interna y la exportación
Lamentablemente no se le ha puesto la debida atención a esta
actividad, lo que ha provocado muchos problemas, como la siembra
indebida de alimentos para la ganadería en tierras propias para la
siembra de alimentos para humanos Además, no se tienen reservas de
aguas, ni para su conservación para las épocas de sequía, lo que
hace que mucho ganado muera de sed y hambre y, además, se malbarate
este ganado ante el miedo de perderlo Los sistemas que se
utilizan en la producción ganadera son obsoletos y desfasados No se
tienen técnicos, planes ni estrategias necesarias para el
desarrollo armónico de la ganadería</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
lo anterior, es que los gastos y costos de producción son elevados,
además de su baja productividad y, lógicamente el precio al
consumidor es prohibitivo, creándose la desnutrición y desempleo en
el campo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
México se tienen las condiciones para tener, fomentar y desarrollar
con éxito la ganadería</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ol>
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Bovina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Bovina</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>-</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
	Es la producción de carne de res y sus derivados como leche,
	quesos y otros Todo se puede aprovechar, como: piel, huesos,
	vísceras, estiércol para fertilizante, etc Este tipo de
	ganadería bajaría gastos y costos de producción si se
	desarrollara de manera integral; lo cual haría que se crearan
	fuentes de trabajo y proporcionar a la población una alimentación
	balanceada a precios accesibles, evitando exportaciones de
	miedo y malbaratando el producto Además, evitando la compra de
	nuestros mismos productos, con la salida de divisas a
	otros países Para esta área se requieren agrónomos, biólogos,
	zootecnistas, veterinarios, ingenieros en ganadería intensiva,
	maquinaria agrícola e industrial, de productos pecuarios,
	administradores y otros Se requiere una muy bien planeada cadena
	productiva, que contemple: producción, distribución,
	comercialización, industrialización, financiamiento,
	educación y capacitación actualizada e integración con
	otros sistemas como la agricultura, silvicultura, turismo,
	explotación marina, nutrición medicina e infraestructura</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="text-indent: -02in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
mismo sucede con la ganadería:</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>2</b></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Porcina;
</font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>3</b></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Avícola;</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>4</b></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Ovina;  </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>5</b></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Caprina;</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>6</b></font></font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">-</font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Otras como la cunicultura, gusanos de maguey y escamoles</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 079in; text-indent: -02in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 059in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
estado, de acuerdo a este artículo 27 está obligado a apoyar esta
actividad y hacerla congruente con las demás actividades, ya que
todo está íntimamente relacionado</font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid">
