<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><span lang="es-ES"><i>SILVICULTURA</i></span></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
otro lado, tenemos que México padece la deforestación más
increíble, ya que se está terminando con los bosques, de manera
irracional, por la explotación de la madera en sus diferentes
aspectos Sin embargo, no se ha tenido el cuidado de reponer con 5
árboles cada árbol que ha sido talado Los bosques son una
gran riqueza natural y necesaria para la vida del ser humano,
así como para guardar el equilibrio ecológico y la conservación
de plantas y otros espacios para animales Es cierto que la
industria maderera es importantísima, pero también es cierto que
debe ser explotada de manera razonable, inteligente y, sobre todo,
cuidando el equilibrio ecológico Por no respetar a la naturaleza es
que tenemos cambios climáticos con sus graves consecuencias Todo va
integrado, como lo hemos estado observando El estado está
obligado a apoyar esta actividad y planear todo lo relacionado
con otras actividades Mucha gente, de diferentes oficios y
profesiones se requieren para la explotación de la
silvicultura, lo que generaría muchas fuentes de trabajo y
el desarrollo armónico e integral del campo Es una garantía
social consagrada en este artículo 27 constitucional</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Es
lamentable que, de acuerdo a la producción agrícola y ganadera, así
como marina, México es autosuficiente en alimentos, pudiendo
proporcionarle a cada mexicano una dieta suficiente y bien
balanceada No sería necesario importar alimentos y no habría
salida de divisas por esta causa Además no habría desnutrición, y
menos, habría hambre Se tendrían los suficientes empleos
y la economía del país iría siempre en crecimiento;
cumpliéndose las garantías constitucionales Sin embargo, es
todo lo contrario Hay un gran desempleo, un gran déficit en la
balanza comercial, cada día mayor importación de alimentos;
aumenta en forma alarmante la desnutrición y empieza la hambruna;
está detenido el crecimiento de la economía nacional y no se cumple
con las garantías constitucionales, en especial con este
artículo 27 El problema principal es que no hay poder adquisitivo
del salario para adquirir alimentos que nos proporcionan una dieta
suficiente y balanceada Los precios al consumidor, o sea la
gente que compra para su consumo, son muy altos Y los precios
que se pagan al campesino productor, son de miseria, ya que la
mayoría de las veces no sacan los gastos y costas de producción y
transporte Independientemente de que los sistemas de producción
agropecuaria son obsoletos y sin productividad, esto hace que lo que
se produzca sea poco y caro Pero aquí es donde está la gran
oportunidad de la gente con conocimientos, con valor para hacer
efectivos sus derechos; creatividad, audacia, amor a su familia y a
su sociedad; con ilusiones y esperanzas; emoción y pasión
y que quiera invertir tiempo, talento y trabajo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos podido observar en esta parte del artículo, se trató de la
propiedad de la tierra; el dominio de la misma, así como de las
medidas necesarias para planear asentamientos humanos, usos,
reservas y destinos de tierras, aguas y bosques Pero existe otra
parte muy importante, en la que el estado tiene una facultad esencial
para salvaguardar la integridad de las tierras que componen el
territorio nacional y que consiste en el dominio directo de los
recursos naturales que se encuentra en la plataforma
continental y sus islas; como son todos los minerales, en sus
formas de metales y metaloides, llamados hierro, plomo, plata,
oro, cobre, piedras preciosas, </font></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>petróleo</b></i></font></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y gas Es decir, todo lo que se encuentre sobre y dentro de la
tierra, que son considerados recursos naturales, y que como los que
ya vimos en estos renglones, son propiedad del estado; aunque se
encuentren en tierras que tengan dominio particular Estos
recursos serán para invertirlos en beneficio de toda la sociedad
mexicana, siendo empleados en educación, infraestructura,
servicios y otros que requiere el pueblo mexicano Muy en especial
son el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Petroleo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>petróleo</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
sus derivados, así como el gas que contienen los mantos petroleros
Quien administra a nombre del estado el petróleo es una empresa
paraestatal llamada </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Petroleos_Mexicanos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>PEMEX</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Esto es debido a que el petróleo, sus derivados y gas, son
prioritarios para el desarrollo del país; ya que son energéticos,
como la luz, que requiere desde el más humilde y alejado
ciudadano hasta la empresa más grande, para su funcionamiento Se
necesita en el campo, con el diesel para el funcionamiento de la
maquinaria agrícola; para generar electricidad que se requiere
en el campo; entre los derivados petroquímicos están los
fertilizantes La industria requiere del petróleo, en sus
formas de gasolinas, solvente, plásticos químicos farmacéuticos,
electricidad y muchos otros De ahí que el estado debe tener el
control de estos recursos materiales, para que se puedan
distribuir y estén a disposición de todo mexicano que lo
solicite Además, es una fuente de ingresos que sirven para el pago
de infraestructuras y servicios que el estado está obligado a
prestar a la población Esto está contemplado como una garantía
social en este artículo 27 constitucional Sin embargo, el
estado empieza a verse en problemas de producción de derivados
del petróleo, como son gasolinas, gas y petroquímicos para la
industria, que ya se tiene la necesidad de importar de otros países
por no poder generarlos Es ilógico que países que no tienen
mantos petroleros y nos compran el producto, lo procesen y nos venden
sus subproductos a precios muy elevados Por eso debe darse la
oportunidad a inversionistas nacionales e internacionales de que
establezcan empresas en territorio mexicano para procesar el
petróleo que le compran a Pemex, al igual que cualquier país,
creando fuentes importantes de trabajo para mexicanos y evitando
compras al extranjero, con salidas de divisas que ponen en riesgo la
balanza comercial y la economía nacional</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ya
hemos visto que este artículo 27 consagra el derecho social
consistente en la propiedad del territorio nacional, sus usos y los
recursos naturales que se encuentran en el territorio Ahora veremos
que esta garantía social da facultades al estado para
salvaguardar las aguas que pertenecen a todos los mexicanos
y que están constituidas por mares, lagunas, esteros, ríos y sus
afluentes, lagos y corrientes interiores; ya que el agua es el
líquido vital para la sobrevivencia de la humanidad y el
equilibrio ecológico Por lo que no sería razonable que los
particulares tuvieran sus mares y ser propietarios de este recurso
De la misma manera que la tierra no puede estar en manos de
extranjeros, lo es también el agua; ya que con esto se podría
chantajear y condicionar la vida del pueblo mexicano El agua es de
todos los mexicanos, y de acuerdo al artículo 27 constitucional, se
puede hacer uso de ella El que el agua sea de todos los mexicanos,
no nos da derecho a desperdiciarla y mucho menos a contaminarla
Tenemos la obligación de cuidarla de manera inteligente, ya que
no hacerlo atentaría contra los derechos de los demás Es
obligación nuestra cuidar y conservar, en las mejores
condiciones el agua, dándole un uso razonado</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
lo que respecta a las tierras y a las aguas, el estado tiene el
dominio inalienable e imprescriptible, o lo que es lo mismo, nada ni
nadie puede quitar esa facultad al Estado Pero también es cierto
que el estado puede otorgar a los particulares la explotación, uso y
aprovechamiento de estos recursos Conforme a la ley que impone las
condiciones para hacerlo y el retiro por violaciones a la misma</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pero
tratándose del petróleo, carbonos de hidrógeno sólidos, líquidos
o gaseosos y de minerales radioactivos, nunca se entregarán
concesiones, ni contratos y los que hubiera ya no tendrán
validez Sólo serán exclusivos del estado, de la misma manera es
exclusiva del estado y no puede dar concesiones para la generación
de energía eléctrica, transformarla y conducirla Lo anterior es
con el objeto de que todos los mexicanos tengan los servicios de
la electricidad, por muy lejanos que estén Una empresa privada sólo
llevará la energía eléctrica donde fuera rentable, dejando a mucha
gente en las serranías y lugares con poca población, sin energía
eléctrica, por incosteable Además, puede ser causa de un
desequilibrio económico y social de la población mexicana, ya que
también se podrán poner condiciones y discriminación de a qué
empresa se le proporciona la energía eléctrica, dando
preferencias a unos y a otros no El principio de igualdad,
establecido como derecho constitucional, no puede ser violado por
intereses particulares Lo mismo sucede con el aprovechamiento de los
combustibles minerales para la generación de energía nuclear; es
exclusividad del estado y sólo se podrá usar para fines pacíficos,
por eso el estado es el único en manejar esta energía nuclear, ya
que en manos particulares podría usarse para otros fines, poniendo
en riesgo la paz social</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
constitución, a través de este artículo 27, fija claramente los
lineamientos para la adquisición del dominio de las tierras
aguas de la nación</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<ol type="I">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nos
	dice que sólo los mexicanos por nacimiento o naturalización y
	sociedades mexicanas tienen el derecho de adquirir el
	dominio de las tierras y aguas, o para obtener concesiones para
	la explotación de minas y aguas El estado puede conceder a los
	extranjeros el dominio de aguas y tierras, siempre y cuando
	convengan con la secretaría de relaciones exteriores en
	que se consideren mexicanos, solamente en la adquisición de
	estos bienes; sin que por eso adquieran la nacionalidad
	mexicana y no invoquen a las leyes de su país de origen, así
	como a sus gobiernos Quien lo hiciere perderá el dominio de
	tierras y aguas que se le hayan proporcionado Existe otra
	condición para los extranjeros, y es la de que no podrán adquirir
	el dominio de tierras y aguas en una faja de 100 kilómetros a lo
	largo de las fronteras y de 50 si son playas Y por ningún motivo
	se les dará algún dominio</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Esta
misma autorización para tener el dominio de tierras se les podrá
otorgar a los estados extranjeros, y de acuerdo con la Secretaría de
Relaciones Exteriores, para que establezcan sus embajadas o
delegaciones</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="2">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
	asociaciones religiosas también podrán tener dominio de bienes,
	como son sus templos, para el ejercicio de sus cultos, con los
	requisitos y limitaciones que establezca la ley respectiva y de
	acuerdo con el artículo 130 de esta constitución Con eso se
	evita, como en décadas anteriores, que las iglesias fueran
	terratenientes y acapararon tierras, aguas y bienes, con el objeto
	de controlar conciencias y gente, en beneficio de su miembros</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="3">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
	mismo, pueden tener bienes las asociaciones de beneficencia pública
	o privada que tengan por objeto el auxilio a la gente necesitada,
	pero sólo podrán adquirir bienes necesarios para el objeto
	que se trazaron y que sea indispensable, pero no más allá  </font></font></font></font>
	</p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="4">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
	se nos menciona que todas las sociedades mercantiles, como fábricas
	de automóviles, de zapatos, centros comerciales, restoranes,
	fábricas de computadoras, de electrodomésticos, etc, puedan tener
	propiedad privada en terrenos rústicos, es decir, en el
	campo, pero sólo la extensión que se necesita para el
	objetivo de cada empresa</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	En
caso de necesitar tierras dedicadas a la agricultura, ganadería o
forestales, están limitándose a 25 veces los límites señalados en
la fracción XV de este artículo 27, que dice que están prohibidos
los latifundios y solamente podrán tener máximo 100 hectáreas
de riego o humedad, si es tierra de temporal será el doble y de
acuerdo a la ley reglamentaria Además, se tomará en cuenta el
capital invertido y el número de socios con el fin de que no se
excedan en los límites de lo que es la propiedad privada</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="5">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
	artículo nos dice qué bancos, debidamente autorizados e
	instituciones de crédito, podrán tener capitales impuestos
	sobre propiedades urbanas y rústicas Lo que quiere decir que
	podrán prestar dinero a la gente para comprar una casa o
	hipotecarla, y esta propiedad privada queda como garantía en caso
	de no pagar la deuda Pero de ninguna manera los bancos pueden
	tener en propiedad o administración esos bienes embargados o
	que fueron comprados para hacer negocios Solo tendrán en propiedad
	los necesarios para su objeto social</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="6">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
	estados, el distrito federal y municipios en toda la república,
	tienen la facultad de adquirir las propiedades necesarias para
	los servicios públicos como: calles, oficinas, estacionamientos,
	guarderías, hospitales, campos deportivos, bibliotecas, escuelas,
	etc</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Además,
de acuerdo a las leyes respectivas, el gobierno federal y los
gobiernos estatales podrán determinar y adquirir las propiedades de
los particulares cuando sean de utilidad pública, como ya vimos,
puede ser que se expropie alguna casa o casas, terrenos, etc, para
beneficio de la comunidad, como pueden ser calles, carreteras,
presas, etc Pero al expropiar esas propiedades privadas, se
deberá pagar al propietario una indemnización, de acuerdo al
precio del catastro y con el cual está pagando los impuestos de
predial</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="7">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Se
	reconoce también la personalidad jurídica de los núcleos de
	poblaciones ejidales y comunitarios protegiendo la propiedad de
	sus tierras, tanto para asentamientos poblacionales como para
	actividades productivas</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -049in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	La
ley y este artículo protegerán a las tierras y grupos indígenas
para que se puedan desarrollar y aprovechar bosques, aguas y tierra
Además, la ley respectiva y esto lo debemos aprovechar todos para
generar fuentes de trabajo, educar y capacitar a la gente del
campo, ya que existen los procedimientos para que los
ejidatarios y comuneros se puedan asociar entre ellos mismos, o
con el estado y los particulares para crear organizaciones o
empresas productivas agropecuarias e industriales de esos mismos
productos, aportando ellos las tierras Esto evita que haya
tierras ejidales y comunales ociosas, abandonadas, sin producir y con
campesinos sin empleo y en la pobreza extrema Todos debemos
participar en el desarrollo armónico del pueblo mexicano en las
mejores condiciones y en un plano de igualdad y democracia Tenemos
todo para salir adelante</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 089in; text-indent: -039in; line-height: 100%">
<br>
</p>
<ol type="I" start="8">
	<li><p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
	supuesto que este derecho social que nos otorga el artículo
	27, hace nulas todas las enajenaciones a tierras, agua y, montes,
	que se hayan hecho por parte de jefes políticos, gobernadores y
	cualquier autoridad; así como concesiones y ventas de
	tierras, aguas y montes, así también como transacciones y
	remates, siempre y cuando estén en contravención a lo
	dispuesto en la ley del 25 de junio de 1856 Esto trata de evitar y
	restituir que se violen los derechos de la gente del campo, como en
	tiempos de la independencia</font></font></font></font></p>
</ol>
<p class="western" align="justify" style="margin-left: 059in; text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 089in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
último, este artículo 27 es de gran interés porque el estado está
obligado a promover las condiciones para el desarrollo rural integral
con todos los sectores, así como la integración de los avances
científicos y tecnológicos, para que se pueda generar empleo,
no sólo en el medio rural, sino en todo el país y para toda la
gente, y garantizando a la población campesina su participación e
incorporación en el desarrollo nacional No se puede entender el
desarrollo del pueblo mexicano dejando a un lado y no tomar en cuenta
al sector campesino Principalmente no habría desarrollo para nadie
Además, como ya lo hemos estado viendo, el estado tiene la
obligación de fomentar la actividad agropecuaria, base de la
alimentación de toda la población de México Así también
promover el buen uso de la tierra, hacer obras de infraestructura;
proporcionar insumos, semillas, fertilizante, herbicidas,
insecticidas, combustibles y otros; otorgar créditos para mano de
obra, transportes, maquinaria, herramientas y lo necesario Sobre
todo, promover, fomentar, proporcionar, estimular y garantizar la
capacitación, en todos los aspectos, para el desarrollo integral de
la actividad agropecuaria y forestal, así como la asistencia
técnica que se requiera Todo de manera integral, promoviendo la
producción agropecuaria; su industrialización, para no ser
sólo proveedores de materia prima barata, sino darle valor agregado,
procesando e industrializando estos productos, creando más y mejores
fuentes de trabajo, para dar respuesta a las necesidades de toda
la población Por supuesto es muy importante la distribución y
comercialización de los productos del campo Crear las verdaderas
cadenas productivas, de manera sólida, permanente, en constante
superación, con la participación de toda la sociedad mexicana,
para mejores expectativas de vida digna y humana Por eso, se
considera de interés público y, es obligación del estado,
hacerla realidad con la participación de todos los mexicanos,
teniendo como base la democracia y ésta como un sistema de
vida, de acuerdo al artículo 3º constitucional Aprovechemos esta
extraordinaria garantía del derecho social que nos da este artículo
27 constitucional Pongamos a nuestro servicio y al de la familia y
sociedad, toda nuestra capacidad mental, creatividad, entusiasmo,
energía, voluntad, valor, sentimientos, pasión y emoción,
para participar en nuestra realización como seres humanos y de
nuestra familia y sociedad, cumpliendo y demostrando, como lo
establece el artículo 3º constitucional el amor a México, a
nuestra patria</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 014in; line-height: 100%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
27</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
La propiedad de las tierras y aguas comprendidas dentro de los
límites del territorio nacional, corresponde originariamente a la
Nación, la cual ha tenido y tiene el derecho de transmitir el
dominio de ellas a los particulares, constituyendo la propiedad
privada</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
expropiaciones sólo podrán hacerse por causa de utilidad pública y
mediante indemnización</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
nación tendrá en todo tiempo el derecho de imponer a la propiedad
privada las modalidades que dicte el interés público, así como el
de regular, en beneficio social, el aprovechamiento de los elementos
naturales susceptibles de apropiación, con objeto de hacer una
distribución equitativa de la riqueza pública, cuidar de su
conservación, lograr el desarrollo equilibrado del país y el
mejoramiento de las condiciones de vida de la población rural y
urbana En consecuencia, se dictarán las medidas necesarias para
ordenar los asentamientos humanos y establecer adecuadas provisiones,
usos, reservas y destinos de tierras, aguas y bosques, a efecto de
ejecutar obras públicas y de planear y regular la fundación,
conservación, mejoramiento y crecimiento de los centros de
población; para preservar y restaurar el equilibrio ecológico; para
el fraccionamiento de los latifundios; para disponer, en los términos
de la ley reglamentaria, la organización y explotación colectiva de
los ejidos y comunidades; para el desarrollo de la pequeña propiedad
rural; para el fomento de la agricultura, de la ganadería, de la
silvicultura y de las demás actividades económicas en el medio
rural, y para evitar la destrucción de los elementos naturales y los
daños que la propiedad pueda sufrir en perjuicio de la sociedad</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Corresponde
a la Nación el dominio directo de todos los recursos naturales de la
plataforma continental y los zócalos submarinos de las islas; de
todos los minerales o substancias que en vetas, mantos, masas o
yacimientos, constituyan depósitos cuya naturaleza sea distinta de
los componentes de los terrenos, tales como los minerales de los que
se extraigan metales y metaloides utilizados en la industria; los
yacimientos de piedras preciosas, de sal de gema y las salinas
formadas directamente por las aguas marinas; los productos derivados
de la descomposición de las rocas, cuando su explotación necesite
trabajos subterráneos; los yacimientos minerales u orgánicos de
materias susceptibles de ser utilizadas como fertilizantes; los
combustibles minerales sólidos; el petróleo y todos los carburos de
hidrógeno sólidos, líquidos o gaseosos; y el espacio situado sobre
el territorio nacional, en la extensión y términos que fije el
Derecho Internacional</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Son
propiedad de la Nación las aguas de los mares territoriales en la
extensión y términos que fije </i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(el,
sic DOF 20-01-1960) </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Derecho
Internacional; las aguas marinas interiores; las de las lagunas y
esteros que se comuniquen permanente o intermitentemente con el mar;
las de los lagos interiores de formación natural que estén ligados
directamente a corrientes constantes; las de los ríos y sus
afluentes directos o indirectos, desde el punto del cauce en que se
inicien las primeras aguas permanentes, intermitentes o torrenciales,
hasta su desembocadura en el mar, lagos, lagunas o esteros de
propiedad nacional; las de las corrientes constantes o interminentes
</i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(intermitentes,
sic DOF 20-01-1960) </b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>y
sus afluentes directos o indirectos, cuando el cauce de aquéllas en
toda su extensión o en parte de ellas, sirva de límite al
territorio nacional o a dos entidades federativas, o cuando pase de
una entidad federativa a otra o cruce la línea divisoria de la
República; la de los lagos, lagunas o esteros cuyos vasos, zonas o
riberas, estén cruzadas por líneas divisorias de dos o más
entidades o entre la República y un país vecino, o cuando el límite
de las riberas sirva de lindero entre dos entidades federativas o a
la República con un país vecino; las de los manantiales que broten
en las playas, zonas marítimas, cauces, vasos o riberas de los
lagos, lagunas o esteros de propiedad nacional, y las que se
extraigan de las minas; y los cauces, lechos o riberas de los lagos y
corrientes interiores en la extensión que fija la ley Las aguas del
subsuelo pueden ser libremente alumbradas mediante obras artificiales
y apropiarse por el dueño del terreno, pero cuando lo exija el
interés público o se afecten otros aprovechamientos; el Ejecutivo
Federal podrá reglamentar su extracción y utilización y aún
establecer zonas vedadas, al igual que para las demás aguas de
propiedad nacional Cualesquiera otras aguas no incluidas en la
enumeración anterior, se considerarán como parte integrante de la
propiedad de los terrenos por los que corran o en los que se
encuentren sus depósitos, pero si se localizaren en dos o más
predios, el aprovechamiento de estas aguas se considerará de
utilidad pública, y quedará sujeto a las disposiciones que dicten
los Estados</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
los casos a que se refieren los dos párrafos anteriores, el dominio
de la Nación es inalienable e imprescriptible y la explotación, el
uso o el aprovechamiento de los recursos de que se trata, por los
particulares o por sociedades constituidas conforme a las leyes
mexicanas, no podrá realizarse sino mediante concesiones, otorgadas
por el Ejecutivo Federal, de acuerdo con las reglas y condiciones que
establezcan las leyes Las normas legales relativas a obras o
trabajos de explotación de los minerales y substancias a que se
refiere el párrafo cuarto, regularán la ejecución y comprobación
de los que se efectúen o deban efectuarse a partir de su vigencia,
independientemente de la fecha de otorgamiento de las concesiones, y
su inobservancia dará lugar a la cancelación de éstas El Gobierno
Federal tiene la facultad de establecer reservas nacionales y
suprimirlas Las declaratorias correspondientes se harán por el
Ejecutivo en los casos y condiciones que las leyes prevean
Tratándose del petróleo y de los carburos de hidrógeno sólidos,
líquidos o gaseosos o de minerales radioactivos, no se otorgarán
concesiones ni contratos, ni subsistirán los que en su caso se hayan
otorgado y la Nación llevará a cabo la explotación de esos
productos, en los términos que señale la Ley Reglamentaria
respectiva Corresponde exclusivamente a la Nación generar,
conducir, transformar, distribuir y abastecer energía eléctrica que
tenga por objeto la prestación de servicio público En esta materia
no se otorgarán concesiones a los particulares y la Nación
aprovechará los bienes y recursos naturales que se requieran para
dichos fines</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Corresponde
también a la Nación el aprovechamiento de los combustibles
nucleares para la generación de energía nuclear y la regulación de
sus aplicaciones en otros propósitos El uso de la energía nuclear
sólo podrá tener fines pacíficos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
Nación ejerce en una zona económica exclusiva situada fuera del mar
territorial y adyacente a éste, los derechos de soberanía y las
jurisdicciones que determinen las leyes del Congreso La zona
económica exclusiva se extenderá a doscientas millas náuticas,
medidas a partir de la línea de base desde la cual se mide el mar
territorial En aquellos casos en que esa extensión produzca
superposición con las zonas económicas exclusivas de otros Estados,
la delimitación de las respectivas zonas se hará en la medida en
que resulte necesario, mediante acuerdo con estos Estados</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
capacidad para adquirir el dominio de las tierras y aguas de la
Nación, se regirá por las siguientes prescripciones:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>I
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Sólo
los mexicanos por nacimiento o por naturalización y las sociedades
mexicanas tienen derecho para adquirir el dominio de las tierras,
aguas y sus accesiones o para obtener concesiones de explotación de
minas o aguas El Estado podrá conceder el mismo derecho a los
extranjeros, siempre que convengan ante la Secretaría de Relaciones
en considerarse como nacionales respecto de dichos bienes y en no
invocar por lo mismo la protección de sus gobiernos por lo que se
refiere a aquéllos; bajo la pena, en caso de faltar al convenio, de
perder en beneficio de la Nación, los bienes que hubieren adquirido
en virtud del mismo En una faja de cien kilómetros a lo largo de
las fronteras y de cincuenta en las playas, por ningún motivo podrán
los extranjeros adquirir el dominio directo sobre tierras y aguas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado de acuerdo con los intereses públicos internos y los
principios de reciprocidad, podrá, a juicio de la Secretaría de
Relaciones, conceder autorización a los Estados extranjeros para que
adquieran, en el lugar permanente de la residencia de los Poderes
Federales, la propiedad privada de bienes inmuebles necesarios para
el servicio directo de sus embajadas o legaciones</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>II
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
asociaciones religiosas que se constituyan en los términos del
artículo 130 y su ley reglamentaria tendrán capacidad para
adquirir, poseer o administrar, exclusivamente, los bienes que sean
indispensables para su objeto, con los requisitos y limitaciones que
establezca la ley reglamentaria;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>III
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
instituciones de beneficencia, pública o privada, que tengan por
objeto el auxilio de los necesitados, la investigación científica,
la difusión de la enseñanza, la ayuda recíproca de los asociados,
o cualquier otro objeto lícito, no podrán adquirir más bienes
raíces que los indispensables para su objeto, inmediata o
directamente destinados a él, con sujeción a lo que determine la
ley reglamentaria;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IV
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
sociedades mercantiles por acciones podrán ser propietarias de
terrenos rústicos pero únicamente en la extensión que sea
necesaria para el cumplimiento de su objeto</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
ningún caso las sociedades de esta clase podrán tener en propiedad
tierras dedicadas a actividades agrícolas, ganaderas o forestales en
mayor extensión que la respectiva equivalente a veinticinco veces
los límites señalados en la fracción XV de este artículo La ley
reglamentaria regulará la estructura de capital y el número mínimo
de socios de estas sociedades, a efecto de que las tierras propiedad
de la sociedad no excedan en relación con cada socio los límites de
la pequeña propiedad En este caso, toda propiedad accionaria
individual, correspondiente a terrenos rústicos, será acumulable
para efectos de cómputo Asimismo, la ley señalará las condiciones
para la participación extranjera en dichas sociedades</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
propia ley establecerá los medios de registro y control necesarios
para el cumplimiento de lo dispuesto por esta fracción;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>V
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
bancos debidamente autorizados, conforme a las leyes de instituciones
de crédito, podrán tener capitales impuestos, sobre propiedades
urbanas y rústicas de acuerdo con las prescripciones de dichas
leyes, pero no podrán tener en propiedad o en administración más
bienes raíces que los enteramente necesarios para su objeto directo</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VI
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Los
estados y el Distrito Federal, lo mismo que los municipios de toda la
República, tendrán plena capacidad para adquirir y poseer todos los
bienes raíces necesarios para los servicios públicos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes de la Federación y de los Estados en sus respectivas
jurisdicciones, determinarán los casos en que sea de utilidad
pública la ocupación de la propiedad privada, y de acuerdo con
dichas leyes la autoridad administrativa hará la declaración
correspondiente El precio que se fijará como indemnización a la
cosa expropiada, se basará en la cantidad que como valor fiscal de
ella figure en las oficinas catastrales o recaudadoras, ya sea que
este valor haya sido manifestado por el propietario o simplemente
aceptado por él de un modo tácito por haber pagado sus
contribuciones con esta base El exceso de valor o el demérito que
haya tenido la propiedad particular por las mejoras o deterioros
ocurridos con posterioridad a la fecha de la asignación del valor
fiscal, será lo único que deberá quedar sujeto a juicio pericial y
a resolución judicial Esto mismo se observará cuando se trate de
objetos cuyo valor no esté fijado en las oficinas rentísticas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
ejercicio de las acciones que corresponden a la Nación, por virtud
de las disposiciones del presente artículo, se hará efectivo por el
procedimiento judicial; pero dentro de este procedimiento y por orden
de los tribunales correspondientes, que se dictará en el plazo
máximo de un mes, las autoridades administrativas procederán desde
luego a la ocupación, administración, remate o venta de las tierras
o aguas de que se trate y todas sus accesiones, sin que en ningún
caso pueda revocarse lo hecho por las mismas autoridades antes que se
dicte sentencia ejecutoriada</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
reconoce la personalidad jurídica de los núcleos de población
ejidales y comunales y se protege su propiedad sobre la tierra, tanto
para el asentamiento humano como para actividades productivas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley protegerá la integridad de las tierras de los grupos indígenas</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley, considerando el respeto y fortalecimiento de la vida comunitaria
de los ejidos y comunidades, protegerá la tierra para el
asentamiento humano y regulará el aprovechamiento de tierras,
bosques y aguas de uso común y la provisión de acciones de fomento
necesarias para elevar el nivel de vida de sus pobladores</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley, con respeto a la voluntad de los ejidatarios y comuneros para
adoptar las condiciones que más les convengan en el aprovechamiento
de sus recursos productivos, regulará el ejercicio de los derechos
de los comuneros sobre la tierra y de cada ejidatario sobre su
parcela Asimismo establecerá los procedimientos por los cuales
ejidatarios y comuneros podrán asociarse entre sí, con el Estado o
con terceros y otorgar el uso de sus tierras; y, tratándose de
ejidatarios, transmitir sus derechos parcelarios entre los miembros
del núcleo de población; igualmente fijará los requisitos y
procedimientos conforme a los cuales la asamblea ejidal otorgará al
ejidatario el dominio sobre su parcela En caso de enajenación de
parcelas se respetará el derecho de preferencia que prevea la ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Dentro
de un mismo núcleo de población, ningún ejidatario podrá ser
titular de más tierra que la equivalente al 5% del total de las
tierras ejidales En todo caso, la titularidad de tierras en favor de
un solo ejidatario deberá ajustarse a los límites señalados en la
fracción XV</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i>La asamblea general es el órgano supremo
del núcleo de población ejidal o comunal, con la organización y
funciones que la ley señale El comisariado ejidal o de bienes
comunales, electo democráticamente en los términos de la ley, es el
órgano de representación del núcleo y el responsable de ejecutar
las resoluciones de la asamblea</i></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
restitución de tierras, bosques y aguas a los núcleos de población
se hará en los términos de la ley reglamentaria;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>VIII
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
declaran nulas</i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>:</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>a)
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Todas
las enajenaciones de tierras, aguas y montes pertenecientes a los
pueblos, rancherías, congregaciones o comunidades, hechas por los
jefes políticos, Gobernadores de los Estados, o cualquiera otra
autoridad local en contravención a lo dispuesto en la Ley de 25 de
junio de 1856 y demás leyes y disposiciones relativas;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i><b>b) </b></i></font><font color="#0000ff"><i>Todas
las concesiones: composiciones o ventas de tierras, aguas y montes,
hechas por las Secretarías de Fomento, Hacienda o cualquiera otra
autoridad federal, desde el día primero de diciembre de 1876, hasta
la fecha, con las cuales se hayan invadido y ocupado ilegalmente los
ejidos, terrenos de común repartimiento o cualquiera otra clase,
pertenecientes a los pueblos, rancherías, congregaciones o
comunidades, y núcleos de población</i></font></p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font color="#0000ff"><i><b>c) </b></i></font><font color="#0000ff"><i>Todas
las diligencias de apeo o deslinde, transacciones, enajenaciones o
remates practicados durante el período de tiempo a que se refiere la
fracción anterior, por compañías, jueces u otras autoridades de
los Estados o de la Federación, con los cuales se hayan invadido u
ocupado ilegalmente tierras, aguas y montes de los ejidos, terrenos
de común repartimiento, o de cualquiera otra clase, pertenecientes a
núcleos de población</i></font></p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Quedan
exceptuadas de la nulidad anterior, únicamente las tierras que
hubieren sido tituladas en los repartimientos hechos con apego a la
Ley de 25 de junio de 1856 y poseídas en nombre propio a título de
dominio por más de diez años cuando su superficie no exceda de
cincuenta hectáreas</i></font></font></font></font></font></p>
<p style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>IX
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
división o reparto que se hubiere hecho con apariencia de legítima
entre los vecinos de algún núcleo de población y en la que haya
habido error o vicio, podrá ser nulificada cuando así lo soliciten
las tres cuartas partes de los vecinos que estén en posesión de una
cuarta parte de los terrenos, materia de la división, o una cuarta
parte de los mismos vecinos cuando estén en posesión de las tres
cuartas partes de los terrenos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>X
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XI
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XII
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XIII
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XIV
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XV
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
los Estados Unidos Mexicanos quedan prohibidos los latifundios</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
considera pequeña propiedad agrícola la que no exceda por individuo
de cien hectáreas de riego o humedad de primera o sus equivalentes
en otras clases de tierras</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Para
los efectos de la equivalencia se computará una hectárea de riego
por dos de temporal, por cuatro de agostadero de buena calidad y por
ocho de bosque, monte o agostadero en terrenos áridos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
considerará, asimismo, como pequeña propiedad, la superficie que no
exceda por individuo de ciento cincuenta hectáreas cuando las
tierras se dediquen al cultivo de algodón, si reciben riego; y de
trescientas, cuando se destinen al cultivo del plátano, caña de
azúcar, café, henequén, hule, palma, vid, olivo, quina, vainilla,
cacao, agave, nopal o árboles frutales</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
considerará pequeña propiedad ganadera la que no exceda por
individuo la superficie necesaria para mantener hasta quinientas
cabezas de ganado mayor o su equivalente en ganado menor, en los
términos que fije la ley, de acuerdo con la capacidad forrajera de
los terrenos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Cuando
debido a obras de riego, drenaje o cualesquiera otras ejecutadas por
los dueños o poseedores de una pequeña propiedad se hubiese
mejorado la calidad de sus tierras, seguirá siendo considerada como
pequeña propiedad, aún cuando, en virtud de la mejoría obtenida,
se rebasen los máximos señalados por esta fracción, siempre que se
reúnan los requisitos que fije la ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Cuando
dentro de una pequeña propiedad ganadera se realicen mejoras en sus
tierras y éstas se destinen a usos agrícolas, la superficie
utilizada para este fin no podrá exceder, según el caso, los
límites a que se refieren los párrafos segundo y tercero de esta
fracción que correspondan a la calidad que hubieren tenido dichas
tierras antes de la mejora;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XVI
</b></i></font></font></font><font color="#ff0000"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>(Se
deroga)</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XVII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Congreso de la Unión y las legislaturas de los estados, en sus
respectivas jurisdicciones, expedirán leyes que establezcan los
procedimientos para el fraccionamiento y enajenación de las
extensiones que llegaren a exceder los límites señalados en las
fracciones IV y XV de este artículo</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
excedente deberá ser fraccionado y enajenado por el propietario
dentro del plazo de un año contado a partir de la notificación
correspondiente Si transcurrido el plazo el excedente no se ha
enajenado, la venta deberá hacerse mediante pública almoneda En
igualdad de condiciones, se respetará el derecho de preferencia que
prevea la ley reglamentaria</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes locales organizarán el patrimonio de familia, determinando los
bienes que deben constituirlo, sobre la base de que será inalienable
y no estará sujeto a embargo ni a gravamen ninguno;</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XVIII
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
declaran revisables todos los contratos y concesiones hechas por los
Gobiernos anteriores desde el año de 1876, que hayan traído por
consecuencia el acaparamiento de tierras, aguas y riquezas naturales
de la Nación, por una sola persona o sociedad, y se faculta al
Ejecutivo de la Unión para declararlos nulos cuando impliquen
perjuicios graves para el interés público</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XIX
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Con
base en esta Constitución, el Estado dispondrá las medidas para la
expedita y honesta impartición de la justicia agraria, con objeto de
garantizar la seguridad jurídica en la tenencia de le </i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(la,
sic DOF 03-02-1983)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
tierra ejidal, comunal y de la pequeña propiedad, y apoyará la
asesoría legal de los campesinos</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Son
de jurisdicción federal todas las cuestiones que por límites de
terrenos ejidales y comunales, cualquiera que sea el origen de éstos,
se hallen pendientes o se susciten entre dos o más núcleos de
población; así como las relacionadas con la tenencia de la tierra
de los ejidos y comunidades Para estos efectos y, en general, para
la administración de justicia agraria, la ley instituirá tribunales
dotados de autonomía y plena jurisdicción, integrados por
magistrados propuestos por el Ejecutivo Federal y designados por la
Cámara de Senadores o, en los recesos de ésta, por la Comisión
Permanente</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
ley establecerá un órgano para la procuración de justicia agraria,
y</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 069in; margin-right: 075in; text-indent: -02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>XX
</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado promoverá las condiciones para el desarrollo rural integral,
con el propósito de generar empleo y garantizar a la población
campesina el bienestar y su participación e incorporación en el
desarrollo nacional, y fomentará la actividad agropecuaria y
forestal para el óptimo uso de la tierra, con obras de
infraestructura, insumos, créditos, servicios de capacitación y
asistencia técnica Asimismo expedirá la legislación reglamentaria
para planear y organizar la producción agropecuaria, su
industrialización y comercialización, considerándolas de interés
público</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART28"></a>
