<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
28</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
artículo 28 constitucional es otra garantía social que nos indica
el desarrollo igualitario de todo tipo de actividades y la
garantía de su distribución de bienes y productos en las mejores
condiciones, y sin condiciones, ni protección a intereses
particulares</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
eso, nos menciona que en los Estados Unidos Mexicanos quedan
prohibidos los monopolios y las prácticas monopólicas, los y
las exenciones de impuestos Esto quiere decir que a nadie se le
puede permitir tener la exclusividad de producir, industrializar
o vender, algún producto o servicio Nadie tiene la exclusividad de
producir naranjas y nadie más; o zapatos, o ser único para poner
restoranes o tiendas de abarrotes Esto sería monopolio, lo cual
este artículo 28 lo prohíbe Tampoco se permiten las prácticas
monopólicas; por ejemplo, que en una tienda o varias tiendas, sólo
se venda una marca de refrescos y que esta modalidad la imponga la
fábrica que produce esa marca O que en algunos restoranes sólo se
venda una marca de cerveza y ninguna otra Estos son ejemplos de
prácticas monopólicas Se debe dar la oportunidad en igualdad de
condiciones, que todos produzcan y vendan los productos que
quieran y que solicite el público en general, sin ninguna
restricción Aparte de violar también los artículos 5º
constitucional, el 14 y 16, que ya hemos visto</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Este
artículo obliga a la autoridad, y de acuerdo a la ley, a castigar
severamente y a perseguir a toda persona que concentre o acapare
artículos y productos de consumo necesario, con el objeto de
aumentar los precios Tampoco se permitirán acuerdos o convenios de
personas y empresas industriales y comerciales, que eviten la
libre competencia y obliguen a la gente a pagar más y a comprarles
solamente a ellos, lo cual perjudica a la población en general y a
la economía nacional A esta gente se le perseguirá y castigará
severamente</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Inclusive,
este artículo menciona que de acuerdo a la ley respectiva, se deben
fijar precios máximos a productos, artículos y materia prima que se
consideran necesarios para la economía nacional y de consumo
popular De la misma manera, se deberán tener sistemas que eviten el
acaparamiento de productos que provoquen la escasez La ley protegerá
a los consumidores y cuidará de sus intereses Por eso se creó la
Procuraduría Federal de protección al consumidor, donde se podrán
presentan quejas y se aplicará la ley a los proveedores que no
cumplan</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Existen
actividades que sólo el estado puede ejercer y no los particulares
Aunque se puede considerar monopolio, este artículo 28 establece
que, por tratarse del estado y ser actividades prioritarias, no
se considerarán monopolios El estado debe tener estas actividades a
su cargo para evitar que los particulares no lo hagan, en
general y sólo unos sectores de acuerdo a sus intereses, dejando
aparte de la población sin esos productos o servicios, como son:
correos, telégrafo, radiotelegrafía, petróleo y otros
hidrocarburos, petroquímica básica, como gasolinas, diesel, gas,
etc, minerales radioactivos, energía eléctrica</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Con
el objeto de proteger la soberanía y la seguridad de la nación, el
estado tendrá la rectoría de la comunicación vía satélite y
de los ferrocarriles, que son áreas prioritarias, de acuerdo al
artículo 25 constitucional Pero en estas actividades el estado
podrá otorgar concesiones o permisos a particulares para participar
en estas áreas De ahí que se autorice que se utilice el espacio
para las estaciones de radio y televisión, telefonía y uso aéreo
de líneas aéreas nacionales y extranjeras, de acuerdo a la
ley Cualquier violación a la ley, se retirará el permiso o
concesión, con sus respectivas sanciones</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Para
cumplir con los objetivos y desarrollo de las actividades que el
estado tiene obligación de llevar la rectoría, podrá contar con
organizaciones y empresas que se requieran y de acuerdo con la
ley podrán ser del estado, o con la participación del sector
social y particular De ahí que exista </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Liconsa,</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">que
provee de lecha a la gente La </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/CFE"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>CFE</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>,</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">que
produce y distribuye la energía eléctrica El transporte público,
como el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Metrobus_(Ciudad_de_Mexico)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>metrobús</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Metro_(sistema_de_transporte)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>metro</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y líneas de autotransporte urbano y foráneo, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Pemex"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>PEMEX</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
que explora, explota, procesa y distribuye el petróleo y sus
derivados; puede dar concesiones a las gasolineras para vender
gasolina, diesel y aceites Esto se encuentra establecido en esta
garantía social </font></font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%">El estado, y de
acuerdo a este artículo 28, tiene la obligación de procurar la
estabilidad del poder adquisitivo de la moneda nacional O lo que es
lo mismo, evitar su devaluación, ya que con esto se compraría menos
con la moneda nacional Para lo cual, el estado tendrá un banco
central, que sea autónomo en sus funciones y administración
No podrá recibir órdenes de ninguna autoridad, inclusive del
presidente de la república</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">No
constituye monopolio el que el estado ejerza, de manera exclusiva y a
través del banco central, la acuñación de monedas y la emisión de
billetes Nadie puede acuñar monedas y emitir billetes Es un
delito de tipo penal hacerlo, porque esas monedas y esos billetes no
tienen ningún respaldo y ponen en grave riesgo la estabilidad
económica del país Independientemente, de que el dinero se gana
con el trabajo</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">De
la misma manera, el banco central regulará los cambios con otras
monedas de otros países; esto es la paridad de nuestro peso en
relación a otras monedas de otros países, sobre todo, con los que
tenemos relaciones comerciales De la misma manera el banco
central tiene que observar y regir los servicios financieros con
otras instituciones, como son los bancos del estado y los
particulares, en los que hay cobros y pagos de intereses; mismos que
no pueden ser al arbitrio y deseo de las instituciones financieras
particulares Estas son garantías de derechos sociales que tenemos
todos los mexicanos, para proteger nuestra economía personal y de
toda la sociedad</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Es
muy importante estimular la creatividad de todas las personas y sobre
todo, garantizarles el derecho que tienen sobre sus creaciones Por
eso, este artículo 28 no considera monopolio el que una persona
haya inventado un producto, o haya escrito un libro, creado una
música u otras cosas y, solo él tenga derecho a recibir utilidades
o regalías por su obra El creador de alguna obra tiene el derecho
garantizado de decir quién y cómo puede usar ese invento y sobre
todo, cuánto le deben pagar Nadie puede ganar algo con la obra de
otro, sin pagarle las regalías justas</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
estado, y de acuerdo a las leyes, tiene la facultad de concesionar la
prestación de servicios públicos, como ferrocarriles y la
construcción de obras públicas, que puede darlos a empresas
particulares para que las hagan, de acuerdo a la ley y licitación
correspondiente También puede dar en concesión la explotación de
minas de hierro, cobre y otros, cuando sean de interés general,
porque de esta manera se da el servicio a todos los mexicanos y no se
les priva de esos servicios y bienes que se requieren</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
siguiente es de gran importancia y toda la gente debe usar el derecho
que consagra este artículo 28 y que consiste en que el estado
otorgará subsidios a actividades prioritarias, como son el
transporte (</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Metro_(sistema_de_transporte)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>metro</b></i></font></font></a></u></span></font><font color="#333399"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,
</i></font></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Metrobús_(Ciudad_de_México)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>metrobús</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>,</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
etc) que están subsidiados para proteger la economía familiar</font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
28</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
En los Estados Unidos Mexicanos quedan prohibidos los monopolios, la
</i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(las,
sic DOF 03-02-1983)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
prácticas monopólicas, los estancos y las exenciones de impuestos
en los términos y condiciones que fijan las leyes El mismo
tratamiento se dará a ls </i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(las,
sic DOF 03-02-1983)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
prohibiciones a título de protección a la industria</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
consecuencia, la ley castigará severamente, y las autoridades
perseguirán con eficacia, toda concentración o acaparamiento en una
o pocas manos de artículos de consumo necesario y que tenga por
objeto obtener el alza de los precios; todo acuerdo, procedimiento o
combinación de los productores, industriales, comerciantes o
empresarios de servicios, que de cualquier manera hagan, para evitar
la libre concurrencia o la competencia entre sí y obligar a los
consumidores a pagar precios exagerados y, en general, todo lo que
constituya una ventaja exclusiva indebida a favor de una o varias
personas determinadas y con perjuicio del público en general o de
alguna clase social</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Las
leyes fijarán bases para que se señalen precios máximos a los
artículos, materias o productos que se consideren necesarios para la
economía nacional o el consumo popular, así como para imponer
modalidades a la organización de la distribución de esos artículos,
materias o productos, a fin de evitar que intermediaciones
innecesarias o excesivas provoquen insuficiencia en el abasto, así
como el alza de precios La ley protegerá a los consumidores y
propiciará su organización para el mejor cuidado de sus intereses</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
constituirán monopolios las funciones que el Estado ejerza de manera
exclusiva en las siguientes áreas estratégicas: correos, telégrafos
y radiotelegrafía; petróleo y los demás hidrocarburos;
petroquímica básica; minerales radioactivos y generación de
energía nuclear; electricidad y las actividades que expresamente
señalen las leyes que expida el Congreso de la Unión La
comunicación vía satélite y los ferrocarriles son áreas
prioritarias para el desarrollo nacional en los términos del
artículo 25 de esta Constitución; el Estado al ejercer en ellas su
rectoría, protegerá la seguridad y la soberanía de la Nación, y
al otorgar concesiones o permisos mantendrá o establecerá el
dominio de las respectivas vías de comunicación de acuerdo con las
leyes de la materia</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado contará con los organismos y empresas que requiera para el
eficaz manejo de las áreas estratégicas a su cargo y en las
actividades de carácter prioritario donde, de acuerdo con las leyes,
participe por sí o con los sectores social y privado</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado tendrá un banco central que será autónomo en el ejercicio
de sus funciones y en su administración Su objetivo prioritario
será procurar la estabilidad del poder adquisitivo de la moneda
nacional, fortaleciendo con ello la rectoría del desarrollo nacional
que corresponde al Estado Ninguna autoridad podrá ordenar al banco
conceder financiamiento</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
constituyen monopolios las funciones que el Estado ejerza de manera
exclusiva, a través del banco central en las áreas estratégicas de
acuñación de moneda y emisión de billetes El banco central, en
los términos que establezcan las leyes y con la intervención que
corresponda a las autoridades competentes, regulará los cambios, así
como la intermediación y los servicios financieros, contando con las
atribuciones de autoridad necesarias para llevar a cabo dicha
regulación y proveer a su observancia La conducción del banco
estará a cargo de personas cuya designación será hecha por el
Presidente de la República con la aprobación de la Cámara de
Senadores o de la Comisión Permanente, en su caso; desempeñarán su
encargo por períodos cuya duración y escalonamiento provean al
ejercicio autónomo de sus funciones; sólo podrán ser removidas por
causa grave y no podrán tener ningún otro empleo, cargo o comisión,
con excepción de aquéllos en que actúen en representación del
banco y de los no remunerados en asociaciones docentes, científicas,
culturales o de beneficiencia </i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>(</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>beneficencia,
sic</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>
DOF 20-08-1993)</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Las personas encargadas de la conducción del banco central, podrán
ser sujetos de juicio político conforme a lo dispuesto por el
artículo 110 de esta Constitución</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>No
constituyen monopolios las asociaciones de trabajadores formadas para
proteger sus propios intereses y las asociaciones o sociedades
cooperativas de productores para que, en defensa de sus intereses o
del interés general, vendan directamente en los mercados extranjeros
los productos nacionales o industriales que sean la principal fuente
de riqueza de la región en que se produzcan o que no sean artículos
de primera necesidad, siempre que dichas asociaciones estén bajo
vigilancia o amparo del Gobierno Federal o de los Estados, y previa
autorización que al efecto se obtenga de las legislaturas
respectivas en cada caso Las mismas Legislaturas, por sí o a
propuesta del Ejecutivo podrán derogar, cuando así lo exijan las
necesidades públicas, las autorizaciones concedidas para la
formación de las asociaciones de que se trata</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Tampoco
constituyen monopolios los privilegios que por determinado tiempo se
concedan a los autores y artistas para la producción de sus obras y
los que para el uso exclusivo de sus inventos, se otorguen a los
inventores y perfeccionadores de alguna mejora</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>El
Estado, sujetándose a las leyes, podrá en casos de interés
general, concesionar la prestación de servicios públicos o la
explotación, uso y aprovechamiento de bienes de dominio de la
Federación, salvo las excepciones que las mismas prevengan Las
leyes fijarán las modalidades y condiciones que aseguren la eficacia
de la prestación de los servicios y la utilización social de los
bienes, y evitarán fenómenos de concentración que contraríen el
interés público</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>La
sujeción a regímenes de servicio público se apegará a lo
dispuesto por la Constitución y sólo podrá llevarse a cabo
mediante ley</i></font></font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Se
podrán otorgar subsidios a actividades prioritarias, cuando sean
generales, de carácter temporal y no afecten sustancialmente las
finanzas de la Nación El Estado vigilará su aplicación y evaluará
los resultados de ésta</i></font></font></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p style="text-indent: 039in; line-height: 100%; page-break-after: avoid"><a name="ART29"></a>
