<font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ARTÍCULO
29</i></font></font></b></font></p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
los primeros 28 artículos de las garantías constitucionales se
encuentran 24 de garantías individuales directas y 4 de
garantías de derechos sociales, que son garantías indirectas
individuales, como ya lo vimos Este artículo 29 que vamos a
estudiar se encuentra dentro de las garantías constitucionales y nos
dice que, todas las garantías que ya hemos visto se pueden suspender
en caso de que tuviéramos una invasión de parte de algún país,
como sucedió con la invasión americana de 1847, o la francesa
También si hubiera alguna perturbación grave de la paz
pública, que pudiera ser de guerrilleros o que pusiera a la sociedad
en un grave peligro, como el enfrentamiento con el crimen
organizado Pero solamente el presidente de la república, y de
acuerdo con los secretarios de estado, como el de la Defensa
Nacional, la Armada, Hacienda, Economía, Educación, Trabajo y
los que existan en ese momento; la Procuraduría General de la
República y la aprobación del Congreso de la Unión, que son la
</font></font><a href="http://eswikipediaorg/wiki/Senado_de_México"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Cámara
de Senadores</b></i></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y</font></font></u></span></font></a><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Camara_de_Diputados_(Mexico)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Cámara
de Diputados</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">;
podrán suspender todas las garantías Lo que quiere decir que,
en caso de enfrentamientos armados, se tirará a matar, sin juicio,
lo que atenta contra el derecho a la vida y los demás artículos
Puede haber toque de queda, violando los derechos de libertad de los
ciudadanos, ya que a determinada hora nadie puede estar fuera de
su casa, sin caminar por las calles Se pueden hacer cateos sin
orden, en todas las casas, para buscar personas y armas A estos
actos no se les llama violaciones a los derechos, sino suspensión de
derechos, que sólo el presidente puede hacer, para hacer frente,
rápida y fácilmente a la situación que pone en riesgo la paz de la
sociedad Pero sólo se hará por tiempo determinado, mientras se
recupera la estabilidad social y de inmediato se volverá a la
normalidad, restableciéndose la constitución en todos los aspectos,
principalmente en los derechos individuales y sociales Este
artículo nos garantiza, a todos los mexicanos, el bienestar
contra enemigos de la sociedad y el restablecimiento de nuestros
derechos</font></font></font></font></p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 039in; text-indent: 039in; margin-bottom: 014in; line-height: 115%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 039in; text-indent: 039in; margin-bottom: 014in; line-height: 115%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 039in; text-indent: 039in; margin-bottom: 014in; line-height: 115%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-right: 075in; text-indent: 02in; background: #c6d9f1; line-height: 100%">
<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Artículo
29</b></i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
En los casos de invasión, perturbación grave de la paz pública, o
de cualquier otro que ponga a la sociedad en grave peligro o
conflicto, solamente el Presidente de los Estados Unidos Mexicanos,
de acuerdo con los Titulares de las Secretarías de Estado y la
Procuraduría General de la República y con la aprobación del
Congreso de la Unión y, en los recesos de éste, de la Comisión
Permanente, podrá suspender en todo el país o en lugar determinado
las garantías que fuesen obstáculo para hacer frente, rápida y
fácilmente a la situación; pero deberá hacerlo por un tiempo
limitado, por medio de prevenciones generales y sin que la suspensión
se contraiga a determinado individuo Si la suspensión tuviese lugar
hallándose el Congreso reunido, éste concederá las autorizaciones
que estime necesarias para que el Ejecutivo haga frente a la
situación; pero si se verificase en tiempo de receso, se convocará
sin demora al Congreso para que las acuerde</i></font></font></font></font></font></p>
</body>
</html>