<?php 
echo $this->headLink()->appendStylesheet($this->baseUrl('/public/css/proposalsStyle.css'));
include_once APPLICATION_PATH . '/services/impl/PreferencesServiceImpl.php';
 $service = new ProjectsServiceImpl();
$this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/viewPriceServices.js'));
	$helpUser = $this->helps->prospectprojectsIndex;
?>

<script>
	$(document).ready(function() {
		$('a.arriba').click(function(){
			$('html, body').animate({scrollTop:0}, 1250);
			return false;
		});

		var idServi = "<?php echo $this->idServi; ?>";
		var oTableO;
		var ind = 1;
		oTableO = jqueryTablePopup('#OrderTablePay');
		//var oTable = $('#OrderTablePay').dataTable();

		$.ajax({ 
		  type : "GET",
		  url : BASE_URL + "/prospectprojects/export",
		  data: {idse: 1, idServi : idServi },
		  //cache : false,
		  dataType: "json",
		success : function(response) {

			if(response.response == "ok"){
				
				for(var i=0;i<response.data.length;i++){
						var item = response.data[i];

						oTableO.fnAddData([
						            ind++,
			    					item.quantity,
			    					item.concept,
			    					formatNumber(item.unitprice,"$"),
			    					formatNumber(item.import,"$"),
						]);
				}

				var nRows = oTableO.fnGetNodes();//numero de filas
				for (var i = 0; i < nRows.length; i++) {
							var aPos = oTableO.fnGetPosition(nRows[i]);
								nRows[i].cells[0].setAttribute("class", "sorting_1 ui-state-highlight");
								nRows[i].cells[1].setAttribute("class", "ui-state-highlight");
								nRows[i].cells[2].setAttribute("class", "ui-state-highlight");
								nRows[i].cells[3].setAttribute("class", "ui-state-highlight");
								nRows[i].cells[4].setAttribute("class", "ui-state-highlight");				
				}						
			}
	
		},
		  error: function(error){
			  $("#message").html("Error desconocido contacta al administrador");
		  }
		});
	});
		
</script>

<script>
/*function imprimir(que) {
	var ventana = window.open("", "", "");
	var contenido = "<html><body onload='window.print();window.close();'>";
	contenido = contenido + document.getElementById(que).innerHTML + "</body></html>";
	ventana.document.open();
	ventana.document.write(contenido);
	ventana.document.close();
}*/
function imprimir(que){

  var objeto=document.getElementById(que);  //obtenemos el objeto a imprimir
  var ventana=window.open('','_blank');  //abrimos una ventana vacía nueva
  ventana.document.write(objeto.innerHTML);  //imprimimos el HTML del objeto en la nueva ventana
  ventana.document.close();  //cerramos el documento
  ventana.print();  //imprimimos la ventana
  ventana.close();  //cerramos la ventana
}

</script>
<h3 class="centerIn">Imprimir Cotizaci&oacute;n de Servicio</h3>
<ul class="toolbar">
		<div id="icons">
				<li class="iconOpacity">
					 <a href="<?php echo $this->baseUrl('/proposals/index') ?>"><img src="<?php echo $this->baseUrl('/public/img/iconnote.png');?>" title="Cotizaciones de Productos"></a> 
				</li>
				<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','exportar propuesta')">
					<a><img title="Ayuda" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icoquestion.png')?>"></a>
				</li>

				<div id="clock"></div>
		</div>	
</ul>
 <br />
<center>
<a href="<?php echo $this->baseUrl('/prospectprojects/index'); ?>" class="subPay" name="Regresar" >Regresar a listado</a>
<a href="javascript:imprimir('fieldsetForm')" class="subPay" name="Imprimir Propuesta">
Imprimir Cotizaci&oacute;n</a>
</center>
<a name="top"></a>
 <br />
<div id="fieldsetForm" class="forms">
	<div id="log">
		<?php $preferencesService =  new Application_Service_Impl_PreferencesServiceImpl();
			  $preference = $preferencesService->getPreferencesById(Preferences::CODE_LOGO);
		foreach ($preference as $valor){ ?>
			<?php if($valor->getValue() != ""): ?>
				<img id="imgLogo" style="width: 150px; height: 180px;" src="<?php echo "data:image/png;base64,".$valor->getValue();?>" alt="logotipo" title="logotipo">
			<?php else: ?>
				<img id="imgLogo" style="width: 150px; height: 180px;" src="<?php echo $this->baseUrl('img/aqui_tu_logo.jpg'); ?>" alt="logotipo" title="logotipo">
			<?php endif; ?>
		<?php } ?>
	</div>
	<div id="title" style="margin-bottom: 10px;" class="center">
		<h1 style="font-size: 34px;position:relative;color: #000;font-weight: 400;text-shadow: 0px 0px 1px rgba(0,0,0,0.3);padding: 20px;text-transform: uppercase;text-align: center;">Cotizaci&oacute;n de Servicio</h1>
		<br />
		<div id="dateCreate" style="text-align: center;color: navy;font-size: 20px;">
			Fecha de creaci&oacute;n: <span><?php echo new Zend_Date(); ?></span>
		</div>
	</div>
	<?php if($this->dataProp):?>
	 <?php foreach($this->dataProp as $propuesta) : ?>
	 	<div id="firstInfo" style="height: auto;margin-bottom: 10px;padding: 10px;">
	 		<h1 style="text-align: center;">Informaci&oacute;n General</h1>
	 		<br />
	 		<div id="objective" align="center" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px;">
	 		Cliente: 
	 		<span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo $propuesta->getNameCompany();?>
	 		</span>
	 		</div>
	 		<br />
	 		<div id="objective" align="center" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px;">Fecha Inicio: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo $propuesta->getStart_date();?>
	 			 &nbsp; &nbsp;  &nbsp;
	 		</span>Fecha Fin: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo $propuesta->getEnd_date();?>
	 		</span>
	 		</div>
	 		<br />
	 		<div id="objective" align="center" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px;">Servicio: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo $propuesta->getName_project();?>
	 		</span>
	 		</div>
	 		<br />
	 		<div id="objective" align="center" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px;">Descripci&oacute;n:
	 		<br />
	 		<span class="cont" style="font-size: 14px;font-weight: normal;">
	 		<textarea disabled="true"><?php echo $propuesta->getDescription();?></textarea>
	 			
	 		</span>
	 		</div>
	 		<br />
	 		<div id="objective" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px; margin-left:160px;">Costo: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo Application_Util_Tools::currency($propuesta->getCost());?>
	 		</span>
	 		</div>
	 		<br />
	 		<div id="objective" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px; margin-left:160px;">Descuento: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo Application_Util_Tools::currency($propuesta->getDiscountPercent());?>
	 		</span>
	 		</div>
	 		<br />
	 		<div id="antecedent" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px; margin-left:160px;">Subtotal: <span class="cont" style="font-size: 14px;font-weight: normal;">
	 			<?php echo Application_Util_Tools::currency($propuesta->getSubtotal());?>
	 		</span></div>
			<br />
			<div id="solution" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px; margin-left:160px;">Iva: <span class="cont" style="font-size: 14px;font-weight: normal;">
				<?php echo Application_Util_Tools::currency($propuesta->getIVA());?>
			</span></div>
 			<br />
 			<div id="audience" style="font-size: 15px;font-weight: bold;margin-bottom: 5px;padding: 5px; margin-left:160px;">Total: <span class="cont" style="font-size: 14px;font-weight: normal;">
 				<?php echo Application_Util_Tools::currency($propuesta->getTotal());?>
 			</span>
 			</div>
		</div>	 
<div>
<br />
			<h1 style="text-align: center;">Detalle de la cotizaci&oacute;n</h1>
<br />
	   		<!--<table id="mitabla" align="center">
    			<thead>
    					<th>Clave</th>
    					<th>Cantidad</th>
    					<th>Concepto</th>
    					<th>Precio Unit.</th>
    					<th>Precio</th>
    			</thead>
    			<tbody>
    		<?php if(count($this->idOrder)) :?>
    		<?php foreach ($this->idOrder as $order): ?>	
    				<tr>
    					<td><?php echo $order['id_service']; ?></td>
    					<td><?php echo $order['quantity']; ?> </td>
    					<td><?php echo $order['concept']; ?> </td>
    					<td><?php echo Application_Util_Tools::currency($order['unityPrice']); ?></td>
    					<td><?php echo Application_Util_Tools::currency($order['price']); ?></td>
    				</tr>
    		<?php endforeach; ?>
			<?php else : ?>
				<tr>
					<td colspan="5" ><?php echo "<center>No hay datos disponibles</center>"; ?></td>
				</tr>
			<?php endif; ?>
    			</tbody>
    	</table>-->
</div>

		<div id="tablaPayDiv" >
    		<table class="display" id="OrderTablePay" align="center">
    			<thead>
    				<tr>
    					<th>Id</th>
    					<th>Cantidad</th>
    					<th>Concepto</th>
    					<th>Importe Unit.</th>
    					<th>Importe</th>
    				</tr>
    			</thead>
    			<tbody>
    			</tbody>
    		</table>	
	     </div>

		<?php endforeach; ?>
			 <?php else:?>
		<div>No hay datos</div>
	<?php endif;?>
</div>
<br />
<center>
<a href="#" class="arriba" id="subPay" name="button">Regresar arriba</a>
</center>
<br />

<style type="text/css">
		
#mitabla{
/*estilo de el cuerpo de nuestra tabla*/
background-color: #1e8cbe;*
width:100%;
margin:20px auto;
border-left: 1px solid #ccc;
border-right: 1px solid #ccc;
font-family:helvetica,arial,sans-serif;
font-weight:normal;
/*text-transform: uppercase;*/
}

#mitabla th{
/*estilo de los elementos(th)*/
background-color: #1e90ff;
color:#ffffff;
font-weight: bolder;
font-size:15px;
padding: 8px;
text-transform: uppercase;
text-align: center;
}

#mitabla td{

/*estilo a los elementos (td)*/
font-weight: bold;
width:100px;
font-size:15px;
}

**Aqui esta la magia ahora vamos usar el  nth-child()**

#mitabla tr:nth-child(odd){

/*para los colores de las filas impares*/
background-color: #ffffff;
}

#mitabla tr:nth-child(even){

/*para los colores de las filas pares*/
background:#EDEDED;
}

</style>