<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Horus\Module'                        => __DIR__ . '/Module.php',
    'Horus\Controller\CustomersController' => __DIR__ . '/src/Horus/Controller/CustomersController.php',
    'HorusTest\Framework\TestCase'        => __DIR__ . '/tests/Horus/Framework/TestCase.php',
    'HorusTest\SampleTest'                => __DIR__ . '/tests/Horus/SampleTest.php',
);
