<script src="http://mymaplist.com/js/vendor/TweenLite.min.js"></script>
<!-- This is a very simple parallax effect achieved by simple CSS 3 multiple backgrounds, made by http://twitter.com/msurguy -->

<?php
$flashMessage = $this->flashMessenger()->getMessages();
if (count($flashMessage)) : ?>
<div class="row">
	<div class="col-md-4 col-md-offset-4">
    <?php foreach ($flashMessage as $msg) : foreach ($msg as $type => $message) :?>
        <!--  <li><span class="<?php echo $type; ?>"><?php echo $message; ?></span></li> -->
        <div class="alert alert-danger" role="alert">
        	<span class="<?php echo $type; ?>"><?php echo $message; ?></span>
        </div>
    <?php endforeach; endforeach; ?>
    </div>
<?php endif; ?>
    
<?php if(isset($this->messages)) : ?>
    <ul>
        <?php foreach ($this->messages as $type => $msg) : ?>
        <li><span class="<?php echo $type; ?>"><?php echo $msg; ?></span></li>
        <?php endforeach; ?>
    </ul>
</div>
<?php endif; ?>

<div class="row vertical-offset-100">
	<div class="col-md-4 col-md-offset-4">
   		<div class="panel panel-info">
			<div class="panel-heading">
				<h3 class="panel-title">Por favor, inicia sesi&oacute;n</h3>
			</div>
			<div class="panel-body">
				
				<h1 class="h1-tittle">::Enlasa::</h1>
				<center>
					<span>Ingresa tu usuario y contrase&ntilde;a para acceder al panel.</span>
				</center>
				
				<?php
	            $form = $this->loginForm;
	            $form->prepare();
	            echo $this->form()->openTag($form);
	            ?>
                	<fieldset>
			    		<div class="form-group" style="margin-top: 20px">
			    			<!--<?php echo $this->formlabel($form->get('email'));?>-->
			    		    <?php echo $this->formElement($form->get('email')); ?>
			    		    <span class="common-error-msg"><?php echo $this->formElementErrors($form->get('email'));?></span>
			    		</div>
			    		<div class="form-group">
			    			<!--<?php echo $this->formlabel($form->get('password'));?>-->
			    			<?php echo $this->formElement($form->get('password')); ?>
			    			<span class="common-error-msg"><?php echo $this->formElementErrors($form->get('password'));?>
			    		</div>
			    		<?php
	                    echo $this->formRow($form->get('loginCsrf'));
	                    echo $this->formElement($form->get('submit'));
                    	?>
			    	</fieldset>
				<?php echo $this->form()->closeTag($form); ?>
			</div>
		</div>
	</div>
</div>

<style>
*{
	border: 0 none;
	margin: 0;
	padding: 0;
}
body{
    /*background: url(http://mymaplist.com/img/parallax/back.png);
	background-color: #444;
    background: url(http://mymaplist.com/img/parallax/pinlayer2.png),url(http://mymaplist.com/img/parallax/pinlayer1.png),url(http://mymaplist.com/img/parallax/back.png);    
	*/
}

.vertical-offset-100{
    padding-top:100px;
}

.h1-tittle{
	margin-top: 0px;
	margin-bottom: 10px;
	color: #5bc0de;
    font-family: 'Bree Serif',serif;
    font-size: 26px;
    font-weight:bold;
    text-align: center;
    text-shadow: 1px 1px 0 rgba(255, 255, 255, 1);
}
span{
	color: #678889;
	font-size: 13px;
	line-height: 16px;
	text-shadow: 1px 1px 0 rgba(255, 255, 255, 1);
}
.panel-body li{
	list-style:none;
	text-align: center;
}
</style>

<script>
$(document).ready(function(){
	  $(document).mousemove(function(event){
	     TweenLite.to($('body'), 
	        .5, 
	        { css: 
	            {
	                backgroundPosition: ""+ parseInt(event.pageX/8) + "px "+parseInt(event.pageY/'12')+"px, "+parseInt(event.pageX/'15')+"px "+parseInt(event.pageY/'15')+"px, "+parseInt(event.pageX/'30')+"px "+parseInt(event.pageY/'30')+"px"
	            }
	        });
	  });
});
</script>