
<?php $this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/addCategory.js')); 
$helpUser = $this->helps->stockAdd;
$helpUser2 = $this->helps->stockIndex2;
?>

<script type="text/javascript">


$(document).ready(function() {
	jqueryTablePopup('#category',2);
	
	 //agregar imagen de equipo propuesto
	new AjaxUpload('#addImage', {
		action: BASE_URL + '/System/users/update?imgUpload=true',
		onSubmit : function(file , ext){
			if (! (ext && /^(jpg|png)$/.test(ext))){
				// extensiones permitidas
				horusAlert('S\u00f3lo se permiten Imagenes .jpg o .png');
				// cancela upload
				return false;
			} else {
				$('#loaderAjax').show();
				this.disable();
			}
		},
		onComplete: function(file, response){
			respuesta = $.parseJSON(response);
			if(respuesta.respuesta == 'done'){
				$('#fotografia').removeAttr('scr');
				$('#fotografia').attr('src', 'data:image/png;base64,'+respuesta.base64);
				$('#p_photo').val(respuesta.base64);
				$('#loaderAjax').show();
			}
			else{
				horusAlert(respuesta.mensaje);
			}	
			$('#loaderAjax').hide();	
			this.enable();	
		}
	});
});
</script>

<h3 class="centerIn"><?php echo 'Agregar '.$this -> titulo;?></h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity ">
			<a href="<?php echo $this->baseUrl("/In/stock/index");?>" >
				<img title="Inventario" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconinventory.png');?>" />
			</a>
		</li>
		<li class="iconOpacity ">
			<a href="javascript:;" onclick="javascript:showCatalogOptions()">
				<img title="Agregar nueva categoria" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/icondepartment.png');?>" />
			</a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser2; ?>')">
				<a>
					<img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
				</a>
		</li>
		<div id="clock"></div>
	</div>	
</ul>

<?php print $this->form; ?>
<!-- 
    Inicia popup
-->
<div id="popupCatalog" class="popHorus">
	<div id="btnCloseCatalog" title="Cerrar ventana">X</div>
	<div id="formCatalog">
		<div class="center">
			<h3>Categor&iacute;as</h3>
			<ul class="toolbar">
					<div id="icons">
						<li class="iconOpacity ">
							<a id="modalAddCategory" href="javascript:;" onclick="javascript:changeView('save');">
								<img title="Agregar categor&iacute;a" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" />
							</a>
						</li>
						<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser2; ?>')">
								<a>
									<img title="Ayuda"  src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
								</a>
						</li>
						<div id="clock"></div>
					</div>	
				</ul>
			<div id="tableCover">
			<img style="display:none; width: 36px; height: 36px;" id="loadEditCategory" alt="cargando..." src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"/>
				<table id="category" class="display">
					<thead>
						<tr>
							<th>Categor&iacute;a</th>
							<th>Descripci&oacute;n</th>
							<th>
								<a onclick="javascript:changeView('save');"> <img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" 
								title="Agregar categor&iacute;a"> </a>
							</th>
						</tr>
					</thead>
					<tbody>
					<?php if($this->categories) foreach ($this->categories as $category):?>
					<?php if ($category->getCategoryId() != Constants::ALMACEN):?>
						<tr>
							<td class="alpha"><?php echo $category->getName()?></td>
							<td class="alpha"><?php echo $category->getDescription()?></td>
							<td> 
				               <a onclick="javascript:editCategory('category',this,'<?php echo $category->getCategoryId()?>')"> 
									<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconedit.png')?>" title="Editar"	alt="Editar">
							   </a>
				               <a onclick="deleteCategory('category',this,'<?php echo $category->getCategoryId()?>','/category/delete','<?php echo Categories::ALMACEN ?>')"> 
									<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconminus.png')?>" title="Eliminar"	alt="Eliminar">
							   </a>
				            </td> 
						</tr>
					<?php endif; endforeach;?>
					</tbody>
				</table>
			</div>
			<div id="hiddenForm" style="display: none;">
					<?php echo $this->categoryForm; ?>
			</div>
		</div>
	</div>
</div>
<div id="backgroundCatalog"></div>
<!-- 
	Termina popup
-->