<?php include_once APPLICATION_PATH . '/Constants/Constants.php'; ?>
<?php
 $this->headLink()->appendStylesheet($this->baseUrl('/public/css/popupAddPayment.css'))
 				  ->appendStylesheet($this->baseUrl('/public/css/paysPop.css'))
 				  ->appendStylesheet($this->baseUrl('/public/css/popupArticle.css'));
 $this->headScript()->appendFile($this->baseUrl('/public/js/jsFunctions/ajax/proposalFunctions.js'));
 
 $layout = Zend_Layout::getMvcInstance();
 $view = $layout->getView(); ?>

	
<script>
	var iva = "<?php echo Application_Util_Tools::getPreferenceTax($this->element->getElement('value')->getValue()); ?>";
	var SEPARATOR = "<?php echo SeparatorString::SEPARATOR;?>";
	var iconsFile = "<?php echo $view->iconset; ?>";
</script>

<input id="suppSele" type="hidden" />
<div id="fieldsetForm" class="forms" style="overflow-x:hidden;">
<legend id="legendhelp">* Datos requeridos</legend>
	  <fieldset>
			<legend>Cotizaci&oacute;n de Productos</legend>
			<table style="margin-left:80px; margin-right:50px;">
				<tbody>
					<tr>
<!--						<td>* N° de pedido: </td>-->
						<td>Fecha: <?php echo date('d/m/Y');?></td>											
					</tr>
						<tr>
							<td>
								<input type="radio" name="mybrand" checked="checked" value="1" style="height: 10px; width: 10px;">
								<span style="margin-left: 5px;">Cliente</span><br />
								<input type="radio" name="mybrand" value="0" style="height: 10px; width: 10px;">
								<span style="margin-left: 5px;">Prospecto</span>
							</td>
						</tr>
					<tr>
<!--//						<td><? $this->element->getElement('account'); ?></td>-->
					</tr>									
					<tr>
						<td> 
						<span id="suppl"> </span>
						</td>
						<td>Fecha: </td>
						<td>Fecha de env&iacute;o esperada:</td>
					</tr>
					<tr>
						<td> 
						<span id="supplSelect">
							<?=$this->element->getElement('id_company'); ?>
							<img id="loadCp" style="display:none;" src="<?php echo $this->baseUrl("/public/img/loader.gif");?>"/>
						</span> 
						<a id="supplAdd">
							<img src="<?php echo $this->baseUrl("/public/img/icons/".$view->iconset."/iconplus.png"); ?>" title="Agregar Nuevo" />
						</a>
						</td>
						<td><?=$this->element->getElement('start_date'); ?></td>
						<td><?=$this->element->getElement('end_date'); ?></td>
					</tr>
					</tbody>
			 </table>
		 </fieldset>
		 <fieldset>
		 	
			<legend>Productos</legend>
				<table>
					<tr>
						<td>Art&iacute;culo: </td>
						<td>Precio Unitario:</td>
						<td>Cantidad:</td>
						<td></td>
					</tr>
					<tr>
						<img id="loadProd" style="display:none;" src="<?php echo $this->baseUrl("/public/img/loader.gif");?>"/>
						<td>
						<?=$this->element->getElement('article'); ?>
						<!--<a id="addArticle" style="display: none" href="javascript:;">Agregar articulo</a>-->
						</td>
						<td><?=$this->element->getElement('amount'); ?></td>
						<td>
							<?=$this->element->getElement('quantity'); ?>
							<div id="toStok" class="stoks" style="display: none;">Total en stock <span id="toS"></span></div>
						</td>
						<td>
							<img id="addPurchase" src="<?php echo $this->baseUrl("/public/img/icons/".$view->iconset."/iconplus.png"); ?>" title="agregar" />
							<span id='maxErr' style='display: none; color: red;'><br/>Tienes que llenar los 3 campos</span>
						</td>
					</tr>
					<tr>
						<td colspan="4"></td>
					</tr>
					<tr>
						<td colspan="4">
							<div id="tableOrderPurchase" style="margin-left:13%; margin-right:13%;">
							<img class="loadTable" style="display:none;" src="<?php echo $this->baseUrl("/public/img/loader.gif");?>"/>
								<table id="tableOrder" class="display">
									<thead>
										<tr>
											<td>Clave</td>
											<td>Art&iacute;culo</td>
											<td>Cantidad</td>
											<td>Precio Unitario</td>
											<td>
												Acci&oacute;n
											</td>
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>
							
							</div>
						</td>
					</tr>


					<tr>
						<td colspan="4">
							<div style="margin-left:50%; margin-right:0%;">
							
					<table >
					<thead>
					<tr>
					<tr>
						<td align="right" colspan="3">* Subtotal:</td>
						<td><?=$this->element->getElement('subtotal');?></td>
					</tr>
					<tr>
						<td align="right" colspan="3">* iva:</td>
						<td><?=$this->element->getElement('iva');?></td>
					</tr>
					<tr>
						<td align="right" colspan="3">* Total:</td>
						<td><?=$this->element->getElement('total'); ?></td>
					</tr>
					<tr>
						<td align="right" colspan="3"></td>
						<td><?=$this->element->getElement('numberofpayments'); ?>
							<!--<img id="paysCalendar" src="<?php echo $this->baseUrl('/public/img/calendar.png');?>" title="Especifique las fechas de pago"/>-->
							<?=$this->element->getElement('value'); ?>
						</td>
					</tr>
										</tr>
									</thead>
									<tbody>
									</tbody>
								</table>
							
							</div>
						</td>
					</tr>



					<tr class="center">
						<td colspan="4">Condiciones:</td>
					</tr>
					<tr class="center">
						<td colspan="4"><?=$this->element->getElement('conditions');?></td>
					</tr>
				</tbody>
			</table>	
		  </fieldset>

	<?=$this->element->getElement('dates'); ?>
<?=$this->element->getElement('purchaseItem');?>	
<?=$this->element->getElement('minstock');?>
<?=$this->element->getElement('maxstock');?>
<?=$this->element->getElement('stock'); ?>
<?=$this->element->getElement('company'); ?>
	<div class="center">
	<?=$this->element->getElement('Enviar'); ?>
	<a href="javascript:location.href='<?=$this->baseUrl("/In/proposals/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
	</div>
</div>

<!-- 
    Inicia popup
-->
<div id="paysPop" class="popHorus">
	<h2>Especifique las fechas de Pago.</h2>
	<div id="btnAccept">Aceptar</div>
	<ul id="paysArea"></ul>
</div>
<div id="paysBack"></div>
<!-- 
    termina popup
-->
