<h3 class="centerHor">Actualiza mi Empresa</h3>
<ul class="toolbar">
	<div id="icons">
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','Actualizar mi empresa')">
				<a><img title="Ayuda" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>
</ul>

    <div id="overflow">
	<p class="triangle-border" >Edita los datos de la empresa.</p>
		<?php echo $this->formulario; ?>
	</div>