
<!DOCTYPE html>
<html lang="en">
<?
$this->title = "Propuestas IOFractal";
$this->headTitle($this->title);
?>
<head>
<meta http-equiv='Content-Type' content='text/html; charset=utf-8' />
<meta charset="UTF-8_unicode_ci" />
<meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
<link rel="stylesheet" type="text/css" href="/css/prin.css" />
<link rel="stylesheet" type="text/css" href="/css/style.css" />
<script type="text/javascript"
	src="http://ajax.googleapis.com/ajax/libs/jquery/1.7.0/jquery.min.js"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('/public/js/jquery.eislideshow.js') ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('/public/js/jquery.easing.1.3.js') ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('/public/js/jquery/css/ui-lightness/jquery-ui-1.8.16.custom.css') ?>"></script>
<script type="text/javascript"
	src="<?php echo $this->baseUrl('/public/js/jquery/js/jquery-ui-1.8.16.custom.min.js') ?>"></script>
<noscript>
	<link rel="stylesheet" type="text/css"
		href="<?php echo $this->baseUrl('/public/css/noscript.css') ?>" />
</noscript>

<script>
	$(document).ready(function() {
		$('a.arriba').click(function(){
			$('html, body').animate({scrollTop:0}, 1250);
			return false;
		});
	});
</script>
</head>
<body>
	<h1></h1>
	<!-- <?php echo $this->url(array('controller'=>'proposals','action'=>'add'));?>  -->
	<a href="<?php echo $this->baseUrl('/proposals/index') ?>"><img
		style="opacity: 0.4; filter: alpha(opacity = 40)"
		onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40"
		alt="agregar" src="<?php echo $this->baseUrl('/public/img/returnIOF.png') ?>">Ir
		a principal propuestas</a>

	<a
		href="<?php echo $this->url(array('controller'=>'proposal',
'action'=>'ppt'));?> "><img
		style="opacity: 0.4; filter: alpha(opacity = 40)"
		onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100"
		onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40"
		alt="agregar" src="<?php echo $this->baseUrl('/public/img/save.gif') ?>"> </a>

	<h1 align="center">Propuestas para exportar</h1>
	<div class="wrapper">
		<div id="ei-slider" class="ei-slider">
			<ul class="ei-slider-large">
				<?php if(count($this->paginatorP2)) ;?>
				<?php foreach($this->paginatorP2 as $propa):?>
				<?php if (strlen($this->escape($propa->antecedent)) > 30)  
					$antecedent = substr($this->escape($propa->antecedent),0,30).'(...)';
				else
                  $antecedent = $this->escape($propa->antecedent); ?>
				<li><img
					onclick="exp('<?php echo $this->escape($propa->idProposals);?>')"
					src="<?php echo $this->baseUrl('/public/img/large/1.jpg') ?>"
					title="click para exportar" />
					<div class="ei-title">
						<h2>
							<?php echo 'propuesta '.$this->escape($propa->idProposals);?>
						</h2>
						<h4>
							<?php echo $antecedent;?>
						</h4>
					</div>
				</li>
				<?php endforeach;?>
				<?php if(count($this->paginatorP2)):?>
				<?php echo $this->paginatorP2 ?>
				<?php endif;?>
			</ul>
			<!-- termina ei-slider-large-->
			<ul class="ei-slider-thumbs">
				<li class="ei-slider-element">Current</li>
				<?php if(count($this->paginatorP2)) ;?>
				<?php foreach($this->paginatorP2 as $prope):?>
				<li><a href="#"><?php echo $this->escape($prope->idProposals);?> </a>
					<img src="<?php echo $this->baseUrl('/public/img/thumbs/1.jpg') ?>"
					alt="propuestas" />
				</li>
				<?php endforeach;?>
				<?php if(count($this->paginatorP2)):?>
				<?php echo $this->paginatorP2 ?>
				<?php endif;?>
			</ul>
			<!-- termina el ie-slider-thumbs -->
		</div>
		<!-- termina ei-slider -->
	</div>
	<!-- termina wrapper -->

	<script type="text/javascript">
            $(function() {
                $('#ei-slider').eislideshow({
                    easing      : 'easeOutExpo',
                    titleeasing : 'easeOutExpo',
                    titlespeed  : 1200
                });
            });
        </script>

	<script type="text/javascript">
    function exp(id){
        // a workaround for a flaw in the demo system (http://dev.jqueryui.com/ticket/4375), ignore!
        $( "#dialog:ui-dialog" ).dialog( "destroy" );
    
        $( "#dialog-confirm" ).dialog({
            resizable: false,
            height:140,
            modal: true,

        });
        document.getElementById("idProposals").value = id;
    }
</script>
	<!-- 
:::::::::::::::: cuadro de dialogo para eliminar propuesta
 -->
	<div id="dialog-confirm" title="Exportar Propuesta"
		style="display: none">
		<p>
			<span class="ui-icon ui-icon-alert"
				style="float: left; margin: 0 7px 20px 0;"></span> ¿Est&aacute;
			seguro de exportar esta propuesta?
		</p>
		<form id="export"
			action="<?php echo $this->url(array('action' => 'export'))?>"
			method="post">

			<input type="hidden" name="idProposals" id="idProposals" />
			<h1></h1>
			<button id="TBsubmit" name="export" value="Si"
				class="ui-button ui-button-text-only ui-widget ui-state-default ui-corner-all">
				<span class="ui-button-text">Aceptar</span>
			</button>
			<button id="TBsubmit" name="export" value="No"
				class="ui-button ui-button-text-only ui-widget ui-state-default ui-corner-all">
				<span class="ui-button-text">Cancelar</span>
			</button>
		</form>
	</div>
	
</body>
</html>