<script type="text/javascript">
$(document).ready(function() {
	jqueryTable('#curses', 8);	
});
var BASE_URL = "<?php echo $this->baseUrl();?>";
</script>
<h3 class="centerHor">Cursos</h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity">
			<a class="tooltipcenter" title="Agregar Nuevo" href="<?php echo $this->baseUrl('/Ioteca/courses/add') ?>" > 
				<img class="iconOpacity" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png')?>" title="Agregar Nuevo" > 
			</a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser; ?>')">
			<a href="javascript:;" title="Ayuda" class="tooltipcenter">
				<img title="Ayuda" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
			</a>
		</li>
		<div id="clock"></div>
	</div>	
</ul>
<div id="overflow"> 
	<table id="curses" class="display">     
	    <thead>
		    <tr>
		        <th>Nombre</th>
		        <th>Tipo</th>
		        <th>Inicio</th> 
		        <th>Fin</th>
		        <th>Estatus</th>
		        <th>Description</th>
		        <th>Registrado por</th> 
		        <th>Fecha y Hora</th>   
		        <th>
		            <a class="tooltipcenter" title="Agregar Nuevo" href="<?php echo $this->baseUrl('/Ioteca/courses/add') ?>">
						<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" title="Agregar Nuevo">
					</a>
		        </th>  
		    </tr>
	    </thead> 
	    <tbody>
	    <?php if($this->courses != 0) :?>
	       <?php foreach ($this->courses as $curse) : ?>
	        <tr>
	        	<td><?php echo $curse->getName(); ?></td>
    			<td><?php echo $curse->getType(); ?></td>
    			<td><?php echo $curse->getDate_start(); ?></td>
    			<td><?php echo $curse->getDate_finish(); ?></td>
    			<td><?php echo $curse->getStatus(); ?></td>
    			<td><?php echo $curse->getDescription(); ?></td>
    			<td><?php echo $curse->getNameUser(); ?></td>
    			<td><?php echo $curse->getDate_hour(); ?></td>
    			<td>    
	                <a class="tooltip" title="Actualizar" href="<?php echo $this->baseUrl() ?>/Ioteca/courses/update?c=<?= $curse->getIdCurses(); ?>">
                    	<img src=" <?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconedit.png') ?>" title="Editar">
                   	</a>
	            
	                <a class="tooltip" title="Eliminar" onclick="javascript:deleteRecord('curses',this,'<?php echo $curse->getIdCurses(); ?>','/Ioteca/courses/delete')">
                   		<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconminus.png') ?>" title="Eliminar">
					</a>
	            </td>
	        </tr>
	    	<?php endforeach; endif;?>
	    </tbody>
	</table>
</div>