<font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>REGLA
DE TRES COMPUESTA DIRECTA</b></i></font></font></font></font></font></p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="left" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>	</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Veamos
otro ejemplo:</font></font></font></font></p>
<p class="western" align="left" style="line-height: 100%"><br>
</p>
<p class="western" style="line-height: 100%">	Sabemos que tenemos que
cubrir una distancia en <b>10</b> días, durante <b>12</b> horas
diarias, a razón de <b>42</b> kilómetros por hora ¿A qué
velocidad debemos ir para recorrer la misma distancia, pero en <b>8</b>
días, durante <b>9</b> horas diarias?</p>
<p class="western" align="justify" style="line-height: 100%"><br>
</p>
<p class="western" align="justify" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Lo
que quiere decir que, ahora tendremos menos días y horas y, por lo
tanto debemos tener más velocidad, para recorrer la misma distancia
Más velocidad, menos tiempo</font></font></font></font></p>
<p align="left" style="line-height: 100%"><br>
</p>
<p class="western" align="left" style="line-height: 100%"><font face="Calibri, serif"><font size="2" style="font-size: 11pt"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	Entonces,
es una: </font></font></font></font>
</p>
<p class="western" align="left" style="line-height: 100%"><br>
</p>
<p class="western" align="left" style="text-indent: 049in; line-height: 100%"><a name="REGLADETRESCOMPUESTAINVERSA"></a>
