<script type="text/javascript">
$(function(){
    // 6 create an instance when the DOM is ready
    $('#jstree').jstree({ 'core' : {
      'data' :
    	<?php
    		echo $this->tree;
    	?>
    },
    "types" : {
 	      "root" : {
 	        "icon" : "<?php echo $this->baseUrl('/public/img/images/tree-icon.png')?>"
 	      },
 	    "folder" : {
 	        "icon" : "<?php echo $this->baseUrl('/public/img/images/folder.ico')?>"
 	      },
 	    "file" : {
 	      "icon" : "<?php echo $this->baseUrl('/public/img/images/file.png')?>"
 	    }
 	    },
 	    "plugins" : [ "state", "types" ]
    });
  });
</script>
<div id="jstree" style="width:20%;; height:100%; float:left; overflow-x : auto;"></div>
<div style="width:80%; height:100%; float:left;margin-bottom:110px">
<div style="display:none;">
<?php
echo $this->formparam; 
?>
</div>
</div>