<script type="text/javascript">
$(function(){
    // 6 create an instance when the DOM is ready
    $('#jstree').jstree({ 'core' : {
      'data' :
    	<?php
    		echo $this->tree;
    	?>
    },
    "types" : {
 	      "root" : {
 	        "icon" : "<?php echo $this->basePath('/img/images/tree-icon.png')?>"
 	      },
 	    "folder" : {
 	        "icon" : "<?php echo $this->basePath('/img/images/folder.ico')?>"
 	      },
 	    "file" : {
 	      "icon" : "<?php echo $this->basePath('/img/images/file.png')?>"
 	    }
 	    },
 	    "plugins" : [ "state", "types" ]
    });
    $( "input:checkbox:checked" ).val();
  });
</script>
<script>
	$('#textContent').css({ color: "#FFFFFF"});
</script>
<script>

function linkContent(idc){
	$("#paramform").attr("action","<?php echo $this->basePath('/contents/contents'); ?>");
	$('#id_topic_content').val(idc);
    document.paramform.submit();
}
function linkContentTopic(id){
	$("#paramform").attr("action","<?php echo $this->basePath('/topics/index'); ?>");
    $('#id_topic_content').val(id);
    document.paramform.submit();
}
function parentLink(){
	window.location.href = "<?php echo $this->basePath('/usermanual/index') ?>";
}


function getBack(){
    javascript:history.back();
}
function validatorForm(){
    if($('#topic_name').val() == ''){
        alert("Debes escribir el nombre del elemento.");
        return false;
    }
    return true;
}
</script>

<?php
	$paramform		= $this->formparam;
	$form			= $this->form;
	
	$paramformLabel	= $this->plugin('formLabel');
	echo $this->form()->openTag($paramform);
?>
<div class="container-responsive">
	<div class="row">
		<div class="col-md-4"><h3>CETEC</h3></div>
		<div id="mensajes" class="col-md-6 col-md-offset-2"></div>
	</div>
	
	<div id="overflow" class="">
		<!-- <div id="mensajes" class=""></div> -->
		
		<div id="jstree"  class="col-md-3" style="overflow-x: auto; overflow-y: auto;  max-height: 500px;"></div>
		
		<div class="col-md-9">
			<div id="textContent">
				<div class="wrap2">
					<?php
					if(isset($this->errorMessage)){
						echo $this->errorMessage;
					}
					?>
					<form method="post" name="updateTopic" id="updateTopic" onsubmit="return validatorForm()" action="#">
						<div class="col-md-9 col-md-offset-3" >
							<h1 align="center">Actualizar elemento</h1>
							</br>
							</br>
						</div>
						<div style="display: none;">
								<?php 
	// 								echo $this->form->id_topic;
									echo $this->formElement($paramform->get('id_topic'));
									echo $this->formElement($paramform->get('id_topic_add'));
									echo $this->formElement($paramform->get('id_topic_content'));
								?>
						</div>
						<div class="col-md-12">
							<div class="col-md-6">
									<?php 
										echo $this->formElement($form->get('topic_name'));
		// 									echo $this->form->topic_name; 
									?>
							</div>
							<div class="col-md-6">
									<?php 
											echo $this->formElement($form->get('type'));
		// 									echo $this->form->type; 
									?>
							</div>
							</br>
							</br>
							</br>
							</br>
						</div>
						<div class="col-md-12">
							<div class="col-md-6">
									<?php 
											echo $this->formElement($form->get('Guardar'));
		// 									echo $this->form->Guardar; 
									?>
							</div>
							<div class="col-md-6">
									<?php 
											echo $this->formElement($form->get('Cancelar'));
		// 									echo $this->form->Cancelar; 
									?>
							</div>
						</div>
					</form>
				</div>
			</div>
		</div>
	</div>
</div>
<?php 
	echo $this->form()->closeTag(); 
?>