<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'Robot\Module'                        => __DIR__ . '/Module.php',
    'Robot\Controller\CustomersController' => __DIR__ . '/src/Robot/Controller/CustomersController.php',
    'RobotTest\Framework\TestCase'        => __DIR__ . '/tests/Robot/Framework/TestCase.php',
    'RobotTest\SampleTest'                => __DIR__ . '/tests/Robot/SampleTest.php',
);
