<form role="form" id="formEditDeparment" method="post">
	<input type="hidden" name="id_deparment"/>
	<div class="form-group">
	    <label for="">Nombre</label>
	    <input type="text" name="name_cash" class="form-control input-lg" placeholder="Nombre" onkeypress="return event.keyCode!= 13">
	</div>
	  				
	<div class="form-group">
		<label for="">Descripci&oacute;n</label>
		<textarea name="description_cash" class="form-control input-lg" rows="3"></textarea>
	</div>  
</form>
						
						