<script src="<?php echo $this->basePath()."/public/js/cash.js";?>"></script>

<div class="panel panel-danger">
	<div class="panel-heading">
		<h3 class="panel-title">Caja</h3>
	</div>
	<div class="panel-body">
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>Clave</th>
					<th>Nombre</th>
					<th>Saldo</th>
					<th>Descripci&oacute;n</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->cash as $i) : ?>
				<tr>
					<td><?php echo $i['id_cash']; ?></td>
					<td><?php echo $i['name_cash']; ?></td>
					<td><?php echo $i['amount']; ?></td>
					<td><?php echo $i['description']; ?></td>
					<td>
						<button type="button" class="btn btn-primary modal-edit-cash" data-toggle="modal" data-target="#modalEditCash" data-backdrop="static" data-keyboard="false">
					  		<span class="glyphicon glyphicon-pencil"></span>
						</button>
					</td>
					<td><a href="<?php echo $this->basePath()."/expenses/delete/".$i['idExpenses'];?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalEditCash" tabindex="-1" role="dialog" aria-labelledby="myModalEditCash" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header modal-back-blue-header">
        		<button type="button" class="close" data-dismiss="modal"><span aria-hidden="true">&times;</span><span class="sr-only">Close</span></button>
        		<h4 class="modal-title" id="myModalLabel">Modificar Caja</h4>
      		</div><!-- end modal-header -->
      		<div class="modal-body" id="modal-body-cash">
				
      		</div><!-- end .modal-body -->
      		<div class="modal-footer modal-back-blue-footer">
      			<button type="button" id="buttonEditCash" class="btn btn-primary">Guardar</button>
        		<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      		</div>
    	</div>
	</div>
</div><!-- end modal edit cash -->

<script>
var $basePath = "<?php echo $this->basePath(); ?>";
</script>