<div class="breadcrumbs">
	<div class="container">
	    <div style="font-size: 30px; vertical-align:middle; float:left; line-height: 38px" class="col-align-left fredoka-one blanco">
	   		<div class="btn-group" style="margin-top:-9px;">
        		<button type="button" data-toggle="dropdown" class="btn btn-default dropdown-toggle">
       				<span class="glyphicon glyphicon-th-list"></span>
        		</button>

        		<ul class="dropdown-menu" role="menu">
            		<li><a href="#"><span class="glyphicon glyphicon-envelope"></span> Action 1</a></li>
            		<li><a href="#"><span class="glyphicon glyphicon-cloud"></span> Action 2</a></li>
            		<li><a href="#"><span class="glyphicon glyphicon-music"></span> Action 3</a></li>
        		</ul>
    		</div> Monitoreo
	    </div>
	    <div style="vertical-align:middle; float:right; line-height: 38px" class="col-align-right">
	    	<div class="btn-group btn-breadcrumb">
		    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
		        <a href="#" class="btn btn-default">Horus</a>
		        <a href="#" class="btn btn-default">Sistema</a>
		        <a href="#" class="btn btn-default">Monitoreo</a>
			</div>
	    </div>
	    <div style="clear: both;"></div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->