<link rel="stylesheet" href="<?php echo $this->basePath() . '/public/Infini/bsa_styles.css';?>">
<script src="<?php echo $this->basePath() . '/public/Infini/ga.js';?>" async="" type="text/javascript"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/public/Infini/.jquery-1.js';?>"></script>
<script type="text/javascript" src="<?php echo $this->basePath() . '/public/Infini/bsa.js';?>"></script>



<style>
	body{ margin:0px; }

	#wrapper{
		width:600px;
		margin:auto;
	}
	.spacer{
		clear:both;
		height:5px;
	}
	.txtarea{
		font-size:18px;
		height:50px;
		width:100%;
	}
	#postswrapper{
		border-bottom:1px dotted #555555;
	}
	.item{
		border-top:1px dotted #555555;
		padding:10px 5px;
		font-size: 16px;
	}
	.item:hover{
		background:#EFEFEF;
	}
	#newpostlink{
		display:block;text-align:center;border:2px solid #414141;background:#7D7D7D;color:#fff; margin: 0 0 10px;padding:5px; -moz-border-radius: 5px; -webkit-border-radius: 5px; border-radius: 5px;font-size:20px;text-decoration:none;
	}
</style>


<div style="display:inline-block;width:100%;padding:10px;background-color:#FFFFFF">
<a href="http://www.jquery4u.com/tutorials/jquery-infinite-scrolling-demos/">< Back to tutorial page</a>
</div>

	<div id="wrapper">
		<div id="postswrapper">

		<p style="font-size:28px">Infinite Scroll Demo 2</p>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>


<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.<p>
</div>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>

<div class="item">
<p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod
tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam,
quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo
consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse
cillum dolore eu fugiat nulla pariatur. Excepteur sint occaecat cupidatat non
proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
</div>
		</div>

		<div id="loadmoreajaxloader" style="display:none;"><center><img src="ajax-loader.gif" /></center></div>

	</div>

<div id="footer" style="display:inline-block;width:100%;padding:10px;background-color:#FFFFFF">
<p>Copyright <a target="_blank" href="http://www.jquery4u.com">jQuery4u.com</a> 2011</p>
</div>

 <form>
 <input id="mate" type="text" value="1">
</form>

<script src="<?php echo $this->basePath() . '/public/Infini/script.js';?>"></script>

<script type="text/javascript">
	var basep="<?php echo $this->basePath();?>";
	$(window).scroll(function(){
	    if($(window).scrollTop() == $(document).height() - $(window).height()){
	    	$('div#loadmoreajaxloader').show();
			var baseurl = basep+'/student/thesis/loader';
			$.ajax({
			type: "POST",
			data: {'id' : $("#mate").val()},
			url: baseurl,
				success: function(html){

					//console.log(html[1]);

					if(html){
						
						$("#postswrapper").append(html);
						$('div#loadmoreajaxloader').hide();
						$('#mate').val(html[0]);
					}else{
						$('div#loadmoreajaxloader').html('<center>No more posts to show.</center>');
					}
				}
			});
	    }
	});
</script>