<!DOCTYPE html>
<html lang="en"><head>
<meta http-equiv="content-type" content="text/html; charset=UTF-8">
  <meta charset="utf-8">

  <title>Infinite Scroll Demo 1 - jQuery4u</title>

  <meta http-equiv="X-UA-Compatible" content="IE=edge,chrome=1">
  <!--[if lt IE 9]><script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script><![endif]-->

  <link rel="stylesheet" href='<?php echo $this->basePath() . "/public/InfiniteScroll/style.css";?>'>

  <!-- scripts at bottom of page -->

<!-- BuySellAds Ad Code -->
<script src='<?php echo $this->basePath() . "/public/InfiniteScroll/ga.js";?>' async="" type="text/javascript"></script><script type="text/javascript">
(function(){
  var bsa = document.createElement('script');
     bsa.type = 'text/javascript';
     bsa.async = true;
     bsa.src = 'http://s3.buysellads.com/ac/bsa.js';
  (document.getElementsByTagName('head')[0]||document.getElementsByTagName('body')[0]).appendChild(bsa);
})();
</script><script src='<?php echo $this->basePath() . "/public/InfiniteScroll/bsa.js";?>' async="" type="text/javascript"></script>
<!-- End BuySellAds Ad Code -->


<script async="async" src='<?php echo $this->basePath() . "/public/InfiniteScroll/s_ea957971a5e1fed9f25dd8e7a8b9f59e.js";?>' id="_bsap_js_ea957971a5e1fed9f25dd8e7a8b9f59e" type="text/javascript"></script></head>
<body class="demos">

  <!-- BuySellAds Zone Code -->
<div id="bsap_1285666" class="bsap_1285666 bsap"></div>
<!-- End BuySellAds Zone Code -->

    

  <section id="content">

      <h1>Demo memoria 1</h1>

<div style="position: relative; height: 1366px;" id="container" class="transitions-enabled infinite-scroll clearfix masonry">

  <div style="position: absolute; top: 5px; left: 5px;" class="box col3 masonry-brick">
    <p>
      <a href="http://www.flickr.com/photos/nemoorange/3318887645/" title="Clarendon Metro by nemoorange, on Flickr"><img src='<?php echo $this->basePath() . "/public/InfiniteScroll/3318887645_1f33364338.jpg";?>' alt="Clarendon Metro"></a>
    </p>
  </div>

  <div style="position: absolute; top: 5px; left: 305px;" class="box col1 masonry-brick">
    <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
  </div>

  <div style="position: absolute; top: 5px; left: 405px;" class="box col2 masonry-brick">
    <p>
      <a href="http://www.flickr.com/photos/nemoorange/3319714470/" title="Whitlow's on Wilson by nemoorange, on Flickr"><img src='<?php echo $this->basePath() . "/public/InfiniteScroll/3319714470_c05a5cb5a8_m.jpg";?>' alt="Whitlow's on Wilson"></a>
    </p>
  </div>


  <div style="position: absolute; top: 5px; left: 605px;" class="box col1 masonry-brick">
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
  </div>

  <div style="position: absolute; top: 5px; left: 705px;" class="box col1 masonry-brick">
    <h2>Sit amet mi ullamcorper vehicula</h2>
  </div>

  <div style="position: absolute; top: 5px; left: 805px;" class="box col1 masonry-brick">
    <p>adipiscing in, lacinia vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus.</p>
  </div>

  <div style="position: absolute; top: 144px; left: 605px;" class="box col5 masonry-brick">

    <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do 
eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad 
minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip 
ex ea commodo consequat. Duis aute irure dolor in reprehenderit in 
voluptate velit esse cillum dolore eu fugiat nulla pariatur. Excepteur 
sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt
 mollit anim id est laborum.</p>

    <h2>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua.</h2>

  </div>

  <div style="position: absolute; top: 156px; left: 305px;" class="box col3 masonry-brick">
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>
    <p>Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla pariatur.</p>
    <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

  </div>

  <div style="position: absolute; top: 222px; left: 5px;" class="box col2 masonry-brick">
    <p>Sit amet mi ullamcorper vehicula</p>
  </div>

  <div style="position: absolute; top: 5px; left: 1105px;" class="box col1 masonry-brick">
    <p>Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
  </div>

  <div style="position: absolute; top: 268px; left: 5px;" class="box col2 masonry-brick">
    <p>Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est 
sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus 
nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing 
lacus. Donec metus. Curabitur gravida.</p>
    <p>Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
  </div>

  <div style="position: absolute; top: 294px; left: 605px;" class="box col3 masonry-brick">

    <p>Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, 
lectus arcu pulvinar risus, vitae facilisis libero dolor a purus. Sed 
vel lacus. Mauris nibh felis, adipiscing varius, adipiscing in, lacinia 
vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus. 
Nunc tellus ante, mattis eget, gravida vitae, ultricies ac, leo. Integer
 leo pede, ornare a, lacinia eu, vulputate vel, nisl.</p>
  </div>

  <div style="position: absolute; top: 113px; left: 1105px;" class="box col1 masonry-brick">
    <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
  </div>

  <div>
    <div style="position: absolute; top: 294px; left: 905px;" class="box col2 masonry-brick">
      <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
      <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    </div>

    <div style="position: absolute; top: 343px; left: 205px;" class="box col2 masonry-brick">
      <p>Sit amet mi ullamcorper vehicula</p>
    </div>

    <div style="position: absolute; top: 313px; left: 1105px;" class="box col1 masonry-brick">
      <p>Morbi purus libero</p>
    </div>

    <div style="position: absolute; top: 343px; left: 405px;" class="box col1 masonry-brick">
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec
 odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
    </div>

    <div style="position: absolute; top: 413px; left: 905px;" class="box col3 masonry-brick">
      <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. Aenean dignissim pellentesque felis.</p>
      <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
      <ul>
        <li>Lacus a ultrices sagittis</li>
        <li>Democratis</li>
        <li>Plummus</li>
      </ul>
    </div>


    <div style="position: absolute; top: 343px; left: 505px;" class="box col1 masonry-brick">
      <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    </div>

    <div style="position: absolute; top: 389px; left: 205px;" class="box col1 masonry-brick">
      <p>Sit amet mi ullamcorper vehicula</p>
    </div>

    <div style="position: absolute; top: 389px; left: 305px;" class="box col1 masonry-brick">
      <h2>Morbi purus libero</h2>
    </div>


    <div style="position: absolute; top: 433px; left: 605px;" class="box col2 masonry-brick">
      <p>Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est
 sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus 
nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing 
lacus. Donec metus. Curabitur gravida.</p>
      <p>Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
    </div>

    <div style="position: absolute; top: 433px; left: 805px;" class="box col1 masonry-brick">
      <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula</p>
    </div>

    <div style="position: absolute; top: 466px; left: 5px;" class="box col3 masonry-brick">
      <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
      <p>Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, 
lectus arcu pulvinar risus, vitae facilisis libero dolor a purus. Sed 
vel lacus. Mauris nibh felis, adipiscing varius, adipiscing in, lacinia 
vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus. 
Nunc tellus ante, mattis eget, gravida vitae, ultricies ac, leo. Integer
 leo pede, ornare a, lacinia eu, vulputate vel, nisl.</p>
      <p>Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, 
lectus arcu pulvinar risus, vitae facilisis libero dolor a purus. Sed 
vel lacus. Mauris nibh felis, adipiscing varius, adipiscing in, lacinia 
vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus. 
Nunc tellus ante, mattis eget, gravida vitae, ultricies ac, leo. Integer
 leo pede, ornare a, lacinia eu, vulputate vel, nisl.</p>
    </div>


    <div style="position: absolute; top: 451px; left: 305px;" class="box col1 masonry-brick">
      <p>adipiscing in, lacinia vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus.</p>
    </div>

    <div style="position: absolute; top: 574px; left: 805px;" class="box col4 masonry-brick">
      <p>Lorem ipsum dolor sit amet, consectetur adipisicing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. </p>


      <p>Ut enim ad minim veniam, quis nostrud exercitation ullamco 
laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor 
in reprehenderit in voluptate velit esse cillum dolore eu fugiat nulla 
pariatur. </p>
      <p>Excepteur sint occaecat cupidatat non proident, sunt in culpa qui officia deserunt mollit anim id est laborum.</p>

    </div>


    <div style="position: absolute; top: 620px; left: 305px;" class="box col2 masonry-brick">
      <p>Sit amet mi ullamcorper vehicula</p>
    </div>

    <div style="position: absolute; top: 482px; left: 505px;" class="box col1 masonry-brick">
      <p>Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
    </div>

    <div style="position: absolute; top: 590px; left: 505px;" class="box col1 masonry-brick">
      <h2>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </h2>
    </div>

    <div style="position: absolute; top: 629px; left: 605px;" class="box col2 masonry-brick">
      <p>Ut convallis, sem sit amet interdum consectetuer, odio augue aliquam leo, nec dapibus tortor nibh sed augue.</p>
      <p>Ut condimentum mi vel tellus. Suspendisse laoreet. Fusce ut est
 sed dolor gravida convallis. Morbi vitae ante. Vivamus ultrices luctus 
nunc. Suspendisse et dolor. Etiam dignissim. Proin malesuada adipiscing 
lacus. Donec metus. Curabitur gravida.</p>
    </div>

    <div style="position: absolute; top: 666px; left: 305px;" class="box col1 masonry-brick">

      <ul>
        <li>Lacus a ultrices sagittis</li>
        <li>Democratis</li>
        <li>Plummus</li>
      </ul>
    </div>

    <div style="position: absolute; top: 735px; left: 805px;" class="box col3 masonry-brick">
      <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. 
Phasellus hendrerit. Pellentesque aliquet nibh nec urna. In nisi neque, 
aliquet vel, dapibus id, mattis vel, nisi. Sed pretium, ligula 
sollicitudin laoreet viverra, tortor libero sodales leo, eget blandit 
nunc tortor eu nibh. Nullam mollis. Ut justo. Suspendisse potenti.</p>
      <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
      <p>Morbi interdum mollis sapien. Sed ac risus. Phasellus lacinia, 
magna a ullamcorper laoreet, lectus arcu pulvinar risus, vitae facilisis
 libero dolor a purus.</p>
    </div>

    <div style="position: absolute; top: 753px; left: 405px;" class="box col2 masonry-brick">
      <p>adipiscing in, lacinia vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus.</p>
      <p>Ut convallis, sem sit amet interdum consectetuer, odio augue 
aliquam leo, nec dapibus tortor nibh sed augue.  Sed vel lacus. Mauris 
nibh felis, adipiscing varius, adipiscing in, lacinia vel, tellus. 
Suspendisse ac urna. Etiam pellentesque mauris ut lectus. Nunc tellus 
ante, mattis eget, gravida vitae, ultricies ac, leo. Integer leo pede, 
ornare a, lacinia eu, vulputate vel, nisl.</p>
    </div>


    <div style="position: absolute; top: 735px; left: 1105px;" class="box col1 masonry-brick">
      <p>Phasellus pede arcu, dapibus eu, fermentum et, dapibus sed, urna.</p>
    </div>

    <div style="position: absolute; top: 774px; left: 305px;" class="box col1 masonry-brick">
      <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula</p>
    </div>

    <div style="position: absolute; top: 781px; left: 5px;" class="box col3 masonry-brick">
      <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
      <p>Sed ac risus. Phasellus lacinia, magna a ullamcorper laoreet, 
lectus arcu pulvinar risus, vitae facilisis libero dolor a purus. Sed 
vel lacus. Mauris nibh felis, adipiscing varius, adipiscing in, lacinia 
vel, tellus. Suspendisse ac urna. Etiam pellentesque mauris ut lectus. 
Nunc tellus ante, mattis eget, gravida vitae, ultricies ac, leo. Integer
 leo pede, ornare a, lacinia eu, vulputate vel, nisl.</p>
    </div>


  </div>

  <div style="position: absolute; top: 843px; left: 1105px;" class="box col1 masonry-brick">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec 
odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
  </div>

  <div style="position: absolute; top: 856px; left: 605px;" class="box col1 masonry-brick">
    <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
  </div>

  <div style="position: absolute; top: 856px; left: 705px;" class="box col1 masonry-brick">
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
  </div>

  <div style="position: absolute; top: 957px; left: 805px;" class="box col2 masonry-brick">
    <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
  </div>

  <div style="position: absolute; top: 913px; left: 305px;" class="box col1 masonry-brick">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec 
odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
  </div>

  <div style="position: absolute; top: 957px; left: 1005px;" class="box col1 masonry-brick">
    <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
  </div>

  <div style="position: absolute; top: 977px; left: 5px;" class="box col1 masonry-brick">
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
  </div>

  <div style="position: absolute; top: 977px; left: 105px;" class="box col2 masonry-brick">
    <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
  </div>

  <div style="position: absolute; top: 995px; left: 605px;" class="box col1 masonry-brick">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec 
odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
  </div>

  <div style="position: absolute; top: 995px; left: 705px;" class="box col1 masonry-brick">
    <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
  </div>

  <div style="position: absolute; top: 1011px; left: 405px;" class="box col1 masonry-brick">
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
  </div>

  <div style="position: absolute; top: 1120px; left: 1005px;" class="box col2 masonry-brick">
    <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
  </div>

  <div style="position: absolute; top: 1011px; left: 505px;" class="box col1 masonry-brick">
    <p>Lorem ipsum dolor sit amet, consectetuer adipiscing elit. Donec 
odio. Quisque volutpat mattis eros. Nullam malesuada erat ut turpis. 
Suspendisse urna nibh, viverra non, semper suscipit, posuere a, pede.</p>
  </div>

  <div style="position: absolute; top: 1116px; left: 5px;" class="box col1 masonry-brick">
    <p>Donec nec justo eget felis facilisis fermentum. Aliquam porttitor mauris sit amet orci. </p>
  </div>

  <div style="position: absolute; top: 1134px; left: 705px;" class="box col1 masonry-brick">
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
  </div>

  <div style="position: absolute; top: 1164px; left: 805px;" class="box col2 masonry-brick">
    <p>Vestibulum volutpat, lacus a ultrices sagittis,</p>
    <p>Fusce accumsan mollis eros. Pellentesque a diam sit amet mi ullamcorper vehicula  </p>
    <p>Morbi purus libero, faucibus adipiscing, commodo quis, gravida 
id, est. Sed lectus. Praesent elementum hendrerit tortor. Sed semper 
lorem at felis.</p>
  </div>

</div> <!-- #container -->

<nav id="page-nav">
  <a href='<?php echo $this->basePath() . "/public/InfiniteScroll/pages/2.html";?>'></a>
</nav>

<script src='<?php echo $this->basePath() . "/public/InfiniteScroll/jquery-1.js";?>'></script>
<script src='<?php echo $this->basePath() . "/public/InfiniteScroll/jquery_002.js";?>'></script>
<script src='<?php echo $this->basePath() . "/public/InfiniteScroll/jquery.js";?>'></script>
<script>
  $(function(){

    var $container = $('#container');

/*    $container.imagesLoaded(function(){
      $container.masonry({
        itemSelector: '.box',
        columnWidth: 100
      });
    });
*/
    $container.infinitescroll({
      navSelector  : '#page-nav',    // selector for the paged navigation
      nextSelector : '#page-nav a',  // selector for the NEXT link (to page 2)
      itemSelector : '.box',     // selector for all items you'll retrieve
      loading: {
          finishedMsg: 'No more pages to load.',
          img: 'http://i.imgur.com/6RMhx.gif'
        }
      });
      // trigger Masonry as a callback
/*      function( newElements ) {
        // hide new items while they are loading
        var $newElems = $( newElements ).css({ opacity: 0 });
        // ensure that images load before adding to masonry layout
        $newElems.imagesLoaded(function(){
          // show elems now they're ready
          $newElems.animate({ opacity: 1 });
          $container.masonry( 'appended', $newElems, true );
        });
      }*/
  /*  );*/

  });
</script>

  </section> <!-- #content -->


<div id="footer" style="display:inline-block;width:100%;padding:10px;background-color:#FFFFFF">

<p>Copyright <a target="_blank" href="http://www.jquery4u.com/">jQuery4u.com</a> 2011</p>
</div>

<script src='<?php echo $this->basePath() . "/public/InfiniteScroll/script.js";?>'></script>




</body></html>
