<script type="text/javascript">

 //   alert("dadad");
    console.log("dadaas");
 </script>


   <!-- portfolio -->
    <section id="portfolio" class="box">
        <div class="container">
            <div class="panel">
                <div class="row-fluid">
                    <div class="span12 header portfoliobg">
                        <hgroup>
                            <h2>UTN xxx 22 gabbb</h2>
                        </hgroup>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12 content">

                        <ul class="portfolio">
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg1.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb1.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg2.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb2.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg3.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb3.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                        </ul>

                        <ul class="portfolio">
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg4.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb4.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg5.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb5.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg1.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb1.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                        </ul>

                        <ul class="portfolio">
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg2.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb2.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name gabo</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg3.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb3.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                            <li class="span4">
                                <div class="item">
                                    <a href="<?php echo $this->basePath() . '/public/architex/img/bg4.jpg';?>" class="lightbox_trigger">
                                        <img src="<?php echo $this->basePath() . '/public/architex/img/tb4.jpg';?>" alt="" />
                                    </a>
                                    <h3>Project name</h3>
                                    <p>project description here</p>
                                </div>
                            </li>
                        </ul>

                    </div>
                </div>
            </div>
        </div>
    </section>

    <!-- contact -->
    <section id="contact" class="box">
       <div class="container">
            <div class="panel">
                <div class="row-fluid">
                    <div class="span12 header contactsbg">
                        <hgroup>
                            <h2>Contact</h2>
                        </hgroup>
                    </div>
                </div>
                <div class="row-fluid">
                    <div class="span12 content">
                        <div class="row-fluid">
                            <div class="span6">
                                <!-- googlemaps -->
                                <div id="map_canvas"></div>
                            </div>
                            <div class="span6">
                                <form>
                                    <fieldset>
                                        <div class="control-group">
                                            <div class="controls">
                                                <input class="span12" type="text" placeholder="Your Full Name">
                                            </div>
                                            <div class="controls">
                                                <input class="span12" type="text" placeholder="Your Email">
                                            </div>          
                                            <div class="controls">
                                                <input class="span12" type="text" placeholder="Message Subject">
                                            </div>
                                            <div class="controls">
                                                <textarea class="span12" id="textarea" rows="6" placeholder="Your Message"></textarea>
                                            </div>
                                            <button class="btn btn-default">Send Message</button>
                                        </div>
                                    </fieldset>
                                </form>
                            </div>
                        </div>
                </div>
            </div>
        </div>
    </section>

    <!-- ligthbox -->
    <div style="display: none;" id="lightbox"><img id="bigimg" src="" /></div>
    <!--Footer -->
    <footer class="footerfixed">
       <div class="container">
           <div class="copyright"><a href="#">ModernCottage.</a> Copyright 2013</div>
           <div class="social-container pull-right">

               <a title="test" data-placement="top" data-toggle="tooltip" data-original-title="Google Plus" class="s-icon-gplus" href="#"></a>
               <a class="s-icon-skype" href="#"></a>
               <a class="s-icon-stumbleupon" href="#"></a>
               <a class="s-icon-addthis" href="#"></a>
               <a class="s-icon-appstore" href="#"></a>
               <a class="s-icon-deviantart" href="#"></a>
               <a class="s-icon-digg" href="#"></a>
               <a class="s-icon-facebook" href="#"></a>
               <a class="s-icon-twitter" href="#"></a>
               <a class="s-icon-youtube" href="#"></a>
               <a class="s-icon-vimeo" href="#"></a>
               <a class="s-icon-wp" href="#"></a>
               <a class="s-icon-rss" href="#"></a>
               <a class="s-icon-pinterest" href="#"></a>
           </div>
       </div>
    </footer>