<h3 class="western" style="margin-right: -0in"><font color="#000066"><i>QUÍMICA</i></font></h3>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
primera pregunta a contestar es: ¿de qué está hecho el hombre y
cómo está hecho?</font><font face="Century Schoolbook, serif"> </font></font>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
hombre se toca, toca a los demás, toca las cosas, las plantas, a los
animales, la tierra, etc. Se ve y ve a los demás. Se da cuenta
que existen, que tienen forma, que tienen peso, que ocupa un
lugar en el espacio. Que oponen resistencia, que se mueven, que
tienen color y olor, tamaños, grande, chico, y microscópico.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Entonces,
nos damos cuenta de que somos </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Materia"><font face="Century Schoolbook, serif"><i><b>materia</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
Entonces queremos saber, ¿qué es la materia? ¿Cuál es su
comportamiento? De esta manera estamos ante el estudio de
la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Quimica"><font face="Century Schoolbook, serif"><i><b>química</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=w1XQZAGZ4D4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=ZPWtPDTW4qY"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=loLK1MvxkDE"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=HRbOTMnvAlU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
01</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=oCsd_iAbJ2g&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
02</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=K1gAtKUIoTE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
03</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=38Qw_D3ISZ4&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
04</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=ADyVqCj5ScQ&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
05</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-  </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=mCRTeO7gPNE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
06</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=rjycK1azlgE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
07</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
- </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=PRusscEIvUY&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
08</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=I_WUVdahA8c&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
09</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=64TT7n56dVQ&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
10</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=BuThjYMLpCc&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
11</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=te5EKp11Keg&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
12</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=te5EKp11Keg&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
13</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-  </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=5zpx1L2l1-I&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
14-1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=YCE4bXyfS3o&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
14-2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
-</font></font><font face="Century Schoolbook, serif"> </font><font face="Century Schoolbook, serif">P</font><font face="Century Schoolbook, serif">or
lo tanto, todo es química. Diario hacemos química. Hablamos de
química cuando decimos que estamos gordos, que tenemos mucha grasa.
Que debemos tomar vitaminas, que hay que hacer dietas con bajas
calorías; que respiramos oxígeno y que exhalamos bióxido de
carbono. Que el agua sabe a cloro, porque se lo ponemos para eliminar
microorganismos. Que el excremento son los desechos de la comida. Que
a una persona le duelen las articulaciones por el ácido úrico. Que
se tienen agruras y siente que se le quema la garganta. Que el doctor
receta medicinas para la gripe o para el dolor, etc. Todo es química.
De ahí la importancia de su estudio.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Materia"><font face="Century Schoolbook, serif"><i><b>materia</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=uNVHJKl3DiI&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
-</font></font><font face="Century Schoolbook, serif"> </font><font face="Century Schoolbook, serif">es
cualquier cosa que ocupa un espacio y tiene </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Masa"><font face="Century Schoolbook, serif"><i><b>masa</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
La </font><font face="Century Schoolbook, serif"><i><b>masa</b></i></font><font face="Century Schoolbook, serif">
es la propiedad de la materia que determina su </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Coeficiente_de_rodadura"><font face="Century Schoolbook, serif"><i><b>resistencia</b></i></font></a></u></span></font><font color="#0000ff"><font face="Century Schoolbook, serif"><i><b>,</b></i></font></font><font face="Century Schoolbook, serif">
o</font><font face="Century Schoolbook, serif"> dureza, su
blandura; así como su resistencia a ponerse en movimiento o un
cambio. Por ejemplo: un coche tiene materia, es duro, pesa
mucho, por lo tanto, presenta mucha resistencia para empujarlo.
Lo mismo sucede con una persona. Si es un niño pequeño no presenta
mucha resistencia para cargarlo. Pero si es una persona grande y
gorda, cuesta mucho cargarlo porque presenta mucha resistencia.
Así hay miles y miles de ejemplos. Con esto podemos comprender
qué es la materia, la masa, la resistencia y qué es la química.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
