<span class="botReturn">
    <a href="/clock/index">
        <img style="opacity:0.4;filter:alpha(opacity=40);width: 50px; height: 50px; text-align: right;" 
             onmouseover="this.style.opacity=1;this.filters.alpha.opacity=100" 
             onmouseout="this.style.opacity=0.4;this.filters.alpha.opacity=40" 
             src="<?php echo $this->baseUrl('/public/img/returnIOF.png') ?>" title="Regresar al men&uacute; anterior">
    </a>
</span>

<div class="imgpdf"><h1>Debes registrar una salida</h1></div>


