<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 40 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>BACHILLERATO  5° Trimestre</title>
	<meta name="generator" content="LibreOffice 4272 (Linux)">
	<meta name="author" content="Educación con Vida, para la Vida">
	<meta name="created" content="20141105;135200000000000">
	<meta name="changedby" content="Rossy CG">
	<meta name="changed" content="20141105;140500000000000">
	<style type="text/css">
	<!--
		@page { size: 827in 1169in; margin-left: 118in; margin-right: 098in; margin-top: 049in; margin-bottom: 049in }
		@page:first { margin-top: 158in; margin-bottom: 049in }
		p { margin-bottom: 01in; direction: ltr; color: #00000a; line-height: 120%; text-align: left; widows: 2; orphans: 2 }
		pwestern { font-family: "Calibri", serif; font-size: 11pt; so-language: es-MX }
		pcjk { font-family: "Droid Sans Fallback"; font-size: 11pt; so-language: es-MX }
		pctl { font-family: ; font-size: 11pt; so-language: ar-SA }
		h1 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h1western { font-family: "Century Schoolbook", serif; font-size: 16pt; so-language: es-MX }
		h1cjk { font-family: "Times New Roman"; font-size: 16pt; so-language: es-ES }
		h1ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		h6 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h6western { font-family: "Times New Roman", serif; font-size: 26pt; so-language: es-MX }
		h6cjk { font-family: "Times New Roman"; font-size: 26pt; so-language: es-ES }
		h6ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		a:link { color: #0000ff; so-language: zxx }
	-->
	</style>
</head>
<body lang="es-MX" text="#00000a" link="#0000ff" dir="ltr">
<h1 class="western"><a name="INDICETEMAXII"></a><font color="#000066"><font size="6" style="font-size: 22pt"><i>INDICE
– TEMA XII</i></font></font></h1>
<p class="western" align="justify" style="margin-bottom: 014in; line-height: 115%">
<br><br>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#HISTORIA"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">HISTORIA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
          </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#INDEPENDENCIA"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">INDEPENDENCIA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
          </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#_ADOLFO_DE_LA"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ADOLFO
DE LA HUERTA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
        </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#ÁLVAROOBREGÓN"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ÁLVARO
OBREGÓN</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
          </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#PLUTARCOELÍASCALLES"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">PLUTARCO
ELÍAS CALLES</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
          </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#EMILIOPORTESGIL"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">EMILIO
PORTES GIL</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
          </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#PASCUALORTÍZRUBIO"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">PASCUAL
ORTIZ RUBIO</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#ABELARDORODRÍGUEZ"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ABELARDO
L RODRÍGUEZ</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
        </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#LÁZAROCÁRDENAS"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">LÁZARO
CÁRDENAS</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#MANUELAVILACAMACHO"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">MANUEL
ÁVILA CAMACHO</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#MIGUELALEMÁNVALDÉS"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">MIGUEL
ALEMÁN VALDÉS</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#ADOLFORUIZCORTINES"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ADOLFO
RUIZ CORTINES</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#ADOLFOLÓPEZMATEOS"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ADOLFO
LÓPEZ MATEOS</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#GUSTAVODÍAZORDÁZ"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">GUSTAVO
DÍAZ ORDAZ</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#LUISECHEVERRÍAALVAREZ"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">LUIS
ECHEVERRÍA ÁLVAREZ</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#JOSÉLÓPEZPORTILLO"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">JOSÉ
LÓPEZ PORTILLO</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#MIGUELDELAMADRIDHURTADO"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">MIGUEL
DE LA MADRID HURTADO</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#CARLOSSALINASDEGORTARI"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">CARLOS
SALINAS DE GORTARI</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
         </font></font>
</p>
<p class="western" align="justify" style="margin-left: 049in; margin-bottom: 014in; line-height: 115%">
<font color="#0000ff"><span lang="zxx"><u><a href="#ERNESTOZEDILLOPONCEDELEÓN"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">ERNESTO
ZEDILLO PONCE DE LEÓN</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
    </font></font></p>
<h6 class="western" style="line-height: 150%"><br>
</h6>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="HISTORIA"></a>
