<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>HISTORIA</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Debemos
saber que la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Historia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Historia</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
es la nrración de los acontecimientos que hacen referencia a los
seres humanos, y a las sociedades creadas por éstos en el pasado De
la misma manera, es la relación de sucesos políticos y públicos de
los pueblos o de cualquier actividad humana (</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ciencia,
literatura, arte y otros</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">)</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">De
acuerdo a lo anterior, debemos conocer la historia de nuestro país
con interés, análisis, reflexión, comprensión y, sobre todo, la
repercusión en nuestros tiempos, para conocer el inicio y el
por qué de acontecimientos, cual es su evolución, y lo más
importante, qué nos falta por hacer para conseguir el desarrollo
personal, familiar y social, armónico, permanente, con respeto y
justicia; con oportunidades de trabajo, educación, capacitación y
diversión sana Cuando vemos nuestros problemas económicos,
políticos y sociales, como son el desempleo, la drogadicción, la
carestía, la inseguridad, secuestros, divorcios, niños de la calle,
contaminación, funcionarios corruptos, hambruna y desnutrición,
y toda una serie de problemas, debemos echar un vistazo al pasado, a
la historia, y ver qué se ha hecho, qué no se ha hecho, qué ha
fallado, qué se debe hacer para combatir la pobreza intelectual y la
material, que es causa de todos los problemas Debemos preguntarnos,
qué debemos hacer para crear riqueza mental y material que nos
permita enfrentar con éxito los retos que la evolución de la
humanidad va creando Debemos ver lo positivo, lo bueno, las
oportunidades, las experiencias, para tener una base sólida de
conocimiento, de información, que nos permita desarrollar
nuevas habilidades, ser mejores, ser humanos y aprovechar todos los
avances científicos y tecnológicos De ahí, la importancia de la
historia La historia no solo son nombres de héroes y fechas, o de
acontecimientos, solo para memorizarlos Lo importante de la historia
es preguntarnos, por qué existieron esos héroes, qué los hizo
ocupar un lugar especial en la historia Debemos conocer y
preguntarnos, cuáles fueron las causas que originaron esos
movimientos históricos y qué resultados se obtuvieron, cómo nos
han repercutido y qué debemos hacer para aprovechar esos resultados
y cambios o qué nuevos movimientos debemos hacer para que haya
justicia social Sobre todo, con la fuerza de la razón y no con
la razón de la fuerza Con la inteligencia y no con las armas Con
el derecho y no los intereses bastardos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todos
los héroes de México, y del mundo entero, son personajes como
cualquiera de nosotros, con defectos y virtudes, con sentimientos,
pasiones, errores, emociones, excesos, tristezas y alegrías, nada
diferente a cualquiera de nosotros Son héroes porque encabezaron
movimientos reivindicatorios de los derechos de la gente, con ideas,
armas y hechos Los héroes no son semidioses ni personajes míticos,
son seres humanos como cualquiera de nosotros Por eso surgieron, y
además se necesitan nuevos héroes, inclusive los hay, aunque no se
conozcan, que luchan por la democracia, la libertad y la justicia
social Todo se resume en conseguir el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Respeto"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>respeto</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
a los derechos naturales del hombre, que son: </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/La_vida"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
vida</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
libertad</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Propiedad_(derecho)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
propiedad</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Felicidad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
felicidad</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nadie
nos da esos derechos, son derechos naturales que nacen con la
persona Son derechos naturales que deben respetarse por todos los
individuos y las sociedades De ahí la necesidad de conocer la
historia de México y la uni-versal, ya que vivimos un mundo
globalizado  </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Somos
sociedades o pueblos interdependientes en tecnología, ciencia,
eco-nomía, política, alimentación, medicina, informática y tantas
otras actividades que nos hacen complementarios</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="INDEPENDENCIA"></a>
