<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>INDEPENDENCIA</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Veamos
la importancia de la historia del movimiento de </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Independencia_de_México"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>independencia
de México</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=k3aZCP2uVx4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=9ED-cBJvSOc&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">surgido
en una fecha convencional de la madrugada del 16 de septiembre
de 1810 Se dice convencional porque no se inició propiamente dicho
en esa fecha, ya que hubo movimientos menores en fechas anteriores,
inclusive con personajes menos conocidos, pero no por ello menos
importantes</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Estudiemos
la historia con alegría, satisfacción e interés; olvidémonos de
resentimientos, rencores y odios Quitemos de nuestra memoria la
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Xenofobia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>xenofobia</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">:
“aversión hacia la cultura y las tradiciones de otros pueblos o
hacia los extranjeros” Por el contrario, debemos pensar que
somos una mezcla de sangres con otros pueblos, en el caso mexicano,
más sangre española, debido a que fue el encuentro de dos mundos en
el año de 1521; entre españoles y aztecas, así como otras
culturas Son nuestros antepasados, tanto españoles como aztecas
Gracias a ellos existimos nosotros Es verdad que se cometieron
muchos atropellos, injusticias y vejaciones entre ellos Lo mismo
sucederá con nuestros descendientes, de otras generaciones
futuras  </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Seremos
sus antepasados, con defectos y virtudes; pero somos consecuencia
de la misma sociedad</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
españoles y los mexicanos de ese tiempo, crearon sus sistemas de
gobierno de acuerdo a sus costumbres, intereses y, sobre todo,
de la fuerza militar y religiosa El reparto de tierras y riquezas
fue de manera injusta e irracional Se restringieron las libertades y
se disponía de vidas de una manera cruel e irracional La forma de
gobierno era para los poderosos, y los débiles, ocuparon las
posiciones de esclavos Sin embargo, los tiempos, usos y costumbres,
fueron teniendo consecuencias, como la de mezclas de españoles y
mexicanos; españoles con españoles, pero nacidos en México,
que los hacían diferentes de los nacidos en España Hijos de
españoles y mexicanos, que eran otra clase; o de nacidos en
México de españoles con hijos de españoles y mexicanos Así las
diferentes mezclas Los intereses y derechos de las diferentes
clases se empezaron a querer hacer valer Se fueron haciendo cambios,
pero todo se gobernaba desde el imperio español México se había
convertido en un virreinato, no en una colonia, como muchos
historiadores mencionan</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Así
llegamos al siglo XVII; cuando la Nueva España, que así se llamaba
a México, tenía alrededor de 65 millones de habitantes; mismos que
estaban divididos en tres clases: españoles, indios y castas Los
españoles eran los menos, ya que representaban la décima parte
de la población, pero eran los poderosos, los dueños de casi
todas las tierras y riquezas del país, como minas de oro y plata y
otras Además, eran los gobernantes poderosos, junto a los jerarcas
de la iglesia católica, que era la que dominaba y sometía a ricos y
pobres a su causa, para su beneficio Por otro lado, estaban los
llamados indios, que eran los esclavos y trabajadores agropecuarios y
de las minas Y las castas, que se encargaban del comercio en pequeño
y tenían y desarrollaban oficios</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
lo tanto, había intereses opositores y resentimientos, rencores y
odios, entre los poderosos y los sometidos; entre ricos e infames
Había una gran discriminación entre seres humanos debido al color,
la miseria y la ignorancia, con los poderosos que abusaban de su
privilegiada posición Las clases menores no tenían derechos de
educación, ni a tener propiedades; siempre sujetos a su amo y
señor; además, tenían que pagar tributos por la protección que se
les proporcionaba, según los potentados, y además porque
consideraban que México era una colonia que estaba obligada a su
matriz que era el reino español</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos podido observar, el pueblo no era respetado en sus derechos
naturales Su </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Vida"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>vida</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que es el derecho más sagrado de todo ser humano, no era respetada y
se disponía de ella de la manera más cruel, inclusive, con castigos
de la santa inquisición, como el ser ejecutados por gente del clero,
masoquistas y enfermos mentales, ya que no se puede entender que
gente sana mentalmente fuera capaz de sentenciar y ejecutar
acciones de tormento aterrador y muerte cruel La </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Libertad"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>libertad</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que es el otro derecho natural, no se respetaba; ya que eran
esclavizados, no tenían derecho de ir a ninguna parte, ni estudiar,
y menos, trabajar en lo que ellos desearan</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Mucho
menos, tenían el derecho de ser </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Propiedad_(derecho)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>propietarios</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
de tierras, riquezas, bienes, etc, ni la libertad de profesar
la religión que quisieran, sino por obligación, la católica Y
todavía, pagar tributos de la miseria que ganaban y la vida
infrahumana que llevaban</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esto
es interesante saberlo, comprenderlo y reflexionar que estamos en el
siglo XXI</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Y
esa falta de respeto a los derechos sustantivos de los seres humanos
no se da, se restringen y se violan Solo basta analizar las guerras,
las invasiones, las dictaduras, el desempleo, la falta de educación,
la hambruna, la desnutrición, el narcotráfico, la enfermedad,
y tantas otras cosas que suceden en estos años recientes</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
aquellos años de los 1800, había una lucha de intereses en Europa,
principalmente entre Francia, gobernada por </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Napoleon"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Napoleón</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>,
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=JzYkGIaZdjg"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=bXCSKNoGJSE&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=Yc0AZipOp-8&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=OcBA3Ta_j_0&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=m-4Ct5bjq_o&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=3Vh_sB2n3Xc&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
España, cuyo emperador era </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Carlos_IV_de_España"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Carlos
IV</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=FCFgg3m-sjA"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–</b></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
1808, Carlos IV abdica a favor de su hijo el príncipe de Asturias,
quien adopta el nombre de </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Fernando_VII_de_España"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Fernando
VII</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
La sociedad española estaba cansada de la corrupción del gobierno y
la subordinación hacia Napoleón Sin embargo, Napoleón desconfiaba
de la fidelidad de Fernando VII Al poco tiempo, Fernando VII
devuelve el trono a su padre, Carlos IV, quien ya había cedido la
corona a Napoleón Napoleón proclama rey de España a su
hermano José Bonaparte  Alias “Pepe botellas”, a quien le
gustaba beber</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
renuncias de Carlos IV y Fernando VII, provocan desconcierto en las
colonias de América, además de crear inquietud para no reconocer a
los franceses como nuevos amos y gobernantes</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Se
empieza a pensar en independizarse y gobernarse por sí mismos En
México se encontraba como virrey José de Iturrigaray, quien no
sabía qué hacer ante la desaparición de la autoridad legítima,
que eran los monarcas españoles No sabían si reconocer o no a los
nuevos monarcas franceses Pensaban si las renuncias habían sido
obligadas y debían luchar para devolver los mandos a Fernando VII
Pero también existía la duda, de si el virrey Iturrigaray era ahora
legítimo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ante
esa situación se reunieron, en 1808, el virrey, oidores, arzobispos,
canónigos, prelados, inquisidores, jefes de oficina, titulares,
vecinos principales y gobernadores, para tomar decisiones En esa
reunión, el Lic Francisco Primo de Verdad y Ramos, quien era
Síndico del Ayuntamiento, propuso la necesidad de formar un gobierno
provisional y el desconocimiento de las juntas peninsulares, es
decir, independizarse No se tomó en cuenta esta propuesta y se
acordó apoyar al virrey, quien era hombre de extrema confianza de
Fernando VII, a quien decidieron jurar fidelidad El virrey acuerda
no hacer caso a las juntas peninsulares, mientras Fernando VII se
encontrara preso y no reconocía a ninguna autoridad en España</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
España, se empezaron a dar cuenta de las intenciones de
independencia y depusieron al virrey Iturrigaray, haciéndolo
preso junto con sus hijos, a quienes enviaron a la santa inquisición
Fueron detenidos y sometidos a prisión a todos los
independentistas, entre ellos, Primo de Verdad La realidad de esa
rebeldía era no someterse ni reconocer al gobierno de Napoleón,
sino apoyar a Fernando VII, por temor a perder el poder económico y
político que te-nían Aunque se tenía como pretexto, la
desigualdad entre clases y la falta de garantías a los
derechos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el año de 1810, varias colonias ya habían iniciado su
independencia, como Venezuela, Colombia y otras Mientras tanto en
México, que todavía era Nueva España, se formalizaba cada vez más
una conspiración que iba a precipitar una lucha de
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Independencia_de_México"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>independencia</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=k3aZCP2uVx4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=9ED-cBJvSOc&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esto
se realizaba en Querétaro, bajo la protección del regidor Miguel
Domínguez, quien estaba vinculado con el cura </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Miguel_Hidalgo_y_Costilla"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>Miguel
Hidalgo y Costilla</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">;
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=dC9ELmLmf-4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=3ss8OYisuGc&amp;feature=fvwrel"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=0_bTXzdCX0Y"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">mismos
que se reunían en la casa del presbítero José María Sánchez,
también se encontraban en este grupo, militares como Ignacio Allende
y Juan Aldana, así como Emeterio y Epigmenio González En febrero
de 1810, se reúnen todos para conocer el movimiento de lucha
preparado por Manuel Iturriaga, y que consistía en que en las
principales ciudades se incitara a la inconformidad contra los
españoles y que la Nueva España no quedara sometida a los
franceses; declarar la independencia, expulsar a los españoles y
crear un nuevo gobierno a nombre de Fernando VII Por lo tanto, no
era una independencia absoluta, ya que seguirían sometidos a
Fernando VII</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Se
crearon algunas juntas de gobierno en Querétaro, Celaya, San Luís
Potosí, Guanajuato y la Ciudad de México, entre otras, nombrando
como jefe del movimiento a Hidalgo, y proponiendo como fecha de la
sublevación el 1º de diciembre, fecha que después se
cambiaría para el 2 de octubre de 1810 Uno de los militares que
asistían a esas reuniones era el general Arias, quien traicionó al
movimiento y los denuncia; lo mismo hace Juan Garrido, el 13 de
septiembre Esto, precipita los acontecimientos, y el cura
Hidalgo da el grito de independencia la madrugada del 16 de
septiembre de 1810</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
españoles poco pueden hacer, ya que enfrentaban las consecuencias de
la intervención francesa y en la Nueva España, el desencanto crecía
por la injusticia imperante; por eso, el cura Hidalgo e Ignacio
Allende tuvieron respuestas favorables por parte de la gente que
engrosaba los ejércitos formados por pobres, esclavizados y sin
derechos En menos de un año tenían dominada la zona de Dolores,
Atotonilco, San Miguel Allende, Celaya, Salamanca, Irapuato, Silao,
Guanajuato y Valladolid Cuando iban sobre la ciudad de México,
cometen el error de no tomarla y regresan al Bajío, donde fueron
derrotados en Aculco Sus tropas quedan diezmadas Miguel Hidalgo
huye a Valladolid e Ignacio Allende a Guanajuato Sin embargo, en
otros lugares las fuerzas insurgentes tuvieron algunos triunfos, como
en Aguascalientes, Zacatecas y León, comandados por Rafael Iriarte
En San Luís Potosí, con Luís de Herrera y Juan de Villerías En
Toluca, Zacatecas y Cuernavaca En Michoacán y Guerrero aparece
triunfando, José María Morelos y Pavón </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=fzd1SwSStDE"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=zgzxc0IyW3g&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=6uJbw2vFkto&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=5K3ERtktDuM&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
En Colima y Jalisco, son dominados por José Antonio Torres,
quien al tomar Guadalajara le abre el camino al cura Miguel Hidalgo
para entrar y reorganizarse   </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Hidalgo
hace nuevos nombramientos en San Blas, Tepic, Chihuahua, algunas
provincias del occidente y Hermosillo En Guadalajara, Hidalgo
publica el tan ansiado decreto de abolición de la esclavitud, lo que
reivindica el derecho natural de los seres humanos, que es la
libertad Un decreto también de derogación de tributos, los
cuales eran injustos, y eran causa en todos los pueblos del
descontento, por excesivo cobro y nula reciprocidad para el pueblo
También ordenó la devolución de las tierras a los naturales,
otro derecho natural del hombre y que consiste en la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Propiedad_(derecho)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>propiedad</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
anterior es para comprometer más, en el momento de insurrección, a
las clases populares, esclavizadas, explotadas y desprotegidas Sin
embargo, no olvidemos que los que inician este movimiento son gente
de clases privilegiadas, como lo son los criollos, que son hijos
de españoles nacidos en nueva España, y españoles jóvenes
que ven amenazados sus propios intereses, y más adelante, involucran
a las clases desprotegidas La lucha es entre las clases del poder,
por el poder Sobre todo la inseguridad que sentían de que los
franceses tomaran el gobierno de España y sus colonias Lógicamente,
harían cambios en el clero, gobierno y establecieran un nuevo
estado, como lo pretendía Napoleón Para entonces, Francia ya tenía
una Constitución, formalizada en 1789 y que establecía derechos y
formas de gobierno, misma que se implantaría en España y en Nueva
España, afectando intereses bastardos de las clases privilegiadas</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Miguel
Hidalgo siguió su lucha y fue derrotado en Puente de Calderón, lo
que lo hace huir al norte; sin embargo, es aprehendido, junto con
Allende, Aldama y Jiménez, los cuales son fusilados y sus
cabezas cercenadas, las cuales son conservadas en sal y
posteriormente colgadas en las 4 esquinas de la Alhóndiga de
Granaditas, en Guanajuato, varios días después Vale la pena que
las personas investiguen y lean la trayectoria de Miguel Hidalgo,
para conocerlo como ser humano y como insurgente en la lucha de
independencia de México Pero se debe hacer con gusto y no por
obligación</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
la muerte del cura Hidalgo, el movimiento de independencia quedaba
provisionalmente en manos de Ignacio López Rayón </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
José María Morelos, aunque muy debilitados y perseguidos Sin
embargo, José María Morelos reestructuró la parte militar
Mientras tanto, la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Constitución_de_Cádiz"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Constitución
de Cádiz</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
fue jurada en las cortes de España y promulgada en México en
1812 A los españoles de la Nueva España no les convenía esta
constitución, porque perdían muchas prerrogativas Morelos,
por sus dotes militares, es nombrado generalísimo, con todos los
poderes y, además se le da el nombramiento de altísima serenísima
Nombramiento que declina Morelos y se hace llamar: </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Siervo
de la Nación</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
El virrey en esos momentos era Félix María Calleja, quien no estaba
de acuerdo con la constitución de Cádiz, porque abría un tanto las
puertas a la democracia, misma que afectaba intereses de los
poderosos De la misma manera, Calleja perseguía a Morelos y a su
gente, ya que las ideas de los insurgentes eran de independencia y de
una constitución democrática</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Entre
los primeros actos de Morelos como generalísimo, fue crear un
decreto que llamó los </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Sentimientos_de_la_Nación"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Sentimientos
de la Nación</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
y con el cual pretende declarar la independencia de México, ya
que es el primero de todos los personajes de esta lucha que declara
que la América es libre e independiente de España y de toda otra
nación, gobierno o monarquía, pues no quería independizarse de
España y someterse a Francia u otra monarquía, dependiendo de
los sucesos de Europa Asimismo, mencionaba que la religión católica
era la única y no había tolerancia para otra Que la iglesia se
sostuviera solo con los diezmos y se suspendiera todo pago que
injustamente solicitaban los ministros clericales, ya que era un
abuso Definía que los poderes legislativo, ejecutivo y judicial
debían estar divididos para evitar concentración de poder, como
venía sucediendo  Sin que hubiera poder para sancionar abusos e
injusticias</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
funcionarios solo durarían en sus cargos 4 años, en lugar de ser
eternos, propiciando la corrupción También quería que los empleos
fueran para los americanos, que era la gente de México, evitando que
solo fueran esclavos y sujetos a los caprichos de los señores
de mayor rango social y laboral; además de no permitir que
extranjeros ocuparan esos puestos Sobre todo pedía, que la
patria no sería libre, ni nuestra, mientras no se reformara el
gobierno tiránico y echar fuera de nuestro suelo a los enemigos
españoles Pero además, indicaba que la ley es superior a todo
hombre, porque todos deben sujetarse a la ley y se obliguen a la
constancia y patriotismo; que modere la opulencia y la
indigencia, darle al pobre que gane lo justo y mejore sus costumbres
con educación y evite la rapiña Que no haya privilegios 
Importantísimo, que se prescribiera la esclavitud para siempre, así
como que no hubiera distinción de clases, siendo todos iguales ante
la ley, y que solo se distingan por sus vicios y virtudes Que todos
tengan derechos y se proteja la propiedad y se respete su casa como
un lugar sagrado, castigando fuertemente a los que violen este
derecho Se deben terminar las torturas Muy importante, que se
quiten todos los tributos por excesivos, que agobian al pueblo,
quedando solo con en el 5% de sus ingresos Que el día 16 de
septiembre se solemnice como el día de la independencia y la
santa libertad, así como recordar al cura Miguel Hidalgo y Costilla
e Ignacio Allende, como los héroes de la independencia </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
podemos observar, Morelos interpreta ya la parte política y social
del pueblo mexicano para convertirse en un país libre, independiente
y, sobre todo, con el respeto a los derechos sustantivos del ser
humano, así como la   forma de gobierno; precisamente interpretó y
lo llamó, con exactitud, los sentimientos de la nación Porque
era el sentir de la nación del pueblo mexicano; de ahí, ahora sí
la razón principal del movimiento de independencia</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
supuesto, estos sentimientos de la nación y la visión militar y
política de Morelos, hizo que se le persiguiera con más rencor
y decisión de eliminarlo a como diera lugar, para terminar con
un movimiento que iba a dar fin no solo a las injusticias, sino con
la disolución de las riquezas mal habidas y con el control excesivo
e injusto de unos cuantos Además, estos poderosos, aparte de perder
sus poderes y riquezas, ya no iban a ser recibidos en buenas
condiciones en España Tendrían por lo tanto, que jugarse el todo
por el todo Morelos y su gente firman el acta solemne de la
declaración de independencia de América septentrional</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Morelos
inicia también una nueva etapa militar y sale de Chilpancingo par
tomar Valladolid, contando con dos grandes personajes de la
independencia, como son </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Mariano_Matamoros"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Mariano
Matamoros</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=neFW0bBf-nQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=iKC8J-kARUA"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Nicolás_Bravo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nicolás
Bravo</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
 </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=RBdWNWwfRjw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=9_krKxRo29I&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quienes
tenían las plazas de Veracruz y Puebla Sin embargo, por traidores,
Calleja el virrey, supo de esta etapa militar y movilizó tropas que
tenía en Toluca y Guanajuato, que eran comandadas por Llano y
Agustín de Iturbide, lográndolos dispersar a Galeana y Bravo
En el Zapote, Iturbide logra confundir a los insurgentes y los hace
pelear entre ellos, lo cual es desastroso, logrando acabar con los
que quedaron en Puruarán, haciendo prisionero a Matamoros Más
tarde, derrota a Víctor Bravo, quien protege Chilpancingo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ante
estas derrotas, Morelos es despojado del grado de generalísimo,
quitándole todos los poderes Esto es aprovechado por los
realistas de Calleja, el virrey, y Morelos tiene que huir El
congreso, que había asumido los poderes que le fueron retirados a
Morelos, también huye En su penoso recorrido, los diputados van
redactando una constitución con el nombre de Decreto Constitucional
para la Libertad de la América Mexicana Este documento fue
sancionado en Apatzingán, y por eso se le conoce como la
Constitución de Apatzingán, el 22 de octubre de 1814 Este
documento es firmado, entre otros, por José María Liceaga y
José María Morelos, que para entonces le habían dado el cargo de
diputado, López Rayón y Quintana Roo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
Constitución de Apatzingán de 1814 estuvo inspirada en los
Sentimientos de la Nación, la Declaración de los Derechos del
Hombre y la Constitución de Cádiz Esto era la culminación de
la lucha iniciada por Miguel Hidalgo y continuada por José María
Morelos y Pavón, quien  aprovecho las amargas experiencias del
inicio de Hidalgo, y con un ejército de 6,000 hombres luchó contra
el ejército realista, de 80 000 miembros Morelos tenía visión de
estadista Lamentablemente, esta Constitución nunca entró en vigor</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Es
claro que Miguel Hidalgo inició y cumplió la primera etapa del
movimiento de independencia, como también es muy claro que a
José María Morelos le tocó llevar a cabo la segunda etapa Morelos
fue atacado por Agustín de Iturbide, teniendo éste que huir
En ese ataque muere un hombre importante de Morelos, como lo fue
Matamoros, y él logra escapar, para declarar la independencia
Morelos es hecho prisionero en Tezmalaca y traído a México,
teniéndolo prisionero en Tlalpan, en una casona de la ahora calle de
San Fernando Más tarde, es llevado a Ecatepec, donde es fusilado el
22 de diciembre de 1815 Es muy importante e interesante leer sobre
la vida de este gran estadista llamado José María Morelos y Pavón</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
partir de 1816 la lucha por la independencia tuvo una etapa de
decadencia, parecía que todo se perdería, que todo lo
realizado por Hidalgo y Morelos había sido en vano Ahora el
virrey era Apodaca, quien impulsó una política de acuerdos para
liquidar la lucha; entre esos acuerdos estuvieron los ofrecimientos
de indulto para los principales personajes y líderes del movimiento
Algunos, para salvar sus vidas, lo aceptaron, lo mismo para salvar
sus propiedades</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Afortunadamente
para el movimiento de independencia, quedaron luchadores
convencidos, como </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Vicente_Guerrero"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Vicente
Guerrero</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=4ebKAkF4F78&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Guadalupe_Victoria"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Guadalupe
Victoria</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=RmhOyrCZbPs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=_pRRQAqezaw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quienes
continuaron la lucha La lucha de estos personajes tuvo a su favor
los acontecimiento de España, como fueron la promulgación y
entrada en vigor de la Constitución de Cádiz y a las reforma
orientadas contra el poder de la iglesia, y que lógicamente
afectaban los intereses y propiedades de los realistas, que eran los
españoles y criollos que lucharon en contra de Hidalgo y Morelos,
por lo que estuvieron dispuestos a luchar a favor de la
independencia, lo cual aprovecharía Guerrero y Guadalupe
Victoria</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Agustín_de_Iturbide"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Agustín
de Iturbide</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=o_ipsF8gSvs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quien
había combatido a Morelos, el cual fue derrotado meses después,
aprehendido y fusilado; ahora era el instrumento de las fuerzas
conservadoras que se oponían al movimiento para que se consumara la
independencia</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Iturbide
era un criollo ambicioso y de muy mala reputación, quien también
combatió a Vicente Guerrero, y que al darse cuenta que la lucha se
ponía difícil, decide pactar con el caudillo Guerrero, mediante el
Plan de Iguala, el 24 de febrero de 1821, donde acuerdan la absoluta
independencia de la Nueva España Se unen el ejército
realista, comando por Iturbide, y el ejército insurgente,
comandado por Vicente Guerrero, creando el Ejército Trigarante,
nombre que significaba, las tres garantías, que eran: </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Religión"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>religión</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>unión</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
e </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Independencia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>independencia</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
El 24 de agosto de 1821 se confirma la independencia a través de los
Tratados de Córdoba</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Vale
la pena reflexionar esta primera etapa en la que se logra la
independencia de nuestro país Sobre todo, y sin rencores,
meditar lo relacionado a los intereses bastardos de mucha gente, a
quienes no interesaban los derechos de sus semejantes y solo se
inclinaban convenencieramente al bando que les beneficiaba, y que con
tal de tener poder y riquezas, eran capaces de matar, torturar y
esclavizar a la gente Pero también es muy importante darnos cuenta
que la gente oprimida tiene límites, y tarde o temprano,
reaccionarían en defensa de sus derechos naturales, los de su
familia y sociedad en general Nadie puede someter a nadie por la
razón de la fuerza, ni nadie puede permitir que lo sometan contra su
voluntad</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
fuerza de la razón debe imperar a través del derecho El respeto al
derecho El respeto a uno mismo, el respeto a los demás, así como
el cumplimiento de nuestras obligaciones, que son los derechos
de los demás y de uno mismo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Sobre
todo, ese pasado de nuestros antepasados, realistas e insurgentes, no
debemos permitir que se repita en nuestros tiempos por caudillos y
falsos líderes, que en todos los tiempos existen Esta es la razón
de estudiar, conocer y analizar la historia</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ahora,
veamos algo muy importante de la historia de la independencia    
Cuando se firman los Tratados de Córdoba, lo hacen Agustín de
Iturbide, Vicente Guerrero, Guadalupe Victoria y los
representantes de España, como el virrey Apodaca y O’donojú</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
19 de mayo de 1822, se nombra como Emperador Iturbide, el Congreso lo
declara “</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Primer_Imperio_Mexicano"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Primer
Emperador Constitucional</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">”,
y se trata de implantar la Constitución de Cádiz, que fue
promulgada desde 1812 La pregunta era, ¿por qué, si México es
independiente tiene que adoptar una constitución donde se reconoce a
Fernando VII como rey de España y, entonces el emperador Iturbide
gobernaría a nombre del rey? La idea de España era solamente que en
esos Tratados de Córdoba se diera autonomía a México para que
nombrara a sus gobernantes y fueran autónomos, pero seguirían
tributando a España La idea de los mexicanos era, una </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>independencia</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
que significara crear un nuevo país, libre y soberano, sin ninguna
atadura con España Eran dos cosas totalmente diferentes, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Autonomia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>autonomía</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
que </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Independencia"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>independencia</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Esta confusión, o trampa, estuvo a punto de provocar conflictos
graves que llevaran otra vez a la guerra</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">México
requería una constitución propia de acuerdo a sus intereses, a su
cultura, a sus recursos y necesidades, sobre todo, la fundación de
un país libre y soberano, con garantías a los derechos humanos y su
forma de gobierno Donde se establecieran sus territorios Una
constitución es un documento base que contiene la fundación y
creación de un país, libre y soberano, con la definición de su
territorio, con sus propias normas, que le permitan a su sociedad un
desarrollo armónico, sólido, permanente e integral en lo
político, económico y social, con el aprovechamiento de sus
recursos naturales y su relación armónica con otros pueblos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el Plan de Iguala, del 24 de febrero de 1821, se acordó establecer
un gobierno monárquico constitucional, que además contemplara
integrar unas Cortes para que elaboraran una Constitución del
Imperio Mexicano Pero al autoproclamarse Iturbide como emperador,
como ya lo vimos, el Congreso se pone en contra de él y decide
disolverlo En ese tiempo, se rebela </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Antonio_López_de_Santa_Anna"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Antonio
López de Santa Anna</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
desconoce a Iturbide como emperador El 30 de marzo de 1823 se
acuerda que, quien gobernara al México independiente, en forma
colegiada, serían Nicolás Bravo, Guadalupe Victoria y Pedro
Celestino Negrete El 7 de noviembre de 1823 se instaló el Congreso,
con Diputados como Lorenzo de Zavala, Miguel Ramos Arizpe,
Manuel Crescencio Rojas, Valentín Gómez Farías y Carlos María de
Bustamante, quienes promulgan la Constitución el 4 de octubre
de 1824 La primera Constitución del México Independiente Con esta
Constitución se funda un país llamado, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Constitución_Política_de_los_Estados_Unidos_Mexicanos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Estados
Unidos Mexicanos</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Vale
la pena conocer el inicio de la Constitución de los Estados Unidos
Mexicanos:</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 039in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff">“<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>En
el nombre de Dios Todopoderoso, autor y supremo legislador de la
sociedad El Congreso general constituyente de la nación mexicana,
en desempeño de los deberes que le han impuesto sus comitentes, para
fijar su independencia política, establecer y afirmar su
libertad, y promover su prosperidad y gloria, decreta la
siguiente Constitución de los Estados Unidos Mexicanos”</i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
su artículo uno, nos dice:</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="margin-left: 039in; margin-right: 039in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff">“<font face="Century Schoolbook, serif"><font size="2" style="font-size: 10pt"><font size="3" style="font-size: 12pt"><span style="font-style: normal"><b>ARTÍCULO
1º-</b></span></font></font><i><font color="#0000ff"><font size="3" style="font-size: 12pt">
La nación mexicana es para siempre libre e independiente del
gobierno español y de cualquier otra potencia”</font></font></i></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Con
este artículo se deja claramente establecida la independencia de
Mé-xico de cualquier potencia y en especial de España, así como su
libertad y esta-blece que será para siempre Esta es el acta de
nacimiento de nuestro México</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff"> <font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	</font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>ARTÍCULO
2º–</b></font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>
Su territorio comprende el que fue del virreinato llamado antes Nueva
España el que se decía capitanía general de Yucatán, el de las
comandancias llamadas antes de provincias internas de Oriente y
Occidente, y el de la baja y alta California con los terrenos anexos
e islas adyacentes en ambos mares Por una ley constitucional se hará
una demarcación de los límites de la federación, luego que
las circunstancias lo permitan”</i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Con
este artículo se definía cual era el territorio que comprendía a
los Estados Unidos Mexicanos Dejaba claro, que todo lo que
decía España que le pertenecía, ahora era solamente de
México Era definitivo que teníamos patria y libertad Esta patria
y libertad, la debemos defender en todos los aspectos Es el
patrimonio de todos los mexicanos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ya
con esta Constitución es elegido como el primer presidente
constitucional de los Estados Unidos Mexicanos, Guadalupe
Victoria, cuyo nombre original era José Miguel Ramón Adaucto
Fernández y Félix Se hizo llamar Guadalupe, por la Virgen de
Guadalupe, y Victoria, por la victoria de la independencia
Recordemos que se inició en la lucha de independencia con Miguel
Hidalgo y, posteriormente, fue nombrado general en el ejército de
José María Morelos y Pavón Guadalupe Victoria fue encarcelado por
Iturbide, a pesar de que lo apoyó, pero no estuvo de acuerdo en que
éste se autoproclamara emperador Escapó de la cárcel, y
junto con Vicente Guerrero y Antonio López de Santa Anna, firmaron
el acta de casa mata para restablecer el congreso constituyente,
el cual lo nombra primer presidente de México</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al
término del mandato de Guadalupe Victoria, el congreso nombra como
segundo presidente a Vicente Guerrero, quien fue uno de los hombres
fuertes de Morelos, distinguiéndose por su valentía y lealtad Es
de todos conocido que su padre fue apresado por el virrey Apodaca,
condicionándolo a que se rindiera o fusilaría a su padre Vicente
Guerrero contestó que, “</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>la
patria es  primero</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">”,
 lo que dio lugar al fusilamiento de su padre, salvando a la patria
A Guerrero le toca gobernar una parte de la transición de la
independencia, situaciones naturales, mientras los grupos de
poder asimilaban la nueva realidad Es así como enfrenta y rechaza
la oferta de Estados Unidos para adquirir el territorio de Texas Lo
mismo sucede, cuando enfrenta a los españoles que pretendían volver
a recuperar México para España Recordemos que Vicente Guerrero e
Iturbide forman el Ejército Trigarante y proclaman la independencia
</font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Es
también muy importante para todos nosotros, observar y comprender
que después de un movimiento, como el de independencia, quedan
muchas personas y grupos de poder con resentimientos y rencores,
así como el no poderse acostumbrar y adaptar a la pérdida de
privilegios a los que estaban acostumbrados Esto sucede en
nuestros tiempos, y nos toca ser realistas, razonables y respetuosos
con la nueva necesidad que vivimos, y participar comprometidamente
en el desarrollo armónico de nuestra sociedad y de nuestras vidas,
sin rencores y mucho menos, odios Por intereses bastardos es
desconocido Vicente Guerrero como presidente, siendo traicionado por
Francisco Picaluga, hecho preso y fusilado</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Durante
la presidencia de Vicente Guerrero, nombra a Antonio López de Santa
Anna como comandante de la plaza de Veracruz, con el objeto de
combatir a los españoles que pretendían recuperar a México
para España Santa Anna logra vencer a estos españoles Entonces,
López de Santa Anna se rebela a Bustamante, el que se proclama
presidente, en sustitución de Guerrero, porque se da cuenta que
Bustamante traicionó a Guerrero y lo derrocó, fusilándolo Apoya a
Gómez Pedraza como nuevo presidente López de Santa Anna es
nombrado presidente de México en 1833, en sustitución de
Anastasio Bustamante López de Santa Anna solicita licencia para
combatir a los españoles Duran y Arista, y queda como presidente en
funciones Valentín Gómez Farías, quien limita el poder de la
iglesia y aumenta la capacidad del gobierno para hacerse obedecer, ya
que había mucha desobediencia El poder de la iglesia continuaba muy
fuerte y ante las disposiciones de Gómez Farías, hace que Santa
Anna lo destituya Pero entonces, se subleva Texas y desea
independizarse, por lo cual Santa Anna se traslada a Texas, los
combate, es derrotado y hecho prisionero Obligándolo a firmar los
tratados de la independencia de Texas  </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Le
toca también la famosa guerra de los pasteles, que no es otra cosa
que una guerra contra los franceses, para obligar a México al pago
de una  indemnización por daños causados a la pastelería de
un francés En esa guerra pierde una pierna Varias veces renuncia y
otras tantas regresa a la presidencia Esto nos debe hacer
reflexionar en que debemos ser congruentes y patriotas, que primero
están los intereses del país y del pueblo mexicano, por encima de
los de los grupos de poder y personales Esto lo vemos en nuestros
tiempos, cuando los partidos políticos ven por sus propios intereses
mezquinos en lugar de ver por los de la sociedad mexicana, a la cual
pertenecemos todos y tenemos la obligación de defenderla Por
la transición y falta de identidad nacional y patriotismo, es que
Santa Anna ocupa varias veces la presidencia, llegando a un total de
11 veces Volviéndose loco y cobrando impuestos por cada ventana que
había en las casas Asimismo, se realizó la venta de las
Californias, después de una guerra declarada por Estados
Unidos La invasión de Estados Unidos es memorable, por los
hechos ocurridos en Pachuca, el sitio de Churubusco, Molino del Rey y
Chapultepec, en donde se desarrolla la gesta de los niños héroes
Precisamente, es Nicolás Bravo, quien con 800 hombres y casi
medio centenar de alumnos del Colegio Militar, hace la defensa del
Castillo de Chapultepec en esta invasión norteamericana</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Antes
había sido 3 veces presidente de México en sustitución de Santa
Anna Se le devuelven muchas facilidades de poder a la iglesia, sobre
todo que la Constitución de 1824 mencionaba, en su artículo 3, que
la religión católica era la oficial y no habría otra</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Debemos
también reflexionar sobre el poder de la iglesia, que en todos los
tiempos ha sido desastroso El estado mexicano es laico, que no
quiere decir contra la iglesia Sino todo lo contrario, es la
libertad de profesar la religión que cada individuo desee Pero los
asuntos políticos, económicos y sociales deben ser laicos, sin la
intervención de ninguna iglesia</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Durante
un último período como presidente, López de Santa Anna se hace
llamar </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Altísima
Serenísima”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Para festejar la independencia, convoca a un concurso para crear el
himno nacional en 1854 Así, el 16 de septiembre de 1854 se estrena
el himno nacional en el teatro Santana, que más tarde se le conoció
como el teatro nacional, bajo la batuta del creador de la música,
Jaime Nunó, de origen español, con letra de Francisco González
Bocanegra, quien era mexicano, y cantado por la soprano Balbina
Steffenone y el tenor Lorenzo Sabil Uno de los himnos más
bellos del mundo y un símbolo patrio que debemos tener siempre muy
presente y sentirnos muy mexicanos cuando lo escuchemos, con respeto,
y siempre recordando nuestro enorme compromiso con la patria y
nuestro pueblo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
esos años, empezaba a destacar uno de los grandes hombres que
luchaban por México Era </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Benito_Juarez"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Benito
Pablo Juárez García</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=aMpbUoIY-lM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=fvwp&amp;v=O81H4mNAPfk&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=JMyYBBSMP0Q&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=7Dy56AEvgcs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=4_h6Is0s4D0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quien
fue regidor del ayuntamiento de Oaxaca en 1831 y después diputado
local en 1833  Más tarde, es electo diputado federal en 1847,
cuando la intervención y guerra contra Estados Unidos, el
presidente de México era Gómez Farías Más tarde, Juárez es
gobernador de Oaxaca, pero al regresar Santa Anna como presidente, es
hecho preso Juárez y desterrado a Nueva Orleáns Santa Anna es
desconocido como presidente y nombrado Juan Álvarez como presidente
Álvarez nombra a Juárez Ministro de Justicia e Instrucción
Pública en 1855 Juárez expide la ley sobre Administración de
Justicia y Orgánica de los Tribunales de la Nación, llamada
Ley Juárez Abolía los fueros y privilegios que tenían los
militares y el clero</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
Constitución es un pacto entre los poderes que constituyen el
gobierno de la nación Poderes que eran el monarca, la iglesia, la
nobleza y la burguesía, que ahora son sustituidos por los partidos
políticos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
pesar de haberse proclamado la independencia y de haberse creado la
Constitución Política de los Estados Unidos Mexicanos, el pueblo
seguía padeciendo de la injusticia; de la falta de libertad; de
la falta del respeto a las leyes y a la vida El poder incontrolable
de la clase militar y del clero era un enorme obstáculo para
conseguir los postulados de la constitución y para lograr el
desarrollo armónico del pueblo De nada sirven las leyes y los
gobiernos si no cumplen con su finalidad, que no es otra que la
justicia social, política y económica del pueblo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">De
ahí, los abusos de autoridades, golpes de estado y la retención de
privilegios y propiedades de los militares y de la iglesia El
pueblo seguía igual de marginado de la justicia Afortunadamente,
existieron hombres libres y patriotas que se esforzaron por
buscar el bienestar de los pueblos, ante tanta injusticia y con
un dictador sátrapa como Santa Anna, se logra crear el Plan de
Ayutla con el objeto de derrocar a Santa Anna y crear un
Congreso para elaborar una nueva Constitución Este plan hace que
sea desconocido Santa Anna como presidente, nombrándose a Ignacio
Comonfort en su lugar, y creando un Congreso para elaborar una
nueva constitución para la república mexicana</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Se
toma como base la Ley Juárez, con el objeto de liquidar los fueros y
  privilegios de la iglesia y del ejército; para poder defender a
una población que, por su ignorancia e incapacidad, seguía viviendo
en la pobreza más radical y en la injusticia más inhumana No
fueron fáciles los pasos dados por el nuevo constituyente para
lograr los objetivos de democracia, libertad y justicia, pero
valieron la pena los sacrificios y vidas que costó elaborar la
Constitución de 1857 Así, fue proclamada la Constitución el 5 de
febrero de 1857 Ese manifiesto decía: </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff"> <font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">	</font></font></font><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“La
igualdad será de hoy más la gran ley en la República; no
habrá más mérito que el de las virtudes; no manchará el
territorio nacional la esclavitud; oprobio de la historia humana; el
domicilio será sagrado; la propiedad inviolable; el trabajo y la
industria libres; la manifestación del pensamiento sin más trabas
que el respeto a la moral, a la paz pública y a la vida privada; el
tránsito, el movimiento, sin dificultades; el comercio, la
agricultura, sin obstáculos, los negocios del estado examinados por
los ciudadanos todos; no habrá leyes retroactivas, ni monopolios, ni
presiones arbitrarias, ni jueces especiales, ni confiscación de
bienes, ni penas infamantes, ni se pagará por la justicia, ni se
violará la correspondencia y en México para su gloria ante Dios y
ante el mundo será una verdad práctica la inviolabilidad de la vida
humana, luego que con el sistema penitenciario pueda alcanzarse
el arrepentimiento y la rehabilitación moral del hombre que el
crimen extravió”</i></font></font></font></p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff">“<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Tales
son, conciudadanos, las garantías que el congreso creyó deber
asegurar en la constitución para hacer efectiva la igualdad, para no
conculcar ningún derecho, para que las instituciones desciendan
solícitas y bienhechoras hasta las clases más desvalidas y
desgraciadas, a sacarlas de su abatimiento, a llevarles la luz de la
verdad, a vivificarlas con el conocimiento de sus derechos Así
despertará su espíritu, que aletargó la servidumbre; así se
estimulará su actividad que paralizó la abyección; así entraran
en la comunión social, y dejando de ser ilotas; redimidos,
emancipados traerán nueva savia, nueva fuerza a la república”</i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
nueva Constitución, que se proclamó el 5 de febrero de 1857, crea
ahora </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“La
República Mexicana”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
sobre la indestructible base de su legítima in-dependencia,
proclamada el día 16 de septiembre de 1810 y consumada el 27 de
septiembre de 1821 Así lo menciona el documento original de la
nueva Constitución</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
Constitución naciente abrió nuevos caminos de esperanza para el
desarrollo del pueblo mexicano, dentro de un marco de derecho en
lo individual y de gobierno Sobre todo, que esta Constitución está
enriquecida con las Leyes de Reforma</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
1857 es nombrado Juárez Ministro de Gobernación y después fue
nombrado Presidente de la Suprema Corte de Justicia, durante el
gobierno de Ignacio Comonfort Este presidente desconoce la
Constitución del 57 y da un golpe de estado, encarcelando a Juárez;
aquí se inicia la guerra de Reforma Juárez es liberado en enero de
1858 y asume la presidencia de la república por ministerio de
ley, al ser derrocado Comonfort En 1859, con la participación de
grandes liberales, como José María Iglesias, Guillermo Prieto,
Francisco Zarco, Sebastián Lerdo de Tejada, Manuel Payno,
Ignacio Ramírez y Melchor Ocampo, promulga las </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Leyes_de_Reforma"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Leyes
de Reforma</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>,
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">las
que declaraban la independencia del estado con la iglesia, la
ley sobre el matrimonio civil y sobre el registro civil, la de
panteones y cementerios y, sobre todo, la expropiación de bienes de
la iglesia, pasando éstos al estado Juárez fue reelecto presidente
en 1861, en 1867 y en 1871 Es memorable su discurso:</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff">“<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Confiemos
en que todos los mexicanos, aleccionados por la prolongada y dolorosa
experiencia de las comunidades de la guerra, cooperemos en el
bienestar y la prosperidad de la nación, que solo pueden conseguirse
con un inviolable respeto a las leyes, y con la obediencia a las
autoridades elegidas por el pueblo”</i></font></font></font></p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="margin-left: 039in; margin-right: 059in; text-indent: 039in; margin-bottom: 0in; background: #dbe5f1; line-height: 100%">
<font color="#0000ff"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>Mexicanos:
encaminemos ahora todos nuestros esfuerzos a obtener y a
consolidar los beneficios de la paz  Bajo sus auspicios será eficaz
la protección de las leyes y de las autoridades para los
derechos de todos los habitantes de la República Que el pueblo y el
gobierno respeten los derechos de todos Entre los individuos,
como entre las naciones, el respeto al derecho ajeno es la paz”</i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Siendo
Juárez presidente en el año de 1864, y ante la inestabilidad
política en que se encontraba la República Mexicana, se
pretendió, por algunos traidores, que México perdiera su
Independencia al entregar el trono a los franceses, a través de
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Maximiliano_I_de_México"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Fernando
Maximiliano de Habsburgo</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=qtDPQu-IAcw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=8OiMkLecLRw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=AJ_Gg88t7Og"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=kg4Nmcc35IM&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">hermano
del emperador de Austria-Hungría, Francisco José Las
ambiciones y falta de patriotismo de algunos malos mexicanos, como
Miguel Miramón, Tomás Mejía y, nada menos que Juan Nepomuceno
Almonte, hijo de otro de los padres de la patria, como lo fue José
María Morelos y Pavón, que fueron a ofrecerle el trono de México y
a pedirle a Maximiliano que nos gobernara, creyendo éste que contaba
con el apoyo del pueblo mexicano, aceptó venir a gobernarnos El 12
de junio de 1864, Maximiliano inicia su gobierno Sin embargo, nunca
tuvo ningún apoyo ni de Napoleón III ni del pueblo mexicano El
Castillo de Chapultepec fue su residencia y creo el Paseo de la
Reforma, antes Paseo de la Emperatriz Afortunadamente, con la
valentía y resistencia de Juárez, en la Presidencia, logran sitiar
en Querétaro a Maximiliano, haciéndolo preso el general Mariano
Escobedo El 14 de junio de 1867, Maximiliano, junto con Miguel
Miramón y Tomás Mejía, son fusilados en el Cerro de las
Campanas, en Querétaro Es interesante leer y comprender la
vida de estos personajes Con esto se terminaba el segundo imperio,
después de la independencia El primer imperio fue de Agustín
de Iturbide y el segundo de Maximiliano</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el año de 1857, en la guerra de reforma, iniciada por los
conservadores a los que les afectó la constitución, aparece en
Oaxaca un militar llamado </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Porfirio_Díaz"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Porfirio
Díaz</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=HZtMy1jNgB0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=eKhi6OpEYv4&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=oPcNm33s7Yc&amp;feature=fvwp"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=O8RYp8db3CU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quien
sofocó una rebelión en Oaxaca El presidente Benito Juárez lo
había nombrado Capitán de la Guardia Nacional Más tarde le otorgó
los nombramientos de Mayor, Teniente Coronel y Coronel
Posteriormente fue nombrado gobernador En 1861, Porfirio Díaz
fue electo diputado al congreso de la unión Más tarde, Juárez lo
hizo general Juárez declara la suspensión de pagos y los países,
Francia, España e Inglaterra, envían tropas a Veracruz para
obligar a México a pagar su deuda Juárez llega a algunos
acuerdos con Inglaterra y España, pero no con Francia, que inicia la
intervención francesa en abril de 1862 Esta intervención se inicia
en Puebla, que es defendida por Ignacio Zaragoza y apoyado por
Porfirio Díaz, la que es ganada el 5 de mayo por los mexicanos
Juárez contaba siempre con el apoyo decidido de Porfirio Díaz,
quien se convertía día a día en su militar más importante
Porfirio Díaz es invitado a pasarse a las filas del ejército de
Maximiliano, lo cual rechaza Gracias a Díaz, en lo militar,
Maximiliano se debilitaba cada vez más En 1867 toma la ciudad de
México y hace posible el regreso de Benito Juárez a la ciudad y el
triunfo de la república</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Porfirio
Díaz era el segundo hombre más importante después de Benito Juárez
y creyó que debía ser presidente Juárez lo supo y dividió al
ejército, nombrando a un general en cada división, que eran seis
Para entonces, Maximiliano había sido fusilado Porfirio Díaz
se siente desplazado por Juárez y renuncia a su división</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Miramón
y Tomás Mejía, son fusilados en el Cerro de las Campanas, en
Querétaro Es interesante leer y comprender la vida de estos
personajes Con esto se terminaba el segundo imperio, después de la
independencia El primer imperio fue de Agustín de Iturbide y el
segundo de Maximiliano</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Al
acercarse la sucesión presidencial en 1871, Porfirio Díaz se
presenta a las elecciones para evitar que Juárez se reeligiera Sin
embargo, Juárez vuelve a ganar la presidencia y Díaz se revela y
crea el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Plan_de_La_Noria"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Plan
de la Noria</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
con el grito de la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“no
reelección”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Juárez era muy fuerte y tenía el apoyo de muchos generales En
ese movimiento de Díaz, tuvo un fuerte golpe al perder a su hermano
Félix Díaz, quien fue torturado, arrastrado, muerto y quemado, al
haberlo tomado prisionero la gente de Juchitán Pero, en esos
días, 18 de julio de 1872, muere Juárez de angina de pecho, y queda
como presidente provisional Sebastián Lerdo de Tejada, quien le
ofrece a Porfirio Díaz una amnistía, que acepta</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lerdo
de Tejada quiere reelegirse y nuevamente Porfirio Díaz se sublevaba
contra quien lo había amnistiado, entrando en la capital triunfante,
meses después es declarado Presidente Constitucional de la República
Mexicana, iniciando lo que se conoce como el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Porfiriato"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>porfiriato</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>”</b></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
todos los años anteriores al porfiriato, el pueblo mexicano vivió
un verdadero desorden en lo político, económico y social, con
guerras, deudas, golpes de estado, injusticia e inseguridad
jurídica; por lo que no podía desarrollarse como pueblo
independiente y en un estado de derecho Porfirio Díaz, que había
sido parte de la situación anómala de la sociedad mexicana, y al
llegar a la presidencia, se propone implantar mano dura y procurar
estabilizar la situación política y económica del país Para
lograr lo anterior, utilizó a la fuerza pública, que sabía manejar
y conocía muy bien Soldados y policías impusieron el orden por
fuerza, lo que contribuyó a que la gente pudiera trabajar, producir
y vender, sobre todo con seguridad</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Durante
el gobierno de Porfirio Díaz se construyeron más de 20 000
kilómetros de vías de ferrocarril, lo que creó fuentes de
trabajo; habilitó un medio de transporte necesario para todo el
país, tanto de personas como de productos, sobre todo, el transporte
con Estados Unidos y los puertos Se le dio auge a los correos y
telégrafos; se crearon algunos bancos Se creó una política de
contribuciones y se niveló un tanto la balanza de pagos El
campo empezó a producir El país tuvo un desarrollo económico que
nunca había tenido</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Se
crearon escuelas y se empezó a educar a la gente; se creó por
consecuencia, la clase media, y hubo profesionistas y gente con
mayor capacitación, lo que incentivó una cultura con medios masivos
de comunicación, como periódicos, libros, revistas y otras
publicaciones, teatro y música, museos Se crearon carreteras y
puentes Se inauguró la Universidad Nacional, por Justo Sierra
Destacaron músicos, como Juventino Rosas y su vals “Sobre las
Olas” Poetas como Manuel Gutiérrez Nájera, Amado Nervo y
Salvador Díaz Mirón Destacando jóvenes estudiosos y
liberales como, Alfonso Reyes y José Vasconcelos, que buscaban
nuevos horizontes para el pensamiento y el arte</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Sin
embargo, la dictadura de Porfirio Díaz fue aprovechada por
apátridas, que vieron la gran oportunidad de recuperar poder
político y económico, a cambio de la injusticia sobre el pueblo
mexicano También se produjo otra enorme desigualdad entre los ricos
y poderosos, ya que éstos se quedaban con todo, y los pobres, eran
la gran mayoría Los ricos adquirían las tierras que los pobres
tenían la necesidad de vender, a precios miserables, y poder
subsistir algún tiempo, lo que creó los latifundios La gente ya no
tenía tierras y se empleaba con los latifundistas como peones,
en peores condiciones, creándose otro sistema de esclavitud, ya que
los peones no tenían libertad de hacer lo que quisieran Tenían
que comprar, con la miserable paga, en las tiendas de raya, cuyos
propietarios eran los mismos hacendados, que vendían caro y a
crédito, lo que hacía que los peones estuvieran obligados a
trabajar para pagar sus deudas</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
anterior empezó a crear un descontento, al igual que las constantes
reelecciones de Porfirio Díaz Por lo tanto, había necesidad de
reprimir más a la gente para someterla y no permitir un cambio de
gobierno De ahí, la forma tan dura de reprimir a los obreros en la
famosa huelga de Cananea, en Sonora; así como la de Río Blanco, en
Veracruz</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Surge
entonces gente como Francisco I Madero, que buscaron la caída del
gobierno de Porfirio Díaz, para proponer otro desarrollo de la
sociedad mexicana, cansada de impuestos, falta de libertad y del mal
gobierno</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Esta
parte de la historia debe hacernos reflexionar, que no basta que la
economía crezca si no es para beneficio de la gente necesitada No
debe crecer la economía para unos cuantos La estabilidad social
solo se genera cuando la mayoría se ve beneficiada con los
resultados de su esfuerzo, a través de una justicia social Es claro
también, que la dictadura, que no es otra cosa que aferrase al
poder para proteger intereses ajenos a la sociedad, causa malestar y
provoca reacciones que nos llevan a una inestabilidad política,
económica y sobre todo, social</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
historia nos hace conocer hechos y sobre todo actitudes, de gente que
solo protege intereses de grupo, personales y mezquinos Pero además,
que no se pueden seguir violando los derechos naturales de cada
miembro de la sociedad mexicana</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">México
tuvo que pagar una cuota de sangre muy dolorosa Recordemos el
apotegma de Benito Pablo Juárez García: </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“El
respeto al derecho ajeno es la paz”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lamentablemente,
muchas personas con las mejores intenciones, son atrapadas por
intereses de grupos de poder y las obligan a claudicar de sus
ideales Este fue el caso de Porfirio Díaz, que enarboló el
principio de </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“no
reelección”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y duró 36 años en el poder Benito Juárez, 16 años
Afortunadamente, surgieron nuevos hombres con nuevos ideales, que
pretendieron terminar con las injusticias al darse cuenta y vivir la
realidad de los oprimidos Es el caso, que en tiempos del porfiriato
aparece un hombre prominente, de familia acomodada, hacendado;
con estudios en México, Estados Unidos y Francia, cuya vida política
empieza en Coahuila Este hombre fue, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Francisco_I_Madero"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Francisco
I Madero González</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=LCxv3i9ibbM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=IRZxV-Lj2hQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=zBT1FYPD0vo"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Madero,
tuvo una visión diferente de la vida al observar el sistema de
gobierno y la sociedad de Estados Unidos y Francia Compara estos
sistemas con los de México y se da cuenta de la necesidad de hacer
algo por el pueblo mexicano Por eso, al regresar a Coahuila y
administrar la hacienda de la familia, participa en la creación
de un partido llamado Democrático Independiente, en 1904, con
el objeto de oponerse a la reelección del gobernador Miguel
Cárdenas Es nombrado presidente de este partido Además, Madero
colaboraba en el órgano del partido </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“El
Demócrata”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
cuyos artículos se basan en los derechos humanos, el voto y la
libertad, a los cuales les imprime un sello particular y tiene
éxito</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
el año de 1908 escribe un libro llamado, </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“la
sucesión presidencial de 1910”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
en el cual propone una democracia basada en la Constitución de 1857,
la cual no era respetada por los gobiernos de Porfirio Díaz, y
también defendía la libertad política Además proponía la
creación de un partido político que enfrentará a Porfirio
Díaz en las elecciones de 1910</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
1909 se crea el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Nacional_Antirreeleccionista"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Partido
Nacional Antireeleccionista</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y es nombrado candidato a la presidencia, Francisco I Madero
Antes, Madero había propuesto a Díaz que siguiera en la presidencia
y Madero fuera vicepresidente, lo que Porfirio Díaz rechazó Madero
inicia una gran campaña por la presidencia, con la premisa de
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Sufragio
Efectivo, No Reelección”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Tiene buena aceptación entre la población, lo que hace que el
gobierno de Porfirio Díaz lo aprehenda y lo acuse de organizar
una rebelión y de ultraje a la autoridad, por lo que es llevado a
San Luís Potosí para encarcelarlo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Las
elecciones se llevan a cabo y gana Francisco I Madero, pero Porfirio
Díaz se declara presidente La familia de Madero logra que lo pongan
en libertad y huye a San Antonio, Texas, en donde lanza el “</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Plan_de_San_Luis"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Plan
de San Luís</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">”,
mis-mo que había elaborado mientras estaba preso En este Plan de
San Luís, se declaraban nulas las elecciones y se desconocía a
Porfirio Díaz Madero se de-claraba presidente provisional e
incitaba a la población a que se sublevara el 20 de noviembre de
1910, a partir de las 6 de la tarde Se declara vigente la
Constitución de 1857 y se solicita la revisión de la tenencia de la
tierra, con el objeto de que se regrese a sus legítimos
propietarios Además, se pongan en libertad a todos los presos
políticos Este Plan de San Luís es proclamado el 5 de octubre de
1910 Vale mucho la pena leerlo y conocerlo para observar y
comprender el por qué de la Revolución Mexicana</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ante
el llamado de Madero a la sublevación, para el 20 de noviembre de
1910, a partir de las 6 de la tarde, surgen levantamientos en el
norte, con </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Pascual_Orozco"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pascual
Orozco</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Francisco_Villa"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Pancho
Villa</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=4GHz99n1wzc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=S1kNJdgXsF0&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=xmldyzNIqT0&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=1VqlAHSSvtE&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=Qw6qO3g4qVE&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
en el sur con </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Emiliano_Zapata"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Emiliano
Zapata</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=A7QIKKx-Th0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=e7wm5b1tXKU&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=4qXZ44GuNYk&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=1VqlAHSSvtE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=Qw6qO3g4qVE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">lo
cual le da fuerza a este movimiento a modo de revolución Al tomar
Orozco y Villa la plaza de Juárez en Chihuahua, Madero instala ahí
su gobierno provisional</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Para
entonces Porfirio Díaz contaban con 80 años, cansado y enfermo, no
soportó esta situación y el 25 de mayo de 1911 renuncia a la
presidencia y se autoexilia, encaminándose a Veracruz para abordar
el barco el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Ipiranga”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y refugiarse en París, donde muere, estando sus restos aún
allá Mientras tanto, se firman los tratados de ciudad Juárez, en
los que se establecen las renuncias de Porfirio Díaz a la
Presidencia Constitucional y la de Francisco I Madero a la
presidencia provisional También se acuerda que el Ministro de
Relaciones Exteriores, Francisco León de la Barra, asuma la
presidencia interina y convoque a elecciones generales</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
Partido Constitucional Progresista postula como su candidato a la
presidencia de la república a Francisco I Madero, así como a José
María Pino Suárez para la vicepresidencia, quienes ganan las
elecciones de una manera libre y democrática Asumen la Presidencia
el 6 de noviembre de 1911, pero con una prensa hostil y en su contra,
y sobre todo con ataques de la gente incrustada en el gobierno y
que eran partidarios de Porfirio Díaz; lo que hace que su gobierno
tuviera muchas dificultades y problemas para gobernar</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lamentablemente,
el primero que se rebela a Madero es Emiliano Zapata, el día 28
de noviembre de 1911, a los 22 días de haber tomado posesión
Zapata formula el “</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Plan_de_Ayala"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Plan
de Ayala</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">”,
argumentando que madero no cumplía con lo estipulado en el Plan de
San Luís, sobre todo en lo relacionado a la cuestión agraria Esto
estimula a otros golpistas que preparan un golpe de estado, entre los
que se encontraban Bernardo Reyes, Manuel Mondragón y Félix Díaz,
sobrino de Porfirio Díaz y quien se encontraba preso en la
Ciudadela</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
una de las revueltas contra el presidente Madero, y que es conocida
como la </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Decena
Trágica”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
está a punto de ser asesinado, y su jefe de las fuerzas armadas,
Lauro Villar, logra salvarlo, pero es herido y tiene que dejar ese
cargo Madero, ante tal situación, llama a ocupar el lugar de Lauro
Villar a Victoriano Huerta, sin darse cuenta que lo
traicionaría</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Victoriano_Huerta"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Victoriano
Huerta</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=_NDqp7gJK1g"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=wyOUN42aCaA&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">y
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Félix_Díaz"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Félix
Díaz</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
se ponen de acuerdo para derrocar al Presidente Madero y se
entrevistan con el Embajador de Estados Unidos Henry Lane Wilson,
quien los apoya contra Madero Victoriano Huerta, un hombre
alcohólico, hace prisioneros a Madero y Pino Suárez, obligándolos
a renunciar el 19 de febrero de 1913 y manteniéndolos presos en la
penitenciaría de Lecumberri Tres días después los manda
asesinar, el 22 de febrero del mismo año Huerta asume la
presidencia Lo primero que hace es suprimir la libertad de prensa;
asesinar a destacados revolucionarios y reprimir todos los
movimientos obreros Así se inicia una lucha armada y con mucha
sangra derramada</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Venustiano_Carranza"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Venustiano
Carranza</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=AMl3UkzUPMU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=QJzMgPxTcww&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=hXWbU3ABoX0&amp;feature=relmfu"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quien
era gobernador de Chihuahua, se une a Pancho Villa y hacen un
levantamiento en Chihuahua, Sonora, Sinaloa y Tamaulipas,
mientras en el sur, Emiliano Zapata continúa con su movimiento</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
alianza de Carranza y Villa en el norte, con Zapata en el sur, se
realiza con el Acuerdo de Guadalupe Este acuerdo es apoyado por
el presidente de Estados Unidos Woodrow Wilson, quien obliga a que
renuncie Victoriano Huerta y a que se exilie En agosto de 1914 es
designado presidente Venustiano Carranza El nuevo presidente tiene
ahora la rebeldía de Pancho Villa, el que no está de acuerdo con la
política de Carranza, por lo que se crean nuevas y sangrientas
luchas revolucionarias Los ideales de Villa y Zapata estaban muy
limitados, ya que solo se basaban en los problemas agrarios y no
evolucionaron hacia otras partes de la república Sin embargo, el
ejército de Carranza, llamado </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Ejército
Constitucionalista”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
era muy fuerte y contaba con el apoyo de los diferentes sectores del
país, como intelectuales, campesinos, obreros y mineros</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Carranza
trata de unir a los diferentes movimientos a través de la
convención de Aguascalientes, a la que asisten representantes
de Villa, de Zapata y un aliado del presidente, llamado Álvaro
Obregón, al cual le da el grado de general de división y lo nombra
ministro de guerra y marina La convención es un fracaso y no se
llega a ningún acuerdo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Villa
y Zapata pelean contra las fuerzas de Carranza y Obregón, siendo
derrotados en Celaya, en 1915 Villa y Zapata se regresan a sus
lugares de origen Zapata es asesinado en una emboscada en 1919,
y Villa continúa con sus guerrillas, sobre todo es famosa la lucha
que tiene dentro de territorio estadounidense contra los
soldados de allá, porque sabía que Estados Unidos apoyaba a
Carranza Estados Unidos envía a combatir a Villa al general John J
Pershing, quien nunca puede capturarlo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
1915, Venustiano Carranza, como presidente, trata de reorganizar al
país y promueve una nueva Constitución en Querétaro, la cual es
promulgada el 5 de febrero de 1917 Es la Constitución que
actualmente nos rige y que fue enriquecida para dar respuesta a las
necesidades y desarrollo integral de la sociedad mexicana Pero al
igual que la Constitución anterior, y que es la de 1857, de nada
sirve si no se aplica con todo rigor Las leyes se deben cumplir por
sobre todas las cosas No puede haber desarrollo armónico si las
normas no se cumplen y, lo más importante, si las autoridades no las
cumplen y hacen cumplir</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Si
observamos, estos movimientos se han generado debido al
incumplimiento, por parte de las autoridades, de hacer cumplir
la constitución y leyes que de ella emanan Es muy cierto que las
leyes se deben actualizar para dar respuesta a las nuevas necesidades
que va generando una sociedad, por su crecimiento, por las
mayores expectativas de vida, avances científicos y tecnológicos
y la globalización de los pueblos Pero la base es el cumplimiento
de las leyes, buenas o malas, pero deben ser cumplidas por
gobierno y pueblo De otra manera, viviríamos en la inseguridad
jurídica, sin bases sólidas para el desarrollo y crecimiento,
lo que hace que haya pobreza material, pero sobre todo intelectual,
que por consecuencia haya injusticia, como lo hemos estado
observando No debemos permitir que la historia se repita No
puede haber derramamiento de sangre, ni sufrimiento del pueblo
mexicano</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Venustiano
Carranza cometió también excesos, como la terminación de la huelga
de los ferrocarrileros, así como la eliminación de sus adversarios,
lo que hizo que sus aliados lo abandonaran como a Álvaro Obregón,
por lo que Carranza huyó de la ciudad de México, siendo
asesinado en 1920</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="_ADOLFO_DE_LA"></a>
