<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ADOLFO
DE LA HUERTA</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Adolfo_de_la_Huerta"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Adolfo
de la Huerta</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=q_orry2iWcU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quedó
como presidente interino y convocó a elecciones, las que ganó
el general Álvaro Obregón, a quien también se le conoce como el
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Manco
de Celaya”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
ya que ahí, en un enfrentamiento contra las tropas de Villa, perdió
un brazo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Vale
la pena mencionar que Obregón renuncia al gabinete de Carranza y se
alía con otro general incondicional llamado Plutarco Elías Calles,
quien junto también con Adolfo de la Huerta y Salvador Alvarado,
firman el Plan de Agua Prieta, mediante el cual desconocen al
gobierno de Carranza</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="ÁLVAROOBREGÓN"></a>
