<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ÁLVARO
OBREGÓN</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Álvaro_Obregón"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Álvaro
Obregón</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=6mzWbz7TeTU&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
 </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">lanza
fuertemente su campaña para la presidencia, después de muerto
Carranza, logra ganar y toma posesión el 1º de diciembre de 1920
Inicia una etapa de paz, se da principio al reparto agrario,
sobre todo en los estados de Morelos y México Nombra como
ministro de educación a José Vasconcelos e inicia un gran
movimiento educativo, destacando el arte con grandes pintores como,
Diego Rivera, Clemente Orozco y David Alfaro Siqueiros Sin embargo,
su gobierno no estaba muy seguro de no tener algún golpe de estado,
por lo que para conseguir apoyo requería del reconocimiento de
Estados Unidos a su gobierno, el cual logró hasta 1923, con la firma
de los Tratados de Bucareli</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Obregón
había nombrado a Plutarco Elías Calles como Secretario de
Gobernación, siendo éste el candidato lógico para las
próximas elecciones presidenciales Adolfo de la Huerta, que
era gente de Obregón, se subleva y pone en riesgo la paz social
Obregón usa la mano dura y destituye a los mandos militares
inconformes Elimina a la gente que le es adversa, sobre todo a
Pancho Villa, quien anuncia que tiene un ejército de 5000 hombres
armados Villa es asesinado, al igual que Francisco Murguía y
Lucio Blanco Obregón aplasta la rebelión, pero cuesta más de
7000 muertos Termina Obregón su mandato, muy dividido</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="PLUTARCOELÍASCALLES"></a>
