<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>PLUTARCO
ELÍAS CALLES</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="_GoBack"></a>
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
1º de diciembre de 1924, toma posesión de la presidencia, el
general </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Plutarco_Elías_Calles"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Plutarco
Elías Calles</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=FAvgIbezzic"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=0ZH9eWcxWmc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=lHdJrRUUtqY"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">después
de ganar las elecciones Intenta hacer una reconstrucción
política, aunque surgen algunas inquietudes, ya que Obregón deja a
mucha gente de su confianza en el gabinete de Calles Adolfo de la
Huerta, Álvaro Obregón y Plutarco Elías Calles, tenían un pacto
de caballeros, mediante el cual se iban a turnar la presidencia
Había quedado ya  eliminado de la Huerta; ya había sido presidente
Obregón y ahora lo era Calles; pero Obregón se sentía el líder y
a pesar de que dijo que retornaba a la vida privada, estaba
preparando su regreso al término de la gestión de Calles</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Calles
se apoya en Alberto Pani y Manuel Gómez Morín para reformar los
asuntos fiscales y hacendarios; funda el Banco de México Le da auge
a la construcción de carreteras y a la producción agrícola Crea
un nuevo sistema educativo basado en higiene, deporte y oficios, muy
diferente al de Vasconcelos, en tiempos de Obregón</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Sin
embargo, Calles se enfrenta a un grave problema con el clero, al
quitarles muchos privilegios, lo que provoca enfrentamientos que
hacen que expulse a muchos curas y cierre templos, ya que
pensaba que la iglesia era cuna de muchas injusticias En 1924, se
inicia lo que se conoce como la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Guerra_Cristera"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Guerra
Cristera”,</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=VHH4yHJYfYk"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=B5iG_6kyjZk&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=_C6qcTCYj6A"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=bMNOtuMyTug"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=77xEBGqLvps&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=oVwT_XYUWDk&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=fvwp&amp;NR=1&amp;v=eUrcLnd7sIg"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
7</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">recrudeciéndose
en 1926</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Enfrentó
también al Poder Legislativo, que en su mayoría era gente de
Obregón, ya que estaban realizando movimientos para modificar la
Constitución y que hubiera reelección para presidente El
líder de los diputados era Gonzalo N Santos, quien representaba los
intereses de Obregón y era presidente de la Cámara de
Diputados Había algunos generales, como Arnulfo R Gómez y
Francisco R Serrano, quienes pretendían la presidencia y se oponían
a que Obregón se reeligiera Estos generales fueron asesinados, lo
que consolidó el poder de Calles y Obregón En julio de 1928 se
realizaron las elecciones para presidente, mismas que ganó Álvaro
Obregón Sin embargo, el 17 de ese mismo mes, fue asesinado Obregón
en el restorán </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“La
Bombilla”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
por José de León Toral</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="EMILIOPORTESGIL"></a>
