<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>EMILIO
PORTES GIL</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">A
partir de este suceso, empieza lo que se conoce como el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Maximato”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
ya que quien toma el control de todo es Calles Después de algunos
desacuerdos con su gente y la gente de Obregón, impone a </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Emilio_Portes_Gil"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Emilio
Portes Gil</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
como Presidente interino, en sustitución de Obregón En el
nuevo gobierno de Portes Gil se nombra Ministro de Guerra y Marina a
Plutarco Elías Calles, con lo cual consolida su poder, manejando a
las fuerzas armadas</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
1919, invita a todos los partidos, organizaciones y grupos, que eran
más de 3 600, a que se unieran y formaran un nuevo partido que
defendiera las causas de la Revolución Así es como se forma el
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Nacional_Revolucionario"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Partido
Nacional Revolucionario</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Calles es nombrado presidente del Partido, pero dura muy poco,
renuncia y se retira a la vida privada, desde donde maneja todos
los hilos de la política Sobre todo, porque se venían las nuevas
elecciones presidenciales, ya que Portes Gil solo era interino La
lucha por la candidatura fue dura, especialmente en el ámbito
militar Calles quería poner a una persona de su confianza y
proponía a Aarón Sáenz, quien fue rechazado</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="PASCUALORTÍZRUBIO"></a>
