<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>PASCUAL
ORTIZ RUBIO</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ante
la oposición a esta candidatura, Calles optó por traer a otra
persona de su confianza, que era embajador en Brasil y cuyo nombre
era </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Pascual_Ortiz_Rubio"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Pascual
Ortiz Rubio</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
quien al llegar a México, la primera visita que hizo fue a Calles; y
se postuló como candidato a la presidencia No hubo oposición,
porque todos los grupos políticos creyeron que podían manipular a
Ortiz Rubio, para proteger sus intereses personales y de grupo
Además, a algunos inconformes, Calles les otorgó concesiones para
construir carreteras, como a Juan Andrés Almazán, y a otros con
dotación de tierras</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Calles
encomendó a Gonzalo N Santos La tarea de hacer ganar a Ortiz
Rubio, a como diera lugar Santos lo logra con sobornos, robo de
urnas y balazos Ante tales hechos, se rebela el general Gonzalo
Escobar, ante lo cual, Calles llama a sus mejores generales para
acabar con esa rebelión Entre esos generales estaban Saturnino
Cedillo, Adalberto Tejeda y Lázaro Cárdenas; mismos que en
poco tiempo terminaron con la revuelta, dejando muchos muertos y
heridos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
contrincante de Ortiz Rubio a la presidencia era José Vasconcelos
Ortiz Rubio toma posesión de la presidencia el 4 de febrero de 1930
Calles impone</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">a
su gente en el gabinete, así como en el Partido Nacional
Revolucionario, que es manejado por Emilio Portes Gil y Lázaro
Cárdenas</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ortiz
Rubio quería imponer a su gente en el gabinete y lleva a cabo sus
políticas propias, lo cual preocupó a Calles, y obligó a toda su
gente, dentro del gobierno, a que renunciara Esta acción obligó a
Ortiz Rubio a renunciar, al encontrarse solo, en agosto de 1932</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Para
sustituir a Ortiz Rubio, calles llamó a otro general de su
confianza,   que había sido subsecretario de Guerra y Marina cuando
Calles fue Secretario en el gobierno de Portes Gil Este general era
Abelardo L Rodríguez</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="ABELARDORODRÍGUEZ"></a>
