<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ABELARDO
L RODRÍGUEZ</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Abelardo_L_Rodríguez"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Abelardo
L Rodríguez</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
era uno de los generales de mayor confianza de Calles, y supuso
que, como buen administrador, podría estabilizar el gobierno
Abelardo Rodríguez era un hombre adinerado; ya que manejaba negocios
como el hipódromo de Tijuana y centros de diversión, con
prostitución y alcohol Aprovechaba el mercado que venía de Estados
Unidos a sus centros, ya que éstos se encontraban en Tijuana
Había ya la prohibición del alcohol Creó el Departamento
Agrario y el Departamento Autónomo del Trabajo También creo
Petromex, compañía petrolera, y Nacional Financiera La parte
política se la dejó a Calles, que fue, en este gobierno, quien por
cierto lo nombró o Calles se autonombró, Secretario de Hacienda</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Calles
se volvió a enfrentar al problema de designar candidato para las
elecciones presidenciales al término del gobierno de Rodríguez
Tenía dos candidatos, uno era Pérez Treviño y el otro Lázaro
Cárdenas Por cuestiones políticas, se inclinó por Lázaro
Cárdenas, quien asume la presidencia en diciembre de 1934</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos visto en todos los acontecimientos de la Revolución y
Postrevolución, no se podía generar una estabilidad política
y económica que repercutiera en una paz y justicia social,
debido a la violación de los derechos del pueblo, y sobre todo, la
continuación del poder de la fuerza para mantener privilegios
de los grupos de poder como los militares y la iglesia Hasta ahora,
hemos visto que todos los presidentes han surgido de las fuerzas
armadas, todos son generales La diferencia ahora es que hay una
lucha entre los militares y los clericales, de ahí, la guerra
cristera Nadie cede en sus intereses de grupo Aun entre grupos hay
diferencias, como lo hemos visto, se destruyen entre los mismos
militares para poder continuar con el manejo de la política y
economía del país El pueblo, como desde los tiempos de la
independencia, seguía en las mismas condiciones precarias De nada
había servido la constitución Se violaba constantemente De
ahí la necesidad de entender y comprender que el respeto y
cumplimiento de la ley, principalmente de las autoridades, así como
del pueblo en general Era la solución a todos los problemas Solo
con el respeto a la ley habría seguridad jurídica, física,
económica y política, que llevara a un desarrollo de los mexicanos
de manera integral, congruente, sólida y armónica</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ya
vimos como eran capaces de utilizar el engaño para conseguir sus
objetivos, como fue el caso de la no reelección, usado como
bandera para obtener el poder, y ya logrado el objetivo reelegirse,
sin importarles nada el pueblo mexicano El caso concreto fue
Porfirio Díaz, más adelante, inclusive, se modificó la
constitución para reelegir a Álvaro Obregón Y posteriormente, una
dictadura simulada, como la de Plutarco Elías Calles Todo lo
anterior debe servir para que cada mexicano conozca la historia y
evite repetirla Pero sobre todo, defender con el ejemplo y con
acciones, dentro de la ley, el derecho consagrado y garantizado en la
constitución y leyes que de ella emanan, respetándonos a nosotros
mismos, a nuestra familia y a nuestra sociedad Eligiendo
adecuadamente a nuestros funcionarios públicos y obligándolos
a cumplir y hacer cumplir las normas establecidas, como es su
obligación, no su derecho Las leyes no les dan derechos a los
funcionarios públicos, solo les dan facultades de acción, que son
obligaciones que deben cumplir, sin pretexto alguno Los ciudadanos
son los únicos que tenemos derechos, mismos que están garantizados
por la Constitución y leyes que de ella emanan</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="LÁZAROCÁRDENAS"></a>
