<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>LÁZARO
CÁRDENAS</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Lázaro_Cárdenas_del_Río"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Lázaro
Cárdenas</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=q41P8cq1Qvg"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=YSnsDQOoyio&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=j4QLbhNdcoE&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=5aseaKFpFEs&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=tcA2sNdnUWY&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">había
sido gobernador de Michoacán y tuvo que dejar su cargo para ocupar
la presidencia del Partido Nacional Revolucionario, en sustitución
de Portes Gil Renuncia a la presidencia del Partido y asume la
Secretaría de Gobernación del presidente Ortiz Rubio</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
ya vimos, Lázaro Cárdenas toma posesión de la presidencia en
diciembre de 1934 Calles, pretende controlarlo con el plan
sexenal que había elaborado su partido, que era el Partido Nacional
Revolucionario, mediante el cual se pretendía desarrollar una
política social, económica y administrativa, capaz de traducir en
hechos los postulados que se proclamaron en la revolución Sin
embargo, esto fue precisamente lo que utilizó Cárdenas como su plan
de gobierno Hizo que el plan sexenal estableciera la rectoría del
estado en el desarrollo económico de México Destruyó los
latifundios y repartió las tierras, incentivó la industria,
estableció una educación socialista Apoyó a los campesinos
para que pudieran producir Apoyó a los obreros para que tuvieran
mejores condiciones de trabajo Sin embargo, tuvo las presiones
de Calles, e inclusive, intentos de golpe de estado, por lo que
el general tuvo que ser expulsado del país, al igual que algunos de
sus incondicionales   </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Inclusive,
dio de baja a algunos militares callistas y apresó a otros El país
que Cárdenas había recibido, seguía en condiciones desastrosas,
como en los tiempos de Porfirio Díaz, pobre, ignorante, dividido,
sin derechos, con fanáticos de la religión Además, todavía
tenía los problemas heredados de Calles con el clero, que veía
afectados sus intereses Al quitarse la sombra de Calles, Lázaro
Cárdenas termina con los problemas de la iglesia al permitir abrir
los templos y aceptar que llegaran más sacerdotes Ayuda a los
campesinos y crea la Confederación Nacional Campesina </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Confederación_Nacional_Campesina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CNC</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Organiza
a los obreros con la ayuda de Vicente Lombardo Toledano, Fidel
Velásquez, Jesús Yuren, Fernando Amilpa, Salvador Sánchez
Madariaga y Luís Quintero, y se funda la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Confederación_de_Trabajadores_de_México"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CTM</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
Confederación de Trabajadores de México, desplazando al nefasto
líder obrero Luís N Morones, quien tenía aspiraciones
presidenciales</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Transforma
al Partido Nacional Revolucionario y funda otro, llamado Partido de
la Revolución Mexicana, </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_de_la_Revolución_Mexicana"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PRM</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
integrado por el sector obrero, la </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Confederación_de_Trabajadores_de_México"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CTM</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
el campesino </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Confederación_Nacional_Campesina"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CNC</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
el de las clases populares </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Confederación_Nacional_de_Organizaciones_Populares"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>CNOP</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y los militares</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Estallan
varias huelgas, sobre todo la de los ferrocarrileros, mineros y
petroleros La huelga de los petroleros propicia que Cárdenas
decretara la expropiación petrolera el 18 de marzo de 1938, lo
que estuvo a punto de provocar una guerra contra México Esta guerra
no se llevó a cabo debido a que estaba por estallar la segunda
guerra mundial Fundó el Instituto Politécnico Nacional En el
ámbito internacional aceptó a un gran grupo de niños y exiliados
españoles antifranquistas que habían huido de España De la
misma manera, a petición de Diego Rivera, aceptó a León Trotsky
como exiliado de Rusia y expulsado por José Stalin Se funda la
Unión Nacional Anarquista, que defendía los intereses de la
iglesia También se funda en 1937 el Partido Acción Nacional,
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Acción_Nacional_(México)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PAN</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
cuyo dirigente era Manuel Gómez Morín, que ya participaba en la
siguiente sucesión presidencial</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
subsecretario de la Secretaría de Guerra era un general de todas las
confianzas de Cárdenas, y más tarde fue el Secretario de Guerra y
Marina durante la presidencia de Cárdenas, llamado Manuel Ávila
Camacho </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="MANUELAVILACAMACHO"></a>
