<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>MANUEL
ÁVILA CAMACHO</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
Partido de la Revolución Mexicana lo nombra candidato a la
presidencia, y ante las inquietudes de sus contrincantes, es
defendido y apoyado por jóvenes militares, entre los que se
encontraban Marcelino García Barragán y Alfonso Corona del
Rosal El contrincante de Ávila Camacho era el general Almazán,
quien tenía muchas casillas a su favor, pero Fidel Velázquez había
ordenado que las urnas fueran tomadas para favorecer a </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Manuel_Ávila_Camacho"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Manuel
Ávila Camacho</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=arTpYCg8X9s"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=D3i0BmT73Bc&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=MaaJyEicdow"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=lqhAMqYuNnQ&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=-qkO6U8ltHQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>–
 </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">quien
al final llegó a la presidencia y tomó posesión el 1º de
diciembre de 1940</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Durante
su período funda, en 1943, el Instituto Mexicano del Seguro Social
Le da impulso a la educación y lanza una campaña contra el
analfabetismo Crea la Secretaría de la Defensa, la Secretaría
de Marina y la Secretaría del Trabajo Durante este período estalla
la segunda guerra mundial y se ve México envuelto en la misma,
declarando Ávila Camacho la guerra a Japón, Italia y Alemania, por
lo que envía al escuadrón 201 a combatir y nombra como Secretario
de la Defensa Nacional a Lázaro Cárdenas, a quien hace regresar
después de su retiro También decretó la congelación de las
rentas en beneficio de las clases desprotegidas Logra reunir en la
Plaza de la Constitución de la Ciudad de México, a los
expresidentes: Emilio Portes Gil, Pascual Ortiz Rubio, Plutarco Elías
Calles, Lázaro Cárdenas del Río y Abelardo L Rodríguez Como
Secretario de Gobernación, del gabinete de Ávila Camacho, estaba el
Lic Miguel Alemán Valdés A pesar de que el general Cárdenas
hizo lo posible por guardar el orden constitucional, siguieron
prevaleciendo los intereses de grupos y la falta de respeto a la ley
Sobre todo haciendo nula la democracia Los hechos son la forma en
que llegó a la presidencia Ávila Camacho, como ya lo vimos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="MIGUELALEMÁNVALDÉS"></a>
