<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>MIGUEL
ALEMÁN VALDÉS</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Miguel_Aleman_Valdes"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Miguel
Alemán Valdés</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=pKdPWN7bHJg"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=XiG0PBwCt8E"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=fk3Bg3atKfU&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=LNqCs-F4zyE"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=RIsZbF41trc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=pjwl_nbI6vs&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">es
el primer presidente civil de la historia de México Inicia una
época moderna de desarrollo, estimulando la industria, el comercio
y, sobre todo, el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Turismo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>turismo</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Crea </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Ciudad_Universitaria_de_la_UNAM"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Ciudad
Universitaria</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
También el Partido Revolucionario Institucional, suprimiéndose la
parte militar La economía del país tiene un aumento fuerte,
pero no logra una justicia social Siguen prevaleciendo
privilegios para los poderosos, creándose una nueva casta de ricos
Hubo mucha corrupción Su presidencia fue de 1946 a 1952 Tenía
como Secretario de Gobernación a Adolfo Ruiz Cortines</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="ADOLFORUIZCORTINES"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>ADOLFO
RUIZ CORTINES</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Adolfo_Ruiz_Cortines"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Adolfo
Ruiz Cortines</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?v=Sxwh7WGZIM0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=9y4qDUnoG7Q&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=Ss9KotZmOBY&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=kwtnUF3kIiU&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=QlOTxNJPJxk"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">es
el segundo presidente civil que ejerce su mandato, de 1952 a 1958
Siendo un presidente austero, cuya función principal fue lograr la
estabilidad económica Su Secretario del Trabajo fue Adolfo López
Mateos</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="ADOLFOLÓPEZMATEOS"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>ADOLFO
LÓPEZ MATEOS</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Adolfo_Lopez_Mateos"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Adolfo
López Mateos</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=UsvjdZMHwCU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=NJqliJDOGgw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=po_IZn8UYP4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=hXd2Ux4Dd8E&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=NluESUJJB1Y&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">continúa
con la época de presidentes civiles Lleva una política de
desarrollo económico, principalmente a nivel internacional, logrando
relaciones internacionales con un gran número de países Tuvo
algunos movimientos, como los de los maestros, médicos y
ferrocarrileros, mismos que fueron sofocados Tenía como
Secretario de Gobernación a Gustavo Díaz Ordaz  Su mandato fue de
1958 a 1964</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="GUSTAVODÍAZORDÁZ"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>GUSTAVO
DÍAZ ORDAZ</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Gustavo_Diaz_Ordaz"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Gustavo
Díaz Ordaz</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=m3dsSYjGyVk&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=5XQ9s5n7LGI&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=7jkvHTCLv2I&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=_m5__Z81MsU&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;v=7PHm5oWIOMY&amp;feature=endscreen"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">hombre
de fuerte carácter, tuvo que enfrentar los movimientos
estudiantiles de octubre de 1968 En ese año se realizaron los
juegos olímpicos Reprimió, encarceló y exilió a muchos líderes
de los movimientos estudiantiles y obreros Su secretario de la
defensa fue Marcelino García Barragán y el jefe del
Departamento del Distrito Federal fue Alfonso Corona del Rosal,
su Secretario de Gobernación lo fue Luís Echeverría Álvarez Su
período fue de 1964 a 1970</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="LUISECHEVERRÍAALVAREZ"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>LUIS
ECHEVERRÍA ÁLVAREZ</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Luis_Echeverría"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Luis
Echeverría Álvarez</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=4YCZp4IaVRo"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=Zc0RVRPZ-Qs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=8vLl_XJH4fM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=V9ddIAwmzd0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=AEGhRkj6Hkc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=xVdJwI6j2ic"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">fue
un presidente que heredó, además de haber sido partícipe de los
hechos y descontento, el movimiento del 2 de octubre del 68 Vivió
el famoso movimiento del 10 de junio de 1971, que se conoce como el
jueves de Corpus Christi Que fue otra represión, con muertes de
estudiantes y maestros La economía del país sufrió descalabros y
se vino una serie de devaluaciones del peso mexicano Se
iniciaron las crisis económicas de los últimos tiempos Su período
fue de 1970 a 1976 Su Secretario de Hacienda fue José López
Portillo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="JOSÉLÓPEZPORTILLO"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>JOSÉ
LÓPEZ PORTILLO</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/José_López_Portillo"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>José
López Portillo</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=f7lxaH_7rk0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=B7KqOCgf1GA"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=-CRGAPHYZcA"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=kHNc6AVP_EY"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=bPRhJKHNJWo"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=ysg_QY2AWSU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">entra
a la presidencia con grandes esperanzas de desarrollo económico
Inicia un crecimiento de la industria petrolera, la cual tiene un
gran potencial Propone un Plan Nacional de Desarrollo de grandes
alcances Sin embargo, el endeudamiento del país es muy
elevado, lo que provoca devaluaciones e inflación Hay corrupción y
nepotismo No se consigue lo que el pueblo requiere, de acuerdo a su
constitución, ya que no se cumplen sus postulados A el se le
debe la implantación de un impuesto que provoca inflación, como es
el impuesto al valor agregado, IVA También nacionalizó la banca y
hubo gran fuga de capitales Su período fue de 1976 a 1982 Su
Secretario de Programación y Presupuesto fue Miguel de la Madrid
Hurtado</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="MIGUELDELAMADRIDHURTADO"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>MIGUEL
DE LA MADRID HURTADO</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Miguel_de_la_Madrid"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Miguel
de la Madrid Hurtado</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
  </font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=9BIZiK7cSSM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=M2oQdmGdD6M"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=m4q7rCGuZ8c"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=wWVuszRDoro"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=sV35PyOgxko"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–   </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=MChoRL__pZE"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">recibe
a un país con problemas financieros y con una gran deuda externa
Lamentablemente enfrenta el problema del ciclón “Gilberto”,
que afecta a la zona turística de Cancún y otras playas México
sufre el terremoto de 1985, que causa muchos estragos Se tuvo la
caída más grande del precio del petróleo, que llegó a 860
dólares el barril, cuando antes costaba 38 dólares La inflación
llega a 160%, algo nunca antes visto La devaluación del peso llega
a niveles de más de 3000%  </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">El
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Revolucionario_Institucional"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PRI</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que es el partido del gobierno, tiene una fuerte crisis y salen
algunos de sus miembros, como Porfirio Muñoz Ledo y Cuauhtémoc
Cárdenas  Se permite la participación de los exbanqueros, a través
de Casas de Bolsa Se genera mucho desempleo Su Secretario de
Programación y Presupuesto es Carlos Salinas de Gortari El período
de de la Madrid es de 1982 a 1988</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%"><a name="CARLOSSALINASDEGORTARI"></a>
<font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>CARLOS
SALINAS DE GORTARI</b></i></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">En
medio de una crisis del PRI, es postulado </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Carlos_Salinas_de_Gortari"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Carlos
Salinas de Gortari</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;v=Eq7T-CQQJCQ&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=RNubLminL34"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=hc9R3Fw4S5A"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=fDCRsWsqMmc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?feature=endscreen&amp;NR=1&amp;v=wl1vzHcCu1k"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=sCsiAvs1vCM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">como
candidato a la presidencia En medio de inconformidades y la famosa
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“caída
del sistema”, </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">gana
las elecciones Salinas, mientras que la coalición de partidos que
postularon a Cárdenas decía que había habido fraude electoral
Salinas toma posesión y somete a dos líderes que le causaban
problemas: Joaquín Hernández Galicia, </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“la
Quina”,</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
líder de los petroleros, y Carlos Jongitud Barrios, líder de los
maestros Reanuda relaciones con el Vaticano y modifica la
Constitución, para permitir que las iglesias fueran reconocidas y
tuvieran propiedades Privatiza nuevamente la banca Establece
los pactos de solidaridad para ayudar a la estabilización de la
economía y detener la inflación y devaluación que ya eran
alarmantes Le quita tres ceros a la moneda</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Durante
su gobierno, se funda el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_de_la_Revolución_Democrática"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Partido
de la Revolución Democrática, PRD</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Como Secretario de Desarrollo Social tuvo a Luís Donaldo Colosio y a
Ernesto Zedillo Ponce de León, quien al desaparecer la Secretaría
de Programación y Presupuesto es nombrado Secretario de
Educación Pública Firma el Tratado de Libre Comercio con Estados
Unidos y Canadá El 1º de enero de 1994 le estalla el movimiento
del Ejército Zapatista de Liberación Nacional, encabezado por el
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“Sub
Marcos”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
El </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Revolucionario_Institucional"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PRI</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
en plena crisis, postula a Luís Donaldo Colosio como candidato a la
presidencia, teniendo a Ernesto Zedillo como el coordinador de la
campaña Manuel Camacho Solís se molesta, pues creía que él sería
el candidato Salinas lo nombra como Comisionado para la Paz, para
tratar de desactivar el movimiento del </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/EZLN"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>EZLN</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Lo nunca visto en el PRI, su candidato, Luís Donaldo Colosio, es
asesinado en Lomas Taurinas, Tijuana, el 23 de marzo de 1994, por lo
que es sustituido por Ernesto Zedillo, Coordinador de la campaña El
período de Salinas es del 1º de diciembre de 1998 a 1994</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="ERNESTOZEDILLOPONCEDELEÓN"></a>
