<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>ERNESTO
ZEDILLO PONCE DE LEÓN</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Ernesto_Zedillo_Ponce_de_Leon"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>Ernesto
Zedillo</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=5gZMEtnbgLk"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=z4YyNi_sWiQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=K_FIvlGQvt0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=LoslUE6xziY"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://wwwyoutubecom/watch?NR=1&amp;feature=endscreen&amp;v=h4jIdrPaF0o"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–  </b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">gana
la presidencia a sus contrarios, Cuauhtémoc Cárdenas del </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_de_la_Revolución_Democrática"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PRD</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
y Diego Fernández de Cevallos del </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Acción_Nacional_(México)"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PAN</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Al inicio de su gobierno, el 1º de diciembre de 1994, tiene
problemas con la paridad del peso, con una fuerte devaluación el 20
de diciembre, lo que se le llama el </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>“el
error de diciembre”</b></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Encarcela al hermano del expresidente Salinas, Raúl Salinas de
Gortari Logra estabilizar la economía con un préstamo que
hace el presidente de Estados Unidos, Bill Clinton Para salvar a la
banca crea el llamado </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/FOBAPROA"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>FOBAPROA</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que más tarde se convierte en </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/IPAB"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>IPAB</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Nombra a Francisco Labastida como Secretario de Gobernación, el cual
llega a ser el candidato del PRI a la presidencia, misma que pierde
con el candidato del PAN Vicente Fox Quezada  Con esto termina la
época del partido del gobierno, el </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://eswikipediaorg/wiki/Partido_Revolucionario_Institucional"><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><b>PRI</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Como
hemos estado estudiando, siempre los grupos de poder han
prevalecido, y aunque el pueblo mexicano vive en desarrollo, no
ha logrado hacerlo de manera sólida, congruente e integral No se ha
podido consolidar la democracia, y mucho menos, la justicia social
En cambio, la familia política se ha beneficiado y enriquecido,
como en tiempos de la independencia y la revolución El país vive
en una permanente crisis política y económica, que repercute en lo
social</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Los
resultados son: desempleo, inflación, devaluación, narcotráfico,
nar-comenudeo, drogadicción, inseguridad, secuestros, 8 grados de
escolaridad, 8 millones de analfabetas, más de 35 millones de
mexicanos, mayores de 15 años, que no han terminado su educación
básica; deserción escolar y reprobación alta Pésima calidad
educativa El campo quebrado Emigración creciente Luchas de
partidos políticos irracionales, que solo son por sus intereses
personales y de grupo Dependencia alimentaría; endeudamiento grave</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Todo,
debido a la falta de cumplimiento de la Constitución y leyes que de
ella emanan Violación a los derechos de los mexicanos A la
inseguridad jurídica, al burocratismo creciente e inepto A la
falta de justicia en los tribunales y ministerios públicos A
Diputados y Senadores que chantajean y solo son por intereses ajenos
a la población</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Por
lo anterior, es muy importante revisar y estudiar la historia del
país, para analizar, comprender y sacar conclusiones que permitan, a
cada mexicano y a sus diferentes sectores, tomar acciones que
solucionen las necesidades de la sociedad mexicana Que se haga
realidad, en toda su extensión, la libertad de acción para
construir la democracia, que es la participación de la sociedad en
la solución de sus problemas, y conseguir una verdadera y sólida
justicia social, que solo se logrará con educación, capacitación y
cultura, que permitan a cada mexicano desarrollar nuevas habilidades,
de acuerdo a la realidad, integrando todos los avances científicos y
tecnológicos de punta, para poder competir en los sectores
internacionales en las mejores condiciones, creando riqueza material
pero, sobre todo, riqueza intelectual, generando la inteligencia del
pueblo Además, crear fuentes de empleo con plazas bien remuneradas,
que permitan a cada mexicano satisfacer sus necesidades, de manera
digna y humana Crear conciencia del respeto a las obligaciones y a
los derechos Tener un gobierno honesto y respetuoso de la ley, que
la cumpla primero y la haga cumplir después</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
libertad de pensamiento debe prevalecer en cada mexicano, cada uno es
dueño de su propia verdad, nadie puede imponer a nadie sus ideas
Por lo tanto, cada quien debe sacar sus propias conclusiones y actuar
de acuerdo a su criterio, solamente respetando la ley y los derechos
de los demás, así como de la naturaleza Cada quien debe asumir su
propia responsabilidad</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Debemos
preguntarnos a la luz de la historia, que nos ha mostrado todas las
luchas por la libertad, la democracia y la justicia social, ¿qué
pasa con el gobierno?, ¿con el poder legislativo?, ¿con el poder
ejecutivo?, ¿con el poder judicial?, ¿y los gobernadores y
presidentes municipales?, ¿qué pasa en los partidos políticos, las
iglesias?, ¿por qué no están dando respuestas congruentes a la
sociedad?, ¿por qué tanta pobreza? Pero, sobre todo, ¿qué
estamos haciendo como sociedad, como ciudadanos? ¿Esta es la
sociedad que queremos?, ¿somos conformistas?, ¿qué estamos
haciendo por nosotros mismos y principalmente por nuestra familia?
Cada quien debe contestar y actuar con responsabilidad, compromiso
y respeto a todas estas preguntas</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h1 class="western" style="text-indent: 039in"><a name="INDICETEMAXIII"></a>
<font color="#000080"><font size="6" style="font-size: 22pt"><i>INDICE
– TEMA XIII</i></font></font></h1>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 200%">
