DEL IMPUESTO SOBRE LA RENTA</font></font></a></u></span></font><font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
     ………       </font></font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
