<font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 16pt"><b><font color="#000066"><font size="5" style="font-size: 18pt"><i>COMPUTACIÓN
FISCAL CONTABLE</i></font></font></b></font></font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Hemos
estado estudiando, trabajando, comprendiendo y encontrando
res-puestas a qué somos, cuál es la razón de nuestra existencia,
de nuestro entorno, nuestras relaciones sociales, nuestros
derechos, nuestras obligaciones, nuestra historia, las matemáticas y
muchas cosas más</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Ahora,
debemos prepararnos para administrarnos, para generar salud,
felicidad, satisfactores, los que debemos utilizar para nosotros
mismos y para compartir con nuestras familias y con la sociedad a la
cual pertenecemos, sin descuidar la relación con otras sociedades
del mundo Aportar lo mejor de nuestra cultura y adquirir lo
mejor de otras culturas Pero, ¿qué es administrar?</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Administrar
viene del latín </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ad</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que significa </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>hacia</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
es decir, sentido de movimiento, </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ir
a</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
y </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>ministrare</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
que significa </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>servir</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">,
</font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>dar</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Administrar entonces es, </font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>“</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i><b>dar
o servir a alguien</b></i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt"><i>”</i></font></font><font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">
Cuando nos administramos, nos damos algo a nosotros mismos, nos
servimos Cuando administramos una empresa, le damos algo o le
servimos en algo</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Nosotros
debemos administrar nuestro cuerpo, dándonos nuestros alimentos
para poder subsistir Pero una buena administración consiste en
darnos nuestros alimentos en forma suficiente y con una dieta
balanceada, para que el organismo obtenga la energía y nutrientes
necesarios para desarrollar las actividades de trabajo,
diversión, ejercicio y de estudios; que nos mantenga sanos física y
mentalmente Si no tenemos una buena administración y sólo nos
damos alimentos con el único objeto de quitar el hambre,
entonces tendremos problemas de colesterol, con las consecuencias
naturales de circulación de la sangre, infartos, etc Además,
tendremos anemia, sobrepeso y no tendremos ánimo de trabajar,
estudiar o hacer deporte Estaremos cansados, desganados, etc</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">La
buena administración también la llevamos a nuestras familias, a las
cuales debemos proporcionar todos los satisfactores para su
desarrollo armónico e integral de cuerpo y mente Esa es la
administración de la salud o del cuerpo humano   </font></font>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">También
debemos administrar nuestros recursos económicos El producto
de nuestro trabajo lo debemos administrar de una manera razonable,
que nos permita nivelar ingresos con egresos Es decir, llevar
nuestras cuentas de cuanto ganamos y cuanto podemos gastar</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<font face="Century Schoolbook, serif"><font size="3" style="font-size: 12pt">Lo
mismo sucede cuando tenemos un negocio o trabajamos para una
negociación Por eso, administrar es dirigir la economía de
una persona o una entidad Es gobernar, regir Eso es lo que
trataremos de aprender en este nivel de educación media superior,
para poder integrarnos a la planta laboral de nuestra sociedad,
con los conocimientos básicos de la administración Más adelante,
si nos interesa, podremos, a nivel superior, estudiar para contador
público, abogado, licenciado en administración y otras carreras que
la industria, el comercio, la banca y el gobierno requieren
Vamos a enfocar nuestros conocimientos en la administración de
empresas, para integrarnos en las mejores condiciones a la
planta laboral-productiva de nuestro país</font></font></p>
<p class="western" align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="justify" style="text-indent: 039in; margin-bottom: 0in; line-height: 100%; page-break-after: avoid"><a name="CONTABILIDAD"></a>
