<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Detalle orden de env&iacute;o</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Ingresos</a>
			        <a href="#" class="btn btn-default">Viajes</a>
			        <a href="#" class="btn btn-default">Detalle</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title amaranth text-size-20">
				<span class="glyphicon glyphicon-tag"></span>
				<?php echo "Orden ". Util_Tools::format($data["id_shipping"], 4); ?>
			</h3>
		</div>
		<div class="panel-body">
			<div class="row">
				<div class="col-md-6">
					<fieldset class="responsive-fieldset fieldset">
					
						<legend class="legend amaranth">Informaci&oacute;n general</legend>
						
						<div class="table-responsive">
							<table class="table amaranth text-size-15">
							
								<tbody>
									<tr>
										<td>Cliente:</td>
			                       		<td><?php echo $data["name_company"]; ?></td>
									</tr>
									<tr>
										<td>Precio:</td>
			                       		<td><?php echo $data["cost_journey"]; ?></td>
									</tr>
									<tr>
										<td>Destino:</td>
			                       		<td><?php echo $data["name_destination"]; ?></td>
									</tr>
								</tbody>
							
							</table>
						</div>
					
					</fieldset>
				</div>
			</div>
			<div clasS="row">
				<div class="col-md-12">
				
					<fieldset class="responsive-fieldset fieldset">
					
						<legend class="legend amaranth">Informaci&oacute;n Operador / Ayudante</legend>
						
						<div class="row">
							<div class="col-md-6">
								<fieldset class="responsive-fieldset fieldset">
								
									<legend class="legend amaranth">Operador</legend>
									
									<div class="table-responsive">
										<table class="table amaranth text-size-15">
							
										<tbody>
											<tr>
												<td>Nombre:</td>
			                       				<td><?php echo $data["name_operator"]; ?></td>
											</tr>
											<tr>
												<td>Tarifa:</td>
			                       				<td><?php echo Util_Tools::currency($data["amount_operator"]); ?></td>
											</tr>
										</tbody>
							
										</table>
									</div>
								
								</fieldset>
							</div>
							<div class="col-md-6">
								<fieldset class="responsive-fieldset fieldset">
								
									<legend class="legend amaranth">Ayudante</legend>
									
									<div class="table-responsive">
										<table class="table amaranth text-size-15">
							
										<tbody>
											<tr>
												<td>Nombre:</td>
			                       				<td><?php echo $data["name_assistant"]; ?></td>
											</tr>
											<tr>
												<td>Tarifa:</td>
			                       				<td><?php echo Util_Tools::currency($data["amount_assistant"]); ?></td>
											</tr>
										</tbody>
							
										</table>
									</div>
								
								</fieldset>
							</div>
						</div>
						
						<!-- <div class="table-responsive">
							<table class="table amaranth text-size-15">
							
								<tbody>
									<tr>
										<td>Cliente:</td>
			                       		<td><?php echo $data["name_company"]; ?></td>
									</tr>
									<tr>
										<td>Precio:</td>
			                       		<td><?php echo $data["cost_journey"]; ?></td>
									</tr>
									<tr>
										<td>Destino:</td>
			                       		<td><?php echo $data["name_destination"]; ?></td>
									</tr>
									<tr>
										<td>Operador:</td>
			                       		<td><?php echo $data["name_operator"]; ?></td>
									</tr>
									<tr>
										<td>Ayudante:</td>
			                       		<td><?php echo $data["name_assistant"]; ?></td>
									</tr>
								</tbody>
							
							</table>
						</div> -->
					
					</fieldset>
				</div>
			</div>
		</div>
		<div class="panel-footer">
			<div class="clearfix">
				<a class="btn btn-default pull-right" href="<?php echo $this->basePath("/in/journey/index")?>">
					<span class="glyphicon glyphicon-repeat"></span>
					Regresar
				</a>
			</div>
		</div>
	</div>
</div>