<div id="fieldsetForm" class="forms">
<?=$this->element->getElement('idcurses'); ?>
<legend id="legendhelp">* Datos requeridos</legend>
<fieldset>
		<legend>Curso</legend>
    <table>
    		<tbody> 		
    		<tr>
                <td>*Nombre:</td>
                <td>*Tipo:</td>
            </tr>
    		<tr>
                <td><?=$this->element->getElement('name'); ?></td>
                <td><?=$this->element->getElement('type'); ?></td>
            </tr>
            <tr>
             	<td>*Fecha Inicial:</td>
  				<td>*Fecha Final:</td>     
            </tr>         
            <tr>
            	<td><?=$this->element->getElement('date_start'); ?></td>
               	<td><?=$this->element->getElement('date_finish'); ?></td>
            </tr>         
            <tr>
             	<td>*N&uacute;mero de integrantes:</td>
  				<td>*Status:</td>     
            </tr>         
            <tr>
            	<td><?=$this->element->getElement('members'); ?></td>
               	<td><?=$this->element->getElement('status'); ?></td>
            </tr>
             
    		<tr style="text-align: center;">
               	<td colspan="5">Descripci&oacute;n:</td>
            </tr>
            <tr style="text-align: center;">
               	<td colspan="5"><?=$this->element->getElement('description'); ?></td>
            </tr>
    		</tbody>		
    </table>
</fieldset>
	<div class="center">
		<?=$this->element->getElement('Guardar'); ?>
		<!--  
	    <a href="javascript:document.forms['coursesForm'].submit();" class="horusBtn big icon-iconsave">Guardar</a>
	    -->
	    <a href="javascript:location.href='<?=$this->baseUrl("/Ioteca/courses/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
	</div>
</div>