<?php
// Generated by ZF2's ./bin/classmap_generator.php
return array(
    'In\Module'                        => __DIR__ . '/Module.php',
    'In\Controller\CustomersController' => __DIR__ . '/src/In/Controller/CustomersController.php',
    'InTest\Framework\TestCase'        => __DIR__ . '/tests/In/Framework/TestCase.php',
    'InTest\SampleTest'                => __DIR__ . '/tests/In/SampleTest.php',
);
