<h3 class="centerHor"> Agregar Visi&oacute;n</h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity">
			<a class="tooltipcenter" title="Visi&oacute;n" href="<?php echo $this->baseUrl('/vision/index')?>">
				<img title="Visi&oacute;n" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconvision.png')?>" /></a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser; ?>')">
			<a class="tooltipcenter" title="Ayuda">
				<img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
			</a>
		</li>
		<div id="clock"></div>
	</div>	
</ul>	

<div class="overflow">
	<p class="triangle-border" >Ingresa los datos de la visi&oacute;n.</p>
	<?php echo $this->form; ?>	
</div>    