<div id="fieldsetForm" class="forms">
<?=$this->element->getElement('idtutorial'); ?>
<legend id="legendhelp">* Datos requeridos</legend>
<fieldset>
		<legend>Datos del Manual</legend>
    <table>
    		<tbody> 		
	    		<tr>
	                <td>*Seleccione un Tipo de manual:</td>
	                <td>*Nombre del Manual:</td>
	                <td>*Autor:</td>
	            </tr>
	            <tr>
	                <td><?=$this->element->getElement('id_tipo'); ?></td>
	                <td><?=$this->element->getElement('name'); ?></td>
	                <td><?=$this->element->getElement('author'); ?></td>
	            </tr>   
	            <tr>
	             	<td>*Status:</td>
	                <td>*Url:</td>      
	            </tr>         
	            <tr>
	            	<td><?=$this->element->getElement('status'); ?></td>
	               	<td><?=$this->element->getElement('url'); ?></td>   		
	            </tr>
	    		<tr style="text-align: center;">
	               	<td colspan="5">Descripci&oacute;n:</td>
	            </tr>
	            <tr style="text-align: center;">
	               	<td colspan="5"><?=$this->element->getElement('description'); ?></td>
	            </tr>
    		</tbody>		
    </table>
</fieldset>
<div class="center">
	<?=$this->element->getElement('Guardar'); ?>
	<!--  
    <a href="javascript:document.forms['tutorialForm'].submit();" class="horusBtn big icon-iconsave">Guardar</a>
    -->
    <a href="javascript:location.href='<?=$this->baseUrl("/Ioteca/tutorial/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
</div>
</div>
