<script type="text/javascript">
$(function(){
    // 6 create an instance when the DOM is ready
    $('#jstree').jstree({ 'core' : {
      'data' :
    	<?php
    		$tree = $this->tree;
		 	echo stripcslashes($this->tree);
    	?>
    },
    "types" : {
 	      "root" : {
 	        "icon" : "<?php echo $this->basePath('/img/images/tree-icon.png')?>"
 	      },
 	    "folder" : {
 	        "icon" : "<?php echo $this->basePath('/img/images/folder.ico')?>"
 	      },
 	    "file" : {
 	      "icon" : "<?php echo $this->basePath('/img/images/file.png')?>"
 	    }
 	    },
 	    "plugins" : [ "state", "types" ]
    });
  });
</script>
<script>
function linkContent(idc){
	$("#paramform").attr("action","<?php echo $this->basePath('/Gutenberg/docs_contentsusermanual/index'); ?>");
    $('#id_topic_content').val(idc);
    document.paramform.submit();
}
function linkContentTopic(id){
	$("#paramform").attr("action","<?php echo $this->basePath('/Gutenberg/docs_topicsusermanual/index'); ?>");
    $('#id_topicSend').val(id);
    document.paramform.submit();
}
function parentLink(){
	window.location.href = "<?php echo $this->basePath('Gutenberg/docs_usermanual/index') ?>";
}
</script>

<div class="container">
	<div class="row">
		<div class="col-md-4"><h3>CETEC</h3></div>
		<div id="mensajes" class="col-md-6 col-md-offset-2"></div>
	</div>
	
	<div id="overflow" class="row">
<!-- 	<div id="mensajes"></div> -->
	
		<div id="jstree"  class="col-md-3" style="overflow-x: auto; overflow-y: auto;">
			<?php print_r($this->tree)?>
		</div>
		
		<div class="col-md-9" align="center">
			<div class="textContent">
				<div style="display:none;">
					<?php 
						//echo $this->formparam; 
					?>
				</div>
					<?php
					// echo $this->formcontentparam;
					?>
				<div class="wrap2 col-md-12" class="textContent">
					<h1 align="center" class="textContent" >
						Contenido del archivo <?php //echo $this->cont[0]['topic_name'];?>
					</h1>
					<div class="col-md-12">
						<script src="<?php 
										echo $this->basePath('/js/ck_editor/ckeditor.js')
									 ?>" >
							CKEDITOR.replace( 'editor1' );
						</script>
					</div>
					<div>
						<form method="post">
							<div style="display:none;">
							<?php //echo $this->form->id_content; ?>
							<?php //echo $this->form->id_topic_content; ?>
							</div>
							
							<?php //echo $this->form->content; ?>
							
							<div style="display: none;">
							<?php //echo $this->form->id_topic; ?>
							</div>
							<table>
							<tr>
							<td ><?php // echo $this->form->Guardar; ?></td>
							<td ><?php //echo $this->form->Cancelar; ?></td>
							</tr>
							<script>
							CKEDITOR.replace( 'editor1' );
							</script>
						</form>
					</div>
				</div>
			</div>
		</div>
	</div>
</div>