<?php

?>

<!-- <html> -->
<!-- 	<body> -->
<!-- 		<div class="container-fluid margin"> -->

<!-- 			<div class="col-sm-3 col-md-3 col-lg-3"> -->
<!-- 				<h2>Índice</h2> -->
<!-- 				[onload;file=[var.tmpl_menu];getbody=body;noerr] -->
<!-- 			</div> -->

<!-- 			<div class="col-sm-8 col-md-8 col-lg-8 col-md-offset-1"> -->
<!-- 				[onload;file=[var.tmpl_article];getbody;noerr] -->
<!-- 			</div> -->
<!-- 		</div> -->
<!-- 	</body> -->
<!-- </html> -->

<a href="<?php echo $this->a; ?>"><?php echo $this->a; ?></a>