<div class="container-fluid">
	<div class="row">
		<div class="col-md-10 col-md-offset-1">
			<?php
			$form = $this->form;
			$form->prepare();
			?>
			<?php echo $this->form()->openTag($form); ?>
			<div class="form-group">
    			<label for="amountInput">Monto</label>
    			<?php echo $this->formRow($form->get('amount')); ?>
  			</div>
  			<div class="form-group">
    			<?php echo $this->formRow($form->get('employee')); ?>
  			</div>
  			<div class="form-group">
    			<label for="descInput">Descripci&oacute;n</label>
  				<?php echo $this->formRow($form->get('description')); ?>
  			</div>
			<?php echo $this->form()->closeTag(); ?>
        </div>
	</div>
</div>