 <!-- Add IntroJs styles -->
<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/intro/introjs.css'; ?>" rel="stylesheet">

<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/overlay/jquery.blockUI.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/plainoverlay/jquery.plainoverlay.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/intro/intro.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">N&oacute;mina</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li>
						<a id="step1" href="<?php echo $this->basePath()."/horus/payroll/calendar";?>" data-placement="top" data-toggle="tooltip" title="Calendario" class="btn">
							<span class="glyphicon glyphicon-calendar"></span>
						</a>
					</li>
					<li>
						<a id="step2" href="<?php echo $this->basePath()."/horus/payroll/history";?>" data-placement="top" data-toggle="tooltip" title="Historial" class="btn">
							<span class="glyphicon glyphicon-folder-open"></span>
						</a>
					</li>
					<li>
						<a href="javascript:void(0);" class="btn" onclick="startIntro();" data-toggle="tooltip" data-placement="bottom" title="Ayuda">
							<span class=" glyphicon glyphicon-question-sign"></span>
						</a>
					</li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Horus</a>
			        <a href="#" class="btn btn-default">N&oacute;mina</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

	<div class="panel panel-default">
  		<div class="panel-heading">
    		<h3 class="panel-title amaranth text-size-20">N&oacute;mina</h3>
  		</div>
  		<div class="panel-body">
    		<p>La siguiente tabla contiene informaci&oacute;n relacionada a la n&oacute;mina</p>

    		<table id="payroll" class="table table-striped table-hover table-bordered">
				<thead>
					<tr>
						<th># Empleado</th>
						<th>Apellido Paterno</th>
						<th>Apellido Materno</th>
						<th>Nombre(s)</th>
						<th>Puesto</th>
						<!--<th>Sueldo</th>-->
						<th></th>
						<th></th>
					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->rows as $row) : ?>
					<tr>
						<td><?php echo Util_Tools::format($row['user_id'], 4) ?></td>
						<td><?php echo $row['surname']; ?></td>
						<td><?php echo $row['lastname']; ?></td>
						<td><?php echo $row['name']; ?></td>
						<td><?php echo $row['name_job']; ?></td>
						<!--<td><?php echo Util_Tools::currency($row['cost']); ?></td>-->
						<td id="step3">
							<button type="button" class="btn btn-success" data-user="<?php echo $row['user_id']; ?>" data-toggle="modal" data-target="#modalAddBonus" data-backdrop="static" data-keyboard="false" data-tool="tooltip" data-placement="top" title="Agregar Bono">
								<span class="glyphicon glyphicon-plus-sign"></span>
							</button>
						</td>
						<td id="step4">
							<button type="button" class="btn btn-danger" data-user="<?php echo $row['user_id']; ?>" data-toggle="modal" data-target="#modalAddDiscount" data-backdrop="static" data-keyboard="false" data-tool="tooltip" data-placement="top" title="Agregar Descuento">
								<span class="glyphicon glyphicon-minus-sign"></span>
							</button>
						</td>
					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>

  		</div>
	</div>

</div>

<!-- Modal -->
<div class="modal fade" id="modalAddBonus" tabindex="-1" role="dialog" aria-labelledby="labelAddBonus" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="labelAddBonus">Agregar Bono</h4>
			</div>
			<div class="modal-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-12">
							<form id="formAddBonus">
								<input type="hidden" name="iduser" class="form-control" />
								<input type="hidden" name="type" class="form-control" value="BONO" />
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="amount">Importe</label>
											<input type="text" name="amount" class="form-control input-numeric format-currency" placeholder="Importe" />
										</div>
									</div>
								</div>
								<!--<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="date">Fecha</label>
											<input type="text" name="date" class="form-control inputDate" placeholder="Fecha" />
										</div>
									</div>
								</div>-->
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label for="description">Descripci&oacute;n</label>
											<textarea name="description" class="form-control" rows="3"></textarea>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" id="buttonSaveBonus" class="btn btn-primary buttonSaveBonus">Guardar</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      		</div>
		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalAddDiscount" tabindex="-1" role="dialog" aria-labelledby="labelAddDiscount" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
				<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
				<h4 class="modal-title" id="labelAddDiscount">Agregar Descuento</h4>
			</div>
			<div class="modal-body">
				<div class="container-fluid">
					<div class="row">
						<div class="col-md-12">
							<form id="formAddDiscount">
								<input type="hidden" name="iduser" class="form-control" />
								<input type="hidden" name="type" class="form-control" value="DESCUENTO" />
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="amount">Importe</label>
											<input type="text" name="amount" class="form-control input-numeric format-currency" placeholder="Importe" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-6">
										<div class="form-group">
											<label for="numberpay">Numero de pagos</label>
											<input type="text" name="numberpay" class="form-control inputNumberPay input-numeric" placeholder="Numero de pagos" />
										</div>
									</div>
								</div>
								<div class="row">
									<div class="col-md-12">
										<div class="form-group">
											<label for="description">Descripci&oacute;n</label>
											<textarea name="description" class="form-control" rows="3"></textarea>
										</div>
									</div>
								</div>
							</form>
						</div>
					</div>
				</div>
			</div>
			<div class="modal-footer">
				<button type="button" class="btn btn-primary buttonSaveDiscount">Guardar</button>
				<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      		</div>
		</div>
	</div>
</div>

<script>
var $basePath = "<?php echo $this->basePath();?>";
$(document).on("ready", function(){

	$(".inputDate").datepicker({
			dateFormat      : 'dd/mm/yy' ,
			dayNames        : ["Domingo", "Lunes", "Martes", "Miércoles", "Jueves", "Viernes", "Sábado"],
			dayNamesMin     : ["Do", "Lu", "Ma", "Mi", "Ju", "Vi", "Sá"],
			dayNamesShort   : ["Dom", "Lun", "Mar", "Mié", "Jue", "Vie", "Sáb"],
			monthNames      : ["Enero", "Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre"],
			monthNamesShort : ["Ene", "Feb","Mar","Abr","May","Jun","Jul","Ago","Sep","Oct","Nov","Dic"],
	}).datepicker("setDate", new Date());

	// Datatable
	$("#payroll").DataTable({
		"aoColumnDefs" : [ {
	    	'bSortable' : false,
	        'aTargets' : [5, 6]
		} ],
		"order": [[ 1, "asc" ]]
	});

	$("[data-toggle=tooltip]").tooltip();

	/*
		CLICK EN EL BOTON AGREGAR BONO
	 */
	$("#modalAddBonus").on('show.bs.modal', function(event){
		// Obtenemos el boton que activo el modal
		var $button  = $(event.relatedTarget);
		// Obtener el data-user del boton
		var $id_user = $button.data('user');
		$(this).find(".modal-body input[name=iduser]").val($id_user);
	});

	/*
		CLICK EN EL BOTON GUARDAR BONO
	 */
	$(".buttonSaveBonus").on("click", function(e){
		var $fomName   = "#formAddBonus";
		var $modalName = "#modalAddBonus";
		alertify.confirm("Seguro de agregar el bono?", function(e){
			if(e){
				//Mostramos animacion de cargando
				$("#modalAddBonus").find(".modal-dialog").plainOverlay('show');
				addAmount($fomName, $modalName);
			}
		});
	});

	/*
		CLICK EN EL BOTON AGREGAR DESCUENTO
	*/
	$("#modalAddDiscount").on('show.bs.modal', function(event){
		// Obtenemos el boton que activo el modal
		var $button  = $(event.relatedTarget);
		// Obtener el data-user del boton
		var $id_user = $button.data('user');
		$(this).find(".modal-body input[name=iduser]").val($id_user);
	});

	/*
		CLICK EN EL BOTON GUARDAR DESCUENTO
	 */
	$(".buttonSaveDiscount").on("click", function(e){
		var $fomName = "#formAddDiscount";
		var $modalName = "#modalAddDiscount";
		alertify.confirm("Seguro de agregar el descuento?", function(e){
			if(e){
				//Mostramos animacion de cargando
				$("#modalAddDiscount").find(".modal-dialog").plainOverlay('show');
				addAmount($fomName, $modalName);
			}
		});
	});

	/*
		CUANDO SE CIERRAN LAS VENTANAS MODALES
	 */
	$('.modal').on('hidden.bs.modal', function (e) {
		if(e.currentTarget.id == "modalAddBonus"){$("#formAddBonus")[0].reset();}
		if(e.currentTarget.id == "modalAddDiscount"){$("#formAddDiscount")[0].reset();}
		console.log(e.currentTarget.id);
	});

});

/*
	MOSTRAR TUTORIAL
*/
var intro = introJs();

function startIntro(){

    intro.setOptions({
        steps: [
            {
            	intro: "<p class='text-center'><strong><span class='glyphicon glyphicon-pushpin'></span> Lista de empleados en n&oacute;mina.</strong></p>",
            },
            {
            	element: document.querySelector('#step1'),
            	intro: "Calendario con las fechas de pago de la n&oacute;mina.",
            	position: 'bottom-middle-aligned'
            },
            {
            	element: document.querySelector('#step2'),
            	intro: "Historial de n&oacute;mina por usuario.",
                position: 'bottom-middle-aligned'
            },
            {
                element: '#step3',
                intro: 'Agregar un bono que sera reflejado en la n&oacute;mina.',
                position: 'left'
            },
            {
                element: '#step4',
                intro: "Agregar un descuento que sera reflejado en la n&oacute;mina.",
                position: 'left'
            }
        ],
        nextLabel : "Siguiente <span class='glyphicon glyphicon-arrow-right'></span>", // Etiqueta siguiente botón
        prevLabel : "<span class='glyphicon glyphicon-arrow-left'></span> Anterior", // Etiqueta del botón Anterior
        skipLabel : "<span class='glyphicon glyphicon-remove'></span> Omitir", // Etiqueta del botón Saltar
        doneLabel : "<span class='glyphicon glyphicon-ok'></span> Completo", // Etiqueta del botón Completo
        exitOnEsc: false, // Introducción Salir al pulsar el botón Escape, verdadero o falso
        exitOnOverlayClick : false, // Introducción Salir al hacer clic en la capa de revestimiento, verdadero o falso
        showStepNumbers: false, // Mostrar los pasos del número en el círculo rojo o no, verdadero o falso
		keyboardNavigation: true, // Navegar con el teclado o no, verdadero o falso
        showButtons : true, // Botones de navegación Mostrar introducción o no, verdadero o falso
		showBullets : true, // Mostrar balas introducción o no, verdadero o falso
		showProgress : true, // Mostrar progreso introducción o no, verdadero o falso
		//overlayOpacity : 0.9, // Ajuste la opacidad de superposición, Número
		scrollToElement : true, // Auto de desplazamiento para el elemento resaltado, si está fuera de la ventana gráfica, verdadera o falsa
    });

    intro.start();
}

/*
 * FUNCION PARA AGREGAR UN IMPORTE A ALGUN EMPLEADO
 */
function addAmount($form, $modal)
{
	$.ajax({
		method   : "POST",
		url      : $basePath + "/horus/payroll/addamount",
		dataType : "json",
		data     : $($form).serializeArray()
	})
	.done(function(response) {
		$($modal).find(".modal-dialog").plainOverlay('hide');
		alertify.set({ delay: 1000 });
	  	alertify.success("Agregado correctamente");
	  	setTimeout(function(){
			$($modal).modal('hide');
		}, 2000);

		console.log( "done" );
	})
	.fail(function() { console.log( "error" ); })
	.always(function() { console.log( "complete" ); });
}
</script>