<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/checkbox/label-checkbox.css'; ?>" rel="stylesheet" />

<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/overlay/jquery.blockUI.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/plainoverlay/jquery.plainoverlay.js'; ?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/payroll/listpayroll.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">N&oacute;mina Pagar</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="<?php echo $this->basePath()."/horus/payroll/index";?>" data-placement="top" data-toggle="tooltip" title="Listado Nomina" class="btn"> <span class="glyphicon glyphicon-list"></span></a></li>
					<li><a href="<?php echo $this->basePath()."/horus/payroll/history";?>" data-placement="top" data-toggle="tooltip" title="Historial" class="btn"> <span class="glyphicon glyphicon-folder-open"></span></a></li>
					<li><a href="<?php echo $this->basePath()."/horus/payroll/calendar";?>" data-placement="top" data-toggle="tooltip" title="Calendario" class="btn"> <span class="glyphicon glyphicon-calendar"></span></a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Horus</a>
			        <a href="#" class="btn btn-default">N&oacute;mina</a>
			        <a href="#" class="btn btn-default">Lista</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

	<div class="row">
		<div class="col-md-12">
			<?php
			$meses      = array("Undefined","Enero","Febrero","Marzo","Abril","Mayo","Junio","Julio","Agosto","Septiembre","Octubre","Noviembre","Diciembre");
			$diasSemana = array("Domingo","Lunes","Martes","Mi&eacute;rcoles","Jueves","Viernes","S&aacute;bado");
			$fechaDesde = date('Y-m-d',strtotime('-7 days', strtotime($this->date)));
			$fechaHasta = date('Y-m-d',strtotime('-1 days', strtotime($this->date)));
			$fechaDesdeTexto = $diasSemana[date("w",strtotime($fechaDesde))].", ".date("d",strtotime($fechaDesde))." de ".$meses[intval(date("m",strtotime($fechaDesde)))]." del ".date("Y",strtotime($fechaDesde));
			$fechaHastaTexto = $diasSemana[date("w",strtotime($fechaHasta))].", ".date("d",strtotime($fechaHasta))." de ".$meses[intval(date("m",strtotime($fechaHasta)))]." del ".date("Y",strtotime($fechaHasta));
			?>
			<div style="margin: 0; margin-bottom:30px;" class="page-header">
  				<h1 style="margin:0;" class="font-raleway">N&oacute;mina, <small><?php echo $fechaDesdeTexto ." al ".$fechaHastaTexto;?></small></h1>
			</div>
		</div>
	</div>

	<div class="row">
		<div class="col-md-12">

			<fieldset class="responsive-fieldset fieldset">
				<legend class="legend amaranth">Generar N&oacute;mina</legend>

				<div class="form-group">
					<div class="row">
						<div class="col-md-6 col-md-offset-3">
							<!-- <p class="text-info">Realizar pago:</p> -->
							<p>
								<span style="display:inline-block;" class="text-info">Realizar pago:</span>
								<label style="display:inline-block;" for="checkall" class="label-checkbox">
			  						<input type="checkbox" id="checkall" value="checkall"/>
			  						<i></i> <span>Todos</span>
								</label>
							</p>
							<button type="button" id="addPayRoll" class="btn btn-primary btn-lg btn-block">Pagar N&oacute;mina</button>
						</div>
					</div>
				</div>

			</fieldset>
			<hr>
		</div>
	</div>

	<div class="panel panel-primary">
  		<div class="panel-heading">
  			<div class="clearfix">
  				<h3 style="margin-top:6px;" class="panel-title amaranth text-size-20 pull-left">N&oacute;mina a pagar</h3>
  				<a href="<?php echo $this->basePath()."/horus/payroll/download/".$type."/".$date;?>" class="btn btn-warning pull-right" data-toggle="tooltip" data-placement="top" title="Exportar Nomina">
  					<i class="fa fa-file-excel-o"></i>
  				</a>
  			</div>

  		</div>
  		<div class="panel-body">
    		<p>La siguiente tabla contiene informaci&oacute;n relacionada a la n&oacute;mina a pagar</p>

    		<table id="listpayroll" class="table table-striped table-hover table-condensed table-bordered">
				<thead>
					<tr>
						<th></th>
						<th>#</th>
						<th>Nombre(s)</th>
						<th>A. Paterno</th>
						<th>A. Materno</th>
						<!--<th>Puesto</th>-->
						<!--<th>Ingreso</th>-->
						<th>Percepciones</th>
						<th>Deducciones</th>
						<th>Total a Pagar</th>
						<!-- <th></th> -->
						<th>Pagado?</th>
						<th></th>
						<th></th>

					</tr>
				</thead>
				<tbody>
					<?php foreach ($this->rows as $row) : ?>
					<tr id="<?php echo "user".$row['user_id']; ?>">
						<td style="text-align:center;">
							<?php if ($row['pay'] == 0) :?>
							<label for="<?php echo $row['user_id']; ?>" class="label-checkbox">
  								<input type="checkbox" id="<?php echo $row['user_id']; ?>" class="payCheck" value="<?php echo $row['user_id']; ?>"/>
  								<i></i>
							</label>
							<?php endif; ?>
						</td>
						<td><?php echo Util_Tools::format($row['user_id'], 4) ?></td>
						<td><?php echo $row['name']; ?></td>
						<td><?php echo $row['surname']; ?></td>
						<td><?php echo $row['lastname']; ?></td>
						<!--<td><?php //echo $row['name_job']; ?></td>-->
						<!--<td><?php //echo Util_Tools::currency($row['cost']); ?></td>-->
						<td>
							<?php echo Util_Tools::currency($row['info']['bonos']); ?>
						</td>
						<td>
							<?php echo Util_Tools::currency($row['info']['descuentos']); ?>
						<td>
							<!--<a class="btn buttonDetailPayrollUser" data-user="<?php //echo $row['user_id']; ?>" data-toggle="tooltip" data-placement="top" title="Detalle Nomina">
								<span class="glyphicon glyphicon-plus-sign"></span>
								<?php //echo Util_Tools::currency($row['info']['salario_total']); ?>
							</a>-->
							<!-- <button type="button" class="btn btn-primary buttonDetailPayrollUser" data-user="<?php echo $row['user_id']; ?>">
								<span class="glyphicon glyphicon-plus-sign"></span>
							</button> -->
							<a class="btn" data-toggle="modal" data-target="#modalDetail" data-user="<?php echo $row['user_id']; ?>" data-total="<?php echo $row['info']['salario_total']; ?>" data-namempl="<?php echo $row['name']." ".$row['surname']." ".$row['lastname']; ?>" data-tool="tooltip" data-placement="top" title="Detalle Nomina" data-backdrop="static" data-keyboard="false">
								<span class="glyphicon glyphicon-info-sign"></span>
								<?php echo Util_Tools::currency($row['info']['salario_total']); ?>
							</a>
						</td>

						<!-- <td>
							<a class="btn btn-primary btn-sm buttonAddLoan" data-tooltip="tooltip" data-placement="top" title="Prestamos">
  								<span class="glyphicon glyphicon-usd"></span>
							</a>
						</td> -->
						<td>
							<?php echo ($row['pay'] > 0) ? '<span class="label label-success">Pagado</span>' : '<span class="label label-danger">Pendiente</span>' ;?>
						</td>
						<td>
							<?php if($row['pay'] == 0) : ?>
							<button type="button" class="btn btn-primary btn-sm" data-toggle="modal" data-target="#modalBonus" data-user="<?php echo $row['user_id']; ?>" data-tool="tooltip" data-placement="top" title="Bonos" data-backdrop="static" data-keyboard="false">
								<span class="glyphicon glyphicon-plus-sign"></span>
							</button>
							<?php endif; ?>
						</td>
						<td>
							<?php if($row['pay'] == 0) : ?>
							<button type="button" class="btn btn-danger btn-sm" data-toggle="modal" data-target="#modalDiscount" data-user="<?php echo $row['user_id']; ?>" data-tool="tooltip" data-placement="top" title="Descuentos" data-backdrop="static" data-keyboard="false">
								<span class="glyphicon glyphicon-minus-sign"></span>
							</button>
							<?php endif; ?>
						</td>

					</tr>
					<?php endforeach; ?>
				</tbody>
			</table>

  		</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalDetail" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title font-raleway" id="myModalLabel">DETALLE DE PAGO</h4>
      		</div>
      		<div class="modal-body">

      		</div>
     		<!--<div class="modal-footer">
        		<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      		</div>-->
    	</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalBonus" tabindex="-1" role="dialog" aria-labelledby="myModalLabelBonus" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title font-raleway" id="myModalLabelBonus">Lista de bonos</h4>
      		</div>
      		<div class="modal-body">

      		</div>
     		<div class="modal-footer">
     			<button type="button" id="aplicateBonus" class="btn btn-primary">Aplicar</button>
        		<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      		</div>
    	</div>
	</div>
</div>

<!-- Modal -->
<div class="modal fade" id="modalDiscount" tabindex="-1" role="dialog" aria-labelledby="myModalLabelDiscount" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
			<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title font-raleway" id="myModalLabelDiscount">Lista de descuentos</h4>
      		</div>
      		<div class="modal-body">

      		</div>
     		<div class="modal-footer">
     			<button type="button" id="aplicateDiscount" class="btn btn-primary">Aplicar</button>
        		<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
      		</div>
    	</div>
	</div>
</div>

<div class="modal fade" id="modalLoans" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
		<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title">Prestamos</h4>
      		</div>
      		<div class="modal-body">
      		</div>
      		<div class="modal-footer">
      			<button type="button" class="btn btn-primary saveLoans">Guardar</button>
        		<button type="button" class="btn btn-default" data-dismiss="modal">Cerrar</button>
      		</div>
		</div><!-- /.modal-content -->
	</div><!-- /.modal-dialog -->
</div><!-- /.modal -->

<style>
/*.modal-backdrop {
  position: fixed;
  bottom: 0;
  height: auto !important; \\ to override bootstrap defined height which won't take into account dynamic height
}*/

/* ESTILO PARA LAS TARJETAS */
.card {
  box-shadow: 0 2px 5px 0 rgba(0, 0, 0, 0.16), 0 2px 10px 0 rgba(0, 0, 0, 0.12);
}

.card {
  margin-top: 10px;
  box-sizing: border-box;
  border-radius: 2px;
  background-clip: padding-box;
  padding : 10px;
}
.card span.card-title {
    color: #ccc;
    font-size: 18px;
    font-weight: 300;
    text-transform: uppercase;
}

.card .card-image {
  padding: 10px;
  border-radius: 0 0 2px 2px;
  background-clip: padding-box;
  box-sizing: border-box;
  /*position: relative;
  overflow: hidden;*/
}
.card .card-image span.card-title {
  /*position: absolute;
  bottom: 0;
  left: 0;
  padding: 16px;*/
}
.card .card-content {
  padding: 10px;
  border-radius: 0 0 2px 2px;
  background-clip: padding-box;
  box-sizing: border-box;
}
.card .card-content p {
  margin: 0;
 /* color: inherit;*/
}
.card .card-content span.card-title {
  line-height: 48px;
}
.card .card-action {
  border-top: 1px solid rgba(160, 160, 160, 0.2);
  padding: 16px;
}
.card .card-action a {
  color: #ffab40;
  margin-right: 16px;
  transition: color 0.3s ease;
  text-transform: uppercase;
}
.card .card-action a:hover {
  color: #ffd8a6;
  text-decoration: none;
}
</style>

<script>
var $basePath = "<?php echo $this->basePath();?>";
var $date     = "<?php echo $this->date; ?>";
var $type     = "<?php echo $this->type; ?>";
</script>