<!DOCTYPE html>
<html lang="en">
  <head>
      <meta charset="utf-8">
      <meta http-equiv="X-UA-Compatible" content="IE=edge">
      <meta name="viewport" content="width=device-width, initial-scale=1">
      <meta name="description" content="Acl zf2">
      <meta name="author" content="">
      <link rel="shortcut icon" href="<?php echo $this->basePath("/public/img/logo_odisseo_bk.png"); ?>">

      <title>Bachillerato CTEC</title>

      <!-- Bootstrap core CSS -->
      <link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/bootstrap.min.css';?>" rel="stylesheet">
      
       <!-- NORMALIZE CSS -->
        <link rel="stylesheet" href="<?php echo $this->basePath().'/public/horus-security/css/Normalize/normalize.css'; ?>">
      

      <!-- Custom styles for this template -->
      
      <link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/styleOsiris.css';?>" rel="stylesheet">
       <link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/styleLayoutOsiris.css';?>" rel="stylesheet">
      
      <!--<link href="<?php //echo $this->basepath("/public/css/pace-theme-center-atom.css"); ?>" rel="stylesheet">-->
       <link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/alertify/themes/alertify.core.css';?>" rel="stylesheet">
        <link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/alertify/themes/alertify.default.css';?>" rel="stylesheet">
   
      <link href='http://fonts.googleapis.com/css?family=Pacifico' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Nunito:400,300,700' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Lobster' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Nova+Flat' rel='stylesheet' type='text/css'>
      <link href='http://fonts.googleapis.com/css?family=Poiret+One' rel='stylesheet' type='text/css'>
      
    <!-- Bootstrap core JavaScript
      ================================================== -->
      <!-- Placed at the end of the document so the pages load faster -->
      <script src="https://ajax.googleapis.com/ajax/libs/jquery/1.11.0/jquery.min.js"></script>
      <script src="<?php echo $this->basePath("/public/js/bootstrap.min.js");?>"></script>
     <script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/alertify/lib/alertify.min.js';?>"></script>
      <!-- jquery plainoverlay js -->
        <script src="<?php echo $this->basePath() . '/public/horus-security/js/plainoverlay/jquery.plainoverlay.js'; ?>"></script>
        <script data-pace-options='{ "ajax": false }' src="<?php echo $this->basePath("/public/horus-security/js/pace/pace.min.js");?>"></script>
        
    <!--<script data-pace-options='{ "ajax": false }' src="<?php echo $this->basePath("/public/js/pace.js");?>"></script>-->
      <!-- Just for debugging purposes. Don't actually copy this line! -->
      <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

      <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
      <!--[if lt IE 9]>
        <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
        <script src="https://oss.maxcdn.com/libs/respond.js/1.4.2/respond.min.js"></script>
      <![endif]-->
      
      <style>
      *{
    border: 0 none;
    margin: 0;
    padding: 0;
}

body{
  margin-top : 0;
}



      </style>
      
      <script>
//      $(window).scroll(function() {
//          if ($(this).scrollTop() > 1){  
//              $('header').addClass("sticky");
//          }
//          else{
//              $('header').removeClass("sticky");
//          }
//      });
      </script>
  </head>
  
  <body>

   <nav class="navbar navbar-default navbar-fixed-top" style="background-color:#3399ff;border:none;">
    <div class="container-fluid">
      <div class="navbar-header">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target="#myNavbar">
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <a class="navbar-brand" href="#"><img class="logo" style="margin-top:-6px" src="<?php echo $this->basePath().'/public/img/ODISEO.png';?>"</a>
      </div>
      <div class="collapse navbar-collapse ca_menu" id="myNavbar">
        <ul class="nav navbar-nav navbar-right">
              <li><a class="menuHeader" href="#">Inicio</a></li>
              <li><a class="menuHeader" href="#">Misi&oacute;n</a></li>
              <li><a class="menuHeader" href="#">Visi&oacute;n</a>
              <li><a class="menuHeader" href="#">Acerca de Nosotros</a></li>
              <li><a class="menuHeader" href="#">Contacto</a></li>
              <li><a class="menuHeader" href="#"></a></li>
        </ul>
      </div>
    </div>
  </nav>
<div class="ca_heading_wrap">
  <div class="container">
    <div class="row">
      <div class="col-lg-12 col-md-12 col-sm-12">
        <div class="col-lg-6 col-md-6 col-sm-6 col-xs-6 ca_page_title">
        
        </div>
              </div>
      </div>
    </div>
  </div>
</div>

<br>
<br>
  
    
    <!-- Begin page content -->
    <div class="container">
        <?php echo $this->content; ?>
      </div>
      
<div class="ca_copyright">
  <div class="container">
    <div class="row">
               <div class="col-md-12">
                <center>
                  <p class="nova-flat blanco"><?php echo date("Y");?> &copy; IOfractal. Todos los derechos reservados.
                    <br> 
                    <a href="#">Pol&iacute;ticas de privacidad</a> | <a href="#">Condiciones de servicio</a>
                  </p>
                  </center>
                </div>
        </div>
       
      </div>
    </div>
  </div>
</div>
      
  </body>
</html>

<style>
<style>
     .ctec{
        background-color:#3399ff;
    }
        .navbar,.navbar-collapse {
        border-color: #3399ff;
    }
    
    #mainslider{
      z-index:0;
    }
    
    .navbar-nav > li > a {
      padding-bottom: 15px !important;
      padding-top: 27px !important;
  }
  

    @media (max-width : 770px) {
    .logo{
        width: 200px;
        margin-top:20px;
     }

    .navbar-toggle{
      margin-top:13px !important;
    }
    
    }

    
    @media only screen and (min-width: 760px) and (max-width: 975px) { 
    .logo{
      margin-left: 16px;
        margin-top: -1px;
        width: 170px;
    }
    
    .parrafo2{
      margin-top: -48px;
    }
  }
  
</style>
