<script type="text/javascript">
$(document).ready(function() {
	jqueryTable('#link', 4);
});
</script>
<h3 class="centerHor">Links</h3>
<ul class="toolbar">
	<div id="icons">
		<li class="iconOpacity">
			<a class="tooltipcenter" title="Agreagra Nuevo" href="<?php echo $this->baseUrl('/Ioteca/link/add') ?>" > 
				<img class="iconOpacity" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png')?>" title="Agregar Nuevo" > 
			</a>
		</li>
		<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser; ?>')">
			<a href="javascript:;" title="Ayuda" class="tooltipcenter">
				<img title="Ayuda" style="height: 16px; width: 16px;" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>">
			</a>
		</li>
	<div id="clock"></div>
	</div>	
</ul>
<div id="overflow">
<table id="link" class="display"> 
   <thead>
    <tr>
        <th>Nombre</th>
        <th>URL</th>
        <th>Descripcion</th>
        <th>Registrado por</th>   
        <th>Fecha y Hora</th>  
        <th >
        	<a class="tooltipcenter" title="Agregar Nuevo" href="<?php echo $this->baseUrl('/Ioteca/link/add') ?>">
				<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconplus.png');?>" title="Agregar Nuevo">
			</a>
        </th>  
    </tr>
    </thead>
    <tbody>
    <?php if($this->link != 0) :?>
  		<?php foreach ($this->link as $link) : ?>	
        <tr>
            <td><?php echo $link->getName();?></td>
			<td><a href="<?php echo $link->getUrl();?>" target="_new" ><?php echo $link->getUrl();?> </a></td>
			<td><?php echo $link->getDescription();?></td>
			<td><?php echo $link->getNameUser(); ?></td>
			<td><?php echo $link->getDate_hour();?></td>	  
            <td>
            
                <a class="tooltipcenter" title="Actualizar" href="<?php echo $this->baseUrl('/Ioteca/link/update?l='.$link->getIdlink())?>"> 
					<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconedit.png')?>" title="Actualizar" alt="Actualizar">
				</a>    
            
	            <a class="tooltipcenter" title="Eliminar" onclick="javascript:deleteRecord('link',this,'<?php echo $link->getIdlink()?>','/Ioteca/link/delete')"> 
					<img class="iconOpacity" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconminus.png')?>" title="Eliminar link"	alt="Eliminar">
				</a>
			</td>
        </tr>
   <?php endforeach; ?>
   <?php endif;?>
    </tbody>
</table>
</div>