<link href="<?php echo $this->basePath() . '/public/js/joyride-master/joyride-2.1.css';?>" rel="stylesheet" type="text/css" />
<link href="<?php echo $this->basePath() . '/public/js/joyride-master/mobile.css';?>" rel="stylesheet" type="text/css" />
<script src="<?php echo $this->basePath() . '/public/js/joyride-master/jquery-1.10.1.js';?>"></script>
<script src="<?php echo $this->basePath() . '/public/js/joyride-master/jquery.joyride-2.1.js';?>"></script>
<script src="<?php echo $this->basePath() . '/public/js/joyride-master/jquery.cookie.js';?>"></script>
<script src="<?php echo $this->basePath() . '/public/js/joyride-master/modernizr.mq.js';?>"></script>


<?php $photo_file =  ($this->photo_file != "") ? $this->photo_file : $this->basePath()."/public/bootstrap-3.3.1/dist/img/icon-user.png";
?>

<div class="container">
	<div class="row">
		<div class="col-xs-12 col-sm-6 col-sm-offset-3 col-md-6 col-md-offset-3">

            <div class="page-header" style="margin: 0; margin-bottom:30px;">
            	
                <h1 class="font-raleway" style="margin:0;">
                <?php if($this->sexo=="H"){
                	echo "Bienvenido";
                }elseif($this->sexo=="M"){
                	echo "Bienvenida";
                }?>, <small><?php echo $this->user_name; ?>
                
                </small></h1>
            </div>

            <div class="card-user hovercard">
                <div class="cardheader"></div>

                <div class="avatar">
                    <img class="img-user" alt="" src="<?php echo $photo_file; ?>">
                </div>
                <div class="info">
                
                    <div class="title">
                        <?php //echo $this->user_name; ?>
                    </div>
                    <div class="desc">
                 <!--    <a href="#" id="tutorial">Pasos a seguir <span class="glyphicon glyphicon-question-sign"></span></a>
                  -->
  					<?php //echo "Rol: ".$this->rol_name; ?>
                    </div>
                    
                   <!--<div class="desc"><?php echo "Puesto: ".$this->name_job; ?></div>-->
                </div>
                <div class="bottom">
                    <!--<a class="btn btn-primary btn-twitter btn-sm" href="">
                        <i class="fa fa-twitter"></i>
                    </a>
                    <a class="btn btn-danger btn-sm" rel="publisher"
                       href="">
                        <i class="fa fa-google-plus"></i>
                    </a>
                    <a class="btn btn-primary btn-sm" rel="publisher"
                       href="">
                        <i class="fa fa-facebook"></i>
                    </a>
                    <a class="btn btn-warning btn-sm" rel="publisher" href="">
                        <i class="fa fa-behance"></i>
                    </a>-->
                </div>
            </div>

        </div>
	</div>
</div>
</div>
</div>

	    <ol id="joyRideTipContent">
	      <li data-class="" data-text="Siguiente">
	      	<p>En el men&uacute; "Bachillerato" encontraras 3 secciones</p>
	        <p>En la secci&oacute;n  "Mis notas" se encuentran tus apuntes que agregaste mientras estudiabas</p>
	        <p>En la secci&oacute;n  "Mis clases" se encuentran todos los temas de tu trimestre actual</p>
	    	<p>En la secci&oacute;n  "Mis exam&eacute;nes" podras realizar tu examen una vez que cumplas 80 horas de estudio</p>
	      </li>
	      <li data-class="" data-button="Siguiente" data-options="tipAnimation:fade">
	      	<p class="responsiveLoginInfo" style="display:none;">Dando click en tu foto de perfil podras consultar los detalles de tu perfil y cerrar tu sesi&oacute;n</p>
	        <p class="loginInfo">Dando click en el icono de la parte superior derecha donde aparece tu nombre podras consultar los detalles de tu perfil y cerrar tu sesi&oacute;n</p>
	      </li>
	      <li data-class="" class="welcome" data-button="Comenzar" data-options="tipLocation:right">
	        <h2>Bienvenido a tu bachillerato en linea</h2>
	        <p></p>
	      </li>
	    </ol>
	    

<script>


	$(document).on("click", "#tutorial", function(e){
		var $width = $(window).width(); 
		if($width > 850){
			$("#ingMenu").click();
			$('#joyRideTipContent').find('.responsiveLoginInfo').hide();
			$('#joyRideTipContent').find('.loginInfo').show();
		}else{
			$(".navbar-toggle").click();
			$('#joyRideTipContent').find('.loginInfo').hide();
			$('#joyRideTipContent').find('.responsiveLoginInfo').show();
		}

		$('#joyRideTipContent').joyride({
		      autoStart : true,
		      postStepCallback : function (index, tip) {
		      if (index == 2) {
		        $(this).joyride('set_li', false, 1);
		      }
		    },
		    modal:true,
		    expose: true
		});				

	
	});

</script>

<style>

.card-user {
    padding-top: 20px;
    margin: 10px 0 20px 0;
    background-color: rgba(214, 224, 226, 0.2);
    border-top-width: 0;
    border-bottom-width: 2px;
    -webkit-border-radius: 3px;
    -moz-border-radius: 3px;
    border-radius: 3px;
    -webkit-box-shadow: none;
    -moz-box-shadow: none;
    box-shadow: none;
    -webkit-box-sizing: border-box;
    -moz-box-sizing: border-box;
    box-sizing: border-box;
}
.card-user.hovercard {
    position: relative;
    padding-top: 0;
    overflow: hidden;
    text-align: center;
    background-color: rgba(214, 224, 226, 0.2);
}
.card-user.hovercard .cardheader {
    background: url("<?php echo $this->basePath();?>/public/img/4.jpg");
    background-size: cover;
    height: 200px;
}
.card-user.hovercard .avatar {
    position: relative;
    top: -100px;
    margin-bottom: -100px;
}
.card-user.hovercard .avatar .img-user {
    width: 200px;
    height: 200px;
    max-width: 200px;
    max-height: 200px;
    -webkit-border-radius: 50%;
    -moz-border-radius: 50%;
    border-radius: 50%;
    border: 5px solid rgba(255,255,255,0.5);
}
.card-user.hovercard .info {
    padding: 4px 8px 10px;
}
.card-user.hovercard .info .title {
    margin-bottom: 4px;
    font-size: 24px;
    line-height: 1;
    color: #262626;
    vertical-align: middle;
}
.card-user.hovercard .info .desc {
    overflow: hidden;
    font-size: 12px;
    line-height: 20px;
    color: #737373;
    text-overflow: ellipsis;
}
.card-user.hovercard .bottom {
    padding: 0 20px;
    margin-bottom: 17px;
}
.card-user.hovercard .btn{
    border-radius: 50%; width:32px; height:32px; line-height:18px;
}

</style>