<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/hover.css';?>" rel="stylesheet" media="all" />
<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/datepicker3.css';?>" rel="stylesheet" type="text/css" />
<!-- <link href="<?php //echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/bootstrap-wysihtml5/bootstrap3-wysihtml5.css';?>" rel="stylesheet" type="text/css" /> -->
<link href="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/css/AdminOsiris.css';?>" rel="stylesheet" type="text/css" />

<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/highcharts.js';?>"></script>
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/bootstrap-datepicker.js';?>"></script>
<!-- <script src="<?php //echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/bootstrap-wysihtml5/bootstrap3-wysihtml5.all.min.js';?>"></script> -->
<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/dashboard.js';?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="row">
			<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Panel de control</p></div></div>
			<div class="col-md-4">
				<div class="row">
				</div>
			</div>
			<div class="col-md-4">
				<div class="row">
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">

	<div class="row">

		<div class="row">
			
			<div class="col-md-3">
			
				<div class="small-box bg-aqua hvr-shutter-out-horizontal">
		        	<div class="inner">
		                <h3><?php echo count($this->shippings_active); ?></h3>
		            	<p>Ordenes de env&iacute;o activas</p>
		            </div>
		            <div class="icon">
		            	<i class="ion ion-bag"></i>
		            </div>
		            <a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal" data-backdrop="static" data-keyboard="false">
		            Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
		        	</a>
		    	</div>
		    	
		    	<div class="small-box bg-fuchsia hvr-bounce-to-right">
					<div class="inner">
						<h3><?php echo count($this->clients_active); ?></h3>
						<p>Clientes m&aacute;s activos</p>
					</div>
					<div class="icon">
						<i class="fa fa-users"></i>
					</div>
					<a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal2" data-backdrop="static" data-keyboard="false">
					Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
					</a>
				</div>
	       		
	       		<div class="small-box bg-light-blue hvr-rectangle-out">
		       		<div class="inner">
		            	<h3><?php echo count($this->trucks_active); ?></h3>
		               	<p>Unidades en viaje</p>
		        	</div>
		          	<div class="icon">
		           		<i class="fa fa-truck"></i>
		           	</div>
		        	<a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal3" data-backdrop="static" data-keyboard="false">
		          	Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
		        	</a>
		   		</div>
		    	
			</div> <!-- /.col-md-3 -->
			
			<div class="col-md-6">
			
				<div id="chart"></div>
			
			</div> <!-- /.col-md-6 -->
			
			<div class="col-md-3">
			
				<div class="small-box bg-yellow hvr-sweep-to-top">
		      		<div class="inner">
		     			<h3><?php echo count($this->users_active); ?></h3>
						<p>Empleados con m&aacute;s viajes</p>
					</div>
					<div class="icon">
						<i class="ion ion-person-add"></i>
					</div>
					<a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal4" data-backdrop="static" data-keyboard="false">
					Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
					</a>
		   		</div>
		   		
				<div class="small-box bg-red hvr-shutter-out-vertical">
					<div class="inner">
						<h3><?php echo count($this->trucks_available); ?></h3>
						<p>Unidades disponibles</p>
					</div>
					<div class="icon">
	                	<i class="fa fa-bar-chart"></i>
					</div>
					<a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal5" data-backdrop="static" data-keyboard="false">
					Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
					</a>
				</div>
				
				<div class="small-box bg-green hvr-radial-out">
	           		<div class="inner">
	                	<h3><?php echo count($this->employee_Attendance_today); ?></h3>
	                   	<p>Empeados con asistencia</p>
	          		</div>
	          		<div class="icon">
	            		<i class="fa fa-pie-chart"></i>
	           		</div>
	           		<a href="" class="small-box-footer" data-toggle="modal" data-target="#myModal6" data-backdrop="static" data-keyboard="false">
					Mas Informaci&oacute;n <i class="fa fa-arrow-circle-right"></i>
					</a>
	       		</div>
			
			</div> <!-- /.col-md-3 -->
			
		</div> <!-- /.row -->
		
		
		<div style="display:none" class="row">
			
			<div class="col-md-7">
			
				<div class="clock">
					<div id="Date"></div>
					<ul>
						<li id="hours"> </li>
						<li id="point">:</li>
						<li id="min"> </li>
						<li id="point">:</li>
						<li id="sec"> </li>
					</ul>
				</div>
			
			</div> <!-- /.col-md-6 -->
			
			<div class="col-md-5">
			
				<div class="box box-solid bg-green-gradient">
					<div class="box-header">
						<i class="fa fa-calendar"></i>
						<h3 class="box-title">Calendario</h3>
					</div> <!-- /.box-header -->
					<div class="box-body no-padding">
						<div id="calendar" style="width: 100%;"></div>
					</div> <!-- /.box-body -->
				</div> <!-- /.box -->
			
			</div> <!-- /.col-md-6 -->
			
		</div> <!-- /.row -->
		
		
		<div style="display:none" class="row">
		
			<div class="col-md-7">
			
				<!-- quick email widget -->
				<div class="box box-info">
					<div class="box-header">
						<i class="fa fa-envelope"></i>
						<h3 class="box-title">Correo electr&oacute;nico r&aacute;pido</h3>
							<!-- tools box -->
							<div class="pull-right box-tools">
								<button class="btn btn-info btn-sm" data-widget="remove" data-toggle="tooltip" title="Remove"><i class="fa fa-times"></i></button>
							</div><!-- /. tools -->
					</div>
					<div class="box-body">
						<form action="#" method="post">
							<div class="form-group">
								<input type="email" class="form-control" name="emailto" placeholder="Email to:"/>
							</div>
							<div class="form-group">
								<input type="text" class="form-control" name="subject" placeholder="Subject"/>
							</div>
							<div>
								<textarea class="textarea" placeholder="Message" style="width: 100%; height: 125px; font-size: 14px; line-height: 18px; border: 1px solid #dddddd; padding: 10px;"></textarea>
							</div>
						</form>
					</div>
					<div class="box-footer clearfix">
						<button class="pull-right btn btn-default" id="sendEmail">Enviar <i class="fa fa-arrow-circle-right"></i></button>
					</div>
				</div>
			
			</div> <!-- /.col-md-6 -->
			
			<div class="col-md-5">
			
				<!-- TO DO List -->
				<div class="box box-primary">
					<div class="box-header">
						<i class="ion ion-clipboard"></i>
						<h3 class="box-title">Lista de actividades</h3>
					</div><!-- /.box-header -->
					<div class="box-body">
						<ul class="todo-list">
							<li>
                            	<!-- drag handle -->
                            	<span class="handle">
                             		<i class="fa fa-ellipsis-v"></i>
                              		<i class="fa fa-ellipsis-v"></i>
                         		</span>
                    			<!-- checkbox -->
                               	<input type="checkbox" value="" name=""/>
                                <!-- todo text -->
                                <span class="text">Dise&ntilde;ar un bonito tema</span>
                                <!-- Emphasis label -->
                                <small class="label label-danger"><i class="fa fa-clock-o"></i> 2 mins</small>
                                <!-- General tools such as edit or delete-->
                                <div class="tools">
                                	<i class="fa fa-edit"></i>
                                    <i class="fa fa-trash-o"></i>
                               	</div>
                         	</li>
                          	<li>
                           		<span class="handle">
                        			<i class="fa fa-ellipsis-v"></i>
                          			<i class="fa fa-ellipsis-v"></i>
                    			</span>
                         		<input type="checkbox" value="" name=""/>
                              	<span class="text">Make the theme responsive</span>
                          		<small class="label label-info"><i class="fa fa-clock-o"></i> 4 hours</small>
                           		<div class="tools">
                           			<i class="fa fa-edit"></i>
                          			<i class="fa fa-trash-o"></i>
                            	</div>
                        	</li>
                            <li>
                           		<span class="handle">
                              		<i class="fa fa-ellipsis-v"></i>
                                	<i class="fa fa-ellipsis-v"></i>
                              	</span>
                             	<input type="checkbox" value="" name=""/>
                              	<span class="text">Let theme shine like a star</span>
                            	<small class="label label-warning"><i class="fa fa-clock-o"></i> 1 day</small>
                           		<div class="tools">
                              		<i class="fa fa-edit"></i>
                                	<i class="fa fa-trash-o"></i>
                          		</div>
                    		</li>
                          	<li>
                            	<span class="handle">
                            		<i class="fa fa-ellipsis-v"></i>
                               		<i class="fa fa-ellipsis-v"></i>
                           		</span>
                        		<input type="checkbox" value="" name=""/>
                            	<span class="text">Let theme shine like a star</span>
                         		<small class="label label-success"><i class="fa fa-clock-o"></i> 3 days</small>
                            	<div class="tools">
                              		<i class="fa fa-edit"></i>
                               		<i class="fa fa-trash-o"></i>
                            	</div>
                         	</li>
                         	<li>
                            	<span class="handle">
                               		<i class="fa fa-ellipsis-v"></i>
                               		<i class="fa fa-ellipsis-v"></i>
                              	</span>
                             	<input type="checkbox" value="" name=""/>
                            	<span class="text">Revise sus mensajes y notificaciones</span>
                          		<small class="label label-primary"><i class="fa fa-clock-o"></i> 1 week</small>
                           		<div class="tools">
                             		<i class="fa fa-edit"></i>
                                	<i class="fa fa-trash-o"></i>
                            	</div>
                            </li>
                         	<li>
                           		<span class="handle">
                                	<i class="fa fa-ellipsis-v"></i>
                                	<i class="fa fa-ellipsis-v"></i>
                           		</span>
                               	<input type="checkbox" value="" name=""/>
                                <span class="text">Let theme shine like a star</span>
                             	<small class="label label-default"><i class="fa fa-clock-o"></i> 1 month</small>
                              	<div class="tools">
                               		<i class="fa fa-edit"></i>
                                	<i class="fa fa-trash-o"></i>
                           		</div>
                        	</li>
               			</ul>
					</div><!-- /.box-body -->
					
                    <div class="box-footer clearfix no-border">
                   		<button class="btn btn-default pull-right"><i class="fa fa-plus"></i> Add item</button>
                	</div>
                                
         		</div><!-- /.box -->
			
			</div> <!-- /.col-md-6 -->
		
		</div> <!-- /.row -->
		
	</div> <!-- /.row -->
	
</div> <!-- /.container -->
                                
                                
<!-- Modal -->
<div class="modal fade" id="myModal" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-aqua">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Ordenes de env&iacute;o activas</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Cliente</th>
      							<th>Fecha</th>
      							<th>Estatus</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->shippings_active as $sh) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($sh['id_shipping'], 4);?></td>
      							<td><?php echo $sh['name_company']; ?></td>
      							<td><?php echo Util_Tools::dateFormat("-", $sh['start_date']); ?></td>
      							<td><span class="label label-success">Activo</span></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal2" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-fuchsia">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Clientes m&aacute;s activos</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Nombre</th>
      							<th>RFC</th>
      							<th>Total Viajes</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->clients_active as $cli) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($cli['id_company'], 4);?></td>
      							<td><?php echo $cli['name_company']; ?></td>
      							<td><?php echo $cli['rfc']; ?></td>
      							<td><?php echo $cli['totalShipp']; ?></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal3" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-light-blue">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Unidades en viaje</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Nombre</th>
      							<th>Placa</th>
      							<th>Viaje</th>
      							<th>Fecha</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->trucks_active as $truck) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($truck['id_inventories'], 4); ?></td>
      							<td><?php echo $truck['article']; ?></td>
      							<td><?php echo $truck['id_product']; ?></td>
      							<td><?php echo Util_Tools::format($truck['id_shipping'], 4); ?></td>
      							<td><?php echo Util_Tools::dateFormat("-", $truck['start_date']); ?></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal4" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-yellow">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Empleados con m&aacute;s viajes</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Nombre</th>
      							<th>Puesto</th>
      							<th>Total Viajes</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->users_active as $user) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($user['user_id'], 4);?></td>
      							<td><?php echo $user['name']." ".$user['surname']." ".$user['lastname']; ?></td>
      							<td><?php echo $user['name_job']; ?></td>
      							<td><?php echo $user['totalShipp']; ?></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal5" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-yellow">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Unidades disponibles</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Nombre</th>
      							<th>Placa</th>
      							<th>Modelo</th>
      							<th>Capacidad</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->trucks_available as $truck) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($truck['id_inventories'], 4); ?></td>
      							<td><?php echo $truck['article']; ?></td>
      							<td><?php echo $truck['id_product']; ?></td>
      							<td><?php echo $truck['model']; ?></td>
      							<td><?php echo $truck['model']." toneladas"; ?></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>

<!-- Modal -->
<div class="modal fade" id="myModal6" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
  <div class="modal-dialog modal-lg">
    <div class="modal-content">
      <div class="modal-header bg-yellow">
        <button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        <h4 class="modal-title" id="myModalLabel">Empeados con asistencia</h4>
      </div>
      <div class="modal-body">
      	<div class="container-fluid">
      		<div class="row">
      			<div class="col-md-12">
      				<table class="table table-striped table-hover dataTable">
      					<thead>
      						<tr>
      							<th>#</th>
      							<th>Nombre</th>
      							<th>Puesto</th>
      							<th>Fecha</th>
      						</tr>
      					</thead>
      					<tbody>
      						<?php foreach ($this->employee_Attendance_today as $user) : ?>
      						<tr>
      							<td><?php echo Util_Tools::format($user['id_user'], 4);?></td>
      							<td><?php echo $user['name']." ".$user['surname']." ".$user['lastname']; ?></td>
      							<td><?php echo $user['name_job']; ?></td>
      							<td><?php echo Util_Tools::dateFormat("-", $user['date_assistance']); ?></td>
      						</tr>
      						<?php endforeach; ?>
      					</tbody>
      				</table>
      			</div>
      		</div>
      	</div>
      </div>
    </div>
  </div>
</div>