<script src="<?php echo $this->basePath() . '/public/bootstrap-3.3.1/dist/js/inventory.js'; ?>"></script>

<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Agregar inventario</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<!--<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>-->
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Horus</a>
			        <a href="#" class="btn btn-default">Inventario</a>
			        <a href="#" class="btn btn-default">Agregar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	
	<p class="triangle-border text-size-20 font-open-sans">Ingresa los datos del nuevo art&iacute;culo.</p>
	
	<div class="content-forms">
	
		<div style="text-align:right;">
			<span style="text-align:right;" class="label label-info">* Datos requeridos</span>
		</div>
		
		<?php 	
		$form = $this->form; 
		$form->prepare(); 
		echo $this->form()->openTag($form);
		/* echo $this->formRow($form->get('id_inventory')); */
		?>
		
		<fieldset class="responsive-fieldset fieldset">
		
			<legend class="legend amaranth">
				<span class="glyphicon glyphicon-tag"></span> Informaci&oacute;n del equipo
			</legend>
			
			<div style="padding:30px;" class="col-md-4">
				<?php echo $this->formElement($form->get('file')); ?>
				<?php echo $this->formElement($form->get('photofilename')); ?>
				<?php echo $this->formElement($form->get('photofile')); ?>
				
				<strong><p class="text-center text-amaranth">Foto:</p></strong>
				
				<div id="preview" class="thumbnail">
    				<a href="#" id="file-select" class="btn btn-info">Elegir archivo</a>
    				<img style="width:200px; height:200px;" src="<?php echo $this->basePath()."/public/images/inventory.jpg";?>"/>
				</div>
				
			</div>
			
			<div class="col-md-8">
			
				<div class="col-md-6">
					<div class="form-group">
		          		<?php echo $this->formRow($form->get('types_id_types')); ?>
		         	</div>
		      	</div>
		      	
	          	<div class="col-md-6">
		           	<div class="form-group">
		           		<label>* Art&iacute;culo:</label>
		          		<?php echo $this->formRow($form->get('article')); ?>
		           	</div>
	           	</div>
			
				<div class="col-md-6">
	            	<div class="form-group">
	                	<label>No. serie:</label>
	                   	<?php echo $this->formRow($form->get('serialnumber')); ?>
	            	</div>
				</div>
			
				<div class="col-md-6">
	              	<div class="form-group">
	               		<label>Marca:</label>         
	               		<?php echo $this->formRow($form->get('brand')); ?>
	            	</div>
	            </div>
                                
	            <div class="col-md-6">
	            	<div class="form-group">
	                  	<label>Existencias:</label>
	                    <?php echo $this->formRow($form->get('amount')); ?>
	            	</div>
	            </div>
                
				<div class="col-md-6">
	            	<div class="form-group">
	                	<label>Modelo:</label>
	                    <?php echo $this->formRow($form->get('model')); ?>
	          		</div>
				</div>
				
				<div id="camposCamiones" style="display:none;">
				
				<div class="col-md-6">
	            	<div class="form-group">
	                	<label>Placa:</label>
	                    <?php echo $this->formRow($form->get('id_product')); ?>
	          		</div>
				</div>
				
				<div class="col-md-6">
	            	<div class="form-group">
	                	<label>Capacidad:</label>
	                    <?php echo $this->formRow($form->get('capacity')); ?>
	          		</div>
				</div>

				<div class="col-md-6">
					<label for="name" class="text-amaranth">* Tipo de unidad:</label>
					<?php $this->formRadio()->setSeparator('</div><div class="radio">'); ?>
					<div class="radio">
	    				<?php echo $this->formRadio($form->get('chilled_dry')->setValue(1)) ?>
					</div>
				</div>
				
				</div>
				
		      	<!-- col-xs-12 col-sm-6 col-md-6 -->
			
			</div> <!-- end col-md-8 -->
			
			<div class="col-md-12">
				<div class="col-md-4">
					<div class="form-group">
		          		<?php echo $this->formRow($form->get('state')); ?>
		         	</div>
		         </div>
		         <div class="col-md-4">
		         	<div class="form-group">
		          		<?php echo $this->formRow($form->get('id_department')); ?>
		           	</div>
		         </div>
		         <div class="col-md-4">
		         	<div class="form-group">
		          		<?php echo $this->formRow($form->get('id_employee')); ?>
		           	</div>
		         </div>
		    </div>
			
			<div style="padding-left:30px; padding-right:30px;" class="col-md-12">
	        	<div class="form-group">
		            <label>Descripci&oacute;n:</label>
		         	<?php echo $this->formRow($form->get('description')); ?>
		        </div>
	       	</div>
	           	
		</fieldset>
		
		<div style="margin-top: 15px; margin-bottom:10px;" class="row">
			<div class="col-md-6">
				<?php echo $this->formElement($form->get('saveInventory')); ?>
			</div>
			<div class="col-md-6">
				<a href="<?php echo $this->basePath()."/horus/inventory/index";?>" class="btn btn-danger btn-lg btn-block">Cancelar</a>
			</div>
		</div>
		
		<?php echo $this->form()->closeTag(); ?>
		
	</div>
	
</div>		

<script>
	var $basePath = "<?php echo $this->basePath();?>";
	var $photo    = ""
</script>