<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Eliminar inventario</p></div></div>
		<div class="col-md-4">
			<!--<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>-->
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Horus</a>
			        <a href="#" class="btn btn-default">Inventario</a>
			        <a href="#" class="btn btn-default">Eliminar</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="row">
		<div class="col-md-12">
			<h3 class="font-lato text-info text-center">&#191;Seguro que quieres eliminar "<?php echo $this->escapeHtml($data['article']); ?>"&#63;</h3>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-6 col-md-offset-3">
			<hr>
			<form action="" method="post">
				<input type="hidden" name="id" value="<?php echo (int) $data['id_inventories']; ?>" />
				<div class="row">
					<div class="col-md-6">
						<input type="submit" name="del" value="Aceptar" class="btn btn-primary btn-lg btn-block" />
					</div>
					<div class="col-md-6">
						<input type="submit" name="del" value="Cancelar" class="btn btn-danger btn-lg btn-block" />
					</div>
				</div>
			</form>
		</div>
	</div>
	
</div>