
<h3 style="text-align: center;" class="centerIn">Modificar Cliente Prospecto</h3>
<ul class="toolbar">
	<div id="icons">
				<li class="iconOpacity">
					<a href="<?php echo $this->baseUrl('/In/crm/index')?>"><img title="Clientes Prospecto" src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/icongroup.png')?>" /></a>
				</li>
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','En el formulario puede editar los datos de la compa&ntilde;ia y del contacto de la misma')">
				<a><img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>	
</ul>

<div class="center">
</div>
<?php echo $this->form; ?>
