<!DOCTYPE HTML PUBLIC "-//W3C//DTD HTML 4.0 Transitional//EN">
<html>
<head>
	<meta http-equiv="content-type" content="text/html; charset=utf-8">
	<title>BACHILLERATO  1er. Trimestre</title>
	<meta name="generator" content="LibreOffice 4.2.7.2 (Linux)">
	<meta name="author" content="Educación con Vida, para la Vida">
	<meta name="created" content="20130215;52300000000000">
	<meta name="changedby" content="Rossy CG">
	<meta name="changed" content="20141012;200500000000000">
	<style type="text/css">
	<!--
		@page { size: 8.27in 11.69in; margin-left: 1.18in; margin-right: 0.98in; margin-top: 0.49in; margin-bottom: 0.49in }
		@page:first { margin-top: 1.58in; margin-bottom: 0.49in }
		p { margin-bottom: 0.1in; direction: ltr; color: #00000a; line-height: 150%; text-align: left; widows: 2; orphans: 2 }
		p.western { font-family: "Century Schoolbook", serif; font-size: 12pt; so-language: es-ES }
		p.cjk { font-family: "Times New Roman"; font-size: 12pt; so-language: es-ES }
		p.ctl { font-family: "Tahoma"; font-size: 11pt; so-language: ar-SA }
		h1 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h1.western { font-family: "Century Schoolbook", serif; font-size: 16pt; so-language: es-MX }
		h1.cjk { font-family: "Times New Roman"; font-size: 16pt; so-language: es-ES }
		h1.ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		h2 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h2.western { font-family: "Century Schoolbook", serif; font-size: 22pt; so-language: es-ES }
		h2.cjk { font-family: "Times New Roman"; font-size: 22pt; so-language: es-ES }
		h2.ctl { font-family: "Tahoma"; font-size: 16pt; so-language: ar-SA; font-style: italic; font-weight: normal }
		h3 { text-indent: 0.39in; margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: left; widows: 2; orphans: 2 }
		h3.western { font-family: "Century Schoolbook", serif; font-size: 18pt; so-language: es-ES }
		h3.cjk { font-family: "Times New Roman"; font-size: 18pt; so-language: es-ES }
		h3.ctl { font-family: "Tahoma"; font-size: 12pt; so-language: ar-SA; font-style: italic; font-weight: normal }
		h6 { margin-top: 0in; margin-bottom: 0in; direction: ltr; color: #00000a; line-height: 100%; text-align: center; widows: 2; orphans: 2 }
		h6.western { font-family: "Times New Roman", serif; font-size: 18pt; so-language: es-MX }
		h6.cjk { font-family: "Times New Roman"; font-size: 18pt; so-language: es-ES }
		h6.ctl { font-family: "Times New Roman"; font-size: 12pt; so-language: ar-SA }
		a:link { color: #0000ff; so-language: zxx }
	-->
	</style>
</head>
<body lang="es-ES" text="#00000a" link="#0000ff" dir="ltr">
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h1 lang="es-MX" class="western" style="margin-right: -0in"><a name="INDICETEMAI"></a>
<font color="#000066"><font size="6" style="font-size: 22pt"><i>INDICE
- TEMA I</i></font></font></h1>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#INTRODUCCIÓN"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">INTRODUCCIÓN</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
    ..      </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#QUÍMICA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">QUÍMICA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   
...  
   </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#FUERZA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">FUERZA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   
.
     </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_ENERGÍA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">ENERGÍA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   
..   
  </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#AGUA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">EL
AGUA</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   
...  
   </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#GASES"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">GASES</font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   

     </span></font></font></font>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h6 lang="es-MX" class="western" style="margin-right: -0in"><font color="#0000ff"><font face="Century Schoolbook, serif"><font size="6" style="font-size: 22pt"><i>	PASA
AL SIGUIENTE TEMA: </i></font></font></font>
</h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in"><br>
</h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in; line-height: 200%">
<font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">	</font></font><a href="#TEMAII"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span style="font-weight: normal">2ª
INDICE</span></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
– TEMA II</font></font></u></span></font></a></h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in; line-height: 200%">
<font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">	</font></font><a href="#TEMAIII"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span style="font-weight: normal">3ª
INDICE</span></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
– TEMA III</font></font></u></span></font></a></h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in; line-height: 200%">
<font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">	</font></font><a href="#TEMAIV"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span style="font-weight: normal">4ª
INDICE</span></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
– TEMA IV</font></font></u></span></font></a></h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in; line-height: 200%">
<font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">	</font></font><a href="#TEMAV"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span style="font-weight: normal">5º
INDICE</span></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
– TEMA V</font></font></u></span></font></a></h6>
<h6 lang="es-MX" class="western" style="margin-right: -0in; line-height: 200%">
<font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">	</font></font><a href="#TEMAVI"><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span style="font-weight: normal">6º
INDICE</span></font></font></u></span></font><font color="#0000ff"><span lang="zxx"><u><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt">
– TEMA VI</font></font></u></span></font></a></h6>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<h2 class="western" style="margin-right: -0in"><a name="INTRODUCCIÓN"></a><a name="_INTRODUCCIÓN"></a>
<font color="#000066">INTRODUCCIÓN</font></h2>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#000066">El </font>
<font size="4" style="font-size: 14pt">hombre, para vivir en armonía
y de manera integral consigo mismo, con su sociedad y con la
naturaleza, debe conocerse, conocer su entorno, así como el por
qué de la vida, de la naturaleza, de la misma manera el cómo, el
cuándo, el qué y el dónde, las actividades y sus
consecuencias.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 150%">
<br>
</p>
<p style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 150%">
<font size="4" style="font-size: 14pt">El hombre siempre se ha
preguntado quién es, de qué está hecho, cómo creció, por qué se
enferma, por qué actúa; por qué come, respira y tiene necesidades
fisiológicas; por qué oye, ve, siente, habla, respira y muere. Cuál
es su relación con la naturaleza y con sus semejantes. Cómo se
reproduce, cómo se reproducen los animales, las plantas. Por
qué llueve, hace aire, calor, frío y tantas y tantas preguntas
más.</font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
