<h3 class="western" style="margin-right: -0in"><a name="FUERZA"></a><a name="_FUERZA"></a>
<font color="#000066"><i>FUERZA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Pero
también es cierto que todo está en movimiento. Para que haya
movimiento se requiere de una </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Fuerza"><font face="Century Schoolbook, serif"><i><b>fuerza</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">.
- </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=1E8rhGfRoFM"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=hDyP8WyJGjQ&amp;NR=1&amp;feature=fvwp"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif">Fuerza para
empujar, para cargar, para jalar, etc. A la fuerza se le define como
una acción que causa un efecto. La acción de empujar, de jalar
o de cargar, produce el efecto de trasladar o mover un objeto que
puede ser un coche, o levantar a una persona es una acción que
requiere una fuerza.   </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
quema de la gasolina produce gases que producen una fuerza que puede
presionar a los pistones del motor, lo que hace que gire el cigüeñal
y, por lógica, que se mueva el automóvil.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
   
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Otra
fuerza es la fuerza de la gravedad. Cuando lanzamos un objeto para
arriba, éste tiende a bajar. Esto es debido a la atracción de la
tierra sobre el objeto, es la fuerza que ejerce la tierra sobre el
mismo. Si no fuera así, el objeto lanzado quedaría suspendido en el
aire, no caería. Por eso vemos que todo lo que soltamos desde algo
alto, por ejemplo un edificio, tiende a caer al suelo. Cuando
saltamos, tenemos que realizar una fuerza grande dependiendo la
altura que saltemos. Sobre todo cuando lanzamos un objeto para
arriba o saltamos, depende </font><font face="Century Schoolbook, serif"><i><b>del
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Peso"><font face="Century Schoolbook, serif"><i><b>peso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
del objeto o de la persona que salta, es la fuerza que necesitamos.
La masa puede ser mucha, pero el peso poco. La masa puede ser poca y
el peso mucho.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
peso es debido a la fuerza gravitacional que ejerce la tierra sobre
el objeto o persona. La tierra jala todo cuerpo. Por eso todo
está sobre la tierra. Existe también la fuerza eléctrica; esta
fuerza tiene dos tipos: la negativa y la positiva. Si hay dos fuerzas
negativas o dos fuerzas positivas se repelen, se rechazan. Un
ejemplo son los imanes. Cuando acercamos uno al otro y se rechazan,
ejercen una fuerza de rechazo debido a las dos cargas iguales, es
decir que un lado del imán es positivo y el otro lado de otro imán
es positivo. Lo mismo sería el rechazo con fuerza, si un lado de un
imán es negativo y un lado de otro imán también lo es. Pero cuando
el lado de un imán es negativo y del otro imán es positivo, la
fuerza que se ejerce es de atracción, es decir, se juntan. Lo que
quiere decir que polos opuestos se atraen. La gente normalmente
observa, cuando da la mano a otra persona para saludarla, que se
produce una descarga eléctrica. Quiere decir que son polos iguales y
se rechazan. Lo mismo sucede cuando se besan, se produce una descarga
eléctrica que es una fuerza eléctrica de rechazo.</font></font></p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
