<h3 class="western" style="margin-right: -0in"><a name="_ENERGÍA"></a>
<font color="#000066"><i>ENERGÍA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Cuando
nosotros realizamos una acción, como caminar, martillar, subir
escaleras, escribir, pensar, comer, jugar, etc., estamos realizando
un </font><font face="Century Schoolbook, serif"><i><b>trabajo</b></i></font><font face="Century Schoolbook, serif">.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Cuando
un automóvil o un tractor lo encendemos y se pone en movimiento está
realizando un </font><font face="Century Schoolbook, serif"><i><b>trabajo</b></i></font><font face="Century Schoolbook, serif">.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Por
lo tanto,</font><font face="Century Schoolbook, serif"><b> </b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Trabajo"><font face="Century Schoolbook, serif"><i><b>trabajo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
es una fuerza que se ejerce o se hace a través de una distancia. Sin
embargo, hay momentos en que no podemos hacer un trabajo porque no
tenemos fuerzas. El automóvil no se pone en movimiento porque no
tiene fuerza. ¿Qué pasa?, lo que pasa es que tanto la persona como
el automóvil no tienen </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Energia"><font face="Century Schoolbook, serif"><i><b>energía</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>.</b></i></font><font face="Century Schoolbook, serif">
</font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">-
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=zPVF0iilvfc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=KsHp6uYjFbk"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font size="2" style="font-size: 9pt">
-</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
Por lo que, una persona con energía tiene la capacidad de hacer un
trabajo. Lo mismo un automóvil con energía es capaz de ponerse
en movimiento. Entonces: energía es la capacidad para realizar un
trabajo. Es también muy cierto que para que haya movimiento, una
fuerza debe superar a otra fuerza. Es decir, para que un automóvil
se mueva, la fuerza que se ejerce en el motor debe superar a otra
fuerza. Es decir, para que un automóvil se mueva, la fuerza que se
ejerce en el motor debe superar a la fuerza que presenta el automóvil
al estar parado. O lo que es lo mismo, el peso del automóvil
requiere de una fuerza mayor para moverlo. Lo mismo pasa a una
persona que debe ejercer una fuerza mayor a la que presenta el peso
de su cuerpo para levantarse del sillón en que está sentado y
ponerse en pie. Esto se llama trabajo y que se ha tenido la energía
necesaria para realizarlo. Nuestros músculos y nuestro cuerpo
gastaron energía en realizar un trabajo.   
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Existe
la energía solar. El sol produce esa energía y lo observamos cuando
esa energía es calorífica, caliente, la cual calienta el agua del
mar y la evapora; este es un trabajo, ya que en forma de vapor el
agua se mueve, trabaja y sube a la atmósfera en forma de nubes.
Estas nubes, cuando se enfrían se convierten en agua y se ejerce la
fuerza de atracción de la tierra y cae. Cae en las montañas,
en el mar, en todas partes y se le conoce por lluvia.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
