<h3 class="western" style="margin-right: -0in"><a name="AGUA"></a><a name="_EL_AGUA"></a>
<font color="#000066"><i>EL AGUA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Se
dice que el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Agua"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><i><b>agua</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
- </font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=zN58di9zLHs&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
- </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=Ov3xLFb8Lw8&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=U6OwBwcL9A8"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
</font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=tPNrq5U1feY"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
- </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=IIde2YLJ4zg&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=UcZjDAq0RaQ&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
7</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=3LLbL3rDNNM&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
8</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
-</font></font><font face="Century Schoolbook, serif"> </font><font face="Century Schoolbook, serif">es
el líquido vital</font><font face="Century Schoolbook, serif"><b>.
</b></font><font face="Century Schoolbook, serif">Es verdad que el
agua es la parte principal de la vida, ya que sin ésta no hay vida
vegetal y mucho menos animal. De ahí la importancia de cuidarla y
aprovecharla al máximo para guardar el equilibrio ecológico y,
sobre todo, la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Salud"><font face="Century Schoolbook, serif"><i><b>salud</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">de la naturaleza y
principalmente del </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hombre"><font face="Century Schoolbook, serif"><i><b>hombre</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Es
importante saber y familiarizarnos con los elementos químicos que
componen el agua, así como de otros elementos que componen la
materia que forma todo: cosas, muebles, coches, frutas, vegetales,
plantas, árboles, animales, pero, sobre todo, al hombre. El
agua está compuesta por </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrogeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font>
          <font face="Century Schoolbook, serif"><b>  </b></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=9oDo2lthkZ4"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
7</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt">
-</font></font><font face="Century Schoolbook, serif"> </font><font face="Century Schoolbook, serif">y
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxigeno"><font face="Century Schoolbook, serif"><i><b>oxigeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
      </font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=gOn__UI1HKQ"><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt">
</font></font><font face="Century Schoolbook, serif">No olvidemos
estos elementos. La fórmula del agua es (</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif">.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">¿Qué
significa (</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">)?
Significa que son </font><font face="Century Schoolbook, serif"><i><b>dos
átomos</b></i></font><font face="Century Schoolbook, serif"><i> de
</i></font><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">)
y </font><font face="Century Schoolbook, serif"><i><b>un átomo</b></i></font><font face="Century Schoolbook, serif">
de </font><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font><font face="Century Schoolbook, serif"><b>.</b></font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Pero</font><font face="Century Schoolbook, serif"><b>,
</b></font><font face="Century Schoolbook, serif">¿qué es un </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Átomo"><font face="Century Schoolbook, serif"><i><b>átomo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?
Es la mínima unidad de un elemento. Todos conocemos y usamos el
agua. El agua la podemos tocar, pesar, además, ocupa un lugar en el
espacio, igual que nosotros, entonces, es materia. Todo tipo de
materia está compuesta por </font><font face="Century Schoolbook, serif"><i><b>moléculas</b></i></font><font face="Century Schoolbook, serif">.
  </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">¿Qué
es una </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Molecula"><font face="Century Schoolbook, serif"><i><b>molécula</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?
Es la parte más pequeña de la materia, sin perder sus
propiedades de la sustancia original. Es decir, si tenemos un pedazo
de madera, lo podemos cortar hasta la parte más pequeña, que sólo
se ve a través del microscopio, pero que sigue siendo madera. Pero
cuando seguimos dividiendo esa porción última de la madera y
deja de ser madera, entonces sabemos que esa molécula de la materia
llamada madera, está formada por átomos de algunos elementos que
componen la materia llamada madera.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Este
es el caso del agua. El agua es materia líquida, que podemos ir
haciendo porciones cada vez menores, hasta llegar a su mínima
expresión, donde todavía es agua, esta es la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Molecula"><font face="Century Schoolbook, serif"><i><b>molécula</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Si esta molécula de agua la dividimos, deja de ser agua y nos
daremos cuenta que está compuesta por dos átomos de hidrógeno y
uno de oxígeno (</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">).
Pero aun así, podemos dividir el átomo de hidrógeno y nos
encontraremos que está formado por un </font><font face="Century Schoolbook, serif"><i><b>núcleo</b></i></font><font face="Century Schoolbook, serif">
y un </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Electron"><font face="Century Schoolbook, serif"><i><b>electrón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
¿Qué es el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Núcleo_atómico"><font face="Century Schoolbook, serif"><i><b>núcleo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
</font><font face="Century Schoolbook, serif"><i><b>núcleo</b></i></font><font face="Century Schoolbook, serif">
es centro del átomo que contiene </font><font face="Century Schoolbook, serif"><i><b>protones</b></i></font><font face="Century Schoolbook, serif">
y </font><font face="Century Schoolbook, serif"><i><b>neutrones</b></i></font><font face="Century Schoolbook, serif">.
¿Qué son los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Protones"><font face="Century Schoolbook, serif"><i><b>protones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?
Los </font><font face="Century Schoolbook, serif"><i><b>protones</b></i></font><font face="Century Schoolbook, serif">
son cargas positivas. Es energía positiva. ¿Y los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Neutrón"><font face="Century Schoolbook, serif"><i><b>neutrones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?,
son carga neutra. Alrededor del núcleo giran los electrones. ¿Que
son los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Electron"><font face="Century Schoolbook, serif"><i><b>electrones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?
Los </font><font face="Century Schoolbook, serif"><i><b>electrones</b></i></font><font face="Century Schoolbook, serif">
son cargas negativas. Energía negativa. Recordemos que cargas
positivas atraen a las negativas. De ahí que exista un equilibrio
entre cargas negativas y positivas. Debe haber el mismo número de
cargas positivas y negativas.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<span dir="ltr" style="float: left; width: 3.25in; height: 1.1in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<img src="data:image/png;base64,iVBORw0KGgoAAAANSUhEUgAAAFUAAAAFCAYAAAA0e6CtAAAACXBIWXMAAA64AAAQRwHv3YZTAAABEElEQVR4nGP5//8/w2AA8fHxCwsKCiYYGhqeH2i3kAImTZqUx8PD8yUuLm4RCwvLH5AYy0A7CgYOHDjgsGTJkpioqKhlra2t1XJyco8G2k3EgOfPn0t2dHRU9Pb2FoNoX1/fzSzfvn3j2rp1q/dAO+779++c//79YwIF7ObNm30PHTpkp6end4kaZv/69YttwYIFCdQwCx1cuHDBAERfu3ZNy8/Pb1NdXV0TC8gj79+/F6SFhaQAkDtAdGBg4Pqurq4yFRWVO9Qym5GR8b+goOB7apmHDDg4OH6AaC0trWvwlAoqD9LS0mbRwkJSwLZt27xAZaqDg8MBapvNysr6OzQ0dDW1zQUBUPYHBSRymQoAZe1s8gK3rccAAAAASUVORK5CYII=" align="left" hspace="12"><br>
	</p>
	<h1 lang="es-MX" class="western" style="background: #e6e6e6"><font color="#000080"><font size="4" style="font-size: 14pt"><i>HIDRÓGENO</i></font></font></h1>
	<p lang="es-MX" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
</span><br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
        <font face="Times New Roman, serif"><font face="Century Schoolbook, serif">En
el caso del </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
cuyo símbolo es (</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif"><b>,
</b></font><font face="Century Schoolbook, serif">es un elemento que
compone al agua, tiene un </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Protón"><font face="Century Schoolbook, serif"><i><b>protón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
(</font><font face="Century Schoolbook, serif"><i><b>positivo</b></i></font><font face="Century Schoolbook, serif">)
en el núcleo y un </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Electron"><font face="Century Schoolbook, serif"><i><b>electrón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
(</font><font face="Century Schoolbook, serif"><i><b>negativo</b></i></font><font face="Century Schoolbook, serif">)
que gira alrededor del núcleo.</font></font></p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">De
la misma manera nos vamos a encontrar otros elementos químicos que
su formación está de acuerdo al número de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Protón"><font face="Century Schoolbook, serif"><i><b>protones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,
</b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Neutrón"><font face="Century Schoolbook, serif"><i><b>neutrones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Electron"><font face="Century Schoolbook, serif"><i><b>electrones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><span lang="es-MX">
   </span></font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxigeno"><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i>
</i></font><font face="Century Schoolbook, serif">es el otro elemento
químico que forma el agua y su símbolo es la letra (</font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">).
El </font><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font><font face="Century Schoolbook, serif">
tiene dos electrones y lógicamente dos protones. Entonces,
para unirse al hidrógeno y formar el compuesto agua se requieren dos
átomos de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">,
ya que cada átomo tiene un electrón y un protón y el oxígeno
tiene dos electrones y dos protones. De ahí que el agua esté
formada por dos átomos de </font><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font><font face="Century Schoolbook, serif">
y un átomo de </font><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font><font face="Century Schoolbook, serif">:
(</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">).
Dos átomos de hidrógeno y uno de oxígeno forman una molécula de
agua. Muchas moléculas de agua forman una gota; mucha gotas un vaso
con agua. Así se forman muchos litros y, muchos litros
hacen charcos, lagunas ríos y mares.</font></font><span dir="ltr" style="float: left; width: 1.25in; height: 1.16in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	 <font face="Times New Roman, serif"><font color="#000080"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><i><b>AGUA</b></i></font></font></font></font></p>
</span>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
agua está en constante movimiento debido a la energía térmica.
Debido a la acción solar el mar se mueve, por el
calentamiento. De la misma manera por calentamiento el agua se
evapora formando nubes, las cuales suben y se transportan a
diferentes lugares debido al viento. Cuando las nubes se
enfrían, el agua cae nuevamente a la tierra. De la misma manera
el agua está en movimiento debido a reacciones químicas, que
se producen en los cambios y movimientos de las plantas y
de los animales que la consumen, para su mantenimiento,
crecimiento y reproducción. Así como también en la transformación
que se produce de la materia cuando plantas y animales mueren. Está
en permanente reciclaje.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
