<h3 class="western" style="margin-right: -0in"><a name="GASES"></a><a name="_GASES"></a>
<font color="#000066"><i>GASES</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">También
es importante saber que el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxigeno"><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i>
</i></font><font face="Century Schoolbook, serif">son gases. No los
podemos ver ni tocar, pero cuando se unen se convierten en una masa
visible, líquida con peso. Esto es lo que conocemos como </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Agua"><font face="Century Schoolbook, serif"><i><b>agua
pura</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font></font></p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="center" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%"><a name="TEMAII"></a>
<font face="Times New Roman, serif"><font color="#000066"><font face="Century Schoolbook, serif"><font size="6" style="font-size: 22pt"><i><b>INDICE
– TEMA II</b></i></font></font></font></font></p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_BIOLOGÍA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">BIOLOGÍA</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
     
    </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_EL_HOMBRE"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">EL
HOMBRE</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
         
</span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_CÉLULA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">CÉLULA</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">
   
...  
   </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_MEMBRANA_CELULAR"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">MEMBRANA
CELULAR</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">
    .      </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_NÚCLEO"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">NÚCLEO</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">
   
...  
   </span></font></font></font>
</p>
<p class="western" style="margin-left: 0.49in; margin-right: -0in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_CITOPLASMA_1"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">CITOPLASMA</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="pt-BR">
    ..      </span></font></font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_TEJIDOS"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">TEJIDOS</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
   
..   
  </span></font></font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_INICIO_DE_LA"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">INICIO
DE LA VIDA</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
    ...      </span></font></font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.49in; margin-bottom: 0in; line-height: 200%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#_CLOROPLASTOS"><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">CLOROPLASTOS</span></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="4" style="font-size: 14pt"><span lang="es-MX">
        </span></font></font></font>
</p>
<p lang="pt-BR" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="#INDICETEMAI"><font size="4" style="font-size: 14pt"><b><span style="background: #ffff00">REGRESAR
A PRIMER INDICE</span></b></font></a></u></span></font></font></p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="es-MX" class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
