<h3 class="western" style="margin-right: -0in"><a name="BIOLOGÍA"></a><a name="_BIOLOGÍA"></a>
<font color="#000066"><i>BIOLOGÍA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%"><a name="_GoBack"></a>
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Biología"><font face="Century Schoolbook, serif"><i><b>biología</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=F02thBDu8us"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
–</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif">es la
ciencia que estudia la vida. Qué son las plantas y cómo son los
animales. Cómo están formados y cómo se forman. Sobre todo, cómo
está formado el ser humano y cuál es su relación con el medio
ambiente que lo rodea, es decir, con la naturaleza. Cómo funciona su
cuerpo. Por qué y para qué respira, come, defeca, orina, etc. Qué
debe y qué no debe hacer para desarrollarse armónicamente como
ser humano y con la naturaleza misma. Por qué tiene sed, hambre,
calor, dolor. Por qué huele, escucha, ve, siente y saborea. Qué
relación tiene el hombre con otros animales y con las plantas. Todas
estas preguntas y muchas más son la razón del estudio de la vida,
es decir de la biología.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
