<h3 class="western" style="margin-right: -0in"><a name="ELHOMBRE"></a><a name="_EL_HOMBRE"></a>
<font color="#000066"><i>EL HOMBRE</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
  </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hombre"><font face="Century Schoolbook, serif"><i><b>hombre</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
</font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=5tRXxWU8Lp0"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
- </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=j2_V4R8gKNA&amp;feature=iv&amp;annotation_id=annotation_430138"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?annotation_id=annotation_5233&amp;v=wIlFqsS4_o0&amp;feature=iv"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?annotation_id=annotation_822781&amp;v=LMp95BGO-Ss&amp;feature=iv"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
4</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?annotation_id=annotation_505385&amp;v=yTTWKj6t-kk&amp;feature=iv"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
5</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=VFj3upj8FZU"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
6</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
  </b></font></font><font face="Century Schoolbook, serif">está
hecho de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Materia"><font face="Century Schoolbook, serif"><i><b>materia</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">;</font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt">
</font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif">ya hemos
visto qué es la materia. Es cualquier cuerpo que ocupa un lugar
en el espacio y tiene </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Masa"><font face="Century Schoolbook, serif"><i><b>masa</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
El cuerpo humano ocupa un lugar en el espacio y tiene masa.
Lógicamente tiene </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Peso"><font face="Century Schoolbook, serif"><i><b>peso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y tiene </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Energia"><font face="Century Schoolbook, serif"><i><b>energía</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=zPVF0iilvfc"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=KsHp6uYjFbk"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">entonces, si
el cuerpo humano es materia, está formado por moléculas y las
moléculas por átomos.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Los
átomos son </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Elementos_quimicos"><font face="Century Schoolbook, serif"><i><b>elementos
químicos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
Todo lo que en el hombre se conoce como </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Musculoso"><font face="Century Schoolbook, serif"><i><b>músculos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=DZpvFXgCxyE"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=7J8M4Ozz1Pk&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=IinGTOkmMbQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif">y comúnmente
es la carne, está formada por </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Proteinas"><font face="Century Schoolbook, serif"><i><b>proteínas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
¿Qué son las proteínas? Son moléculas formadas por
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Aminoacidos"><font face="Century Schoolbook, serif"><i><b>aminoácidos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
que están encadenados. ¿Qué son los aminoácidos? Son
moléculas formadas por:</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxígeno"><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>,</b></i></font><font face="Century Schoolbook, serif">
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">,
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Carbono"><font face="Century Schoolbook, serif"><i><b>carbono</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">,
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Nitrogeno"><font face="Century Schoolbook, serif"><i><b>nitrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
Lo que quiere decir que estamos hechos de hidrógeno, carbono,
oxígeno y nitrógeno.  </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Aparte
de los elementos químicos que componen el agua y que ya hemos visto,
como son el hidrógeno y el oxígeno, ahora agregamos otros dos que
son el carbono y el nitrógeno.  Al carbono se le conoce con el
símbolo (</font><font face="Century Schoolbook, serif"><b>C</b></font><font face="Century Schoolbook, serif">),
y al nitrógeno con (</font><font face="Century Schoolbook, serif"><b>N</b></font><font face="Century Schoolbook, serif">).
</font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Los
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Aminoácidos"><font face="Century Schoolbook, serif"><i><b>aminoácidos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=wjQMHFCGGcs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
01</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=FoBikm5MZy0&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
02</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=49D6-fPGtsA&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
03</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=STSwWQnpjsY&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
04</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=RbgBi3yRoZ4&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
05</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=a1nIuQz_Ryw&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
06.1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=K4rMhKiPOjw&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
06.2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=DLNU2W3d3nU&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
07</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=8Qm7Sb25kr8&amp;NR=1"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
08</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> están
formados por tres partes que son: </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Amina"><font face="Century Schoolbook, serif"><i><b>aminos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.
</b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Ácido"><font face="Century Schoolbook, serif"><i><b>Ácidos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
y </b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Radicales_libres"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 11pt"><i><b>radicales</b></i></font></font></a></u></span></font><font face="Century Schoolbook, serif">.
¿Qué son los aminos? Los aminos son derivados del amoníaco, que es
un gas, con olor muy irritante y que está formado por </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Nitrogeno"><font face="Century Schoolbook, serif"><i><b>nitrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
e </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.</font></font><span dir="ltr" style="float: left; width: 3.08in; height: 1.4in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	        
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<i><b><font color="#000080">AMONÍACO</font></b></i></p>
</span>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
El amoníaco está formado por un átomo de nitrógeno y tres átomos
de hidrógeno.  
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Cuando
un hidrógeno del amoníaco es reemplazado por un grupo alquilo–</font><font face="Century Schoolbook, serif"><b>R</b></font><font face="Century Schoolbook, serif">,
entonces deja de ser </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Amoniaco"><font face="Century Schoolbook, serif"><i><b>amoníaco</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y se convierte en amino:</font></font><span dir="ltr" style="float: left; width: 3.46in; height: 1in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	     
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%; page-break-after: avoid">
	<i><b><font color="#000080">Grupo alquilo-</font></b></i><font color="#000080"><span style="font-style: normal"><b>R
	=</b></span></font><b><font color="#000080"><span style="font-style: normal">
	</span></font><i><font color="#000080">AMINO</font></i></b></p>
</span>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Existen
ácidos orgánicos, éstos son los que forman parte de la vida de
plantas y animales y también se conocen como </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Acido_carboxilico"><font face="Century Schoolbook, serif"><i><b>ácidos
carboxílicos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
Entre estos ácidos carboxílicos está el ácido acético,
cuya fórmula estructural es:</font></font><span dir="ltr" style="float: left; width: 3.46in; height: 1.08in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<i><b><font color="#000080">ÁCIDO CARBOXÍLICO</font></b></i></p>
</span>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p style="margin-left: 0.2in; margin-right: -0in; margin-bottom: 0.08in; line-height: 100%">
<span dir="ltr" style="float: left; width: 3.46in; height: 1in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<i><b><font color="#000080"><font face="Times New Roman, serif">ÁCIDO
	CARBOXÍLICO Y AMINO</font></font></b></i></p>
</span><br><br>
</p>
<p style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0.08in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Normalmente
los ácidos carboxílicos se unen a un amino de la siguiente manera:</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<span dir="ltr" style="float: left; width: 3.49in; height: 1.2in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<i><b><font color="#000080"><font size="2" style="font-size: 11pt">AMINO
	Y ÁCIDO CARBOXÍLICO</font></font></b></i></p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
</span><br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
idea es comprender que el compuesto derivado del amoníaco y que
se convirtió en   </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Amina"><font face="Century Schoolbook, serif"><i><b>amino</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif"><b>(</b></font><font face="Century Schoolbook, serif"><b>-NH</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>),</b></font><font face="Century Schoolbook, serif">
se unió a un ácido orgánico o carboxílico.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
 
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-bottom: 0in; line-height: 100%"><font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Por
eso, la combinación del amino con el ácido orgánico se llama
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Aminoacido"><font face="Century Schoolbook, serif"><i><b>aminoácido</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">.
Existen 21 aminoácidos que se diferencian unos de otros por el
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Radicales_libres"><font face="Century Schoolbook, serif"><i><b>radical</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
(</font><font face="Century Schoolbook, serif"><b>R</b></font><font face="Century Schoolbook, serif">),
como veremos más adelante. Pero todos los aminoácidos </font>tienen<font face="Century Schoolbook, serif">
como base:</font></font><span dir="ltr" style="float: left; width: 3.49in; height: 1.18in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<i><b><font color="#000080">AMINOÁCIDO</font></b></i></p>
</span>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Así
tenemos los principales</font><font color="#0000ff"><font face="Century Schoolbook, serif"><b>
21</b></font></font><font face="Century Schoolbook, serif">
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Anexo:Aminoácidos"><font face="Century Schoolbook, serif"><i><b>aminoácidos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
que son:</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p align="center" style="margin-right: -0in; margin-top: 0.14in; margin-bottom: 0in; line-height: 100%; page-break-inside: avoid; page-break-after: avoid">
<font color="#404040"><font face="Cambria, serif"><font size="2" style="font-size: 10pt"><font color="#000066"><font face="Century Schoolbook, serif"><font size="5" style="font-size: 18pt"><i><b>T
A B L A</b></i></font></font></font></font></font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" align="center" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p lang="en-US" class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Estos
aminoácidos al unirse forman cadenas y estas cadenas forman la
proteína. Dependiendo del tipo y número de aminoácidos que se unan
depende el tipo de proteína que se forme y dependiendo del tipo
de proteína que se forme, será el tejido que forma los músculos,
los huesos, los órganos, la sangre y, el cerebro, en los animales
pero, también están en la formación del </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Reino_Vegetal"><font face="Century Schoolbook, serif"><i><b>reino
vegetal</b></i></font></a></u></span></font><font color="#0000cc"><font face="Century Schoolbook, serif"><i><b>.</b></i></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt">
</font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–</b></font></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">Es decir, en todas
las plantas. Hemos visto hasta ahora los elementos químicos que
forman los tejidos de animales y vegetales. ¿Pero qué hace que las
plantas y los animales se formen, crezcan y se reproduzcan?</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Este
milagro de la vida se llama </font><font face="Century Schoolbook, serif"><i><b>célula</b></i></font><font face="Century Schoolbook, serif">.
¿Qué es la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Celula"><font face="Century Schoolbook, serif"><i><b>célula</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">?</font></font></p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
