<h3 class="western" style="margin-right: -0in"><a name="_CÉLULA"></a>
<font color="#000066"><span lang="pt-BR"><i>CÉLULA</i></span></font></h3>
<p lang="pt-BR" class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Célula"><font face="Century Schoolbook, serif"><i><b>célula</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=naKy7ubwCJM&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><i> </i></font><font face="Century Schoolbook, serif">es
la unidad fundamental de los organismos. Es la unidad básica de
los tejidos. Es la unidad estructural de los seres vivos. Sólo los
seres vivos tienen células.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
