<h3 class="western" style="margin-right: -0in"><a name="MEMBCELULAR"></a><a name="_MEMBRANA_CELULAR"></a>
<font color="#000066"><i>MEMBRANA CELULAR</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">La
célula está compuesta por una </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Membrana_celular"><font face="Century Schoolbook, serif"><i><b>membrana</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">que viene siendo la
envoltura de la célula, la capa exterior que envuelve todo un
contenido de la célula. Esta membrana celular protege el fluido
acuoso que se encuentra dentro de la célula; al mismo tiempo que
protege a la célula del medio acuoso del exterior.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
