<h3 class="western" style="margin-right: -0in"><a name="NÚCLEO"></a><a name="_NÚCLEO"></a>
<font color="#000066"><i>NÚCLEO</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Núcleo_celular"><font face="Century Schoolbook, serif"><i><b>núcleo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">está formado por
una membrana exterior que protege al semifluido en el
cual se encuentran los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Cromosoma"><font face="Century Schoolbook, serif"><i><b>cro-mosomas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–</b></font></font>
<font face="Century Schoolbook, serif">El núcleo podría
pensarse que es el centro de la célula, pero se puede mover dentro
de la misma. Los cromosomas es-tán compuestos por </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/ADN"><font face="Century Schoolbook, serif"><i><b>ADN</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> y
proteínas. Los principales aminoácidos que componen
estas proteínas son la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Lisina"><font face="Century Schoolbook, serif"><i><b>lisina</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Arginina"><font face="Century Schoolbook, serif"><i><b>arginina</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i>
</i></font><font face="Century Schoolbook, serif">que contienen
cargas positivas. El </font><font face="Century Schoolbook, serif"><i><b>ADN</b></i></font><font face="Century Schoolbook, serif">
lleva carga negativa porque tiene presencia de grupos fosfato.
El</font><font face="Century Schoolbook, serif"><i> </i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Fosfato"><font face="Century Schoolbook, serif"><i><b>fosfato</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">está formado por</font><font face="Century Schoolbook, serif"><b>
</b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Fósforo_(elemento)"><font face="Century Schoolbook, serif"><i><b>fósforo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
otro elemento químico, que se conoce con el símbolo químico (</font><font face="Century Schoolbook, serif"><b>P</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif"><i>.</i></font><font face="Century Schoolbook, serif">
El </font><font face="Century Schoolbook, serif"><i><b>ADN</b></i></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">es</font><font face="Century Schoolbook, serif"><b>
</b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/ADN"><font face="Century Schoolbook, serif"><i><b>ácido
desoxirribonucleico</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Por lo tanto, en los cromosomas se encuentran los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Genética"><font face="Century Schoolbook, serif"><i><b>genes</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
los elementos hereditarios. De ahí, que para conocer la
ascendencia y familiaridad de plantas y animales, se hace el estudio
del </font><font face="Century Schoolbook, serif"><i><b>ADN</b></i></font><font face="Century Schoolbook, serif">.
El clásico ejemplo es el estudio de las células de un niño y las
de un adulto, para determinar si existe entre ellos un
parentesco (</font><font face="Century Schoolbook, serif"><i><b>padre
e hijo</b></i></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif"><b>.</b></font></font><span dir="ltr" style="float: left; width: 3.6in; height: 2.87in; border: 1px solid #000000; padding: 0.05in 0.1in; background: #ffffff">
	<p align="center" style="margin-bottom: 0in; background: #e6e6e6; line-height: 100%">
	<br>
	</p>
</span>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Se
puede saber si el tejido estudiado es de un animal o de un ser
humano. Si es un animal, qué tipo de animal. Si es un tejido de
humano, se puede saber el sexo, la edad, enfermedades, parentescos,
etc. Lo mismo sucede con las plantas.</font></font></p>
