<h3 class="western" style="margin-right: -0in"><a name="_CITOPLASMA_1"></a>
<font color="#000066"><i>CITOPLASMA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Entre
la membrana celular y el núcleo se encuentra un fluido acuoso que
contiene varios elementos y se le llama </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Citoplasma"><font face="Century Schoolbook, serif"><i><b>citoplasma</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>.</b></i></font><font face="Century Schoolbook, serif">
El citoplasma en su mayoría está compuesto de agua, proteínas
y enzimas, para metabolismo celular.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Como
hemos visto, la célula es la unidad fundamental de los organismos
vivos. Existen organismos vivos de una sola célula. Esta célula es
capaz de desplazarse, buscar alimento y reproducirse. Es
independiente, es el caso de la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Amibiasis"><font face="Century Schoolbook, serif"><i><b>amiba</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Las amibas son microorganismos que normalmente se encuentran en
el agua dulce y que son capaces de causar grandes problemas al ser
humano, cuando éste bebe agua contaminada. Existen otros
microorganismos de una sola célula que son capaces de hacer
fermentar algunos productos, como el jugo de uva y convertirlo en
vino; y otros que causan graves enfermedades a las plantas y
animales. </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">También
existen células que se encadenan con otras para formar tejidos de
las plantas, animales y del hombre. Pero estas células no son
independientes, no se pueden desplazar y, mucho menos,
conseguir sus alimentos. Todas las células son capaces de
reproducirse por sí mismas. De ahí que las células tienen vida y
vienen de otra célula con vida. No se producen de la materia
inerte. Normalmente los seres vivos, plantas, animales y el
hombre están estructurados de cientos de miles de millones de
células diferentes. En el ser humano hay aproximadamente
100 tipos diferentes de células.</font></font></p>
<p class="western" style="margin-right: -0in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
