<h3 class="western" style="margin-right: -0in"><a name="_TEJIDOS"></a>
<font color="#000066"><i>TEJIDOS</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Las
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Plantas_terrestres"><font face="Century Schoolbook, serif"><i><b>plantas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
animales y el hombre, están estructuradas por tejidos y éstos por
células encadenadas. Dependiendo del tipo de tejido es el tipo
de células que lo componen.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_epitelial"><font face="Century Schoolbook, serif"><i><b>Tejido
epitelial</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
 </b></font></font><font face="Century Schoolbook, serif">Este tejido
es el que cubre todo el cuerpo del hombre y es lo que se conoce como
piel. Su función es proteger al cuerpo de la radiación
ultravioleta, deshidratación, invasión de bacterias, etc.
Estos tejidos también cumplen la función de transportar materiales
que alimentan a las células o transportan los desechos de ellos
mismos. Este tejido epitelial también cubre las paredes del
intestino, realizando la función de secretar enzimas digestivas
que permiten y participan en el metabolismo de los alimentos; así
como también absorbe los compuestos generados en la digestión
para transportarlos a las células para su alimentación. También
este tipo de tejido cubre a los pulmones por dentro y por fuera y
otra función es la de secretar el mucus, para mantener húmedos los
pulmones; deteniendo al mismo tiempo partículas de polvo que
penetran por la nariz al respirar, expulsando el mucus con estos
polvos y microorganismos atrapados a través de la
garganta. Además de otras funciones en otros órganos. Esto es sólo
para dar una idea de este tipo de tejido y su importancia.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Como
podemos observar, cada célula de cada tejido no es independiente,
depende de cada tipo de tejido y hace la función del órgano al que
pertenezca. Las células de los riñones son diferentes a las del
hígado y estas son diferentes a las del corazón, del páncreas,
etc. Por eso, en un estudio de células, se puede determinar de dónde
son. Además, estas células de tejidos esperan ser
alimentadas; es decir, se les lleva el alimento y se les retiran
los desechos.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_conjuntivo"><font face="Century Schoolbook, serif"><span lang="pt-BR"><i><b>Tejido
conectivo o conjuntivo</b></i></span></font></a></u></span></font><font face="Century Schoolbook, serif"><span lang="pt-BR"><i><b>
de enlace</b></i></span></font><font face="Century Schoolbook, serif"><span lang="pt-BR">.-
</span></font><font face="Century Schoolbook, serif">Este tipo de
tejido está formado por células muy diferentes, ya que
son el sostén, la fuerza, apoyo y protección a las partes
blandas del cuerpo. Estos tejidos son los que forman los huesos y los
cartílagos. Tienen un fuerte componente de </font><font face="Century Schoolbook, serif"><i><b>fosfato
de calcio</b></i></font><font face="Century Schoolbook, serif">, así
como </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Magnesio"><font face="Century Schoolbook, serif"><i><b>magnesio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>,</b></i></font><font face="Century Schoolbook, serif"><i>
</i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Flúor"><font face="Century Schoolbook, serif"><i><b>flúor</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Carbonato"><font face="Century Schoolbook, serif"><i><b>carbonato</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
  </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Como
podemos observar, hay otros elementos químicos aparte de los que ya
hemos visto y que son</font><font face="Century Schoolbook, serif"><i>:
</i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Calcio"><font face="Century Schoolbook, serif"><i><b>calcio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
con el símbolo (</font><font face="Century Schoolbook, serif"><b>C</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif">.
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Flúor"><font face="Century Schoolbook, serif"><i><b>Flúor</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
con el símbolo (</font><font face="Century Schoolbook, serif"><b>F</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif">.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Este
tipo de tejido forma también los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Ligamentos"><font face="Century Schoolbook, serif"><i><b>ligamentos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">y los </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tendón"><font face="Century Schoolbook, serif"><i><b>tendones</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
La mayoría de la gente llega a sufrir </font><font face="Century Schoolbook, serif"><b>“</b></font><font face="Century Schoolbook, serif"><i><b>estiramiento
de ligamento o ruptura</b></i></font><font face="Century Schoolbook, serif"><b>”,</b></font><font face="Century Schoolbook, serif">
lo que causa fuertes dolores y poca fuerza. De la misma manera,
por golpes en los tendones se tienen fuertes dolores. Sobre
todo los deportistas sufren esto por golpes en los tendones. La
función de los tendones es unir a los músculos con los huesos.
Y la función de los ligamentos es unir a un hueso con otro
hueso.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_conjuntivo"><font face="Century Schoolbook, serif"><i><b>Tejido
conjuntivo fibroso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif">
Este tipo de tejido tiene como función la de envolver y
enlazar todos los músculos, así como también todos nuestros
órganos. También proporciona el paso de los vasos
sanguíneos que llevan los nutrientes a cada célula, así como
también abre los espacios por donde pasan los nervios. También
pertenece a este tipo de tejido el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_adiposo"><font face="Century Schoolbook, serif"><i><b>tejido
adiposo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,
</b></font><font face="Century Schoolbook, serif">el cual contiene
y almacena las grasas de reserva que tiene el cuerpo. Más adelante
veremos los riesgos e inconvenientes de sobrepasar las reservas
de grasas en el tejido adiposo, que nos llevan al sobrepeso y
sus graves consecuencias.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Existe
otro tejido importantísimo, que es el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_hematopoyético"><font face="Century Schoolbook, serif"><i><b>tejido
hematopoyético o (linfoideo)</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
formado por células que se hayan en la sangre y que todos conocemos
como </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Glóbulos_blancos"><font face="Century Schoolbook, serif"><i><b>glóbulos
blancos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>,
</b></i></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=2dNbwVnJzrY&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=T5W6VpKPt1Y&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Globulos_rojos"><font face="Century Schoolbook, serif"><i><b>glóbulos
rojos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,
</b></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=ygrQFaaOr24"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
 </b></font></font><font face="Century Schoolbook, serif">y</font><font face="Century Schoolbook, serif"><b>
</b></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Plaqueta"><font face="Century Schoolbook, serif"><i><b>plaquetas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=k1OcWZB_-tY&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"><b> </b></font><font face="Century Schoolbook, serif">Los
</font><font face="Century Schoolbook, serif"><i><b>glóbulos
blancos</b></i></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif">se encargan
de combatir y defender al cuerpo de atacantes malignos, como
bacterias, virus, etc., que causan todo tipo de enfermedades.
Los </font><font face="Century Schoolbook, serif"><i><b>glóbulos
rojos</b></i></font><font face="Century Schoolbook, serif"> son los
encargados de llevar a todas las células el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxígeno"><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y llevar el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Bióxido_de_carbono"><font face="Century Schoolbook, serif"><i><b>bióxido
de carbono</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
a los pulmones. (</font><font face="Century Schoolbook, serif"><b>CO</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">bióxido de
carbono, formado por un carbono y dos oxígenos. </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Las
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Plaqueta"><font face="Century Schoolbook, serif"><i><b>plaquetas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
que se encuentran en la sangre sirven para su coagulación cuando hay
una herida, evitando el desangrado y por esta causa la muerte. Es
importante entender y conocer de qué y cómo estamos formados y
hechos, para prevenir, restituir y conservar nuestra salud y tener
los cuidados necesarios.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_muscular"><font face="Century Schoolbook, serif"><i><b>Tejido
muscular</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif">
Hay un tejido muscular llamado </font><font face="Century Schoolbook, serif"><i><b>liso</b></i></font><font face="Century Schoolbook, serif">,
el cual cubre las paredes de los órganos huecos, como es el
caso de los vasos sanguíneos y los intestinos; en los vasos
sanguíneos se trasporta y circula la sangre; en los intestinos
transporta y circulan los alimentos procesados y los desechos de los
mismos alimentos.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Hay
otro tejido muscular llamado </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Corazón"><font face="Century Schoolbook, serif"><i><b>corazón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=W2mik2uGZhQ"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> Es un
músculo car-díaco y cuya función es bombear la sangre. Otro
tejido muscular se llama </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_cartilaginoso"><font face="Century Schoolbook, serif"><i><b>tejido
esquelético o cartilaginoso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-
</b></font><font face="Century Schoolbook, serif">Este tejido produce
contracciones y, gracias a esto, se puede doblar la mano, el brazo,
las piernas, para la locomoción y todo tipo de movimiento del
cuerpo, de manera voluntaria. Es decir, se puede mover cualquier
parte de nuestro cuerpo cuando nosotros lo deseemos. También cuando
la persona lo desea puede caminar y trasladarse a donde quiera. O
simplemente hacer ejercicio y jugar. Los músculos hacen uso de
su energía para contraerse y ejecutar el movimiento deseado.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Tejido_nervioso"><font face="Century Schoolbook, serif"><i><b>Tejido
nervioso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-
</b></font><font face="Century Schoolbook, serif">Este tejido está
compuesto por células muy especiales, que son capaces de conducir
impulsos electroquímicos nerviosos. En la médula espinal y el
encéfalo, se encuentra la mayor concentración de este
tejido, así como en todo el cuerpo se encuentran ramificaciones. Ya
veremos más adelante el funcionamiento de este tejido nervioso.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
