<h3 class="western" style="margin-right: -0in"><a name="_INICIO_DE_LA"></a>
<font color="#000066"><i>INICIO DE LA VIDA</i></font></h3>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Nosotros
vivimos en un planeta del sistema solar llamado </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/La_tierra"><font face="Century Schoolbook, serif"><i><b>tierra</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Hasta ahora se sabe que en este planeta del sistema existe vida. El
planeta tierra</font><font face="Century Schoolbook, serif"><b> </b></font><font face="Century Schoolbook, serif">está
compuesto de suelo y rocas, que se encuentran en la superficie del
planeta y a esta parte se le llama </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Litosfera"><font face="Century Schoolbook, serif"><i><b>litosfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=89mBm5utqsY&amp;feature=fvsr"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=0Ap5eFEN8Hk&amp;feature=related"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=XiZ9v7J7PSs"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
3</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> También
existen aguas que pueden ser saladas o dulces, por lo que se forman
mares (</font><font face="Century Schoolbook, serif"><i><b>aguas
saladas</b></i></font><font face="Century Schoolbook, serif">) ríos,
lagos y lagunas (</font><font face="Century Schoolbook, serif"><i><b>aguas
dulces</b></i></font><font face="Century Schoolbook, serif">), a esta
parte se le llama </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrosfera"><font face="Century Schoolbook, serif"><i><b>hidrosfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Y sobre la superficie de la tierra se encuentra el aire, es decir, la
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/w/index.php?title=Especial%3ASearch&amp;search=atmosfera"><font face="Century Schoolbook, serif"><i><b>atmósfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>-</b></font></font><font face="Century Schoolbook, serif">
De tal manera que la litosfera, hidrosfera y atmósfera forman
la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/w/index.php?title=Especial%3ASearch&amp;search=biosfera"><font face="Century Schoolbook, serif"><i><b>biosfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Es decir, donde se genera la vida.</font>‬‬‬‬‬</font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Sin
embargo el hombre no se puede alimentar de tierra, de aire y agua. No
podría vivir comiendo tierra, bebiendo agua y respirando aire
solamente. Las células del hombre y de los animales no están
preparadas para procesar los componentes químicos que le sirvan de
alimento para su desarrollo, mantenimiento y reproducción. El
hombre no se puede alimentar de materia </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Inorgánica"><font face="Century Schoolbook, serif"><i><b>inorgánica</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.
</b></font><font face="Century Schoolbook, serif">Sabemos que el
hombre está formado de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxígeno"><font face="Century Schoolbook, serif"><i><b>oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Carbono"><font face="Century Schoolbook, serif"><i><b>carbono</b></i></font></a></u></span></font><font face="Century Schoolbook, serif">
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Nitrógeno"><font face="Century Schoolbook, serif"><i><b>nitrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
así como otros elementos químicos; no se puede hacer
compuestos para formar los aminoácidos que forman la proteína</font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif">de la que está
formado el hombre. Estos elementos sólo se pueden transformar en
proteína, sólo cuando son obtenidos de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Compuesto_orgánico"><font face="Century Schoolbook, serif"><i><b>compuestos
orgánicos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
hombre se alimenta de materia orgánica que sólo producen los seres
vivos. Por eso el hombre se alimenta de la carne de diferentes
animales y de </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Plantas_terrestres"><font face="Century Schoolbook, serif"><i><b>plantas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
que son seres vivos y que contienen compuestos químicos que el
organismo humano puede transformar en nutrientes, de acuerdo a
su estructura celular y funciones de éstas.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Suelo"><font face="Century Schoolbook, serif"><i><b>Suelos</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif">
A partir de la materia inorgánica, que son la tierra, el agua y el
aire, se pueden formar compuestos químicos que generan la vida. Esta
función sólo la pueden realizar las plantas mediante un proceso de
reciclaje de elementos químicos a través de compuestos que
forman las plantas y éstas a su vez pueden ser transformados por los
animales, incluyendo al hombre, como lo veremos.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">El
suelo está compuesto de rocas, que con el tiempo van sufriendo
transformaciones por procesos físicos y químicos. Uno de
estos procesos físicos es la temperatura. La roca está expuesta a
los rayos solares que la calientan y, por lógica, se llena de
energía, que hace que la roca se expanda. Cuando el sol se pone y
llega el frío o la lluvia, baja la temperatura y enfriamiento
de la roca, contrayéndose, causando con el tiempo la fractura de la
roca convirtiéndose en partículas más pequeñas. Por otra parte,
el agua comienza su acción disolvente y también erosiona. A esta
pulverización de la roca se le llama </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Regolito"><font face="Century Schoolbook, serif"><i><b>regolito</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif">
Así es como se va formando el suelo. Por otro lado, el agua (</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">)
se combina con bióxido de carbono (</font><font face="Century Schoolbook, serif"><b>CO</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif">
y se forma el compuesto ácido carbónico (</font><font face="Century Schoolbook, serif"><b>HCO</b></font><font face="Century Schoolbook, serif"><b>3</b></font><font face="Century Schoolbook, serif">)</font><font face="Century Schoolbook, serif">.
Este ácido es un solvente de algunos minerales que contienen las
piedras y la tierra, preparando un suelo más propicio para la vida.
Por otro lado, las sales que contiene la tierra también se
disuelven al contacto con el agua, formando un mejor suelo. Con este
suelo se tienen las condiciones óptimas para que las plantas
inicien su vida. El suelo les sirve de apoyo y, sobre todo, de
anclaje, además de su alimento.   </font></font>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Como
hemos venido observando, esto está formado por los elementos
químicos en su forma natural o en compuestos químicos. Todo es
química orgánica e inorgánica. Pero todo es química.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Fotosintesis"><font face="Century Schoolbook, serif"><i><b>Fotosíntesis</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.-</b></font><font face="Century Schoolbook, serif">
Las plantas, con un suelo que contiene un sinnúmero de elementos
químicos inorgánicos, los aprovechan para su alimentación; además
de elementos y compuestos químicos que se encuentran en la
atmósfera. Pero tienen la cualidad, las </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Plantas_terrestres"><font face="Century Schoolbook, serif"><i><b>plantas</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
de aprovechar la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Energia_solar"><font face="Century Schoolbook, serif"><i><b>energía
solar</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
para sintetizar estos elementos químicos y convertirlos en
compuestos orgánicos que le dan vida, crecimiento y reproducción a
las plantas. El suelo contiene elementos químicos que son nutrimento
de las plantas como: </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Nitrógeno"><font face="Century Schoolbook, serif"><i><b>Nitrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>N</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Fósforo_(elemento)"><font face="Century Schoolbook, serif"><i><b>Fósforo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>F</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Azufre"><font face="Century Schoolbook, serif"><i><b>Azufre</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>S</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Potasio"><font face="Century Schoolbook, serif"><i><b>Potasio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>K</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Calcio"><font face="Century Schoolbook, serif"><i><b>Calcio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Ca</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Magnesio"><font face="Century Schoolbook, serif"><i><b>Magnesio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>M</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hierro_(química)"><font face="Century Schoolbook, serif"><i><b>Hierro</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Manganeso"><font face="Century Schoolbook, serif"><i><b>Manganeso</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Mn</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Boro"><font face="Century Schoolbook, serif"><i><b>Boro</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>B</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Zinc"><font face="Century Schoolbook, serif"><i><b>Zinc</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
 </b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Zn</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Cobre"><font face="Century Schoolbook, serif"><i><b>Cobre</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Cu</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Sodio"><font face="Century Schoolbook, serif"><i><b>Sodio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Na</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Cloro"><font face="Century Schoolbook, serif"><i><b>Cloro</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Cl</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Cobalto"><font face="Century Schoolbook, serif"><i><b>Cobalto</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Cu</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Bario"><font face="Century Schoolbook, serif"><i><b>Bario</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Ba</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Molibdeno"><font face="Century Schoolbook, serif"><i><b>Molibdeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Mo</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Silicio"><font face="Century Schoolbook, serif"><i><b>Silicio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Si</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Flúor"><font face="Century Schoolbook, serif"><i><b>Flúor</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Fl</b></font><font face="Century Schoolbook, serif">),</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Yodo"><font face="Century Schoolbook, serif"><i><b>Yodo</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>I</b></font><font face="Century Schoolbook, serif">).</font><font face="Century Schoolbook, serif">
Estos elementos se encuentran abundantes o escasos, dependiendo del
tipo de tierras. Así como también depende del tipo de plantas, que
los utilizan o no y en qué cantidades. De la misma manera, las
plantas aprovechan los elementos y compuestos químicos que se
encuentran en la atmósfera, como el </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Bióxido_de_carbono"><font face="Century Schoolbook, serif"><i><b>Bióxido
de Carbono</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>CO</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif">),</font><font face="Century Schoolbook, serif"><i><b>
el </b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Nitrógeno"><font face="Century Schoolbook, serif"><i><b>Nitrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>N</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Oxígeno"><font face="Century Schoolbook, serif"><i><b>Oxígeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Neon"><font face="Century Schoolbook, serif"><i><b>Neón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Ne</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Helio"><font face="Century Schoolbook, serif"><i><b>Helio</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>He</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Criptón"><font face="Century Schoolbook, serif"><i><b>Criptón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Kr</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Xenón"><font face="Century Schoolbook, serif"><i><b>Xenón</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Xe</b></font><font face="Century Schoolbook, serif">),</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Metano"><font face="Century Schoolbook, serif"><i><b>Metano</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>Ch</b></font><font face="Century Schoolbook, serif"><b>4</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrógeno"><font face="Century Schoolbook, serif"><i><b>Hidrógeno</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif">);</font><font face="Century Schoolbook, serif"><i><b>
Óxidos de Nitrógeno </b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>H</b></font><font face="Century Schoolbook, serif"><b>2</b></font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif">);
</font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Ozono"><font face="Century Schoolbook, serif"><i><b>Ozono</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>
</b></i></font><font face="Century Schoolbook, serif">(</font><font face="Century Schoolbook, serif"><b>O</b></font><font face="Century Schoolbook, serif"><b>3</b></font><font face="Century Schoolbook, serif">).</font><font face="Century Schoolbook, serif">
Estos son los componentes naturales del aire.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<font face="Times New Roman, serif"><font face="Century Schoolbook, serif">Con
todos estos elementos de la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Litosfera"><font face="Century Schoolbook, serif"><i><b>litosfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><i><b>,
</b></i></font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Hidrosfera"><font face="Century Schoolbook, serif"><i><b>hidrosfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>
</b></font><font face="Century Schoolbook, serif"><i>(</i></font><font face="Century Schoolbook, serif"><i><b>agua</b></i></font><font face="Century Schoolbook, serif"><i>)</i></font><font face="Century Schoolbook, serif">
y </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Atmosfera"><font face="Century Schoolbook, serif"><i><b>atmósfera</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>,</b></font><font face="Century Schoolbook, serif">
las</font><font face="Century Schoolbook, serif"><b> </b></font><font face="Century Schoolbook, serif">plantas
utilizan la energía solar para la fotosíntesis, que se realiza
con la </font><font color="#0000ff"><span lang="zxx"><u><a href="http://es.wikipedia.org/wiki/Clorofila"><font face="Century Schoolbook, serif"><i><b>clorofila</b></i></font></a></u></span></font><font face="Century Schoolbook, serif"><b>.</b></font><font face="Century Schoolbook, serif"><font size="1" style="font-size: 7pt"><b>
</b></font></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>–
</b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=mvvSHhdoZ7Y"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
1</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
– </b></font></font><font color="#0000ff"><span lang="zxx"><u><a href="http://www.youtube.com/watch?v=_qLD8tPJOYw"><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>VIDEO
2</b></font></font></a></u></span></font><font face="Century Schoolbook, serif"><font size="2" style="font-size: 9pt"><b>
-</b></font></font><font face="Century Schoolbook, serif"> Sólo las
plantas tienen clorofila y por eso la materia inorgánica la
convierte en materia orgánica y pueden alimentar a sus células, que
forman tejidos y compuestos orgánicos.</font></font></p>
<p class="western" style="margin-right: -0in; text-indent: 0.39in; margin-bottom: 0in; line-height: 100%">
<br>
</p>
