
<div class="container-responsive">
	<div class="row">
		<div class="col-md-4"><h3>CETEC</h3></div>
		<div id="mensajes" class="col-md-6 col-md-offset-2"></div>
	</div>
	
	<div class="row">
		<div class="col-md-12" align="center">
			<h1>Control de Publicidad</h1>
			<br/>
			<br/>
		</div>
	</div>
	
	<div class="row">
		<div class="col-md-12">
			<div class="col-md-4">
				<h4>Patrocinador</h4>
				<input type="text" class="form-control" placeholder="Patrocinador">
			</div>
			<div class="col-md-4">
				<h4>Tipo de Contrato</h4>
				<input type="text" class="form-control" placeholder="Contrato">
			</div>
			<div class="col-md-4">
				<h4>Fecha de Alta</h4>
				<input type="date" class="form-control" placeholder="Fecha de Alta">
			</div>
		</div>
	</div>
	
</div>
