<?php $this->headLink()->appendStylesheet($this->baseUrl('/public/css/popupStockDiscount.css' )); ?>
<div class="forms">
<?=$this->element->getElement('id_products'); ?>
<?=$this->element->getElement('type_product'); ?>
	<fieldset>
		<legend>Actualizar inventario</legend>
		<table>
			<tr>
				<td colspan="2">Existencias actuales:  <label id="total"></label></td>
			</tr>
			<tr>
				<td><?=$this->element->getElement('stock'); ?></td>
				<td><img style="display:none" id="load" alt="" height="18" src="<?php echo $this->baseUrl('/public/img/load.gif') ?>"></td>
			</tr>
		</table>
	</fieldset>
	<?=$this->element->getElement('discount'); ?>
	<?=$this->element->getElement('close'); ?>
</div>
