<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Servicios</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Ingresos</a>
			        <a href="#" class="btn btn-default">Servicios</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel">
		<div class="panel-heading">
			<h3 class="panel-title amaranth text-size-20">Informaci&oacute;n de los servicios</h3>
		</div>
		<div class="panel-body">
			<p>La siguiente tabla contiene informaci&oacute;n relacionada a los servicios</p>
			<table id="services" class="table table-striped table-hover table-condensed">
				<thead>
					<th>Clave</th>
					<th>N&deg;</th>
					<th>Nombre</th>
					<th>Fecha</th>
					<th>Descripci&oacute;n</th>
					<th>Costo</th>
					<th></th>
					<th>
						<a class="btn btn-success" href="<?php echo $this->basePath()."/in/services/add"?>">
							<span class="glyphicon glyphicon-plus-sign"></span>
						</a>
					</th>
				</thead>
				<tbody>
			    	<?php foreach($this->data as $obj) : ?>
					<tr>
				        <td><?php echo $obj['clave']; ?></td>
						<td><?php echo $obj['id_service']; ?></td>
						<td><?php echo $obj['name']; ?></td>
						<td><?php echo $obj['dateService']; ?></td>
						<td>
							<?php 
							echo (strlen($obj['description']) > 40) ? substr($obj['description'], 0, -20)."  ..." : $obj['description'];
							?>
						</td>
						<td><?php echo $obj['cost']; ?></td>
				        <td><a class="btn btn-primary" href="<?php echo $this->basePath().'/in/services/edit/'.$obj["id_service"]; ?>"><span class="glyphicon glyphicon-pencil"></span></a></td>
				        <td><a class="btn btn-danger" href="<?php echo $this->basePath().'/in/services/delete/'.$obj["id_service"];?>"><span class="glyphicon glyphicon-trash"></span></a></td>
			    	</tr>
			    	<?php endforeach; ?>
			    </tbody>
			</table>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$("#services").dataTable();
});
</script>