
<script type="text/javascript">
<!--
$(document).ready(function() {
	var type = "<?=$this->element->getElement('type_product')->getValue(); ?>";

	$('#p_price').change(function() {
		$('#p_price').formatCurrency();
	});
	
	$('#purchasePercentage').change(function(){
		var formPer = formatPercentage($('#purchasePercentage').val());
		$('#purchasePercentage').val(formPer);
	});
	
	$('#stock').change(function(event){
		var min = $('#min_stock').val();
		var max = $('#max_stock').val();
		var stock = $(this).val();
		if(parseInt(stock) < parseInt(min)){
			horusAlert("minimo tienen que ser " + min + " existencias");
			$(this).val("");
		}else if(parseInt(stock) > parseInt(max)){
			horusAlert("maximo tienen que ser " + max + " existencias");
			$(this).val("");
		}
	});

	$('#Guardar').click(function() {
		var costInput = $('#p_price');
		costInput.toNumber();
		
		if(type == "1"){
			var perPo = $('#purchasePercentage');
			var proPoClea = removePercentage(perPo.val());
			perPo.val(proPoClea);
		}
	});


	if($("input[name='mybrand']:checked").val() == 1){
		$('.suppl').hide();
		$('#productForm').removeAttr('onsubmit');
		$('#productForm').attr("onsubmit", "return isEmptyForm('productForm',7)");
		$('#id_company').attr('class', 'canBeNull');
	}else{
		$('.suppl').show();
		$('#productForm').removeAttr('onsubmit');
		$('#productForm').attr("onsubmit", "return isEmptyForm('productForm',8)");
		$('#id_company').removeAttr('class');
	}

	$("input[name='mybrand']").change(function(){
		var check = $(this).val();
		if(check == 1){ 
			$('.suppl').hide();
			$('#productForm').removeAttr('onsubmit');
			$('#productForm').attr("onsubmit", "return isEmptyForm('productForm',7)");
			$('#id_company').attr('class', 'canBeNull');
		}else{
			$('.suppl').show();
			$('#productForm').removeAttr('onsubmit');
			$('#productForm').attr("onsubmit", "return isEmptyForm('productForm',8)");
			$('#id_company').removeAttr('class');
		}
	});
	
	if($("#p_photo").val() != null && $("#p_photo").val() != ""){
		$('#fotografia').removeAttr('src');
		$('#fotografia').attr('src', 'data:image/png;base64,'+$("#p_photo").val());
	}else{
		$('#fotografia').removeAttr('src');
		$('#fotografia').attr('src', BASE_URL + '/public/img/noConozco.jpg');
	}
	
});
//-->
</script>
<div id="fieldsetForm" class="forms">
<legend id="legendhelp">* Datos requeridos</legend>
<?=$this->element->getElement('id_products'); ?>
<?=$this->element->getElement('type_product'); ?>
	<fieldset>
		<legend>Agregar nuevo producto</legend>
		<table>
			<tr>
				<td>
					<div class="title">Foto:</div>
	        		<div id="contenedorImagen">
			    				<img id="loaderAjax" src="<?php echo $this->baseUrl('/public/img/default-loader.gif'); ?>">
								<img id="fotografia" style="width: 285px;" class="fotografia" src="<?php echo $this->baseUrl('/public/img/noConozco.jpg'); ?>">
								<br />
								<img id="addImage" src="<?php echo $this->baseUrl('/public/img/agregarImg.png');?>" onclick="uploadAjaxImg('addImageProg', 'program', 'fotografiaProg', 'loaderAjaxProg');" />
								<p>M&aacute;ximo: 1000px x 1000px, Formato: jpeg, jpg, png</p>
								
								<?=$this->element->getElement('p_photo'); ?>
			    	</div>
				</td>
				<td>
					<table >
						<tr>
							<td>
								<input type="radio" name="mybrand" checked="checked" value="1" style="height: 10px; width: 10px;">
								<span style="margin-left: 5px;">Marca propia</span><br />
								<input type="radio" name="mybrand" value="0" style="height: 10px; width: 10px;">
								<span style="margin-left: 5px;">Otra marca</span>
							</td>
						</tr>
						<tr>
							<td><span class="suppl">* Proveedor: </span></td>
							<td><span class="suppl"><?=$this->element->getElement('id_company');?></span></td>
						</tr>					
						<tr>
							<td>Clave:</td>
							<td><?=$this->element->getElement('p_key'); ?></td>
						</tr>
						<tr>
							<td>*Nombre:</td>
							<td><?=$this->element->getElement('p_name'); ?></td>
						</tr>
						<tr>
							<td>*M&iacute;nimo en existencias:</td>
							<td>*M&aacute;ximo en existencias:</td>
						</tr>
						<tr>
							<td><?=$this->element->getElement('min_stock'); ?></td>
							<td><?=$this->element->getElement('max_stock'); ?></td>
						</tr>
						<tr>
							<td>*Cantidad:</td>
							<td><?=$this->element->getElement('stock'); ?></td>
						</tr>
						<tr>
							<td>*Categor&iacute;a:</td>
							<td><?=$this->element->getElement('id_category'); ?></td>
						</tr>
						<tr>
							<td>Fecha de Caducidad:</td>
							<td><?=$this->element->getElement('expiration'); ?></td>
						</tr>
						<tr>
							<td>*Precio unitario:</td>
							<td><?=$this->element->getElement('p_price'); ?></td>
						</tr>
						<tr>
							<td>*Este producto esta revisado: </td>
							<td><?=$this->element->getElement('review_product'); ?></td>
						</tr>
						<tr>
							<td>*Unidad de medici&oacute;n del producto: </td>
							<td><?=$this->element->getElement('measuring_fk_id'); ?></td>
						</tr>
					</table>
				</td>
			</tr>
		<tr class="center">
			<td colspan="4">Descripci&oacute;n:</td>
		</tr>
		<tr class="center">
			<td colspan="4"><?=$this->element->getElement('p_description'); ?></td>
		</tr>
		</table>
	</fieldset>
	<div class="center">
	    <?=$this->element->getElement('Guardar'); ?>
	    <a href="javascript:location.href='<?=$this->baseUrl("/In/warehouse/index")?>'" class="horusCancelBtn big icon-iconcancel">Cancelar</a>	
	</div>
</div>