<script>
$(document).ready(function() {
    $('#example').dataTable();
} );
</script>
<h3 style="text-align: center;">::Clientes::</h3>
<div>
<table id="example" class="table table-striped table-bordered" cellspacing="0" width="100%">
        <thead>
            <tr>
                <th>Nombre</th>
                <th>RFC</th>
                <th>Dirección</th>
                <th>Contacto</th>
                <th>Telefono</th>
                <th>Correo</th>
                <th>+</th>
            </tr>
        </thead>
 
        <tfoot>
            <tr>
                <th>Nombre</th>
                <th>RFC</th>
                <th>Dirección</th>
                <th>Contacto</th>
                <th>Telefono</th>
                <th>Correo</th>
                <th></th>
            </tr>
        </tfoot>
 
        <tbody>
            <tr>
                <td>Larry Page</td>
                <td>LSHDGW73T3U</td>
                <td>Col del valle</td>
                <td>Sony</td>
                <td>5569874321</td>
                <td>Larry.Page@zzz.com</td>
                <td>Edit Delete</td>
            </tr>
            <tr>
                <td>Shawn Fanning</td>
                <td>SHJFY37HEFA</td>
                <td>Vicente villada #30</td>
                <td>Shawn Fanning</td>
                <td>5589764432</td>
                <td>shawn.fanning@zzz.com</td>
                <td>Edit Delete</td>
            </tr>
            <tr>
                <td>Bill Gates</td>
                <td>8277211234</td>
                <td>SanFrancisco #45</td>
                <td>Microsoft</td>
                <td>3456789021</td>
                <td>bill.gates@zzz.com</td>
                <td>Edit Delete</td>
            </tr>
            <tr>
                <td>Jeff Bezos</td>
                <td>BLL342FFGFS</td>
                <td>Avenida Siempre Viva</td>
                <td>mark zuckerberg</td>
                <td>12345643</td>
                <td>jeff.bezos@zzz.com</td>
                <td>Edit Delete</td>
            </tr>
        </tbody>
    </table>
</div>