SET FOREIGN_KEY_CHECKS = 0;

-- -----------------------------------------------------
-- Borrar Tablas 
-- -----------------------------------------------------
DROP TABLE IF EXISTS `account`;
DROP TABLE IF EXISTS `account_category`;
DROP TABLE IF EXISTS `account_current_balance`;
DROP TABLE IF EXISTS `account_tx`;
DROP TABLE IF EXISTS `acc_receivable`;
DROP TABLE IF EXISTS `acl_permissions`;
DROP TABLE IF EXISTS `acl_resources`;
DROP TABLE IF EXISTS `acl_roles`;
DROP TABLE IF EXISTS `acl_users`;
DROP TABLE IF EXISTS `activities`;
DROP TABLE IF EXISTS `activityDates`;
DROP TABLE IF EXISTS `addresses`;
DROP TABLE IF EXISTS `articles_of_inventories`;
DROP TABLE IF EXISTS `bank`;
DROP TABLE IF EXISTS `banks`;
DROP TABLE IF EXISTS `banks_tx`;
DROP TABLE IF EXISTS `bank_current_balance`;
DROP TABLE IF EXISTS `books`;
DROP TABLE IF EXISTS `cash`;
DROP TABLE IF EXISTS `cash_current_balance`;
DROP TABLE IF EXISTS `cash_tx`;
DROP TABLE IF EXISTS `category`;
DROP TABLE IF EXISTS `clock`;
DROP TABLE IF EXISTS `company`;
DROP TABLE IF EXISTS `company_contact`;
DROP TABLE IF EXISTS `components`;
DROP TABLE IF EXISTS `contents`;
DROP TABLE IF EXISTS `contract_types`;
DROP TABLE IF EXISTS `cron_token`;
DROP TABLE IF EXISTS `curses`;
DROP TABLE IF EXISTS `cv`;
DROP TABLE IF EXISTS `cv_curses`;
DROP TABLE IF EXISTS `cv_curses_employee`;
DROP TABLE IF EXISTS `cv_jobexperience_tech`;
DROP TABLE IF EXISTS `cv_job_experience`;
DROP TABLE IF EXISTS `cv_job_users`;
DROP TABLE IF EXISTS `cv_language`;
DROP TABLE IF EXISTS `cv_language_name`;
DROP TABLE IF EXISTS `cv_tech`;
DROP TABLE IF EXISTS `cv_technologies`;
DROP TABLE IF EXISTS `data`;
DROP TABLE IF EXISTS `data_meeting`;
DROP TABLE IF EXISTS `datepaymentsorder`;
DROP TABLE IF EXISTS `dates_of_payments`;
DROP TABLE IF EXISTS `days`;
DROP TABLE IF EXISTS `department`;
DROP TABLE IF EXISTS `district`;
DROP TABLE IF EXISTS `documents`;
DROP TABLE IF EXISTS `documents_fields`;
DROP TABLE IF EXISTS `documents_fields_content`;
DROP TABLE IF EXISTS `entry_out_merchandize`;
DROP TABLE IF EXISTS `entry_out_product`;
DROP TABLE IF EXISTS `expenses`;
DROP TABLE IF EXISTS `ho_mondays`;
DROP TABLE IF EXISTS `inventories`;
DROP TABLE IF EXISTS `invoices`;
DROP TABLE IF EXISTS `iof_permission`;
DROP TABLE IF EXISTS `iof_resource`;
DROP TABLE IF EXISTS `iof_role`;
DROP TABLE IF EXISTS `iof_role_permission`;
DROP TABLE IF EXISTS `iof_users`;
DROP TABLE IF EXISTS `iof_user_role`;
DROP TABLE IF EXISTS `job_users`;
DROP TABLE IF EXISTS `keys`;
DROP TABLE IF EXISTS `liabilities`;
DROP TABLE IF EXISTS `link`;
DROP TABLE IF EXISTS `made_payments`;
DROP TABLE IF EXISTS `made_payments_order`;
DROP TABLE IF EXISTS `measuring_unit`;
DROP TABLE IF EXISTS `merchandize`;
DROP TABLE IF EXISTS `minutes`;
DROP TABLE IF EXISTS `minutesbyuser`;
DROP TABLE IF EXISTS `neighborhood`;
DROP TABLE IF EXISTS `num`;
DROP TABLE IF EXISTS `payments`;
DROP TABLE IF EXISTS `pay_payroll`;
DROP TABLE IF EXISTS `preferences`;
DROP TABLE IF EXISTS `price_products`;
DROP TABLE IF EXISTS `price_services`;
DROP TABLE IF EXISTS `products`;
DROP TABLE IF EXISTS `projects`;
DROP TABLE IF EXISTS `project_contact`;
DROP TABLE IF EXISTS `project_role`;
DROP TABLE IF EXISTS `purchase`;
DROP TABLE IF EXISTS `purchase2`;
DROP TABLE IF EXISTS `purchase_invoices`;
DROP TABLE IF EXISTS `purchase_order`;
DROP TABLE IF EXISTS `saleproducts`;
DROP TABLE IF EXISTS `sales`;
DROP TABLE IF EXISTS `services`;
DROP TABLE IF EXISTS `shoppingcart`;
DROP TABLE IF EXISTS `states_of_mexico`;
DROP TABLE IF EXISTS `state_of_inventories`;
DROP TABLE IF EXISTS `stock`;
DROP TABLE IF EXISTS `stock_merchandize`;
DROP TABLE IF EXISTS `technologies`;
DROP TABLE IF EXISTS `techtype`;
DROP TABLE IF EXISTS `themes`;
DROP TABLE IF EXISTS `tipo_books`;
DROP TABLE IF EXISTS `tipo_tutorial`;
DROP TABLE IF EXISTS `topic`;
DROP TABLE IF EXISTS `tutorial`;
DROP TABLE IF EXISTS `types`;
DROP TABLE IF EXISTS `update_actions`;
DROP TABLE IF EXISTS `users_addresses`;
DROP TABLE IF EXISTS `users_projects`;
DROP TABLE IF EXISTS `user_details`;
DROP TABLE IF EXISTS `vision`;

-- Checar estas tablas porque no aparecen
DROP TABLE IF EXISTS `prospect_of_projects` ;
DROP TABLE IF EXISTS `prospect_contact` ;
DROP TABLE IF EXISTS `proposals` ;
DROP TABLE IF EXISTS `dates_of_payments2` ;
DROP TABLE IF EXISTS `prospects_projects` ;