INSERT INTO `states_of_mexico` (`id`, `state`) VALUES 
(1,'Aguascalientes'),
(2,'Baja California Sur'),
(3,'Baja California'),
(4,'Campeche'),
(5,'Chiapas'),
(6,'Chihuahua'),
(7,'Coahuila de Zaragoza'),
(8,'Colima'),
(9,'Distrito Federal'),
(10,'Durango'),
(11,'Guanajuato'),
(12,'Guerrero'),
(13,'Hidalgo'),
(14,'Jalisco'),
(15,'Michoacán de Ocampo'),
(16,'Morelos'),
(17,'México'),
(18,'Nayarit'),
(19,'Nuevo León'),
(20,'Oaxaca'),
(21,'Puebla'),
(22,'Querétaro'),
(23,'Quintana Roo'),
(24,'San Luis Potosí'),
(25,'Sinaloa'),
(26,'Sonora'),
(27,'Tabasco'),
(28,'Tamaulipas'),
(29,'Tlaxcala'),
(30,'Veracruz de Ignacio de la Llave'),
(31,'Yucatán'),
(32,'Zacatecas');