<?php
	$helpUser = $this->helps->contactAdd;
?>
<h3 class="centerHor">Agregar Contacto</h3>
<ul class="toolbar">
	<div id="icons">
			<li class="iconOpacity">
				<a href="<?php echo $this->baseUrl('/Horus/contact/index') ?>"><img title="Contactos"  src="<?php echo $this->baseUrl('/public/img/icons/'.$this->iconset.'/iconcontact.png');?>"></a>
			</li>
			<li class="iconOpacity" onclick="openDialog('Ayuda','Informaci&oacute;n','<?php echo $helpUser; ?>')">
				<a><img title="Ayuda" src="<?php echo $this->baseUrl('/public/img/icons/icoquestion.png')?>"></a>
			</li>
			<div id="clock"></div>
	</div>	
</ul>

<script>
	var nameContact = "Nuevo Contacto";
</script>

<div id="overflow">
<p class="triangle-border" >Ingresa los datos del contacto.</p>
<?php echo $this->form ;?>
</div>