<script src="https://ajax.googleapis.com/ajax/libs/jquery/2.1.3/jquery.min.js"></script>
</script>
<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

    <head>

        <title>Cetec Carga dinamica de clase</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Page description" />
        <meta name="author" content="dxthemes" />
        <meta charset="utf-8" />


    </head>

<body>



    <?php echo $this->content;?>



</body>

</html>
