<!DOCTYPE html>
<html lang="en" xmlns="http://www.w3.org/1999/html">

    <head>

        <title>Architex - pesponsive one page portfolio</title>

        <meta name="viewport" content="width=device-width, initial-scale=1.0" />
        <meta name="description" content="Page description" />
        <meta name="author" content="dxthemes" />
        <meta charset="utf-8" />

      
        <!--[if IE 7]>
        <![endif]-->

        <!--[if lt IE 9]>
        <script src="http://html5shim.googlecode.com/svn/trunk/html5.js"></script>
        <![endif]-->
        
        <!--[if gte IE 9]>
        <style type="text/css">
        </style>
        <![endif]-->

        <script src="<?php echo $this->basePath() . '/public/education/js/vendor/jquery-1.10.2.min.js';?>"></script>

    </head>

<body>
    <?php echo $this->content;?>
</body>

</html>