<div class="breadcrumbs">
	<div class="container">
		<div class="col-md-4"><div class="row"><p class="title-breadcrumbs">Cuentas por cobrar</p></div></div>
		<div class="col-md-4">
			<div class="row">
				<ul class="toolbar">
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Uno </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Dos </a></li>
					<li><a href="#" class="btn"> <span class="glyphicon glyphicon-home"></span> Tres </a></li>
				</ul>
			</div>
		</div>
		<div class="col-md-4">
			<div style="line-height: 38px" class="row text-right">
				<div class="btn-group btn-breadcrumb">
			    	<a href="#" class="btn btn-default"><i class="glyphicon glyphicon-home"></i></a>
			        <a href="#" class="btn btn-default">Ingresos</a>
			        <a href="#" class="btn btn-default">CXC</a>
			        <a href="#" class="btn btn-default">Inicio</a>
				</div>
			</div>
		</div>
    </div> <!-- end container -->
</div> <!-- end breadcrumbs -->

<div class="container">
	<div class="panel panel-default">
		<div class="panel-heading">
			<h3 class="panel-title amaranth text-size-20">Informaci&oacute;n de las cuentas por cobrar</h3>
		</div>
		<div class="panel-body">
			<p>La siguiente tabla contiene informaci&oacute;n relacionada a las cxc</p>
			<table id="cxc" class="table table-striped table-hover table-condensed">
				<thead>
					<th>N&deg;</th>
					<th>Cliente</th>
					<th>Proyecto</th>
					<th>Importe</th>
					<th>Fecha de cobro</th>			
					<th>N&uacute;mero de Pago</th>
					<th>Estatus</th>
					<th></th>
				</thead>
				<tbody>
			    	<?php foreach($this->data as $obj) : ?>
					<tr>
				        <td><?php echo Util_Tools::format($obj['id_datePayment'], 4); ?></td>
				        <td><?php echo $obj['name_company']; ?></td>
						<td><?php echo $obj['project_name']; ?></td>
						<td><?php echo Util_Tools::currency($obj['amount']); ?></td>
						<td><?php echo Util_Tools::dateFormat("-", $obj['datePayment']); ?></td>
						<td><?php echo $obj['number']."/".$obj['numberofpayments']; ?></td>
						<td>
						<?php 
						if ($obj['statusCxc'] == 1)
						{
							echo "<label class='label label-success'>Cobrado</label>";
						}else{
							echo "<label class='label label-warning'>Pendiente</label>";
						}
						?>
						</td>
				        <td>
			    			<button type="button" class="btn btn-info" data-toggle="modal" data-target="#modalPayments" data-backdrop="static" data-keyboard="false">
  								<span class="glyphicon glyphicon-plus-sign"></span>
							</button>
			    		</td>
			    	</tr>
			    	<?php endforeach; ?>
			    </tbody>
			</table>
		</div>
	</div>
</div>


<!-- Modal -->
<div class="modal fade" id="modalPayments" tabindex="-1" role="dialog" aria-labelledby="myModalLabel" aria-hidden="true">
	<div class="modal-dialog">
    	<div class="modal-content">
      		<div class="modal-header">
        		<button type="button" class="close" data-dismiss="modal" aria-label="Close"><span aria-hidden="true">&times;</span></button>
        		<h4 class="modal-title" id="myModalLabel">Realizar pago</h4>
      		</div>
		    <div class="modal-body" id="modal-body-payments">
		    	<div class="row">
		    		<div class="col-md-12">
		    			<p class="text-muted">Cliente:</p>
		    			<p class="text-info">Proyecto:</p>
		    			<form class="form-horizontal">
						  	<div class="form-group">
						    	<label for="" class="col-sm-4 control-label">*Saldo por cubrir:</label>
						    	<div class="col-sm-8">
						      		<input type="text" class="form-control" id="">
						    	</div>
						  	</div>
  							<div class="form-group">
    							<label for="" class="col-sm-4 control-label">*Pago</label>
    							<div class="col-sm-8">
      								<input type="text" class="form-control" id="">
    							</div>
  							</div>
  							<div class="form-group">
    							<label for="" class="col-sm-4 control-label">*Saldo pendiente de cobro:</label>
    							<div class="col-sm-8">
      								<input type="text" class="form-control" id="">
    							</div>
  							</div>
  							<div class="form-group">
    							<label for="" class="col-sm-4 control-label">Numero de cuenta:</label>
    							<div class="col-sm-8">
      								<input type="text" class="form-control" id="">
    							</div>
  							</div>
  							<div class="form-group">
    							<label for="" class="col-sm-4 control-label">Referencia:</label>
    							<div class="col-sm-8">
      								<input type="text" class="form-control" id="">
    							</div>
  							</div>
						</form>
		    		</div>
		    	</div>
		    </div>
		    <div class="modal-footer">
		    	<button type="button" class="btn btn-default" data-dismiss="modal">Cancelar</button>
		    </div>
		</div>
	</div>
</div>

<script>
$(document).ready(function(){
	$("#cxc").dataTable({
		"aoColumnDefs" : [ {
	    	'bSortable' : false,
	        'aTargets' : [ 7 ]
		} ]
	});
});
</script>