<script src="<?php echo $this->basePath()."/public/js/expenses.js";?>"></script>
<h1>Ingresa los datos del gasto.</h1>

<div class="panel">
	<div class="panel-heading"></div>
	<div class="panel-body">
		<?php 	
		$form = $this->form; 
		$form->prepare(); 
		echo $this->form()->openTag($form);
		/* echo $this->formRow($form->get('id_inventory')); */
		?>
		<!--  <form> -->
		<fieldset>
		
			<legend>Detalles del gasto</legend>
			
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
          				<?php echo $this->formRow($form->get('reference_of_expenses')); ?>
         			</div>
         			<span id="amountAccountTxt"></span>
				</div>
				<div class="col-md-6">
					<div class="form-group">
          				<?php echo $this->formRow($form->get('expenses_type')); ?>
           			</div>
				</div>
			</div>
			
			<div class="row">
				<div class="col-md-6">
					<div class="form-group">
          				<label>Fecha</label>
                		<?php echo $this->formRow($form->get('date_of_expenses')); ?>
          			</div>
				</div>
				<div class="col-md-6">
					<div class="form-group">
         				<label>Importe</label>         
       					<?php echo $this->formRow($form->get('amount_of_expenses')); ?>
        			</div>
				</div>
			</div>
			               
            <div class="form-group">
            	<label>Comentarios</label>
            	<?php echo $this->formRow($form->get('description_of_expenses')); ?>
          	</div>
                            
           	<hr>
            <div class="row">
            	<div class="col-md-6">
                	<?php echo $this->formRow($form->get('submit')); ?>
               	</div>
                <div class="col-md-6">
                	<input type="button" value="Cancelar" class="btn btn-danger btn-block btn-lg">
            	</div>
           	</div>
           	
      	</fieldset>
		<!--</form> -->
		<?php echo $this->form()->closeTag(); ?>
	</div><!-- Fin panel-body -->
</div><!-- Fin panel -->		


<script>
var $basePath = "<?php $this->basePath(); ?>";

$(document).ready(function(){
    $.datepicker.regional['es'] = {
            closeText: 'Cerrar',
            prevText: '<Ant',
            nextText: 'Sig>',
            currentText: 'Hoy',
            monthNames: ['Enero', 'Febrero', 'Marzo', 'Abril', 'Mayo', 'Junio', 'Julio', 'Agosto', 'Septiembre', 'Octubre', 'Noviembre', 'Diciembre'],
            monthNamesShort: ['Ene','Feb','Mar','Abr', 'May','Jun','Jul','Ago','Sep', 'Oct','Nov','Dic'],
            dayNames: ['Domingo', 'Lunes', 'Martes', 'Miércoles', 'Jueves', 'Viernes', 'Sábado'],
            dayNamesShort: ['Dom','Lun','Mar','Mié','Juv','Vie','Sab'],
            dayNamesMin: ['Do','Lu','Ma','Mi','Ju','Vi','Sa'],
            weekHeader: 'Sm',
           // dateFormat: 'dd/mm/yy',
            firstDay: 1,
            isRTL: false,
            showMonthAfterYear: false,
            yearSuffix: ''
    };
        
	$.datepicker.setDefaults($.datepicker.regional['es']);

	$( "#dateExpenses" ).datepicker({ 
    	dateFormat: 'yy-mm-dd' 
	});
	
});
</script>
						