<div class="panel panel-danger">
	<div class="panel-heading">
		<div class="clearfix">
			<h3 class="panel-title pull-left" style="margin-top:9px;">Gastos</h3> 
    		<a href="<?php echo $this->basePath()."/expenses/add" ?>" class="btn btn-success pull-right" >
				<span class="glyphicon glyphicon-plus-sign"> </span>
			</a>
		</div> <!-- end clearfix -->
	</div>
	<div class="panel-body">
		<table class="table table-striped table-hover table-condensed">
			<thead>
				<tr>
					<th>Id</th>
					<th>Fecha</th>
					<th>Tipo</th>
					<th>Descripci&oacute;n</th>
					<th>Importe</th>
					<th></th>
					<th></th>
				</tr>
			</thead>
			<tbody>
			<?php foreach ($this->expenses as $i) : ?>
				<tr>
					<td><?php echo $i['idExpenses']; ?></td>
					<td><?php echo $i['date_of_expenses']; ?></td>
					<td><?php echo $i['expenses_type']; ?></td>
					<td><?php echo $i['description_of_expenses']; ?></td>
					<td><?php echo $i['amount_of_expenses']; ?></td>
					<td><a href="<?php echo $this->basePath()."/expenses/edit/".$i['idExpenses'];?>" class="btn btn-primary"><span class="glyphicon glyphicon-pencil"></span></a></td>
					<td><a href="<?php echo $this->basePath()."/expenses/delete/".$i['idExpenses'];?>" class="btn btn-danger"><span class="glyphicon glyphicon-trash"></span></a></td>
				</tr>
			<?php endforeach; ?>
			</tbody>
		</table>
	</div>
</div>